### ISSUE TITLE
Overflow button is always visible when the ToolBar is used as ActionBar on mobile device

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1000]
Example: http://dojo.telerik.com/EZidi

**Comment by SimonWaterer** [comment]
I found this exact bug too, and was about to submit a ticket to Telerik for it.

The DOM tree is different in Kendo Mobile. In non-mobile, the this.popup.element.children is a UL with LI children. In mobile, the this.popup.element.children is:

    <div class="km-popup-wrapper ... 
        <div class="km-actionsheet-wrapper ... 
            <ul class="k-overflow-container ... 

The problem is in kendo.toolbar.js in _toggleOverflowAnchor at around line 1224:
` if (this.popup.element.children(":not(." + OVERFLOW_HIDDEN + ", ." + POPUP + ")").length > 0) {`

Should be:
` if (this.popup.element.find("li:not(." + OVERFLOW_HIDDEN + ", ." + POPUP + ")").length > 0) {`

See my fiddle: https://jsfiddle.net/simon_waterer/r3jqa1my/

**Comment by valchev** [comment]
@simonwaterer Thank you for the hint. I've pushed a fix and added test for it.
