### ISSUE TITLE
Widget renders two identical items when interval is '1'

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1003]
Repro demo: http://dojo.telerik.com/AmeSE/3

Reported in TicketID: 957666

**Comment by KirilNN** [comment]
The problem here is that an incorrect format has been set, therefore there are duplicate entries in the list, and widgets selects both of them. The actual problem is that the widget should select a single entry , as there is just one value. Closing this issue and opened the following one:

https://github.com/telerik/kendo-ui-core/issues/1142
