### ISSUE TITLE
Scroll issue with virtualization

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1022]
Steps:
1) Open [http://demos.telerik.com/aspnet-mvc/combobox/virtualization](http://demos.telerik.com/aspnet-mvc/combobox/virtualization) 
2) Click on the drop arrow to see the list of items in the drowdown
3) Scroll using mouse wheel or click on the scroll bar down arrow.

Result: After few records the selection will jump again to first item.
(Could not reproduce for DropDownList) 

Reported in Ticket ID: 960049

**Comment by eugeneelchugin** [comment]
I catch sight of that issue causes on fifth page of scroll list. Maybe it somehow depends from magic paging  formula: (heigth / itemHeigth) * **4**. I supose that additional requests start to send exactly in fifth page showing, and after getting response, control rebind its select list using this portion of data. I think exactly in this moment somthing going wrong

**Comment by valchev** [comment]
Works on Chrome, seems to be specific for Firefox and IE

**Comment by danilo-mena** [comment]
any update for this issue?

**Comment by pgatilov** [comment]
It does NOT work in Chrome. Reproduces at http://demos.telerik.com/kendo-ui/multiselect/virtualization in IE 11, latest Chrome and Firefox.

**Comment by ikkovalev** [comment]
Workaround found. Actually this code jumpes selection to the first item again: https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.multiselect.js#L491
"if condition" becomes "true" because page === 1 during scrolling (both mouse and keyboard) for some reason. Setting <b>highlightFirst</b> to false solves problem for me. So just set this property to false http://docs.telerik.com/kendo-ui/api/javascript/ui/multiselect#configuration-highlightFirst
