### ISSUE TITLE
Update releases (just add tags to github)

### ISSUE THREAD

**Issue by jesperronn** [telerik/kendo-ui-core#1075]
on https://github.com/telerik/kendo-ui-core/releases there are merely only 8 releases currently.

This is inconsistent with https://github.com/kendo-labs/bower-kendo-ui/releases, where it seams you consistently register all releases.

For the sake of consistency, can you add the same tags into `kendo-ui-core` repositories. This makes it simpler to track down regression errors or issues which our customers will have.

I reckon the work to be done is very simple. You basically just need to put a tag to the last commit for each release. If you are REALLY nice, you can put a hand written note on the https://github.com/telerik/kendo-ui-core/releases page, but that would only be sugar (and could point to a changelog).

Thanks!

**Comment by underlog** [comment]
The releases present in the repository are mirrors of one of the features we have exposed for commercial accounts - the so called internal builds. I would not call them "real" releases, as we don't branch them off for maintenance afterwards. 

The Kendo UI Core users may utilize our maintenance `production` branch for the very same purpose. In fact, the production branch is more up-to-date from those, since the internals are published on a weekly basis, while we push the fixes in production immediately.
