### ISSUE TITLE
Close window when click in overlay

### ISSUE THREAD

**Issue by brunowego** [telerik/kendo-ui-core#1098]
To improve experience with modal mode, I think add a event to close window when click in overlay background can be helpful. :+1:

**Comment by naskog** [comment]
Hi @brunowego,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests, so I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!
