### ISSUE TITLE
Add a way to opt-out of integration with Globalize 0.1

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1107]
Currently, the integration with Globalize [is unconditional](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L1060). This is quite unfortunate, given that the Globalize 0.1 branch is deprecated **and** has an incompatible feature set with our globalization routines.

My suggestion is to add an escape hatch, e.g.
`kendo.support.globalize = false;`

Comments welcome.

cc @ggkrustev

**Comment by ggkrustev** [comment]
In general, Kendo will not use GlobalizeJS 0.1 if the script is loaded after the kendo scripts. I suppose that is current `kendo.support.globalize`.

The only purpose of such option would be if we decide to drop support for Globalize 0.1, but allow users to set option to `true` to enable it again.

If we decide to add such option, let's name it `kendo.support.jQueryGlobalize` because just "globalize" is a bit misleading.

**Comment by ggkrustev** [comment]
We removed support for GlobalizeJS in Q1 2016:

http://docs.telerik.com/kendo-ui/backwards-compatibility/2016/2016-backward-compatibility#kendo-ui-2016-q1
