### ISSUE TITLE
Clear applied filter after selection if in tagMode: 'single' and autoClose: 'false'

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1118]
### Description

Basically, the widget keeps popup opened and the user needs to type something and then clear the text in order to see all items, which is not good UX.

Repro demo: http://demos.telerik.com/kendo-ui/multiselect/tag-mode
Steps:
- Type "Steve" and select
- Notice that you need to type "a" and then clear it in order to see all items

**Comment by Dimitar-Goshev** [comment]
https://github.com/telerik/kendo-ui-core/issues/2591

**Comment by Dimitar-Goshev** [comment]
Since R3 2016, when some text is entered for filtering and a filtered item is selected, the text is not cleared. Thus, if the filter returns multiple items, it is possible to select more than one item using the entered filter text. In prior versions, the entered filter text is cleared. So since R3 2016 version, the above described enhancement is not credible, it is contradicting with the current behavior.
