### ISSUE TITLE
Add support for the new jQuery Globalize API

### ISSUE THREAD

**Issue by bundyo** [telerik/kendo-ui-core#115]
Library is here https://github.com/jquery/globalize, currently Core crashes [on the missing format method](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L1050) if the lib is loaded.

**Comment by alaney** [comment]
Is this still relevant? Kendo documentation does not specify which version of Globalize.JS it supports.

**Comment by ggkrustev** [comment]
Hi @alaney,

Kendo UI supports only Globalize.js 0.1.x. Newer versions will not be used internally. Instead the widgets will use Kendo Globalize. This is clearly stated in my last comment from Jun 2014.

Our position hasn't been changed since then, as support for newer Globalize.js is cumbersome and error prone.

If you need to use Globalize.js, then parse the date/numbers manually instead of using kendo.parseDate.
