### ISSUE TITLE
The expanded list of numeric values of kendo.ui.Pager is not accessible when embedded in kendo.ui.ToolBar 

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#1181]
![image](https://cloud.githubusercontent.com/assets/2556751/10455456/4c150c5e-71b3-11e5-8614-4e0e6bdfc849.png)

One way to sort this out is to add style "overflow: visible" to the toolbar but does it have side effects?

![image](https://cloud.githubusercontent.com/assets/2556751/10455492/871714f0-71b3-11e5-9463-255138eaec9b.png)

**Comment by yordanov** [comment]
In general, it is not advisable to place the Pager inside a ToolBar widget. The pager is designed as a standalone toolbar-like widget. 

However, if one is willing to place it inside a ToolBar, the ToolBar should not be `resizable`. When set to true, the `resizable` configuration triggers as you mentioned `overflow: hidden`. In order to avoid this the ToolBar must have `resizable: false`. You can see an isolated demo here: http://dojo.telerik.com/@yordanov/ejiXU
