### ISSUE TITLE
ENHANCEMENT: Consider expanding the list of numeric values of kendo.ui.Pager downward when there is not enough space upward

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#1182]
Consider expanding the list of numeric values of kendo.ui.Pager downward when there is not enough space upward

![image](https://cloud.githubusercontent.com/assets/2556751/10455557/f2e81af8-71b3-11e5-92ed-7b1522de41d2.png)

**Comment by naskog** [comment]
Hi @jlchereau,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests, so I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!

**Comment by jlchereau** [comment]
# Kendo UI chases new features and hardly improves old ones 

1) It is a question of opinion and where you aim at in terms of product quality. In the company where I work this would not pass QA. IMHO there are far too many frustrating bits like this one in components that are several years old and have hardly progressed.

2) I am not contributing feedback anymore on user voice because the system is biased: requests for new components obviously get hundreds of votes whereas basic, obvious and necessary  improvements to existing components are almost always ignored and never make their way to RTM.
