### ISSUE TITLE
Impossible to change mask at runtime

### ISSUE THREAD

**Issue by bakura10** [telerik/kendo-ui-core#1215]
Hi,

It's currently impossible to change the mask of a MaskedTextBox element. However this is often needed. For instance I'd like to have a masked text box for number (I cannot use the NumericTextbox component because it only adds the spaces once the element loose focus). However it's not possible because, in French, 100 would have a mask "000", while 1000 would have a mask "0 000", while "10000" would have a mask of "00 000".

**Comment by naskog** [comment]
Hi @bakura10 ,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests, so I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!
