### ISSUE TITLE
Popup is closed when scrolled in modal window

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1223]
Can be reproduced here:
http://dojo.telerik.com/oyIdA
1. It should be a mobile device
2. The window should be _modal_
3. The size of the window should be _less_ than the popup.

**Comment by papaytl185** [comment]
I did some research on trying to come up with a hacked solution for now and the following image may help you guys. When I apply Overflow: Hidden rather than Visible to the main div for the dropdown of datetime options, it seems to quit closing unexpectedly.

<img width="1568" alt="ipad_datetimepicker" src="https://cloud.githubusercontent.com/assets/2963132/10910190/06699c74-820c-11e5-9a8d-d50cdae060b0.png">

**Comment by papaytl185** [comment]
This style seems to have fixed the issue.
div.k-animation-container {
            overflow: hidden !important;
        }

**Comment by papaytl185** [comment]
That css override ends up causing other issues, so this is not a good fix.

**Comment by Iankodj** [comment]
Not reproducible using recent version of Kendo UI under Android and iPad.  http://dojo.telerik.com/eLURI

The only event that closes the DateTimePicker's popup is the mousedown handler (https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.popup.js#L479-L502), which closes the popup only if the mouedown is triggered outside it. And that is an expected behavior.
