### ISSUE TITLE
data-value of calendar

### ISSUE THREAD

**Issue by icyflash** [telerik/kendo-ui-core#1249]
It is February, but data-value is 1.

![58](https://cloud.githubusercontent.com/assets/578257/11114360/2b7a2380-895f-11e5-920c-6f230fdb547c.png)

**Comment by icyflash** [comment]
Get it

toDateString: function(date) {
                return date.getFullYear() + "/" + date.getMonth() + "/" + date.getDate();
}

getMonth() return 0~11

**Comment by icyflash** [comment]
Why close?

toDateString() returns the wrong value,  need to be fixed.

**Comment by ggkrustev** [comment]
Please excuse me for closing the issue without posting a comment. I thought that you've found the answer of your first question.

As to the described behavior, it is intended. The data-value is used internal to create new Date instance. Even though it has date-like format, it is used strictly for internal purposes. 

What exactly you are trying to achieve and need to use data-value attribute?

**Comment by icyflash** [comment]
I have some data like:
```javascript
[{
    'date': '2015-11-11',
    'count': 3
},
{
    'date': '2015-11-12',
    'count': 4
}]
```

I wanna to add the count to the cell as a badge like this:
<img width="296" alt="1" src="https://cloud.githubusercontent.com/assets/578257/11124331/6ed2255c-899f-11e5-8787-c301c25a22d3.png">

**Comment by ggkrustev** [comment]
Thank you for the clarification.
As I mentioned, the `data-value` attribute is designed for specific, internal usage, where the values are passed directly to the JavaScript Date function. We do not consider this behavior as a bug as it is intended. Changing the rendering will introduce a breaking change.

That said, we do appreciate your feedback, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!
