### ISSUE TITLE
Switch does not function if initialized in a hidden container

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1320]
Reproducible here http://plnkr.co/edit/QXl96X0cznwZtJpgp7Ix?p=preview

**Comment by underlog** [comment]
The problem is "by design". The switch performs some measurements upon initialization. Changing this means to re-write most of the switch. One of the ways to overcome this problem would be through the k-ng-delay or k-ng-rebind attribute + initialization of the respective scope flag when the switch is visible.
