### ISSUE TITLE
kendoMultiSelect long value block goes beyond the limit of selects' area

### ISSUE THREAD

**Issue by torfeld6** [telerik/kendo-ui-core#1322]
Please have a look at the following screenshot:
http://screencast.com/t/wlzipD5xY7

As you can see in the devices selection the value goes beyond the size of the selection itself.

**Comment by naskog** [comment]
Hi @torfeld6 ,

Thanks for your post, and for your interest in Kendo UI Core! 
We tried to replicate the issue reported but to no avail. Tests were performed using the following dojo snippet:

[http://runner.telerik.io/fullscreen/@naskog/edUVe](http://runner.telerik.io/fullscreen/@naskog/edUVe)

In order for us to be able to quickly verify this issue, we’ll need a runnable test case that reproduces the problem you’re experiencing. To create a repro, head on over to the [Kendo UI Scratchpad](http://trykendoui.telerik.com/), reproduce your issue using the latest version of Kendo UI, and create a new issue with a link to the test case. Please note that, in order to be considered, your repro must target the *latest version of Kendo UI*. Bug reports against previous versions will be closed.

Once we’re able to verify the issue, we’ll follow up and let you know when to expect a fix.

Thanks again for the issue report, and for using Kendo UI Core!

**Comment by torfeld6** [comment]
Hi @naskog. I did as you told and the new issue's here: https://github.com/telerik/kendo-ui-core/issues/1328
