### ISSUE TITLE
Widget sends filter value twice

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1373]
### Description

For some reason, widget sends filter value twice to the server.

Repro demo: http://demos.telerik.com/kendo-ui/dropdownlist/cascadingdropdownlist
Steps:
1. Select a value from Categories
2. Select another value from the same widget
Inspect the request and notice how the filter value is sent twice:

![2016-01-18_1121](https://cloud.githubusercontent.com/assets/495188/12387513/c6a03930-bdd5-11e5-81a7-686595822ae4.png)

Reported in TicketID: 1001439

**Comment by pepinho24** [comment]
Cascaded ComboBox or DropDownList adds filters instead of changing them which results in very long query string that throws an error "HTTP Error 404.15 - Not Found …because the query string is too long".  The issue is reproducible in the Cascading ComboBox demo with version 2017.1.16 as demonstrated in this [screencast](http://screencast.com/t/ZaMDBj3BmB)
