### ISSUE TITLE
DataSource cancelChanges method does not undo deleted models when called with paramter

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-ui-core#1377]
The DataSource "cancelChanges" method does not undo deleted models when called with parameter. It's expected that the model passed to the method is returned to it's original state even if it's already deleted. 

For example:
````
var model = dataSource.view()[0];
dataSource.remove(model);
dataSource.cancelChanges(model);
//at this point it's expected that the model is removed from the destroyed items collection and returned to the dataSource data
````

Reported in Ticket ID: 1000522

**Comment by danielwermann** [comment]
I am experiencing the same issue.

**Comment by rkonstantinov** [comment]
I'm afraid that the behavior in question is by design. It is not possible to re-insert the model to the position prior the destroy operation. The actual state of the data collection, might have been already changed multiple times when the cancelChanges method is execuded. Reverting changes to destroyed record is only possible if the entire data is reverted by calling the cancelChanges without parameters.
