### ISSUE TITLE
Boolean column could not be edited in Safari ("incell" edit mode)

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#1418]
The issue could be replicated in the Batch Editing demo:
[http://demos.telerik.com/kendo-ui/grid/editing](http://demos.telerik.com/kendo-ui/grid/editing)

Steps to reproduce:
1-> Open the kendo grid in batch editing mode by clicking the below link in safari
2-> You will four columns in this sample ri 
3-> click on fourth cell (discontinued)
4-> You will see a check box in that cell
5-> Now try to check/uncheck the checkbox using mouse (click the checkbox)
6-> You will notice that cell goes in read mode without checking/unchecking the check box

**Comment by naskog** [comment]
We are aware of this behavior. It is a browser issue, that can be reproduced without Kendo UI as well. Here is an example:
 
[http://dojo.telerik.com/itaVU/2](http://dojo.telerik.com/itaVU/2)

What happens is - focusout event of the parent element is fired, when the checkbox inside is clicked, which is not the expected behavior and works differently in other browsers. 
We have already submitted a bug report for Safari (ID 22434512 at [https://developer.apple.com/bug-reporting/](https://developer.apple.com/bug-reporting/)). 

The [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1234766) also exists in Firefox for OS X.
