### ISSUE TITLE
Failed to instantiate module kendo.directives using JSPM/SystemJS

### ISSUE THREAD

**Issue by mfidemraizer** [telerik/kendo-ui-core#1421]
Please take a look at the following issue I've already published on StackOverflow: [Failed to instantiate module kendo.directives using JSPM](http://stackoverflow.com/questions/35200734/failed-to-instantiate-module-kendo-directives-using-jspm).

I'm experiencing big troubles trying to load this package using SystemJS. If I import `"kendo-ui"` module, even when I've already checked that it's loading `"kendo.ui.core"` which includes Angular directives, the whole Angular module is never loaded. 

Actually, I've been digging on `"kendo.ui.core"` source code, line 40K is never executed before my own module loading `"kendo-ui"` is already loaded.

How do I fix this?

Thank you in advance.

**Comment by mfidemraizer** [comment]
For now, I've managed to fix it using some workaround. Check [my own answer](http://stackoverflow.com/questions/35200734/failed-to-instantiate-module-kendo-directives-using-jspm/35221597#35221597) to the Q&A on StackOverflow.

**Comment by underlog** [comment]
The problem you are facing is due to the named AMD modules we introduced - several discussions are available in the closed issues of this repo. You may also use [this help article](http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-requirejs#use-angularjs-and-kendo-ui-with-requirejs) as a starting point.

**Comment by mfidemraizer** [comment]
@underlog BTW, this article (particularly SystemJS one) won't work in my scenario. 

I believe you need to re-think how you name Kendo UI dependencies. For example, if you use the minified suite, Kendo UI requires *jquery.min*. I don't think dependency names should change based on a physical detail (minified/raw).

In the other hand, the whole approach won't work with Angular if you use *kendo.all* distribution (or even just *kendo.ui.core* including all core components): Angular directives aren't loaded and the whole module isn't available.

Finally I did this:
        ...
        paths: {
            "local:*": "js/lib/local/*",
            "kendo.*": "js/lib/local/kendo-ui@2016.1.125/js/kendo.*.min",
            } 
        ...
        map: {
            "jquery.min": "github:components/jquery@2.2.0",
            "kendo-ui": "local:kendo-ui@2016.1.125/js/kendo.imports",
            "kendo.core.min": "local:kendo-ui@2016.1.125/js/kendo.core.min",
        }

Since I want to use Kendo UI Professional, I had to download the package and place in some local location. 

Also, because I need to integrate it with Angular, I'm importing *kendo.angular* in some JavaScript file, and since it requires *kendo.ui.core,min* (I still don't understand why you suffix the module name with `.min`) I had to map it too.

**Comment by mfidemraizer** [comment]
Update: Sadly the above solution doesn't fix the issue at all... For example, if I try to import *kendo.colorPicker*, since this module requires *kendo.popup*, *kendo.slider* and *kendo.userevents* and these are actually called using the *.min* suffix, SystemJS tries to load *kendo.popup.**min.min**.js*...

Actually I feel the stable solution is loading Kendo UI + Angular directives using regular `<script>` tags without using SystemJS at all. This has an additional problem: I'll need to load both jQuery and Angular without SystemJS to let Kendo UI work...

**Comment by underlog** [comment]
> I believe you need to re-think how you name Kendo UI dependencies. For example, if you use the minified suite, Kendo UI requires jquery.min. I don't think dependency names should change based on a physical detail (minified/raw).

Correct - especially the jQuery dependency was wrong. We have fixed this in #1379

I am not sure that I understand the rest of the message. The .min suffix is necessary so that requiring kendo.dropdownlist.min.js will (correctly) pick the kendo.popup.min.js dependency. 

Also, did you check this help article? http://docs.telerik.com/kendo-ui/third-party/systemjs .

**Comment by IlBaffo** [comment]
Why do you change modules names in the minified version?
It is ok to change file names but the whole point of dependency injection is to be transparent for the invoker, min and not-min files could be even mixed without changing anything but the path in the require config.

**Comment by mfidemraizer** [comment]
@IlBaffo  This is my point.

**Comment by underlog** [comment]
@IlBaffo - perhaps I am missing something here. Is there a way (in requirejs) to map `kendo.*` to `kendo.*.min`? SystemJS can do that quite easily, but I did not find that for RequireJS, which we support, too.

**Comment by IlBaffo** [comment]
That was what I have tried to do but I didn't find a way. You have to specify every single path in the config.
But, since I am using "kendo.web", i don't need to require single widgets so I ended up with a short config.

**Comment by IlBaffo** [comment]
Also, at one point I have tried to minimize "Kendo.Web" by myself but I couldn't because many minifiers failed on the task.
In particular, the "[Bundler & Minifier](https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40)" extensions that uses "Microsoft Ajax Minifier" fails with the error "[Can't have 'break' outside of loop](https://github.com/madskristensen/BundlerMinifier/issues/39)" but this is not your fault because JS specifics allows the use of break in label blocks.
