### ISSUE TITLE
Keyboard jiggling in Win Phone 10 (Edge)

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1425]
Navigate to [http://demos.telerik.com/kendo-ui/numerictextbox/index](http://demos.telerik.com/kendo-ui/numerictextbox/index)
Tap in an Numeric TextBox

Result: The virtual keyboard is popping up for a second and then it closes automatically
[https://onedrive.live.com/redir?resid=F988A5B9FE59C6AD!5502&authkey=!AI6vtomgdScspK0&ithint=video%2cmp4
](https://onedrive.live.com/redir?resid=F988A5B9FE59C6AD!5502&authkey=!AI6vtomgdScspK0&ithint=video%2cmp4
)

Reported in Ticket ID: 1007967

**Comment by tapopov** [comment]
After investigating, @ggkrustev and I concluded that this behavior is caused by the Edge browser. The behavior is easily reproduced without using any Kendo UI widgets, as seen [here](http://dojo.telerik.com/@popov/AJuRu). The solution would be to toggle the inputs' visibility a bit later on instead of immediately after the `touchend` event is triggered. This is also illustrated in the above example.
