### ISSUE TITLE
sprite error in IE and Edge:

### ISSUE THREAD

**Issue by kennywangjin** [telerik/kendo-ui-core#1456]
**Kendo-UI-Boostrap**** Datepicker and numeric textbox show their sprite incorrectly when in IE and Edge browser with value filled, while correctly when no value filled. They are rendered correctly in chrome!
widgets with value:
![datepicker-error](https://cloud.githubusercontent.com/assets/3364218/13213065/34929e80-d981-11e5-82a4-e228f79b8e47.PNG)
![numeric-error](https://cloud.githubusercontent.com/assets/3364218/13213066/3561f1bc-d981-11e5-8cdc-8d58c2ff816c.PNG)
widgets without value (empty):
![datepicker-ok](https://cloud.githubusercontent.com/assets/3364218/13213073/3e903d5c-d981-11e5-9106-de3bc81abe6c.PNG)
![numeric-ok](https://cloud.githubusercontent.com/assets/3364218/13213077/4038e5d2-d981-11e5-87f8-279b4472a2aa.PNG)

Please help to check! 
How to fix that?

**Comment by naskog** [comment]
We were not able to replicate the issue in our [online demos](http://demos.telerik.com/kendo-ui/datepicker/index)

![image](https://cloud.githubusercontent.com/assets/961037/13217189/50fa10b6-d969-11e5-9cd1-3686c47659b8.png)

Please create an isolated runnable example in a [Kendo UI Dojo](http://dojo.telerik.com/), where the issue is present and we will be happy to take a look

**Comment by kennywangjin** [comment]
Thanks for your response.
I noticed that these problems only occur on my 2 different laptops (Win10 10586 / 14267). The other computers work correctly. Even I have rebuilt my operating system, the problems are still there. That's really weird.
I'm sure that's not your widgets' problems. They are really great.
Thanks again for your response.
