### ISSUE TITLE
NumericTextBox doesn't support floating point numbers with a "-" decimal separator in "kk" culture

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1490]
When a floating point number in the format X-XX is entered in a NumericTextBox, the widget's is changed to null when the input loses focus.

Steps to reproduce:

1) Open http://dojo.telerik.com/iruHO/3

2) Enter 3-14 in the input and click outside the box

Expected result: ₸3-140
Actual result: the value of the widget is null, the content of the input is an empty string

**Comment by ag-petrov** [comment]
The issue is caused by the duality of the "-" character meaning. It serves both as a minus symbol and decimal separater. There are cases in which it is not clear how a value should get parsed. For example it is not possible to determine whether "-3" should be parsed as 0.3 or -3. Moreover altering the logic to interpret the "-" symbol as a decimal separator can cause a breaking change which is not desirable.
