### ISSUE TITLE
License header of CSS files from CDN

### ISSUE THREAD

**Issue by fskpf** [telerik/kendo-ui-core#1492]
Hi,

the readme recommends using the Kendo-UI-Core via cdn. Obviously, this is fine for the kendo.ui.core.min.js since it contains the Apache License header. However, the css files (from the cdn) state that they're part of Kendo-UI-Complete.

It is unclear to me, if I'm allowed to use them for my Kendo-UI-Core application without having a commercial license. Especially concerning the bootstrap theme, i.e.

http://kendo.cdn.telerik.com/2016.1.112/styles/kendo.common-bootstrap.core.min.css
http://kendo.cdn.telerik.com/2016.1.112/styles/kendo.bootstrap.min.css

which are both part of the Kendo-UI-Core github repository.

Or is there another cdn link for the css files with an appropriate Apache License header?

**Comment by tsvetomir** [comment]
I'm afraid we don't have the required metadata during the build process of the CSS files. We can't immediately tell if one file is originating from Kendo UI Core or not. They all get the same license header as a result.

The other option is to use different URL for Kendo UI Core. Doesn't sound like a great solution.
I'm closing this as Won't fix for the moment due to technical limitations.

You're free to use everything included in Kendo UI Core under its MIT license. If the license header is causing you trouble, feel free to use a local build of the styles.
