### ISSUE TITLE
DateTimePicker sets incorrect time on day that switches daylight savings time

### ISSUE THREAD

**Issue by frankhuiskamp** [telerik/kendo-ui-core#1552]
Open below link with your computer set to timezone UTC +1 (Amsterdam) and date on March 27.

http://dojo.telerik.com/UfUZi

In the Kendo DateTimePicker select date: March 27 2016 and time: 02:00. The time component will jump to 03:00. This is expected behavior as that is when daylight savings begins in the Netherlands.

However, if we set the date to anything after March 27 and try to set the time to 02:00, it will still jump to 03:00. The problem only seems to occur if selecting the time from the dropdown. Entering 02:00 manually in the text field does not make it jump to 03:00.

This only happens if the computer's date is March 27. If the example is run on March 28 everything works as expected.

I have not yet verified if a similar problem occurs on the date daylight savings ends.

Tested on KendoUI version 2016.1.226

**Comment by ggkrustev** [comment]
Hi @frankhuiskamp,

The described behavior is caused by the way TimeView is implemented. Basically, we pass the selected string "02:00" to the parser, which will use the today's date (JavaScript Date always contains date and time portion) to create a Date object. 

https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.timepicker.js#L380

As in this date DST happens, the user would not be able to select anything in that time.

We will further investigate how to overcome this limitation. I am afraid that there is no feasible workaround that we could suggest.

**Comment by MilenaCh** [comment]
Another scenario about the same problem:

TimeView shows wrong time in some time zones(tested with Central time US and Canada) 
![image](https://user-images.githubusercontent.com/3844466/52862818-d69f2c80-313e-11e9-87db-78b7fc21ec71.png)
Example: https://dojo.telerik.com/abeWIdes
TicketID: 1388092

**Comment by slapheadted** [comment]
I've had success with this solution (at least to the problem of 12:00-1.30 repeated):

```$("#timepicker").kendoTimePicker({
  min: new Date(2019,02,10,12,,
  max: "23:30"
})

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1412567. Raising priority.

**Comment by Xizario** [comment]
@Alex-Bubblemaster, 
`31/03/2019 3:00 AM` does not exist in Bulgaria. The times goes from `2:59:59` to `4:00:00` in 1 second. This is same way as Outlook works for example, try to schedule an appointment for this particular time. 

My point is, even if the bug above exist, the last case is something that is probably different and this client have some issues configuring the moment.js library that he is using.

**Comment by Alex-Bubblemaster** [comment]
Another report in ticket with ID 1408475. [Dojo](https://dojo.telerik.com/@bubblemaster/AJAFeWuK) with instructions.

**Comment by gyankov** [comment]
The issue with the duplicating time options in the time picker occurs since internally we have a condition which checks whether there is a difference in the timezone offset between the current date and the previous date when generating the options. In case there is such a difference, we adjust the current date accordingly. However, in the case where the time changes, we have аn offset of one hour. Due to the time change, the current date is no longer in the same timezone as the previous date and from 01:30 the next slot becomes 03:00. Then when we try to adjust the timezone by decreasing with one hour to 2:00, as this is a not existing time, the Date object sets the time to 01:00.  

I have discussed this with my colleagues and we agreed that the most reasonable solution would be to skip adding an option to the time picker for the hour when the time changes as even if the options exists, the user will not be able to select it. For example, 01:00, 01:30, 03:00, 03:30.

**Comment by dmanova** [comment]
In this issue are described 3 different cases. After testing all 3 the status is:

1. Not fixed :  DateTimePicker shown in http://dojo.telerik.com/UfUZi 
2. Fixed and Verified : TimePicker shows wrong time in https://dojo.telerik.com/abeWIdes
3. Not fixed : DateTimePicker shows next date shown in https://dojo.telerik.com/@bubblemaster/AJAFeWuK

If any of the cases is not related to the others, please enter another issue. 

P.S. If you use Sofia time zone you should test with 31.03.2019 03:00

**Comment by dmanova** [comment]
The three described cases are fixed and verified.
