### ISSUE TITLE
Grouped DataSource does not return ObservableObjects

### ISSUE THREAD

**Issue by frankhuiskamp** [telerik/kendo-ui-core#1553]
If a datasource is grouped, it can not be bound in MVVM.

http://dojo.telerik.com/IVeSU

The above code will cause an error because the click binding can not be found. The text binding is also not working.

**Comment by underlog** [comment]
Indeed, this is so. Actually The MVVM binding does not support grouped data source at all, because the scenario is quite complicated. For instance, you need two templates - one for the group and one for the item in it. In the dojo, the [object object] being displayed is the actual group. However, as you have correctly noticed, the group itself is not an observable object, which means that you can't "nest" the binding further. 

Given the above, I may suggest that you use one of the widgets which support grouping out of the box.
