### ISSUE TITLE
Dropdowns are appended to a wrong body tag, if there are multiple body tags on the page

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1559]
When an object of type foreignObject with the tag body is present in the page (third-party library, generating valid SVG), the dropdowns of the DropDownList are attached to the SVG's body instead of the document.body.

![227c596e-3609-4f49-8771-420ec5efd44b_pic1](https://cloud.githubusercontent.com/assets/7533599/14209149/679ee9be-f82b-11e5-8c03-2a11445fe385.png)
![fb4e4880-cea9-4587-b1e8-62f19f801549_pic2](https://cloud.githubusercontent.com/assets/7533599/14209155/6cc2c47e-f82b-11e5-89c5-834865d9233d.png)

### Repro demo

http://dojo.telerik.com/eriWU

**Comment by palmor** [comment]
I found this issue as well and I have a proper fix for it. I guess I'm gonna fork to create a pull request, I need this change.

**Comment by ggkrustev** [comment]
@palmor, I couldn't replicate the issue in a standalone demo. Could you assist with that task?

Here is my attempt to reproduce the erroneous behavior
- http://dojo.telerik.com/OhIWE

**Comment by palmor** [comment]
Hi @ggkrustev, I did a comment in the pull request, you can't replicate the issue from your dojo tool, the reason is that your standalone tool remove the body tag from other html entities. In the Ticket ID:1023316 I provided a zip with an example of the issue in a simple html that you can run from your local. Let me know if you want me to forward to you the zip.

**Comment by ggkrustev** [comment]
@palmor thank you for the additional details. Indeed, the repro demo in the ticker were very helpful. I updated the main comment to add  a repro demo.
