### ISSUE TITLE
TabStrip gains focus on scrolling of the containing div

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1636]
If the TabStrip contains inputs, and the focus is on one of them, after the containing div is scrolled, the TabStrip takes the focus away from the input.

The issue can be observed here:

http://dojo.telerik.com/IPEGa/13

**Comment by vladimirivanoviliev** [comment]
The difference between the TabStrip and the plain HTML demo is the missing `tabindex` attribute in the second case. When you add this attribute to the demo it starts to behave the same way as the Tabstrip. Please keep in mind that this attribute is required in order to make the widget ARIA compatible.
