### ISSUE TITLE
Support user-defined names

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1701]
This story includes an API, persistence and UI elements to support defining custom names.

The Spreadsheet already implements the internals needed to use the defined names in formulas.

**Comment by tsvetomir** [comment]
Early design mock-up for the UI:
![image](https://cloud.githubusercontent.com/assets/90405/11761597/83b39df4-a0d1-11e5-88d5-5957115eef29.png)

**Comment by mishoo** [comment]
This feature is almost done (on branch `spread-user-names`) and I'd like to get some feedback before I merge the branch in.  Here are some notes.

Test in `playground/spreadsheet/sheet.html`.

First, a styling issue that perhaps @gyoshev can help with.  To place the name editor to the left of the formula bar, I've used a `<table>` ([see code](https://github.com/telerik/kendo/blob/spread-user-names/src/spreadsheet/view.js#L606)). Looks almost good to me, but somehow the formula bar has a black border now (I guess the `<table>` prevents border-color from being inherited).

![toolbar](https://cloud.githubusercontent.com/assets/334725/16772152/bf238868-485b-11e6-952f-eb366428a79a.png)

If you prefer me to attempt to do it without `<table>` please let me know. Also, the name editor styles are [still in playground](https://github.com/telerik/kendo/blob/spread-user-names/playground/spreadsheet/sheet.less).

Brief description of current functionality:

- select a range and type a name in the name editor, press ENTER.  Now you've defined a name for that range, can can use it in formulas instead of typing the range.

- to delete a name, click the "x" in the dropdown.  This operation is undo-able (as well as defining a name), so I did not include a confirmation dialog.  Still, we could display a warning if the name is referenced in formulas — should I work on this?

- the named references created from the UI are absolute and fully qualified (i.e. `Sheet1!$A$1` instead of just `A1`).  They are properly adjusted on insert/delete rows/columns.  XLSX import/export works fine.

- names are adjusted when a sheet is renamed.

- we also support relative references through the API.  Example:

  ```js
  spreadsheet.defineName("TOTAL", "SUM(R1C:R[-1]C)");
  ```

  Now we can type "=TOTAL" in any cell, in any sheet, to get the sum of all cells above it.  It's a pity this doesn't work in any other tool (tried Excel, LibreOffice, Google Sheets and Gnumeric Spreadsheet).  The reference there *has* to be in `RC` notation, because only this notation can represent a relative reference unambiguously (to properly read a reference like `A1` we need know the cell where it is used; but there's no such thing for defining names).

  Excel does support a form of relative references (they must always have the `Sheet1!` part though), but only in `A1` notation.  I tried the following.  Select cell D3, open Name Manager (in tab Formulas) and create new name `TEST` with value `Sheet1!A1:C3`.  Typing `=SUM(TEST)` works as expected both in D3 and D4 (the reason why the value differs is because the reference is relative; it's correct).  Then select cell A5 and open Name Manager, and look what it did to the name:

  ![excel-bug](https://cloud.githubusercontent.com/assets/334725/16772048/5595c190-485b-11e6-8dc1-9aa58c8bca7b.png)

  It even serializes the name like this:

  ```xml
  <definedName name="TEST">Sheet1!XFB1048575:XFD1</definedName>
  ```

  I don't get how, but Excel is able to read back that file.  Our import doesn't work properly yet in this case.  UPDATE: [figured it out](https://github.com/telerik/kendo/commit/51b68c68fcb93e11737eb8e5ed9ebe3bca9f5374).

  Google Sheets does not support relative references in names, and no formulas either — names must be fully qualified absolute ranges.

  Neither one supports references that have no sheet in a name definition.

**Comment by tsvetomir** [comment]
Great work, Mihai :+1: 

- A confirmation dialog would be a bit of annoyance. I'm more in favor of letting know the user that the action can be undone, GMail style. But that's something @yordanov can think about, not a requirement for this task.

- Can you get the user-defined names to appear in the formula auto-complete?

@ivanchev we'll also need to add the corresponding support in the server-side export module as well

**Comment by gyoshev** [comment]
I pushed some basic styling and used a few other-than-a-table elements. Currently looks like this, but it should be checked by @yordanov, too.

![image](https://cloud.githubusercontent.com/assets/90405/16804198/46d7e5ee-4913-11e6-8e2d-b53111518a7a.png)

Currently, the UI does not use any widget, and has a separate rendering. Why not use the ComboBox, so that we inherit its keyboard support and styles?

**Comment by mishoo** [comment]
@gyoshev the bar looks much better, but the popup seems broken:

![popup](https://cloud.githubusercontent.com/assets/334725/16810434/7e5d0d6e-492c-11e6-8c86-52b916578add.png)

I'll try to fiddle with the ComboBox.  Indeed, keyboard support would be nice.

**Comment by mishoo** [comment]
@gyoshev I changed it to use a ComboBox.  The only problem now is that when I mouse over a resize handle, the popup closes:

![popup](https://cloud.githubusercontent.com/assets/334725/17811667/6bd30dd4-662c-11e6-932c-e0ad607206a3.gif)
I suspect it's because the Spreadsheet's render is triggered, and it steals focus from the combo (maybe the clipboard stuff?) — any idea how to fix this?

**Comment by gyoshev** [comment]
The combobox seems great, nicely done!

The problem with hovering the resize handles is quite annoying. I believe it is triggered also when using all other drop-downs in the toolbar. A way to workaround this is to raise a flag in the worksheet object when a drop-down is opened, so that the resize handles do not trigger a refresh. Not very great, but the only other alternative that I can come up with is to pull out the resize handles outside the view rendering code, and that seems to be a bigger hack.

**Comment by mishoo** [comment]
Indeed, it's happening with the font family/size selectors.  Not with the border or color pickers though, which is strange.  I'll investigate further, perhaps there is an even simpler solution.

**Comment by mishoo** [comment]
@gyoshev [this](https://github.com/telerik/kendo/commit/9258c9e476d97089c298cf9d269651da9f293012) fixes it for the user names popup.  Not great either, but I like it more than a flag on the spreadsheet.

**Comment by tsvetomir** [comment]
Stopping the mousemove propagation here actually seems pretty decent solution. And it reuses the flag that is already in the browser event code :) #saynotoflags
