### ISSUE TITLE
JS error after typing characters via AltGr (Ctrl+Alt)

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-ui-core#1714]
Steps to reproduce:

1. Switch to a Italian keyboard layout
1. Focus a cell (say, H4) and type `Ctrl+Alt+;` or `Ctrl+Alt+'`.
1. Click on a cell with a formula (say, F4)
1. A JS error is triggered from the clipboard contents rendering

The codes above correspond to the @ and # characters, but are not inserted into the formula input; maybe this is the culprit of the issue.

Reported in ticket ID 1034908

**Comment by mishoo** [comment]
I can't manage to repro this one (that is, I don't get any errors).

But indeed, when I press `Ctrl-Alt-;` nothing happens (it only inserts a `@` if I open the editor first with `F2`).  This is because, presuming we add `"alt+ctrl+:alphanum": "edit"` in [ENTRY_ACTIONS](https://github.com/telerik/kendo/blob/master/src/spreadsheet/controller.js#L32), `event.mod` is true on [this line](https://github.com/telerik/kendo/blob/master/src/spreadsheet/controller.js#L353), and the editor is not opened.

I'm not sure how to fix.

**Comment by gyoshev** [comment]
From what I gather, [AltGr can only be detected as `ctrl+alt`](http://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press). Seems like a good idea to handle it, as it is [used on quite a few keyboards](https://en.wikipedia.org/wiki/AltGr_key#Romanian). I couldn't get it working with the line added to `ENTRY_ACTIONS`, though.

**Comment by mishoo** [comment]
> I couldn't get it working with the line added to ENTRY_ACTIONS, though.

Yeah, it's not working because `event.mod` is true (set on [this line](https://github.com/telerik/kendo/blob/master/src/spreadsheet/eventlistener.js#L123) when Ctrl is on) and in controller's `onEntryAction` we don't enter the branch that activates the editor ([see code](https://github.com/telerik/kendo/blob/master/src/spreadsheet/controller.js#L353)).

**Comment by mishoo** [comment]
Please review https://github.com/telerik/kendo/commit/ed6d1de41f2bb6a8f369f99e9b7337a004bd8558 (branch spread-issue-1714), that seems to fix the issue at hand, but I'm not entirely sure it's correct.

**Comment by gyoshev** [comment]
> Yeah, it's not working because event.mod is true

Ah, I overlook this previously, sorry.

> Please review telerik/kendo@ed6d1de

This solves the JS error on my side, and triggers edit mode correctly for `AltGr` characters. The only noticeable change is that now `ctrl+alt+:alphanum` enters edit mode even if no character will be inserted, but I'm not even sure if we can detect this. I say :shipit:

**Comment by mishoo** [comment]
> The only noticeable change is that now ctrl+alt+:alphanum enters edit mode even if no character will be inserted, but I'm not even sure if we can detect this.

Yeah, noticed.  I too think it can't be avoided.

> I say :shipit:

The test suite checks out.  Merged.
