### ISSUE TITLE
Cascade event is fired without changing the widget value

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1738]
Steps describing how the issue is reproduced:
1. Type fr in the combo, it will show France, click it with the mouse. You'll see an alert box confirming it has been selected. Everything goes well, and now France is selected in the combobox.
2. Click the arrow to open the combobox options. The alert box is shown again, and this is not expected as nothing has been selected(changed) (France was already selected before). The user simply asked to open the combobox to see all the options (and might close it without changing the selection which is France).

**Comment by simonssspirit** [comment]
This issue is associated with the following ticket: https://admin.telerik.com/?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1039740&SM=0

**Comment by Iankodj** [comment]
The behavior here occurs because the List triggers the cascade event when the index is changed as well (which is the case of opening the ComboBox's list). 

In my opinion, the cascade event should not be triggered when index is changed, but only when the value is different as this is the main impact on UI element that are cascaded from the component. 

This behavior, however, is introduced due to a bug fix (https://github.com/telerik/kendo-ui-core/issues/584). 

Triggering an event both when value and index is changed seems more relevant to the change event, which already exists. And I am not sure why cascade should act the same as change. Even if custom value is entered that matches an existing value of the data set, still cascade should be triggered. It is up to the cascading logic to process that.

Generally, my opinion is that the bug fix (https://github.com/telerik/kendo-ui-core/issues/584) should be reverted and

**Comment by Dimitar-Goshev** [comment]
After a fix is applied, the described issue is no longer reproducible. But upon testing I found 2 other scenarios, which coincide with the issue's title. They are reproducible even before the fix:
- Open and then close the dropdown of the combobox in the Dojo above - cascade event is fired without changing combo's value.
- Open the dropdown and select an item. Then delete the item though the Clear button - cascade event is fired two times, instead of only once - [R3 2017 Dojo](http://dojo.telerik.com/AdoMe/4)
