### ISSUE TITLE
Router performs unexpected encoding

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#1749]
http://dojo.telerik.com/IMAKo/3  - reproduction. I should double check if this is not by design, the test suite should show that.

**Comment by simonssspirit** [comment]
The issue is fixed when using the router.navigate() but not when the user enters the URL into the URL bar themselves.

The issue can be reproduced in the following Dojo after saving it as a local file: http://dojo.telerik.com/IMAKo/8

Noticed that the router still incorrectly decodes path components.
Router Change /A/B%2FC/D
Router Route A/B/C/D
