### ISSUE TITLE
Editing works on the formatted value instead of the original value

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1763]
In versions up to and including 2016.1.226 clicking on the cell in the [following snippet](http://dojo.telerik.com/@tsvetomir/uCUlu) shows the numeric value of the cell:

```js
    <div id="spreadsheet"></div>
    <script>
      $("#spreadsheet").kendoSpreadsheet({
        sheets: [{
          columns: [{
            width: 150
          }],
          rows: [{
            cells: [{
              value: 1231231231,
              format: " _(* #,##0.00_);_(* (#,##0.00);_(* \"\"-\"\"_)"
            }]
          }]
        }]
      });
    </script>
```

In later versions, the formatted value is shown instead. After editing the value seems to be converted to text.

/cc @ggkrustev @vladimirivanoviliev @mishoo

**Comment by mishoo** [comment]
Seems to have happened for fixing https://github.com/telerik/kendo/issues/5335.

**Comment by underlog** [comment]
Seems that the bug is still here for values less than 100. Reproduction - http://dojo.telerik.com/@petyosi/OQucU

**Comment by mishoo** [comment]
@underlog that's because in this case it can parse back the value as a number (notice it does not convert such values to text).

I'm not sure how to best handle this.  If we always put the unformatted value in the editor, then we will have to edit `42531` instead of `6/10/2016`.  Currently it attempts to maintain the formatted value in the editor, if it can be parsed back to the same value and type as the current cell value.

**Comment by IvanDanchev** [comment]
The behavior shown in the dojo sample linked below might be related to the bug. Numbers smaller than 1000 are displayed rounded in the formula bar and when editing the cell value, whereas the original value is displayed for numbers bigger than 1000: 
[dojo](http://dojo.telerik.com/eRUwe)
