### ISSUE TITLE
Add support for search matching multiple words

### ISSUE THREAD

**Issue by sylvain-hamel** [telerik/kendo-ui-core#1790]
Given a dropdown with these values:
- George Washington
- John Adams
- Thomas Jefferson
- James Madison
- James Monroe

I need to support for searching beginning of word with multiple words "Ja M" to return:
- **Ja**mes **M**adison
- **Ja**mes **M**onroe

I can do it using a custom datasource filter but I'd be willing to contribute a PR that adds a new filter option. Will you accept a PR for that?

**Comment by mparvanov** [comment]
Hi Sylvan,

Thanks for your post, and for your interest in contributing to Kendo UI! Since this issues list is for bugs only, not feature requests, I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this feature request and send us your sample example for the dropdown searching using a custom datasource.

Thanks for your collaboration in advance!
