### ISSUE TITLE
Multi-line content pasted in a cell is visible near top-corner when active

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#1854]
Reported in Ticket ID: 1046041.

Steps to recreate:
- Paste multi-line content into a single cell in one of [our ](http://demos.telerik.com/kendo-ui/spreadsheet/datasource) demos. (test the linked demo with min 5 lines, others need more lines to recreate)
- When the cell is active, it's content hangs around the top-corner, even when scrolling

**Comment by mishoo** [comment]
The formula bar should probably have `overflow: hidden` and not increase its height.  I'll take this one.

**Comment by ipeshev** [comment]
If just click(single) on cell and CTRL+V ( our multiline content) then it fills cells bellow.

**Comment by mishoo** [comment]
@ipeshev That is by design.

When you paste and the editor is not active, you don't just paste text into a cell.  If the clipboard contains HTML, that means it's copy/paste from i.e. Google Sheets (or even Excel — there's no other way we can get data from Excel via copy/paste), and we search for a `<table>` and parse its contents.

When the clipboard data is text, it is assumed to be TSV (tab-separated values), therefore consecutive lines will fill cells in consecutive rows.

**Comment by mishoo** [comment]
By the way, I am not the author of this code, just noticed that it's intentional.  This is a bit constraining — for instance, why TSV?  Maybe it's CSV, or maybe it's just plain text (in which case it would just paste multiline content into a single cell).

We could probably ask the user in a dialog how should we interpret the data. (that would be a new feature, though)
