### ISSUE TITLE
TreeList silently ignores schema errors

### ISSUE THREAD

**Issue by vdachev** [telerik/kendo-ui-core#1857]
I have a `TreeList` component declared in a Razor template like this:

``` cshtml
@(Html.Kendo().TreeList<DirectoryTreeItemViewModel>()
    .Name("directoryList")
    .Columns(columns =>
    {
        columns.Add().Field(x => x.Name);
    })
    .DataSource(dataSource => dataSource
        .Read(read => read.Action(nameof(DirectoryController.DataSource), "Directory"))
        .ServerOperation(false)
        .Model(model =>
        {
            model.Id(x => x.Id);
            model.ParentId(x => x.ParentId).Nullable();
            model.Expanded(true);
            model.Field(x => x.Name).Nullable();
        })
    )
)
```

`Id` and `ParentId` properties are of type `string`, and `ParentId` is `null` for root elements. By default the generated schema for these fields states `nullable: false`, although the `string` type is nullable (is this a bug or a feature worth documenting?), unless `.Nullable()` is called. 

If `.Nullable()` is omitted the binding fails **silently** as if there was no data at all - no alerts, no console warnings, nothing.

**Comment by ag-petrov** [comment]
By default the MVC wrapper does not check whether the type of the Id and ParentId is nullable and the default value is false which is expected. If you want to mark a field as nullable you should do so by calling the respective method. 

As for the binding problem it is probably caused by the type of the Id and ParentId fields. The treelist expects the Id and ParentId to be number fields. When using strings there are cases in which the logic will fail and this is also expected and [was reported earlier](https://github.com/telerik/kendo-ui-core/issues/3142). That said I am marking this item as closed. If you experience problems when using number fields for Id and ParentId please reopen the case so we could further investigate.
