### ISSUE TITLE
Window does not update its options.position when window is moved using keyboard arrow keys.

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#1858]
Please refer to http://dojo.telerik.com/UcESA.

**Comment by gyoshev** [comment]
Indeed, the configuration does not reflect the widget state, yet the window seems to be storing the state in the options. :confused:
This is not reflected in the unit tests, so I'm not sure what we should do.

**Comment by tsvetomir** [comment]
This is pretty non-standard behavior, I say we close that as won't fix. The position can be obtained from the DOM if needed.

**Comment by dimodi** [comment]
The widget state is stored in options... so that when setOptions is used, all existing state, that is not overwritten by the passed method arguments, is preserved.

An alternative way to resolve this is to check what is received in setOptions and execute the corresponding methods conditionally (_dimensions(), _position(), etc)
