### ISSUE TITLE
Inline Editor is not blurred in IE11 on clicking below the tasks

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#1869]
### Bug report
Editing an inline field and then clicking on the empty area bellow the tasks in the treelist does not blur the edited record.

### Reproduction of the problem
1. Run the following Dojo in IE 11 - http://dojo.telerik.com/@zdravkov/iquHo
1. Double click on a record in the treelist to edit any of its columns, e.g. Title
1. Change the value
1. Click on the empty space inside the Gantt, below the treelist

### Current behavior
The cell is still in edit mode

### Expected/desired behavior
The cell is blurred and its value is changed

### Environment
* **Kendo UI version:** 2019.1.220
* **Browser:** IE 11

**Comment by nenchef** [comment]
Closing due to changes in the rendering of the Gantt, low interest for this specific bug, quite a unique scenario, and the fact that Microsoft is looking [towards ending the IE11 support.](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666)
