### ISSUE TITLE
When importing an xlsx with hidden columns to Spreadsheet, the hidden columns letter headings (A, B, C etc.) remain visible and overlap each other

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#1885]
The above issue could be reproduced in the [Import / Export Spreadsheet demo](https://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export).

**Comment by veselints** [comment]
[Book1.xlsx](https://github.com/telerik/kendo-ui-core/files/349508/Book1.xlsx)

![collapsedhiddencellsheadings](https://cloud.githubusercontent.com/assets/3431388/16614407/bb271f86-4379-11e6-9900-77e45bbef2b6.png)

**Comment by tsvetomir** [comment]
This is apparent in the client-side import as well. Pinging @mishoo

**Comment by veselints** [comment]
A related issue might be:
- An xls file created with Excel 2010 with hidden colums;
- The file is Saved as xlsx using Excel 2013;
- The hidden columns are not respected at all in the Spreadsheet, however they remain hidden in the xlsx file.

Sample converted test file:
[TextConvertedMine.xlsx](https://github.com/telerik/kendo-ui-core/files/351846/TextConvertedMine.xlsx)

**Comment by mishoo** [comment]
The issue here is that we only care about the [hidden attribute](https://github.com/telerik/kendo/blob/master/src/spreadsheet/excel-reader.js#L267) when deciding to hide a column/row in import.  We should probably set it hidden if it has a zero width/height, even if the attribute is missing.  Will do that.

**Comment by mishoo** [comment]
This is more tricky than I thought.  Turns out, if you set a column's width to zero, it can be no longer hidden.  Here's [the relevant code](https://github.com/telerik/kendo/blob/master/src/spreadsheet/axis.js#L80-L94).  In short, `axis.hide(column)` will move its width to the `_hidden` list, and set it in the main list to zero (if it's not already hidden), and `axis.hidden(column)` returns true only if the `_hidden` list contains a non-zero value for that column.  Higher level, the following will happen:

```js
sheet.columnWidth(0, 0);
sheet.hideColumn(0);
sheet.isHiddenColumn(0); // returns false
```

To workaround the Excel import issue with minimum impact, I'll just skip setting a column's width to zero, and will mark it hidden instead.  But it's still a bug we might need to revisit.
