### ISSUE TITLE
Component flash when dragging free node-link under IE

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1921]
It can be seen on official demos [here](http://demos.telerik.com/kendo-ui/diagram/layout).
Try to detach a link from some of nodes, then switch the layout to "Tree up", try to drag the freed link.
Component flashes a bit, after flash it is ok , when dragged , but every time layout is switched first drag causes component to flash. On other browsers it is ok.

**Comment by danielkaradachki** [comment]
This occurs because the diagram element must be focused in order to handle key events and in this case the browser automatically performs scrollIntoView. The diagram will restore the scroll position after focus but the in some cases the effect can be seen. Unfortunately there isn't a way to avoid this.
