### ISSUE TITLE
Unable to leave formula editing mode

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1941]
100% reproducable on all browsers in [official demos](http://demos.telerik.com/kendo-ui/spreadsheet/index) 
DBLClick on some cell with formula , click "Undo".
Again DBLClick on same cell. Try to press ESC or ENTER to leave editing state.

**Comment by mishoo** [comment]
A lot of bad things happen because we don't `deactivate()` the editor when it loses focus, as pointed out [here](https://github.com/telerik/kendo/issues/5552) and in [this long thread](https://github.com/telerik/kendo/issues/5686) (for example, see [this bug](https://github.com/telerik/kendo/issues/5686#issuecomment-218987774) also).

Maybe it's time to reopen discussion.  If I remember correctly, the only issue with `deactivate()` on blur was validation, because closing the editor saves the value and if it's not valid we wanted to *force* the user to enter valid data (that is, never save invalid data).  I suggest we give up this requirement, since users *can* enter invalid data in a variety of ways, like, via copy/paste.

**Comment by ipeshev** [comment]
#1964 Has its own workaround in current version.

**Comment by ipeshev** [comment]
It looks fine
