### ISSUE TITLE
Can't undo after #CIRCULAR! error

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1945]
Can be seen in [official demos](http://kendobuild/staging-kendo-ui/spreadsheet/index).
Try to edit F7 cell hold Shit key and select E6 , hit Enter.  More that one cell is populated and when Undo is hit their values are not cleared.

**Comment by mishoo** [comment]
This isn't related to the `#CIRCULAR` error, but rather the fact that undoing a formula that returns a matrix will only undo the field where the formula was entered.

**Test for the CIRCULAR error:** type in A1 `foo`, then edit and type `=A1`.  You get a CIRCULAR error.  Pressing CTRL-Z correctly undoes it (i.e. gets back to "foo").

**Test for array formulas:** Type some numbers in A1 and A2, and in B1 type `=A1:A2+1`.  This formula returns an array, therefore it fills B1 and B2.  When you press undo, only B1 gets back to the previous value.

At this time we don't have a good fix for undoing array formulas.  In the latter example, B1 was modified as a result of typing a formula — so we store the undo information, since that's an `EditCommand`.  B2, however, was filled by formula evaluation (which isn't even called immediately, but after a short timeout).  That's not a `Command`, and we hold no undo.

There is some description about how we differ from Excel for array formulas, [here](http://docs.telerik.com/kendo-ui/controls/data-management/spreadsheet/end-user/list-of-formulas#differences-from-excel).  To be able to implement proper undo for them, we should implement something similar to Excel (require pre-selecting the target range, for a formula to be able to return a matrix, and store all values in the `EditCommand`).  We should lock the cells too, to prevent edition or deletion (same as Excel).  Not exactly a trivial task...
