### ISSUE TITLE
A cell in edit mode will appear available for editing when a new sheet is added.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1979]
**Issue**:  When a cell is in _edit_ mode after a double click and a new sheet is added, the same cell will appear available in the new sheet.

**Reproduced at**: It can be reproduced in our demos - http://demos.telerik.com/kendo-ui/spreadsheet/index

**Steps to reproduce the issue**: 
- Double-click a cell to enter the edit mode.
- Add a new sheet without leaving the edit mode.
- The edit cell will appear in a random place in the new sheet and will be available for editing.

**Telerik admin ticket**: 1052082

**Comment by mishoo** [comment]
See also https://github.com/telerik/kendo-ui-core/issues/1941#issuecomment-232623166

**Comment by mishoo** [comment]
Fixed after https://github.com/telerik/kendo/pull/6380

**Comment by simonssspirit** [comment]
The issue can still be reproduced on our demo page and it was reported in ticket: 1084659.

Additional details from the new ticket:

Dojo: http://dojo.telerik.com/ayulA

Steps:

1. make double click on the cell A3 to enter in edit mode 
2. type any text and without leaving the cell switch to sheet 'xx'
3. You will see bellow the text that you was typing in the back sheet
4. If you make click; the value will set in the cell B2, if you press ENTER, the value will be set in the cell A1

**Comment by jzatarain** [comment]
Any news about this issue?

**Comment by jzatarain** [comment]
At least give us a workaround...

**Comment by simonssspirit** [comment]
@mishoo Could you please take a look at this.

**Comment by veselints** [comment]
Raising priority as reported again in [Ticket ID: 1162053](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1162053)

**Comment by mishoo** [comment]
As far as I can tell, this is intentional — it allows you to select a cell from a different sheet while editing a formula.  Example, type `=1+`, select another sheet and click a cell, and it'll insert a reference of the form `Sheet2!B3`, then pressing ENTER will save the formula and return to the initial sheet.  Google Sheets has this too.

OTOH, I agree that when we're *not* editing a formula (e.g. didn't start with `=`) then we should just save the value and hide the editor.  I'll look into this.
