### ISSUE TITLE
Error when Spreadsheet is initialized in a hidden container

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1990]
Example: http://runner.telerik.io/fullscreen/IQEde (the error reproduces in Dojo's full screen mode)

To reproduce simply click the button and open the window. The sheet grid is not rendered, there is a JS error.

**Comment by ws6** [comment]
I am getting the same problem.
v2016.1.406
pro
thanks for taking look at it.

**Comment by mishoo** [comment]
The error is due to the global `mousemove` handler that the spreadsheet attaches.  I pushed a workaround for it, but one has still to call `spreadsheet.refresh()` in the Window's `activate` handler, as in [this updated dojo](http://runner.telerik.io/fullscreen/@mishoo/inEcA).  Otherwise the spreadsheet will appear empty.

**Comment by tsvetomir** [comment]
@gyoshev: this can be solved if the Window calls kendo.resize upon *activate*. This will help other widgets as well.

**Comment by kingofamani** [comment]
when init, i just set position out of screen...
@(Html.Kendo().Window().Position(p=>p.Top(-1000).Left(-1000)))

**Comment by ipeshev** [comment]
Currently error is not thrown, but it needs to minimize/maximize window to display the cells of the spreadsheet.

**Comment by mishoo** [comment]
@ipeshev As I said, _“one has still to call spreadsheet.refresh() in the Window's activate handler, as in [this updated dojo](http://runner.telerik.io/fullscreen/@mishoo/inEcA). Otherwise the spreadsheet will appear empty.”_

I'm afraid there's no better workaround for now (unless it can be done automatically by the Window widget? /cc @gyoshev)
