### ISSUE TITLE
Widget should place caret at first position on focus if input is empty

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#20]
The issue can be reproduced in Google Chrome and our online demos.

reference ID 811203  and 810627

**Comment by dhmorrison** [comment]
This is not working for me.  I create a kendo-maskededittextbox and set the direction to 'ltr' for western cultures.  The cursor appears in the right-most position of the box when the user activates by clicking an edit button.  This is the *opposite* of what one would expect.  The expected behavior is for the cursor to appear in the left-most area of the textbox so they can enter text *left to right."  Right? :)  When the cursor appears in the right-most area of the box, the user is forced to reposition it by clicking the left-most area of the box.  The opposite is true for the "rtl" setting.  Here the cursor appears in the left-most area of the box, and the user is forced to repostion the cursor.  In either situation the user cannot type without extra work.  This is not great user experience.
