### ISSUE TITLE
Widget with 'hightlightFirst: false' focuses first item

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2001]
### I'm submitting a ...
- Bug report

### Reproduction of the problem
When there is no filter set expicitly, the highlightFirst property is ignored (the first item is focused). The same happens if the suggest property is set to true.
Demo: http://dojo.telerik.com/ejAde/16

Enter "fr" in ComboBox and press enter

### Current behavior
Select "France", which is the first match

### Expected/desired behavior
Select "fr" 

### Environment

* **Browser:** [all]

**Comment by ggkrustev** [comment]
After a detailed research, it turned out that the described behavior is expected.

The widget is designed to **focus the first matching item** when filtering is **disabled** (default state). The `highlightFirst` option is not affect the focusing functionality of the widget in this setup. We will need to scroll to the focused item, however, which we don't do. This, however, is a topic of an another discussion.

To resolve the issue in this particular case, I would enable the filtration. Thus the `highlightFirst` will work:

```
filter: "contains",
highlightFirst: false
```
Working demo: http://dojo.telerik.com/UFAVi
