### ISSUE TITLE
[ASP.NET Core] GridToolBarCustomCommandBuilder does not contain .Action() method as it does in ASP.NET MVC 5

### ISSUE THREAD

**Issue by TeamCityBuildUser** [telerik/kendo-ui-core#2008]
### Reproduction of the problem

When using ASP.NET MVC Core 1.0 the `GridToolBarCustomCommandBuilder` class does not contain `.Action()` method as it does in ASP.NET MVC 5
### Current behavior

The following code is giving me compilation error:

``` cs
toolbar.Custom()
       .Action("Index", "Navigation", new {area = "Administration"})
       .Name("custom-toolbar-button")
       .Text("Back to administration");
```
### Expected/desired behavior

The above code used to work in ASP.NET MVC 5.2.3 but when migrating the project to ASP.NET Core 1.0 it is giving the following compilation error: `CS1929 'GridToolBarCustomCommandBuilder' does not contain a definition for 'Action' and the best extension method overload 'NavigatableExtensions.Action(INavigatable, string, string, object)' requires a receiver of type 'INavigatable'   Stratus.Web.Infrastructure..NETStandard,Version=v1.6`.
### Environment
- **Kendo UI version:** 2016.2.714
- **jQuery version:** doesn't matter
- **Browser:** all

**Comment by eyupyusein** [comment]
The same issue is apparent with Custom command column as well:
` columns.Command(command => command.Custom("Command").Action(...))`

**Comment by eyupyusein** [comment]
This one too:    
.ToolBar(toolbar => { toolbar.Template(...); })

**Comment by eyupyusein** [comment]
columns.Bound(p => p.ProductName).MinScreenWidth(200);

**Comment by primahealthsolutions** [comment]
It's now November 24 - it's been 4 months since this was first reported - what is the solution?

**Comment by primahealthsolutions** [comment]
I just submitted a ticket and got pointed back to this page with an "apology for the inconvenience".   This is getting absurd.

**Comment by GreenStarlight** [comment]
This is a standard piece of functionality that is missing. Very frustrating.

**Comment by primahealthsolutions** [comment]
I agree... I got a work around on top of my hack and when I asked if and
eta on this being added I was told "things are bring added all the time and
no date is set" for anything.

My subscription ends in 2 weeks and I won't be renewing   These off shore
companies better re think their customer service approach.

**Comment by ag-petrov** [comment]
Guys I completely understand your frustration however please bear in mind that the MVC Core wrappers have a different code base than the MVC 5 wrappers. In regards to the issue, in MVC 5 the grid header was rendered on the server and it used html helpers to create action buttons which render a link. However in MVC Core the helper [was removed](https://github.com/aspnet/Home/issues/343). Moreover the grid header is no longer rendered on the server. 

That said with the current implementation in order to get the desired result you can add a toolbar template, attach a click event to the buttons inside, it and navigate manually.

**Comment by dimodi** [comment]
Hello @primahealthsolutions, @GreenStarlight,

My name is Dimo Dimov and I am a support lead at Telerik.

I regret to find out about the negative experience that you have had with our technical support. I am willing to review any relevant support tickets that you have submitted, analyze the possible causes of miscommunication, and discuss ways to avoid such incidents in the future with my colleagues. I found some tickets and forum thredas mentioning this GitHub issue, but in order to be sure that I am not missing anything, can you please post here your support ticket IDs or forum threads?

Thank you in advance. I will be able to comment further afterwards.

Regards,
Dimo

**Comment by Znow** [comment]
Nearly a year since the last comment in this issue, any news?!?!
