### ISSUE TITLE
Virtualized widget may be unable to set its initial value

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#2038]
### Bug report

Virtualized widget (DropDownList in this case) may be unable to set its initial value, depending on which data item it points to.

### Reproduction of the problem
Attached runnable ASP.NET MVC application in ticket 1054743. The DropDownList should have an initial value set, but the value does not appear.

### Current behavior
If the initial value in the Model is "836", it is not applied by the DropDownList. If it is 835 or 837, it is applied successfully.

`Models.CEBE record = new Models.CEBE { Codigo = "000000836" };`
 
### Environment

* **Kendo UI version:** 2016.2.714, 2016.2.804

May be related to https://github.com/telerik/kendo-ui-core/issues/1807

**Comment by Rumpelstinsk** [comment]
When is this problem anticipated to be solved?

**Comment by Rumpelstinsk** [comment]
3 months past after the last comment. Any progress here?

**Comment by ggkrustev** [comment]
@Rumpelstinsk we've worked on tasks with higher priority for the last 3 months. This issue is on the top of our tasks pool and actually we've just started working on it. I am afraid that I cannot share any specific time frame when it will be fixed as the duration depends on the bug specifics.

We will update the thread once we have more details about the issue.

**Comment by ggkrustev** [comment]
@Rumpelstinsk it seems that the issue was resolved in Q3 2016 release (2016.3.914). I would suggest you give it a try. 

Also the upcoming service pack includes several improvements in the Virtualization logic. I would suggest you upgrade directly to the service pack.
