### ISSUE TITLE
Add SharePoint 2013 integration topic to documentation

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2093]
### Current behavior
The [SharePoint 2013 sample project](https://github.com/telerik/kendo-ui-sharepoint-2013-demo) is currently not mentioned in our documentation.

### Expected result
A short summary of what the project demonstrates should be good for a start:
* Widgets used
* Data-binding specifics

The topic should be linked back in the project README.

**Comment by dmihaylo** [comment]
Updates are now deployed to [http://docs.telerik.com/](http://docs.telerik.com/). 

This issue is related to [https://github.com/telerik/kendo-ui-core/pull/2314#issuecomment-253792966](https://github.com/telerik/kendo-ui-core/pull/2314#issuecomment-253792966) and [https://github.com/telerik/kendo-ui-sharepoint-2013-demo/pull/1#issuecomment-254130139](https://github.com/telerik/kendo-ui-sharepoint-2013-demo/pull/1#issuecomment-254130139).

Please close the issue.
