### ISSUE TITLE
Validation not working correctly in Mozilla Firefox

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2114]
### Bug report/Feature request

After a correct value is set in the cell, the validation error message will still appear. 

### Reproduction of the problem

The problem can be reproduced in our demo in Mozilla: http://demos.telerik.com/kendo-ui/spreadsheet/validation

_Steps:_

1) Enter an invalid value in column E and the error message will appear.
2) Delete the whole text from the cell.
3) Enter a valid value and the error message will still appear.

### Expected/desired behavior
The error message does not have to appear if a valid value is set.

### Environment

* **Kendo UI version:** from 2016.2.504, it is working as expected up to version 2016.1.412.

* **Browser:**  Firefox

**Comment by vladimirivanoviliev** [comment]
After some investigation it seems that current the behavior most probably is browser-specific (issue). The issue is that the parse function in the "calc.js" receives the editor value with new line character appended (in FF browser) at the end. When you type "text" in the editor here is what is the result:

- FF editor value: "test\n"
- Other browsers editor value: "test"

This can be reproduced by open the editor for column with boolean value, delete it **using backspace**, type new value and press enter to save it. 

Possible source of the issue is the way the new lines are added in the editor. See 6686c02 commit in private repo.

**Comment by mishoo** [comment]
Looks like a browser bug.  Firefox inserts a newline into an element with `contenteditable` as soon as the cursor reaches a space char, or when the element becomes empty.  That newline stays there when you next try to type something (I mean, you can't even delete it).  A quick demo here (vanilla JS, no Kendo): http://lisperator.net/@file/156/9dd1891dbc46e7ac156383f7886d45608db3a8e2/contenteditable2.html

I'm not sure how to workaround, but probably just ignore a final newline in Firefox...?
