### ISSUE TITLE
RecurrenceEditor should honour Start/End date/time pickers update

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2118]
### Feature request

[End recurrence On date](http://screencast.com/t/i4bLFndgAo) should be updated based on the Start/End date/time pickers. 
### Current behavior
- Start creating event (e.g. 20 aug 2016). Start and end date are 20 aug 2016
- Set the start and end date in the future (e.g. 25 aug 2016)
- Set recurrence to Daily. The End On date is still the initial one (20 aug 2016) 
### Expected/desired behavior
- Start creating event (e.g. 20 aug 2016). Start and end date are 20 aug 2016
- Set the start and end date in the future (e.g. 25 aug 2016)
- Set recurrence to Daily. The End On date should be updated based on the new dates in the Start/End pickers (e.g. the End On date should be the same as the End Date) 
### Reason for Suggesting the Feature

The user would like to end the recurring event after at least one occurrence.

**Comment by Dimitar-Goshev** [comment]
@veselints Adding a validator, which compares the End On and the start date is a partial solution of the issue - it covers the scenario from the issue's description. But it does not cover the scenario where the start date of the event are changed backwards, e,g, to 15th of august 2016. In this case End On remains 20 aug 2016 - the dates before 20th are disabled and selecting any date before it, e.g. 16 aug 2016 triggers validation as invalid date.

I think the expected behavior provided in the issue's description is valid:
The End On date should be updated based on the new dates in the Start/End pickers (e.g. **the End On date should be the same as the End Date)**

**Comment by Dimitar-Goshev** [comment]
- [ ] "End on " picker's min date is not updated initially - start creating an appointment on 6/11/2013, then change Start and End to 6/05/2013 and try to select 6/07/2013 for the End on picker - its min date is still the initial one - 6/11/2013

- [ ] "End on" picker is shown as before start date in the following scenario:
  - Start creating an event on 6/11/2013
  - Change start and end to 6/21/2013
  - Choose Repeat Daily, then End on 6/21/2013
  - Make End on invalid - type 16/21/2013 and blur - On is not valid date appears
  - Make End on valid again - type 6/21/2013 and blur - _End date should be greater than or equal to the start date_ is shown which was considered valid before inputting invalid date
