### ISSUE TITLE
Repeated calls to add() with autoSync result in duplicate records

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2126]
### Bug report
Copy of support ticket 1059782

### Reproduction of the problem
http://dojo.telerik.com/akIwuf

### Current behavior
Datasource.created() iterates over the existing items and adds "new" `(item.isNew && item.isNew())` items to the list of items to submit in the currently-requested sync() promise list. 

However, it does not test whether there are existing promises outstanding for those items.
Given a DataSource with a remote AJAX endpoint and the configuration of `autoSync: true`, calling 
`DS.add({"name":"A"}); DS.add({"name":"B"});` results in 3 ajax requests and 3 items created on the back-end.

The first call to `.add({}) `
* inserts the "A" record
* iterates over the records, selects the "A" record, and:
* creates an AJAX request to create the "A" record.

The second call
* inserts the "B"record
* iterates over the records, selects the "A" record,
* continues iterating, selecting the "B" record,
* creates an AJAX request to create the "A" record (it not having an identity yet, because the previous AJAX call has not completed
* creates an AJAX request to create the "B" record.

So there are 3 Ajax calls outstanding:
* Create "A" (giving id 1)
* Create "A" again (giving id 2)
* Create "B" (giving id 3)

Now there are three new items in the database, only two of which are shown ("A" now having id 2, despite the existence if A:1)

### Expected behavior
But ideally the DataSource would (knowing as it does which records it is making requests for) not produce a second request so long as there were a previous request outstanding.

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** any
* **Browser:** all

**Comment by rkonstantinov** [comment]
The described behavior is a by design limitation. The DataSource supports only single state of the data - either sync or not. Thus, it is not possible to have records which are 'pending' and others which are in 'syncing' state. Implementing such functionality will require major change in the DataSource internals and behavior.

Currently it is up to the calling code to handle such cases and allow/disallow changes until the DataSource is in the appropriate state.
