### ISSUE TITLE
Slider and RangeSlider do not display correctly on mobile devices when placed inside Window and kendo.mobile.min.css is loaded on the page

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2200]
### Bug report
Slider and RangeSlider do not display correctly on mobile devices (iOS and Android tested) when placed inside Window and **kendo.mobile.min.css** is loaded on the page  
Another scenario is inside Grid's detailRowTemplate.

### Reproduction of the problem
- Run this [Dojo with mobile.min.css](https://runner.telerik.io/fullscreen/@Goshev/AXoYEdUz) in Chrome emulator with iPad/Android device or on a mobile device browser
- Scenario inside Grid's detailRowTemplate:  http://dojo.telerik.com/aCidO

### Current behavior

![image](https://user-images.githubusercontent.com/6614183/56806515-cb4e3880-6834-11e9-858e-829b625cc87e.png)

### Expected/desired behavior
[Dojo without mobile.min.css](https://runner.telerik.io/fullscreen/@Goshev/ESIdARUx)
![image](https://user-images.githubusercontent.com/6614183/56806459-a5289880-6834-11e9-9a5b-2b6ac65ccbe1.png)

### Environment
* **Kendo UI version:** 2019.1.220
* **Browser:** iOS Safari, Android Chrome

**Comment by Juveniel** [comment]
The kendo.mobile.all.css file should be included and used only with Hybrid UI applications as described in [the Hybrid UI Styling Documentation](https://docs.telerik.com/kendo-ui/controls/hybrid/styles/styling).

Taking the above into consideration, in order to correctly style the RangeSlider as part of a Hybrid UI Application we should:

- Include kendo.mobile.all.css

-  Initialize a Hybrid UI Application

- Initialize the ProgressBar through data attributes.

A very basic configuration of the above is the following:
```
<div data-role="view" data-title="Hello world">
    <div id="mywindow" class='dialog' data-role="window" data-width="100%">
        <div id="temperatureRange" data-role="rangeslider" data-min="10" data-max="50">
            <input />
            <input />
        </div>
    </div>
</div>

<script>
    new kendo.mobile.Application(document.body);
</script>
```

Here is [an updated Dojo example ](https://dojo.telerik.com/arIzOsAB)that demonstrates the described approach.

Closing the issue.
