### ISSUE TITLE
The ViewModel change event is not firing after setting Grid source property to empty array.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2229]
### Bug report

The ViewModel change event is not firing after setting Grid source property to an empty array and a filter is applied to the dataSource. This is causing a difference between the Grid data and the Grid view.
### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/eSIbo.

Steps to reproduce:

To reproduce:

1) Click add new record (notice that the text 'viewModel changed' is appended to the bottom of the screen)
2) Click reset products (notice that the text 'viewModel changed' is again added to the bottom of the screen)
3) Click add new record...notice that the text 'viewModel changed' is NOT added to the bottom of the screen
4) Any future changes to the grid no longer fire the change event (you can remove the filter and try editing items)

You can uncomment the line of code in the resetProductsAndSetGridFilter function to set the products collection to an array with a single item (instead of an empty array) and retry the steps above. You will see the change handler remains intact.

Both scenarios work if the filter is not applied.
### Environment
- **Browser:** all

**Comment by ag-petrov** [comment]
The reason behind the described behavior is that the products instance is totally replaced with a new one. On initialization we create a **LazyObservable** and in the process two change events are attached internally to it. Later after replacing the instance, one change is lost. Adding code that re-attaches events for collections is possible, however is a bad practise since this means that we should probably look for all the previously attached events and re-attach them. Moreover we can not guarantee at which point what event is attached to a collection and whether the developer whats to re-attach it after providing a enterily new collection. The latter does not seem logical at all.

As a solution to the specific case I can suggest just emptying the **LazyObservable** as shown in [this ](http://dojo.telerik.com/EniFUpoQ)dojo.
