### ISSUE TITLE
ToolBar items of type ButtonGroup and template items cannot be hidden through  the hidden property

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#2289]
### Bug report
Reported in ticket: 1067944. The hidden property does not work for a buttongroup. 
Note: it works for separate buttons, but not for entire buttongroup

### Reproduction of the problem
Run this [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/ebaCIyob)

### Expected/desired behavior
Setting hidden: true to the buttongroup and template does NOT hide the entire buttongroup and the template

### Expected/desired behavior
Setting hidden: true to the buttongroup should hide the entire buttongroup and the template

### Environment
- **Kendo UI version:** 2019.3.1023
- **jQuery version:** 1.12.3
- **Browser:** all

**Comment by inikolova** [comment]
Also does not work for an item with a template - http://dojo.telerik.com/@Iliana/APALU

**Comment by movedoa** [comment]
Found another interesting case.
http://dojo.telerik.com/obojaROX

When you execute this sample code and have enough space for the three groups, the hide function works.
If you resize the window to a smaller size (when the overflow button is visible), and you restart the example, the third group is still visible in the overflow popup.
If you resize the window again, the buttongroup stays in the overflow menu and doesn't become visible in the normal menu even if there is enough space.

Is this the same bug? Will this be fixed in the near future? Our customers see buttons that should be hidden because of this which leads to all kinds of problems.

**Comment by movedoa** [comment]
any news on this?

**Comment by movedoa** [comment]
We cannot use Buttongroups because hidden just doesn't work. Could you please prioritize this or at least provide a workaround?

**Comment by Dimitar-Goshev** [comment]
@movedoa We have fixed the logged issue. And the issue discussed in https://github.com/telerik/kendo-ui-core/issues/2289#issuecomment-394330970 is a different one related to hide() method. I logged it separately - https://github.com/telerik/kendo-ui-core/issues/6764
