### ISSUE TITLE
No filtering is applied in grid when a datetime column is set with a DateTime picker 

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2330]
### Bug report

No filtering is applied in grid when a datetime column is set with a DateTime picker 
### Reproduction of the problem

Use the following setup:
@(Html.Kendo().Grid<Kendo.Mvc.Examples.Models.OrderViewModel>()
    .Name("grid")
    .Columns(columns =>
    {
        columns.Bound(p => p.OrderID).Filterable(ftb => ftb.Cell(cell => cell.ShowOperators(false))).Width(225);
        columns.Bound(p => p.ShipName).Width(500).Filterable(ftb => ftb.Cell(cell => cell.Operator("contains")));
        columns.Bound(p => p.Freight).Width(255).Filterable(ftb => ftb.Cell(cell => cell.Operator("equalTo")));
        columns.Bound(p => p.OrderDate).Format("{0:MM/dd/yyyy HH:mm:ss}").Filterable(ftb => ftb.Cell(cell => cell.Operator("equalTo").Template("DateTimeFilter")));
    })
    .Pageable()
    .Sortable()
    .Scrollable()
    .Filterable(ftb => ftb.Mode(GridFilterMode.Row))
    .HtmlAttributes(new { style = "height:550px;" })
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .ServerOperation(true)
        .Read(read => read.Action("Orders_Read", "Grid"))
     )
)

<script type="text/javascript">

    function DateTimeFilter(control) {
        $(control.element).kendoDateTimePicker();
    }
 
</script>

Steps:

1) Open the page
2) Set the following date and time in the filtering datetime picker:
07/08/1996 09:00:00
### Current behavior

Filtering is applied to the grid
### Expected/desired behavior

Filtering is not applied to the grid

**Comment by boyandim** [comment]
Filtering is not performed to the grid because such date format (07/08/1996 09:00:00) is not defined for the Kendo UI DateTimePicker widget parseFormats. It assumes that this is not a valid date, does not parse it to Date object and pass it to the DataSource. 

According to the [parseFormats](http://docs.telerik.com/kendo-ui/api/javascript/ui/datetimepicker#configuration-parseFormats) article if it is not defined the [format](http://docs.telerik.com/kendo-ui/api/javascript/ui/datetimepicker#configuration-format) value will be used to parse values typed in the input. The default value for the format option is "M/d/yyyy h:mm tt". There are two options to choose from in order the described scenario to work: 

- Define a parse format to work with 07/08/1996 09:00:00 value. It will look like: parseFormats: ["MM/dd/yyyy hh:mm:ss"]
- Type a value in the default format - 07/08/1996 09:00 AM
