### ISSUE TITLE
PDF Export of Documents with text set to heading is cut off

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2338]
### Reproduction of the problem
When testing PDFExport with the Editor I came across an odd issue where larger documents with all their text set to heading 1, when exported, would have a blank first page, then only a second page which would cut off the rest of the document.  Text outside of the heading 1 styling get put onto the next page.  This problem happens when using every heading except heading 6. 

Screenshot of the problem - https://admin.telerik.com/ClientsFiles/6ca6c46a-3691-457f-8bcb-6c964c8dc167_Capture.PNG

Can be reproduced at http://demos.telerik.com/kendo-ui/editor/pdf-export

The HTML content is attached.
[HTML.txt](https://github.com/telerik/kendo-ui-core/files/538842/HTML.txt)

For more information see ticket: 1069218

### Expected/desired behavior
The whole content in the editor should be exported to PDF. The first empty page in the exported pdf should not be there too.

### Environment

* **Kendo UI version:** 2016.3.914
* **Browser:** Chrome | Firefox

**Comment by mishoo** [comment]
Page breaks are not allowed in headlines (i.e. `<H1>`) and a bunch of other elements.  For headlines in particular, the reason is that if we have, say, a 2-lines headline at the bottom of the page, it feels nicer to move them both on the next page, even if the first one would fit.

I'd expect headlines to have reasonable-sized content in most use cases; clearly didn't have in mind a big document written in a `<H1>` tag :-)  I will add an exception for such cases.
