### ISSUE TITLE
The AND formula returns different result depending on argumetns order.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2347]
### Bug report

The AND formula returns different result depending on arguments order.

For example: 
=AND(ISNUMBER(F3), LEN(G3)=0) - FALSE
=AND(LEN(G3)=0, ISNUMBER(F3)) - #VALUE!

### Reproduction of the problem

The issue can be reproduced on our demo page: http://demos.telerik.com/kendo-ui/spreadsheet/validation

### Environment

* **Kendo UI version:** 2016.2.504.. 2016.3.914, this was working as expected on version : 2016.1.112
* **Browser:** [all]

**Comment by mishoo** [comment]
For the record, the issue here wasn't the `AND` function, but the fact that `=LEN(EmptyCell)` would throw a `#VALUE!` error, because it expects a string and it's getting `undefined` instead (empty cell means no value).

I fixed it so that all functions expecting strings will silently convert empty cells to `""` (empty string), which seems to be what Excel and other spreadsheets do.

To explain the difference in `AND` results: the error is not encountered in the first case, because `ISNUMBER` returns false and the second argument is not evaluated.  In the second case, `LEN` is checked first and since it returns an error, computation is aborted and the error is passed to the cell.  After the fix, since no error is thrown, both lines will return `false`.
