### ISSUE TITLE
Nodes on level the third level cannot be checked from the data.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2348]
### Bug report

When the TreeView has loaded the nodes on the level the third level are not checked.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/eBusE

### Environment

* **Kendo UI version:** 2016.3.914, working as expected with 2015.1.408
* **Browser:** [all ]

**Comment by vasind** [comment]
hi, any idea when this bug get resolved? Or do we have any workaround to this issue?

**Comment by gyoshev** [comment]
The reason for this behavior is that the DataSource is not read in a single pass when provided to the TreeView. This causes the TreeView to load only the first level, infer that all nodes are not checked, and then propagate the checked state downwards, as in remote loading scenarios. The data is not read in a single pass, because (a) the TreeView does not have a `loadOnDemand: false` flag set, or (b) the data provided is wrapped in a HierarchicalDataSouce, which is asynchronous by default.
To resolve the problem, either [set `loadOnDemand: false`](http://dojo.telerik.com/eBusE/3), or [pass the new data as an array](http://dojo.telerik.com/eBusE/4).

Closing this. While not intuitive initially, it follows the component design.
