### ISSUE TITLE
Removing an ObservableObject from an ObservableArray will keep listening to change events

### ISSUE THREAD

**Issue by ricardomomm** [telerik/kendo-ui-core#2398]
### Bug report

After removing an ObservableObject from an ObservableArray, the array will keep the binding to the item "change" event. If by any reason we add and remove the same ObservableObject multiple times it will keep multiple bindings to the "change" event, so if we change this ObservableObject it will trigger the "itemchange" event from the ObservableArray multiple times.

I forked the repository and I have the intent of fixing it with your help.

### Reproduction of the problem
http://dojo.telerik.com/AfasA

### Expected/desired behavior
The expected behavior is that after removing an ObservableObject from an ObservableArray, changes to that ObservableObject should not trigger events in the ObservableArray anymore.

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by matanasov** [comment]
@ag-petrov @Stamo-Gochev 
Can you please take a look at this? Seems like a bug to me.

**Comment by Stamo-Gochev** [comment]
@ricardomomm The main concern with the fix is introducing a breaking change, so are you aware of any real scenario, which uses Kendo UI widgets and where this is problematic?

**Comment by ricardomomm** [comment]
@Stamo-Gochev , kind of, this turned into an issue in a SPA application for live monitoring with real-time chat, the use case was an operator logging in to the system and using it for 6 hours directly, so during this time we would add and remove lots of items in ObservableCollections, and also we were using ObservableCollections to track item selection, so you can Select and Deselect an item several times making Add/Remove to be called a lot. I don't remember the ObservableObject structure anymore but I remember we saw things like 800 event handlers in a single ObservableObject after using the system for a long period. This was the trigger to find this issue, we had several performance issues at the time and we choose to remove a few feature because changing the MVVM framework was too expensive.

The company has a paid support ticket about it 1072448 and it is closed without solution.

**Comment by ricardomomm** [comment]
Also, can this be impacting the memory usage since we are keeping a referente from the collection to the object? can this avoid an object from being garbage collected?

**Comment by Stamo-Gochev** [comment]
@ricardomomm We discussed the scenario from the ticket once again and still think that manually detaching the "change" event handlers (or handling the scenario with a "selected" boolean flag as discussed in the ticket) is the current approach that we can recommend as the alternative will not improve the overall performance, but might introduce a breaking change.

I am sorry for the fact that this information was not included in this issue back then and kept you waiting. If we decide to reconsider the above in the future, we will reopen the issue and provide more details about the new functionality because of its big impact on the suite.
