### ISSUE TITLE
kendo ui editor refresh issue on firefox after insert html

### ISSUE THREAD

**Issue by alonisoft** [telerik/kendo-ui-core#2432]
### Current behavior
http://stackoverflow.com/questions/40505227/kendo-ui-editor-refresh-issue-on-firefox-after-insert-html

when using firefox and insert html content like:
var editor = $("#editor").data("kendoEditor"); 
editor.exec("inserthtml", { value: "some html" });
// and do refresh: 
editor.refresh();

### Expected/desired behavior
The Inserted Html tags will shown instead of the html content inserted...

### Environment >> any Environment >>
http://dojo.telerik.com/AnEbe/2
* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by nstoychev** [comment]
@alonisoft [editor.refresh();](http://docs.telerik.com/kendo-ui/api/javascript/ui/editor#methods-refresh) is used when the editor is moved into the DOM in order to recreate the iframe and reattach the events handlers. 

I don't see the issue in this case.
For editor.exec("inserthtml", { value: "some html" }), the value will be inserted at the editor's selection and it is not necessary to refresh anything.

**Comment by alonisoft** [comment]
we need to refresh...  in firefox you can see the bug.
http://dojo.telerik.com/AnEbe/2

**Comment by nstoychev** [comment]
Thank you @alonisoft for clarifying

**Comment by alonisoft** [comment]
Great ! Thank's
