### ISSUE TITLE
Clipboard is visible in IE when editing cell then Tab is pressed

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2474]
### Reproduction of the problem
Open the [SpreadSheet demo](http://demos.telerik.com/aspnet-mvc/spreadsheet/index) in IE, edit a cell, press TAB - [screencast](http://screencast.com/t/MVCZCuygq1yk)

### Current behavior
[screenshot](http://screencast.com/t/vCGPGnDb) 

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** x.y
* **Browser:** [IE ]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible on my side with latest Kendo UI version R2 2018 SP1 - 2018.2.620.
I tested on https://demos.telerik.com/aspnet-mvc/spreadsheet demo and on https://demos.telerik.com/kendo-ui/spreadsheet/index . I also tested in a Dojo with the reproduction version 2016.3.914 - https://dojo.telerik.com/ALEmituj - but still the issue is not reproducible.
