### ISSUE TITLE
Parse error thrown, when load a specific Excel file

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2489]
### Reproduction of the problem
When attempt in load specific Excel file. The issue is replicable only in our latest Service Pack - Q3 2016 SP1, while there is no error in Q2 2016 SP2.

File attached
[example.zip](https://github.com/telerik/kendo-ui-core/files/618460/example.zip)

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mishoo** [comment]
Seems this is because it contains user-defined names that point to external spreadsheets.  They have some weird syntax I'm not familiar with, and our parser croaks.

Implementing the syntax would be pointless, since we cannot support references to external data anyway.  Options:

- We could make it drop those names silently.  Formulas using them will be yield incorrect results, of course (probably `#NAME?`)

- We could warn in a message box that the spreadsheet canot be fully imported (and still import whatever we can make sense of).

I vote for the latter.

**Comment by petyosi** [comment]
Agreeing with the second proposal.

**Comment by tsvetomir** [comment]
How much information can we include in the warning?

Excel has something similar that's not very helpful due to the lack of details on what exactly failed to import:

![image](https://cloud.githubusercontent.com/assets/247917/20717996/07239c08-b660-11e6-85e8-5f6c1f829da0.png)

**Comment by mishoo** [comment]
Was just thinking about this.  We can include what failed to parse, of course. (FWIW, we already silently ignore parse errors in formulas; it would probably be better to list them).

**Comment by nenchef** [comment]
Indeed a meaningful message with a list of the parse errors would be best. Also, we can include a statement regarding that user-defined names which point to external spreadsheets are not supported (or a link to documentation, describing this).

**Comment by mishoo** [comment]
Just for reference, there are 64 errors reading this sheet.  Here's the JSON error log that I can produce: https://gist.github.com/mishoo/57e381bab6db028ce53a925ac9629fc4.  Do you think it's OK if we just display this log in a textarea, or should I think about a more elaborate UI?

Besides the external refs, there are also errors reading names like `整理1` — that's a different bug that I will push a fix for.
