### ISSUE TITLE
Cannot read property 'dataSource' of undefined(…) error is thrown with jQuery 3.1.1

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2493]
### Bug report
The upgrade to jQuery version 3.1.1 breaks functionality with Kendo UI that works with the earlier jQuery versions 1.x and 2.x.

You can see the error in action in this Dojo project: [http://dojo.telerik.com/@RumenJ/UgIlu](http://dojo.telerik.com/@RumenJ/UgIlu).

The error is thrown on this line $("#DepId").data("kendoDropDownList").dataSource.read(); because the dropdown list is not initialized at the right time in the onEdit event of the grid.

A workaround is to fire the onEdit function with a small timeout:

    function onEdit(e) {
        setTimeout(function () {
            triggerRead();
        }, 1000);
    }

### Reproduction of the problem
1. Run this demo: [http://dojo.telerik.com/@RumenJ/UgIlu](http://dojo.telerik.com/@RumenJ/UgIlu)
2. Edit a record and try to update it.
3. You'll see the error is thrown.

### Current behavior
The dropdown is not initialized and the user is unable to update the record.

### Expected/desired behavior
The user should be able to update the record.

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 3.1.1
* **Browser:** [all ]

**Comment by rkonstantinov** [comment]
This behavior is not related to the Grid widget itself. It is caused by the way Editor Template is generated. The sample is using the output  generated by the ASP.NET MVC wrapper. As the Editor template will generate the widget initialization code wrapped inside a document.ready handler with jQuery 3.x it will run asynchronous. Thus, the widget will not be initialized yet.
 
This could be addressed either by providing a different overload of the widgets which to skip the document.ready initialization wrapper, or by using the appropriate event of the Editor's widget.

**Comment by nlazarov** [comment]
By removing the jQuery wrapping function from the custom editor in the grid, the error does not occur. Here is an updated version of the code - [http://dojo.telerik.com/OJetO](http://dojo.telerik.com/OJetO).

In this scenario it does not make sense to wait for the document to be ready, because it will definitely be ready since the grid has been initialized.
