### ISSUE TITLE
The MS Word bullet lists are not converted to OL/UL/LI tags when formatted with headings

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2498]
### Bug report

The MS Word bullet lists are not converted to OL/UL/LI tags when formatted with headings

### Reproduction of the problem
Copy the content of the attached word file and paste it in the following live demo: https://demos.telerik.com/kendo-ui/editor/paste-cleanup
You'll see that the bullets are not converted. If you remove the headings from the bullets in the word file, the bullets will be converted to OL and LI tags. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** [Firefox]
[test doc.docx](https://github.com/telerik/kendo-ui-core/files/625524/test.doc.docx)

**Comment by sankarkannanse** [comment]
Hi I have created basic formatting. There is no any headings or other styles. Content includes basic Bullet & numbering. When paste contend from MS word to kendo Text editor then Number formatting is failing . Kindly find attached MS Document which includes basic Numbering  & bullet formatting
[Basic Numbering in  MS word.docx](https://github.com/telerik/kendo-ui-core/files/626813/Basic.Numbering.in.MS.word.docx)

**Comment by Iankodj** [comment]
The topics here address several differences between how MS Word and HTML handles list. In order to best clarify what is fixed  I will get into some details. 

MS Word considers the content as flat data. Which makes lists hard to manage in hierarchical structure as XML (HTML), where semantics should be also taken into account. 

For example, while the following is perfectly fine with rich text: 

```
1. List Item 1

Paragraph

2. List Item 2
```

In HTML, there is no applicable way to make a semantic list that can recreate the same hierarchy of list. The best option is to nest the paragraph in the previous list item. 

```
<ol>
    <li>List Item 1
           <p>Paragraph</p>
    </li>
    <li>List Item 2</li>
</ol>
```

The fixes here accomplishes the above behavior. However, there are known limitations for the case with nesting because when pasting from  MS Word, there are cases, where meta data shows nested lists as entirely different list and there is no programmatic way to tell that the list is a nested one. 

For example: 

```
1. List Item 1

Paragraph

    1. Nested List Item
```

will output this HTML: 

```
<ol>
    <li>List Item 1</li>
</ol>
<p>Paragraph</p>
<ol>
     <li>Nested List Item</li>
</ol>
```

Which is semantically incorrect, but there is no sufficient data that indicates that the nested list is actually  is nested and which is the list container.

**Comment by mparvanov** [comment]
Using the [Basic Numbering in  MS word.docx](https://github.com/telerik/kendo-ui-core/files/626813/Basic.Numbering.in.MS.word.docx) the actual HTML of the pasted content is:
`<ol>
<li><span lang="EN-IN">Tamil Nadu</span><p><span lang="EN-IN">&nbsp;</span></p>
<ol style="list-style-type:lower-alpha;">
<li><span lang="EN-IN">Chennai</span></li>
<li><span lang="EN-IN">Coimbatore </span><p style="margin-left:36.0pt;"><span lang="EN-IN">Chennai &amp; Coimbatore are the best places to work as techie</span></p>
</li>
</ol>
</li>
<li><span lang="EN-IN">Kerala</span><ol style="list-style-type:lower-alpha;">
<li><span lang="EN-IN">Cochin</span></li>
<li><span lang="EN-IN">Trivandrum</span><p style="margin-left:36.0pt;"><span lang="EN-IN">Cochin &amp; Trivandrum are the historic places in Kerala</span></p>
</li>
</ol>
</li>
<li><span lang="EN-IN">Karnataka</span></li>
</ol>
<ol style="list-style-type:lower-alpha;">
<li><span lang="EN-IN">Bangalore </span></li>
<li><span lang="EN-IN">Mangalore </span></li>
</ol>
<p style="margin-left:36.0pt;"><span lang="EN-IN">Bangalore and Mangalore are main metropolises of Karnataka</span></p>`

Expected HTML:

`<ol>
<li><span lang="EN-IN">Tamil Nadu</span>
 <ol style="list-style-type:lower-alpha;">
<li><span lang="EN-IN">Chennai</span></li>
<li><span lang="EN-IN">Coimbatore </span>
 </li>
</ol>
<p><span lang="EN-IN">Chennai &amp; Coimbatore are the best places to work as techie</span></p>
</li>
<li><span lang="EN-IN">Kerala</span><ol style="list-style-type:lower-alpha;">
<li><span lang="EN-IN">Cochin</span></li>
<li><span lang="EN-IN">Trivandrum</span>
 </li>
</ol>
<p><span lang="EN-IN">Cochin &amp; Trivandrum are the historic places in Kerala</span></p>
</li>
<li><span lang="EN-IN">Karnataka</span>
 <ol style="list-style-type:lower-alpha;">
<li><span lang="EN-IN">Bangalore </span></li>
<li><span lang="EN-IN">Mangalore </span></li>
</ol>
<p><span lang="EN-IN">Bangalore and Mangalore are main metropolises of Karnataka</span></p>
</li>
</ol>`

**Comment by Iankodj** [comment]
The empty paragraph tag is expected to be appended as it comes from the MS Word content: 

![image](https://user-images.githubusercontent.com/4222379/31808433-c51743de-b57b-11e7-84f6-303fe0a6132e.png)

**Comment by mparvanov** [comment]
Lists are created in accordance with the content that comes from msWord and more precisely the mso-list style value. Paragraphs with identical mso-list values are combined into a single list in Kendo editor now.
Number formatting is applied with basic numbering from MS Word Document:
[BasicNumbering.docx](https://github.com/telerik/kendo-ui-core/files/1401863/BasicNumbering.docx)

**Comment by Iankodj** [comment]
One more thing,  as if Internet Explorer 11, pasting MS Word lists in content editable elements, it is the browser that converts them to HTML lists. Thus, Kendo Editor has less control over the HTML pasted and generated as the HTML that the clipboard fetches is already processed and any information about the original MS Word content is lost.  

Due to that, some of the fixes here will not affect pasting of lists in Internet Explorer 11 or later.
