### ISSUE TITLE
The border of kendo styled checkboxes and radio buttons is not visible when exported to PDF in IE

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-ui-core#2544]
example: http://dojo.telerik.com/@SiliconSoul/iHuSA

To reproduce open the example in IE(any version) and click the export button.

**Comment by mishoo** [comment]
Seems it's [an old IE bug](http://stackoverflow.com/questions/32607904/can-not-read-border-style-from-pseudo-elements-in-microsoft-edge-and-ie).  IE's `getComputedStyle(element, ":before")` reports `none` instead of `solid`, even if the pseudo-element has a solid border (in fact, it returns the border of the parent element).

The workaround is to set a solid border on the parent element (and `border-width: 0` if a border is not desired).

Working example: http://dojo.telerik.com/@mishoo/IKilu — note the added style:

```html
    <style>
      .k-checkbox-label,
      .k-radio-label {
        border-style: solid;
        border-width: 0;
      }
    </style>
```

I don't know where's the best place to do this in our stylesheets, so I added @inikolova.

**Comment by inikolova** [comment]
Thanks, @mishoo! I will add this rule in the corresponding stylesheet

**Comment by inikolova** [comment]
Commit: 61b5aaba21d7333859
