### ISSUE TITLE
Tooltip does not hide Safari's built-in tooltip on OS X

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2565]
### Bug report

Reported in 1079768. Client has provided a video in the ticket.

### Reproduction of the problem

Open  and run the how-to article from [Kendo UI Grid in the docs](http://docs.telerik.com/kendo-ui/controls/data-management/grid/how-to/Layout/grid-with-kendo-ui-tooltip)

Or directly from [here](http://runner.telerik.io/fullscreen/@bubblemaster/UjUXI) in fullscreen.

Hover over the columns continuously for 1-2 seconds
- The Kendo UI Tooltip appears
- The built-in Safari tooltip appears

### Current behavior

Two tooltips are shown on the page

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** 1.12
* **Browser:** [ Safari 9.1.2 & Safari 10 | OS X 10.11 & 10.2 ]

**Comment by Iankodj** [comment]
By design, the Kendo Tooltip would prevent the tooltip from the title attribute to not show. This tooltip, however, is a WebKit core feature about showing full text when hidden with ellipsis (like in the demo linked). In Safari, this feature is enabled by default and there is no suitable programmatic approach to prevent it from showing by using web application logic (CSS or JavaScript).

You can test by removing the style attribute of the cells and see that the built-in Safari tooltip does not show up: http://dojo.telerik.com/utazU. 

Some more details and possible CSS workarounds about the same topic is discussed in these forum threads: 

https://stackoverflow.com/questions/20974276/prevent-safari-from-showing-tooltip-when-text-overflow-is-hidden-with-ellipsis/26824515#26824515

https://stackoverflow.com/questions/20974276/prevent-safari-from-showing-tooltip-when-text-overflow-is-hidden-with-ellipsis
