### ISSUE TITLE
Workbook cell wrap does not wrap cell value

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2580]
### Bug report

The workbook [sheets.rows.cells.wrap](http://docs.telerik.com/kendo-ui/api/javascript/ooxml/workbook#configuration-sheets.rows.cells.wrap) property does not wrap the cell. 

### Reproduction of the problem

[Dojo](http://dojo.telerik.com/@bubblemaster/AKOLa/2)

### Current behaviour

Interestingly, both the Spreadsheet toolbar and MS Excel toolbar recognise that wrap has been applied, however, the cell does not appear wrapped visually. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.1

**Comment by mishoo** [comment]
Wrapping does work.  It only seems not to because the row heights are not increased to fit the text.  Example with adding a height: http://dojo.telerik.com/oMEWU

I don't think we can measure the text during `fromJSON` initialization to increase the height, that would be extremely slow (see also #2582).
