### ISSUE TITLE
Masked Textbox allows user to enter underscore characters

### ISSUE THREAD

**Issue by rmorrise** [telerik/kendo-ui-core#2607]
### Reproduction of the problem

This bug is observable anywhere where the Masked Textbox is used.

1. Open the "AngularJS" demo for the Kendo Masked Textbox: http://demos.telerik.com/kendo-ui/maskedtextbox/index

2. Click on the Social Security Number field

3. Type in the underscore character 9 times. ("_")

4. Press ENTER

### Current behavior
The "value" is set to an invalid string: "\_\_\_-\_\_-\_\_\_\_"

### Expected/desired behavior
The user should be prevented from entering underscore characters, which are not specified in the input mask.

### Environment

* **Kendo UI version:** 2016.3.1118 (Dojo)
* **jQuery version:** 1.12.3
* **Browser:** [Chrome 55.0.2883.75 m (64-bit) ]

**Comment by jlchereau** [comment]
Maybe @dtopalov can consider https://github.com/telerik/kendo-ui-core/issues/2096 too.

**Comment by ag-petrov** [comment]
If by value you mean the [value API](https://docs.telerik.com/kendo-ui/api/javascript/ui/maskedtextbox/methods/value) method this means that the problem is not present in the current version. Allowing the entering of symbols which are part of the mask is not incorrect. However the value which is consumed via the API should correctly reflect things.
