### ISSUE TITLE
Last navigator series items are not displayed

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#2644]
### Bug report

Some of the last series items are not shown in the navigator - they appeared to be "cut". However, the dragging (range selection) functionality is working. Reported in Ticket ID: 1084514

### Reproduction of the problem
The following dojo example reproduces the issue: http://dojo.telerik.com/@stamo/epUbE

### Current behavior
Several of the last items from the data source are not displayed:
```
28/11/2016 19:39:33
28/11/2016 19:39:40
28/11/2016 19:39:47
```
### Expected/desired behavior

The series items are displayed till the end of the date range inside the navigator.

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** all

This might be related to https://github.com/telerik/kendo-ui-core/issues/2331

@danielkaradachki @tsvetomir

**Comment by danielkaradachki** [comment]
They will not be displayed because the categories are aggregated. The navigator categoryAxis uses baseUnit fit, which automatically calculates the baseUnit and baseUnitStep so that the categories do not exceed the maxDateGroups. In the example the calculated baseUnit and baseUnitStep for the labels are "minutes" and 11, so the next category that will be displayed if there is data is 19:44. The 19:39:.. categories are included in the 19:33 category.
