### ISSUE TITLE
Window title() method issue when there is an opening animation, and jQuery 3.1.1 is used

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2674]
### Bug report

The title of the Window cannot be set properly if there is an opening animation, the widget is initially closed, and jQuery 3.1.1 is used. Everything works as expected with jQuery 1.12.3

Reproducible in:

[http://dojo.telerik.com/oNiTU](http://dojo.telerik.com/oNiTU)

Widget is initially visible (works as expected with jQuery 3.1.1):

[http://dojo.telerik.com/oNiTU/2](http://dojo.telerik.com/oNiTU/2)

animation: false - works as expected:

[http://dojo.telerik.com/oNiTU/3](http://dojo.telerik.com/oNiTU/3)

jQuery 1.12.3 - works as expected:

[http://dojo.telerik.com/oNiTU/4](http://dojo.telerik.com/oNiTU/4)

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 3.1.1

**Comment by Iankodj** [comment]
This problem is related to jQuery 3.1.1 bug (https://github.com/jquery/jquery/issues/3193) that is fixed with 3.2.0 version. Also mentioned here: https://github.com/telerik/kendo-ui-core/issues/2882#issuecomment-310987741. 

Possible workaround is to use only the fade animation and prevent zooming (transform-scale) to be applied: 
http://dojo.telerik.com/oNiTU/8
```
$("#dialog").kendoWindow({
  animation:{
  	open: {
    	effects: "fade:in"
    },
    close: {
    	effects: "fade:out"
    }
  },
  visible: false
});
```
