### ISSUE TITLE
Drawing API should wait for fonts to load before drawing 

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2693]
### Bug report

Drawing API starts drawing before fonts are loaded which results in initial load with browser provided fonts. 

### Reproduction of the problem

[Dojo](http://dojo.telerik.com/IdUDOF)
- Press Run - the first time the text overflows the rectangle
<img src="http://image.prntscr.com/image/18b2fbf917d749efa1524cf1298853f1.png">

- Press Run again - the Text fits the Rectangle

### Current behaviour

Drawing API does not check if the fonts have been loaded before beginning to draw

### Workarounds

1) Pre-load the fonts

[Load the document fonts](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/load )
Add the @font-face declarations and then use the promise to draw inside the callback function.

2) Use the font elsewhere on the page - an HTML element either with visibility hidden or positioned off the screen and add a setTimeout before the drawing

[Dojo](http://dojo.telerik.com/oqifAz)

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mishoo** [comment]
Technically, `kendo.pdf.defineFont` has nothing to do with the other drawing objects and methods, like `draw.Text`; that's only to make fonts available in PDF output.

The problem here is that `draw.Text` cannot return the correct bounding box until the font is loaded, of course.  I don't think we can do anything to make this “magically work”; at best we could provide a function that invokes a callback when all fonts declared with `@font-face` are loaded, so rather than a setTimeout you'd wrap the code in it.

**Comment by tsvetomir** [comment]
I don't think there's a reliable way to check if the fonts are loaded apart from waiting for  [fonts.load](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/load). This is not supported in IE though.

**Comment by ag-petrov** [comment]
This seems like something developers should handle themselves.
