### ISSUE TITLE
Spreadsheet Reject validation message does not pop-up, when entering and then leaving a cell with invalid value, without making changes, compared to the initial value

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2726]
### Bug report
Spreadsheet Reject validation message does not pop-up, when entering and then leaving a cell with invalid value, without making changes, compared to the initial value.

### Reproduction of the problem
- Go to the following [Dojo](http://dojo.telerik.com/UJOHI/5);
- You will notice, that there are cells with invalid values in column "C". Those are cells with no values;
- Double click any of the marked cells to enter edit mode;
- Write several characters and then delete them;
- Leave edit mode, by clicking on another cell;
- There will be no reject alert;

### Expected/desired behavior
Reject alert should pop-up, as the empty value is not valid for the specified cell.

**Comment by mishoo** [comment]
The editor will trigger a “change” event only if the [value actually changed](https://github.com/telerik/kendo/blob/master/src/spreadsheet/editor.js#L84).  This is intentional and [there's a test for it](https://github.com/telerik/kendo/blob/master/tests/spreadsheet/sheeteditor.js#L370).  Without the “change” event there is no re-validation.

To fix this I would have to make the editor emit a change event even if the value does not actually change.  Note that this will produce a “change” event for the Sheet object as well, with new value == old value.  Please let me know if this is acceptable.

**Comment by Dimitar-Goshev** [comment]
@mishoo Emitting change event when the value is not changed is not an acceptable solution as it will break the change event purpose - https://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet/events/change
Closing this as Won't fix.
