### ISSUE TITLE
With Virtualization enabled the DropDownList sets the default empty item (optionLabel) as selected  

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2754]
### Bug report
Even though initially the selected item is specified through the valueMapper the DropDownList sets the default empty item as selected. This happens after the open event fires. 

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/ALefA) example. 
1. The item with text "White Clover Markets" is selected on load. 
2. Click on the DropDownList -> The cascade event fires and the selection is changed to the default empty item.

### Current behavior
The default empty item is selected. 

### Expected/desired behavior
The selection is not changed automatically. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by IvanDanchev** [comment]
Another scenario the issue is exhibited in is:
1. Open the dropdown
2. Search for "han"
3. Select an item in the middle of the list of returned items.
4. The item is shown as selected but on re-opening the dropdown the default empty item is set as selected.

**Comment by jivanova** [comment]
ValueMapper function is used to select an item from the dataSource. That's why the user needs to modify the success function in order to select the dataItem. The source code provided by Kendo should not contain such selection outside of the value mapper as this will mean that the dataSource should be traversed to find the correct item and there will be no point in enabling virtualization.

``` javascript
success: function (data) {
     if (data.length == 0) {
           options.success({OrderID: 10649, ShipName: "White Clover Markets"});
     } else {
          $('#orders').data("kendoDropDownList").select(data);
    }
}
```
