### ISSUE TITLE
Drawing does not properly export sub elements content in IE

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2762]
### Bug report

The content of sub elements `<sub>2</sub>` is not properly exported in IE.

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/evUhot) example, demonstrating the problematic behavior. 

### Current behavior
When exported in IE the su**b** element's content in the pdf file looks like a su**p** element. 

### Expected/desired behavior
Exported sub elements content matches the way they are displayed in the browser. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** x.y
* **Browser:** [IE ]

**Comment by mishoo** [comment]
There seems to be a bug in IE's implementation of `getClientRects` — for a `<sub>`, the returned rectangle is as high as the surrounding text, which is why it appears above.  I found a simple workaround though, this CSS fixes it:

```css
sub { display: inline-block }
```

[Demo](http://dojo.telerik.com/evUhot/3).  Should we include this in our default stylesheet?

**Comment by tsvetomir** [comment]
Can we add this style only for exported content?

**Comment by mishoo** [comment]
This should be fixed now.
