### ISSUE TITLE
The page size dropdown instantly closes in Chrome

### ISSUE THREAD

**Issue by igor-shevchenko** [telerik/kendo-ui-core#2768]
### Bug report

The page size dropdown of a grid pager may stop opening. This bug is reproducible in Chrome 56.0.2924.87 (the current latest version).

### Reproduction of the problem

1. Open [Dojo](http://runner.telerik.io/fullscreen/uluxA) in Chrome 56.0.2924.87.
2. Set page size to "All".
3. Set page size to "20".
4. Try to open the page size dropdown again.

The result is that dropdown instantly closes. It starts working after some scrolling up and down.

Video: http://take.ms/Ycv0k

### Expected/desired behavior

The expected behavior for the dropdown is to stay open until a user clicks to close it or selects page size.

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12
* **Browser:** Chrome 56.0.2924.87

**Comment by MilenaCh** [comment]
I tried to replicate the unwanted behavior, but to no avail. 
See the video recorded during the testing and let me know what I am missing:
https://www.screencast.com/t/azBbwuVpM

**Comment by igor-shevchenko** [comment]
@MilenaCh probably depends on a window size. I just tested on a larger screen and everything was OK. The bug started to appear when I changed the height of my browser window to 800px.

**Comment by igor-shevchenko** [comment]
@MilenaCh sorry to bother you, but have you tried to reproduce the bug with smaller window height? Please let me know if there are any problems with validation of this bug.

**Comment by MilenaCh** [comment]
Thank you for the additional information provided.
I replicated the same issue on my end on smaller window size. Our dev team will review the issue.

**Comment by borgaaron** [comment]
Any update on this? We're seeing this behavior as well and will be pushing our product into production in the next month or two and would love to have it fixed first.

**Comment by MilenaCh** [comment]
We added this fix in our planning for 2017 R2 SP1 release.

**Comment by populationtwo** [comment]
Following. We're also experiencing this issue. 

**Environment**
Kendo UI version: 2017.1.118
jQuery version: 2.2.4
Browser: Chrome  58.0.3029.96 (64-bit)

**Comment by ibrahimhamed9** [comment]
I have the same problem with
Kendo UI Web v2014.1.318

**Comment by ibrahimhamed9** [comment]
Please is there any fix i could apply in v2014.1.318, i would really appreciate it @MilenaCh

**Comment by rajibnepris** [comment]
I am facing the same problem with
Kendo UI Web v2014.1.318 in chrome,working fine in firefox
please tell how to fix it

**Comment by Dimitar-Goshev** [comment]
The issue is caused by the following one:
https://github.com/telerik/kendo-ui-core/issues/3516

**Comment by Dimitar-Goshev** [comment]
Closed with a resolution for the DropDownList in Grid.

**Comment by MarcoZama** [comment]
Sorry @Dimitar-Goshev can u help me to fix this problem?
I don't understand "Closed with a resolution for the DropDownList in Grid."
Can you explain to me? thank you!

**Comment by Nayab3d** [comment]
Scroll the page once and try it will work...but it's not a solution :(

**Comment by manolopesquera** [comment]
I'm stuck with the same issue. Could this issue be reopened? @Dimitar-Goshev could you explain how to solve this issue?

**Comment by Dimitar-Goshev** [comment]
@MarcoZama , @Nayab3d , @manolopesquera The issue was caused by the related issue - https://github.com/telerik/kendo-ui-core/issues/3516 . It was reproducible for AutoComplete, ComboBox, MultiSelect and DropDownList. As Grid's pager uses DropDownList, initially we managed to fix the problem only the DropDownList. That is why I wrote "Closed with a resolution for the DropDownList in Grid." as the related issue remained open. Later on we fixed the problem for all four dropdowns and closed the related issue.

Currently I do not reproduce the issue with the latest Kendo UI version - 2018.1.117. I used the following [Dojo ](http://dojo.telerik.com/osUGI) with latest version, which has the same setup as the original one logged for this issue. Here is a [screencast ](https://www.screencast.com/t/Ht7Wz1VB) of the respective test scenario on a smaller screen, as noted in the comments above.

If there are different steps to reproduce the issue with latest Kendo UI, please specify them to allow us reproduce the problem.

**Comment by FedricLawrence** [comment]
in my case the kendo grid in asp.net mvc has several pages and the page size dropdown is flickering when it comes to expand in bottom but if it has no space at bottom it is expanding at top.and also if i decrease the screen resolution the dropdown expanding bottom also i tired several things not worked can any one help me to solve this

**Comment by Dimitar-Goshev** [comment]
@FedricLawrence Hi, please open a support ticket about the issue, providing a runnable reproduction project and steps to reproduce it. Also please specify the product version used and the browser and version used for testing.
