### ISSUE TITLE
Not visible indicator for dropping between TreeView nodes

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#2809]
### Bug report
Only 1 pixel dot is visible, instead of a line between nodes on dragging a node.

### Reproduction of the problem
1. Go to http://demos.telerik.com/kendo-ui/treeview/dragdrop
2. Drag a node between 2 nodes

### Current behavior
![image](https://cloud.githubusercontent.com/assets/6614183/23204666/2acfc19a-f8f0-11e6-8698-3390bdc11fab.png)

**Default v2**
![image](https://cloud.githubusercontent.com/assets/6614183/23210763/b9b1b014-f907-11e6-9031-c379f365a69e.png)

### Expected/desired behavior
**R2 2016 SP1** - [Dojo](https://dojo.telerik.com/iqAferUZ)
![image](https://cloud.githubusercontent.com/assets/6614183/23204721/5bcff5e4-f8f0-11e6-824f-f73be7abd90f.png)

### Environment
* **Kendo UI version:** 2019.1.115
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The old appearance was achieved by adding a div with class k-drop-hint.
When the sprites were substituted by font icons in R1 2017, the class in the div became k-i-drag-and-drop (the new icon can be seen [here](https://docs.telerik.com/kendo-ui/styles-and-layout/icons-web#layout-and-navigation)). But the new icon is not visible with the old height 5px, which still remains from the sprite configuration. Only the top of the icon is slightly visible as a dot.
If the height is increased, the icon appears:
![image](https://user-images.githubusercontent.com/6614183/36907024-238f286e-1e40-11e8-8abf-6c5759dcd443.png)

**Comment by Taygair** [comment]
Hi Dimitar
Got an email as a subscriber of this problem. I've just downloaded/installed KendoUI v2018.1.221 and the problem still exists (1dot visible only). I'm not sure yet whether this problem has already been solved, will be solver (in an upcoming release) or if I have to do something programmatically?

**Comment by Dimitar-Goshev** [comment]
Hi @Taygair ,
I have recently noticed again this issue and I added some more info about the it. The issue is still Open.
As a subscriber, you will receive an email, when the issue gets resolved.

**Comment by harfyt** [comment]
Hi
I am updating my project from 2016.3.914  to 2018.1.221 and fall on this problem.

As a workaround I used this css override.

`.k-treeview .k-i-drag-and-drop {
    margin-left: 7px;
    margin-top: -7px;
    width: auto;
    height: auto;
}`

Thanks, 
Harry

**Comment by Taygair** [comment]
Hi all
I'm currently working with the same workaround as you mentioned Harry and I'm fine with it!

**Comment by alexandrejobin** [comment]
I'm using the Bootstrap 4 theme and the workaround provided by @harfyt doesn't work. Someone from Telerik told be that this workaround only work on LESS based theme. Bootstrap 4 theme us SASS and there is not workaround for now.

**Comment by alexandrejobin** [comment]
Here's a workaround if you use SASS based styling (Default v2, Bootstrap v4 or Material).

```
.k-treeview .k-i-drag-and-drop {
    margin-left: 7px;
    margin-top: -7px;
    width: 50px;
    height: 1px;
    background-color:black;
    position: absolute;
    z-index: 10000;
    visibility: hidden;
    margin-top: -1px;
}

.k-treeview .k-i-drag-and-drop::before {
    content:none;
}
```

Here's a working example: https://dojo.telerik.com/ASEcEtuV

**Comment by Dimitar-Goshev** [comment]
@alexandrejobin Thank you for providing a SASS themes workaround. The SASS issue is logged in the dedicated kendo-themes repository: https://github.com/telerik/kendo-themes/issues/186

**Comment by Dimitar-Goshev** [comment]
@TeyaVes After the fix, which is referenced in the kendo-themes issue, the indicator is visible for both SASS and LESS themes. But its position should be adjusted to be between nodes and to correspond to the level, at which the dragged node would be dropped - **R2 2016 SP1** - [Dojo](https://dojo.telerik.com/iqAferUZ)

**Comment by alexandrejobin** [comment]
With my SASS workaround, there's a little issue where when you are dragging a node and you are in-between 2 nodes, sometimes the "hover" effect on one node is showed when it shoudn't. It let suppose that you can drop the node inside the node when in fact, you are still in-between.

This issue is not present in the LESS theme.

**Comment by TeyaVes** [comment]
@alexandrejobin, this is a known limitation in our SASS themes and it is because apart from Kendo UI for jQuery, the same styles are used across different suites: Kendo UI for Angular, Kendo UI for React, Kendo UI for Vue, etc, so that we can keep them unified.

As a workaround I can suggest adding a custom class to the _treeview_ and using this class to target the _treeview_ items and override their _:hover style_. I have updated your Dojo with the suggested implementation:

[https://dojo.telerik.com/ASEcEtuV/2](https://dojo.telerik.com/ASEcEtuV/2)


**NB: The fix for the visibility of the icon between the nodes will be included in the _R2 2019 Release_ so you'll be able to use it out of the box without the need for your workaround**
