### ISSUE TITLE
After expand or collapse the edited item is no longer marked as `dirty`

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2812]
### Bug report

After expand or collapse the TreeList edited item is losing the dirty status.

The unexpected result can be observed in the following screencast: https://www.screencast.com/t/ojZuo4YKO

### Reproduction of the problem

The shown issues can be observed in the following Dojo: http://dojo.telerik.com/amUnO

### Environment

* **Browser:** [all ]

**Comment by dejongch** [comment]
So I looked into the code a bit when I found this bug. It looks like the issue is when e.success is called it is overwriting the entire pristine data with the current dirty data. So when cancelChanges is being call it is reverting it to that.

**Comment by ag-petrov** [comment]
The real problem is that the datasource stips the model item from the propeties added by our internal logic such as dirty, id and etc when expand is performed. Later when the child item is added it adds these properties again however their previous state is not restored. Altering the data source logic may cause a breaking change which is not desirable, thus the reported problem is a limitation in the current implementation. 

However you can workaround it by placing the below code on the view. What it does is to restore the dirty indicator to the model item after expand/collapse has been performed.

```
kendo.ui.TreeList.fn._toggleChildren = function (e) {
                var icon = $(e.currentTarget);
                var model = this.dataItem(icon);
                var event = !model.expanded ? "expand" : "collapse";
                var dirty;
                var index;

                if (!this.trigger(event, { model: model })) {
                    dirty = model.dirty;
                    index = this.dataSource.indexOf(model);
                    this._toggle(model);
                    this.dataSource.at(index).dirty = dirty;
                }

                e.preventDefault();
            }
```
