### ISSUE TITLE
Add support for vertically aligned text in PDF export

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2827]
### Enhancement

Add support for  `writing-mode: vertical-rl;`. 

[http://caniuse.com/#feat=css-writing-mode](http://caniuse.com/#feat=css-writing-mode)

### Current behaviour

The text is vertically positioned but the letters are not rotated.

<img src="http://image.prntscr.com/image/d5b98780f7d54a2eab4ccaf18f6c54d6.png" height="330px"/>

### Expected/desired behavior

Apply the rotation to the text as it is on screen.

[Dojo](http://dojo.telerik.com/IXIkog)

**Comment by mishoo** [comment]
I took a stab at implementing this with rotations, but it's buggy.  Results differ between Firefox and Chrome (this hapens with the productrion branch as well).

This style messes with our line breaking algorithm, which detects lines of text based on their `y` coordinate — and for this example, instead of seing one rotated line of text, it sees 8 lines of test (one for each character).  It's too tricky to implement properly, and since the same effect can be easily obtained with a `transform: rotate` ([demo](http://dojo.telerik.com/IXIkog/2)) I vote for “Won't Fix”.

**Comment by tsvetomir** [comment]
I agree, this should be listed as a known limitation.

**Comment by mkosieradzki** [comment]
Transform: rotate IS NOT the same, as it requires fixed height. If you invent a workaround with transform: rotate that does not require manual height specification (and in many cases translate) - it would be a good replacement. Currently it is clunky workaround.

**Comment by mishoo** [comment]
@mkosieradzki I agree, fixed height is a hassle.  But unfortunately I can't see a better solution.  There are things we can do, and there are things we can't do.  If you know of a DOM → PDF rendering library that works in a browser and covers this case, as many others that Kendo UI does cover, I'd love to hear about it.
