### ISSUE TITLE
Improve keyboard support for Calendar.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-ui-core#2839]
Feature Request

1. "Today" link in Calendar should be accessed via keyboard.
2. It should be possible to switch to outer view. 

_For example if user currently is on month view in navigation popup, he should be able to navigate to year, decade and century  view via keyboard_

http://demos.telerik.com/kendo-ui/calendar/keyboard-navigation

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Xizario** [comment]
1. The today link is accessible with pressing Tab key, and then Enter.
2. To navigate outer(upper) view you need to press Ctrl + Up

What need to be still improved is hotkey for directly selecting the Today. 
Something like Ctrl+Enter, or Ctrl + Space.

Avoid using Ctrl + T, or any other character, since it is not culturally/language universal.

**Comment by Dimitar-Goshev** [comment]
The Calendar follows the [keyboard specification for Infinite Calendar](https://github.com/telerik/web-components-ux/blob/develop/docs/components/infinitecalendar/keyboard-navigation.json#L62-L63) and the shortcut for focusing the current date is "t". The link for Today is with tabindex -1 as per the aria specification - https://github.com/telerik/web-components-ux/blob/develop/docs/components/calendar/aria.json#L186-L198
