### ISSUE TITLE
Background in inserted cells does not line up with the background in non-inserted cells

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2844]
### Bug report
http://demos.telerik.com/kendo-ui/spreadsheet/index

When inserting new rows/columns and apply background color to the whole column/row accordingly, the width/height of the cell is one pixel wider/higher than the non-inserted cells
[https://www.screencast.com/t/ytRHhOIMoo](https://www.screencast.com/t/ytRHhOIMoo)
### Reproduction of the problem

1. Insert a few rows
2. Select a column that spans the inserted rows
3. Apply background to the selected column

or
1. Insert a few columns
2. Select a row that spans the inserted columns
3. Apply background to the selected row

### Current behavior
The fill along the right/bottom edge of the filled row doesn't line up

### Expected/desired behavior
The fill along the right/bottom edge of the filled row does line up

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3

**Comment by mishoo** [comment]
This happens because the white cells actually have white background, instead of no background at all.  While it's not a pleasant effect, it's not a bug either — cells that have a background and no border will render the gridlines around them with a slightly darker version of that background, and that's what happens there: when you insert a couple of rows, they come with no background at all, so when you assign those cells a background you're making the grid lines next to them render with a certain color.  Meanwhile, the cells that did previously exist have a white background, making the gridlines of a different color.

Here's [an example](https://dojo.telerik.com/OveZimIV) where the white rows have no background, the effect is no longer visible.

**Comment by Dimitar-Goshev** [comment]
Indeed in the example all cells, either inserted or not, have a visible border in the newly set background color:
![image](https://user-images.githubusercontent.com/6614183/42315663-ae297a66-8050-11e8-842a-7ae2dcbcd094.png)
