### ISSUE TITLE
The icons for sorting, column and filter menus in the Grid are not correctly exported in PDF.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2861]
### Bug report

The icons for sorting, column and filter menus in the Grid are not correctly exported in PDF.

![telerik_pdf_export](https://cloud.githubusercontent.com/assets/11087921/23610938/693db48c-027d-11e7-8088-6ab3cdc9c23d.png)

The issue occurs after version 2017.1.117 and it is probably related to the breaking change for the used icons: http://docs.telerik.com/kendo-ui/backwards-compatibility/2017-backward-compatibility#changes-from-2016-r3-sp2

### Reproduction of the problem

The issue can be observed in the following Dojo based on our demo:  http://dojo.telerik.com/eMobE

### Environment

* **Kendo UI version:** 2017.1.117
* **Browser:** [all]

**Comment by mishoo** [comment]
This is because the CSS where we declare the icon font face sits on another domain.  It's a known limitation listed in [this section](http://docs.telerik.com/kendo-ui/framework/drawing/drawing-dom#configuration-Custom). “In order for automatic font discovery to work, your CSS must reside on the same domain as the web page.”

The font should be declared with `kendo.pdf.defineFont`, just like the other fonts.

**Comment by mishoo** [comment]
I added the declarations in the PDF export demos.

**Comment by Aldarkhangai** [comment]
The bug fixed or not?
