### ISSUE TITLE
Editing cells in range, when filter is applied, modifies the cells in between

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#2880]
### Bug report

Cells that are not visible due to applied filter are updated when editing cells range that includes them.

### Reproduction of the problem
1. Go to http://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering
2. Change Date column filter for display just rows with  6/30/2014 and 7/2/2014, it will hide row 5 and 6
3. Select a cell range from a column in  4 and 7 for example client column for both rows, delete the content 
4. Remove the filters

### Current behavior
 Modified rows 4,5,6,7

### Expected/desired behavior
Modified rows 4,7

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** all

**Comment by chriseaton** [comment]
I can note the issue appears when pasting as well, not just deleting - the pasting will paste into cells that aren't even visible. 

This is a huge issue in my mind, it essentially means we have to tell clients **not to perform data entry** if you've applied a filter because you'll most likely _not realize_ you're accidentally overwriting cells you can't see. I hope this gets fixed soon.

**Comment by chriseaton** [comment]
I've been looking into this within the source code, and it seems the crux of the issue is that user-triggered events really need to be handled slightly differently than a JS called function.

The delete command (and presumably paste) don't instruct the Range object anywhere that it should ignore modifying hidden rows/cols - potentially leveraging the "Range.skipHiddenCells" function. instead, the action is triggered for all cells, which, in the case of end-user triggered events, isn't what they expect.

**Comment by veselints** [comment]
Also reported in 
Ticket ID: 1117520

**Comment by chriseaton** [comment]
Hi Telerik team,
   Indeed the fix for the delete issue is actually pretty straight forward:
On line 777: in the "kendo.spreadsheet.ClearContentCommand" function:
Change
` this.range().clearContent();`
to this
` this.range().skipHiddenCells().clearContent();`

and it works as expected.

Please ignore the portion of my first comment about pasting, apparently that is how MS Excel works so no problem there.

**Comment by iiNS0MNIAC** [comment]
Still an issue in 2024

**Comment by sspasova** [comment]
> Still an issue in 2024

Hi @iiNS0MNIAC, 

thank you for bringing this to our attention. 

I could not reproduce the issue using the described scenario, Kendo UI 2024.2.514, and Google Chrome v. 125.
Can you please elaborate more on how you reproduced the issue? Any additional information you can give me will be helpful.

**Comment by iiNS0MNIAC** [comment]
Hello @sspasova 
Okay so if you go here https://netcorerepl.telerik.com/wSkKahvG31jmw4Qq21 it's running the version you mentioined. 
Filter the Qty column to remove all 1's
Paste anything into the C3/C6 consecutive rows/cells
Unhide the rows between C3 and C6 and you'll see it's changed the values in the hidden columns

**Comment by iiNS0MNIAC** [comment]
Also wanted to note i did put in a ticket through the Telerik site

**Comment by sspasova** [comment]
> ###
> **[iiNS0MNIAC](/iiNS0MNIAC) ** commented [Jun 7, 2024](#issuecomment-2154744363) •

Thank you @iiNS0MNIAC!
Using your steps I've managed to reproduce the issue on my side. 
I've logged a new bug for this scenario as it is slightly different than the one in this issue -> https://github.com/telerik/kendo-ui-core/issues/7859
Our support engineers will have a look at your ticket whenever possible.
