### ISSUE TITLE
The whole content is not exported if it contains and img element which cannot be exported. 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2910]
### Bug report

The whole content is not exported if it contains and img element which cannot be exported.  If the img element is removed the other content is exported as expected.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/iwifuW

Notice that the done callback is never reached.

### Environment

* **Browser:** [all]

**Comment by mishoo** [comment]
This isn't a `drawDOM` issue.  It works when we use `exportPDF` instead of `exportImage`: http://dojo.telerik.com/iwifuW/2

I *think* the problem is in [Canvas::image](https://github.com/telerik/kendo-drawing/blob/master/src/canvas/surface.js#L87) — seems that when an image 404's, this method will not resolve the promise.

Not sure what the best fix is. /CC @danielkaradachki

**Comment by gaganjot07** [comment]
The issue also occurs when the image is actually there but has a 'src' attribute pointing to a svg image file

**Comment by danielkaradachki** [comment]
@mishoo 
Right, the promise will be rejected. I guess we do not need all images to be loaded to get the data URI. Will resolve it in this case as well.
