### ISSUE TITLE
DropDownList throws an exception when the optionLabel and valueTemplate are set

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2918]
### Bug report

If in the value template a field not set as dataTextField or dataValueField is evaluated, a js exception is thrown. 

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/EsIRA/2 )example.
The Quantity field evaluated in the value template causes an exception. 

A possible workaround is to set the optionLabelTemplate configuration option. 
Or to pass an object to the optionLabel configuration option with the fields used in the value template

### Current behavior
The DropDownList throws an exception.

### Expected/desired behavior
The DropDownList should not throw an exception regardless of the field used in the value template.

### Environment

The described behavior is exhibited since Q1 2016

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Iankodj** [comment]
The exception thrown is self-explanatory and it is expected to be thrown because this is an incorrect use of the optionLabel option. It should be defined in a way so that the template can be successfully populated with data.  

Like in this dojo: http://dojo.telerik.com/ULUGUgeJ.

The same is also shown in the API (the second example): https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist/configuration/optionlabel
