### ISSUE TITLE
Using an editor in detail template for a field with RegularExpression attribute in Model breaks the template

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#2925]
### Bug report

Using an editor in detail template for a field with RegularExpression attribute in Model breaks the template

### Reproduction of the problem
Using a DetailTemplate with Grid containing a field with the following RegularExpression attribute in the model breaks the rendering when the item is opened for editing:
`[RegularExpression("^[^\n\r\t]+$", ErrorMessage = "Invalid characters")] `

### Environment

* **Kendo UI version:** 2017.2.306

**Comment by gyankov** [comment]
The described behavior is expected as the backslashes in the regex are not escaped. Thus, the Html.EditorFor helper will replace the \n\r\t with their corresponding Html representations - &#10; &#13; &#9;. Due to the replaced values, the initialization script will contain invalid characters and therefore, throw an error.

If the backslashes are escaped, the correct regex is evaluated and the issue does not occur:

`[RegularExpression("^[^\\n\\r\\t]+$", ErrorMessage = "Invalid characters")] `
