### ISSUE TITLE
Incorrect Scheduler time slot selection in Chrome (zoom level 67%)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2972]
### Bug report
In Chrome if the zoom level is set to 67% certain slots in the Scheduler's month view are not selectable. Clicking on a slot sometimes causes the slot above it to be selected. 

### Reproduction of the problem
Necessary settings for the behavior to be reproduced:
selectable: true, month view, Chrome, zoom level 67%

[Screencast](https://www.screencast.com/t/pcbBBRMIF). Sample [dojo](http://dojo.telerik.com/eRoxE).

### Current behavior
Incorrect time slot selection.

### Expected/desired behavior
Correct time slot selection.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [ Chrome 57  ]

**Comment by PleasantD** [comment]
I'm seeing a very similar problem on firefox where the 3rd row highlights the 2nd row instead, but only if you set the height to exactly 900.

I'm using Kendo UI version 2015 R2

**Comment by Dimitar-Goshev** [comment]
Browser zoom level other than 100% is not officially supported.

**Comment by PleasantD** [comment]
My example clearly shows something wrong on Firefox at 100% zoom.

This is a actually a rather disappointing response. A bug has been clearly found, and repeatable examples have been provided. I realize that it may not be worth the effort to fix because it affects so few people (time is money after all)). However, it is still an indication of something wrong with the code.

Where I work, we don't close bug issues just because we don't want to fix them.

**Comment by Dimitar-Goshev** [comment]
Hi @PleasantD ,
The dojo snippet provided has 2 different versions defined in the head. It also uses two different themes. The issue is reproducible with it on my side.

Using only one of them does not reproduce the issue:
- R3 2015 - 2015.3.930 - http://dojo.telerik.com/ADIZa
- R2 2017 - 2017.2.504 - http://dojo.telerik.com/OZiPE
- R1 2018 (latest) - 2018.1.117 - http://dojo.telerik.com/oYEri
