### ISSUE TITLE
Rows are misaligned in IE10 when scrolling Grid with frozen columns

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#2977]
### Reproduction of the problem
The behavior can be seen in the video below.

[https://www.screencast.com/t/T3Z7hesLgv1Y](https://www.screencast.com/t/T3Z7hesLgv1Y)

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [IE 10]

**Comment by theOrlin** [comment]
Could not reproduce.

**Comment by theOrlin** [comment]
Reproduced when scrolling with the mouse, not the scrollbar. The mouse has to be over the unlocked columns. There is a 1px difference that shows between the rows of the locked and unlocked tables. It appears that the synchronization calculation is not working properly.

**Comment by theOrlin** [comment]
Upon further investigation, this appears to be caused by a sluggishness in the IE10's animation when synchronizing the scrollTop positions of the locked and regular content wrappers. The two positions are reported as the same when queried but there is a pixel difference in reality. It is advised to use the newer, faster versions of IE/Edge, and this appears to be a browser bug which is not related to the Kendo UI widgets.
