### ISSUE TITLE
Media player is not rendered correctly in Mobile

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#2986]
Bug report

When the MediaPlayer is in Mobile Application and is created on button click the toolbar appearance is distorted. The buttons are not functional and do not have icons

Reproduction of the problem

dojo reproducing the issue - http://dojo.telerik.com/OFomo

TID: 1126139

**Comment by mikulifourtechnolab** [comment]
We are getting the same issue 
is there any solution for same

**Comment by SwanGit** [comment]
Definitely a bug, see the excact same issue.
in our code will dynamically creating/instantiating the RadMediaplayer in code make the toolbar unusable, causing trouble in functionality (BTW: a little disturbing that this highly visible bug slipped through)

**Comment by SwanGit** [comment]
We downloaded 2017 R3 and tested the Kendo Media player, the bottom menu does still render as horrendously as ever. 

Having this bug for more than 6 months in Media player, and subsequently setting Priority 5, we assume the Kendo media player is no longer supported, and should be pulled from portefolio accordingly, to avoid more developers wasting their time.

**Comment by PreslavKozovski** [comment]
workaround: http://dojo.telerik.com/ADOxOK

**Comment by theOrlin** [comment]
The MediaPlayer was not designed to be used as a mobile app. When inserted into one, some of the class names change to mobile classes (with km- prefix), and the attached event handlers no longer work. It was working before because the classes were hard coded, instead of generated by the Toolbar API, which is used now.

If this is to be fixed, a large portion of the functionality will have to be rewritten, in effect creating a new MediaPlayer Mobile widget, which may be something to consider for the future.

Until such a widget is approved, use the workaround from the [provided dojo](http://dojo.telerik.com/ADOxOK).
