### ISSUE TITLE
German special characters break edit templates for nested Grid in the ASP.NET Core wrappers

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3004]
### Bug report
Having a field in the model containing special characters breaks the edit template for nested grid. 

Here is a simple popup template for the nested Grid:
`
@Model ModelName
@Html.TextBoxFor(m => m.gelöscht)
`

The **ToClientTemplate** method escapes characters like "ö", which breaks the templates for the nested Grid.

The same scenario works correctly with Kendo UI Grid for ASP.NET MVC

Ticket  - 1088131

**Comment by madrianr** [comment]
Hi,
some News about that Problem?

I'm waiting since many weeks for a fix...

robert

**Comment by rjdebona** [comment]
What's update about that?

**Comment by rjdebona** [comment]
Hi,

As workaround i figured out this solution, on my case it's working:

WidgetBase.cs

private static readonly Regex UnicodeEntityExpression = new Regex(@"\\+u(\d+)\\*#(\d+;)", RegexOptions.Compiled); 

The second block of regular expression must consider any characters like that:

@"\\+u(\d+)\\*#(.*?;)

**Comment by madrianr** [comment]
What's update about that?

**Comment by ag-petrov** [comment]
This is a framework behavior and we have already reported it - https://github.com/aspnet/Mvc/issues/7533.

Once the fix is available and we update our project to a version that contains the fix it should work without issues. 

For now I can suggest altering the model properties names to not include special characters or checking out if the workaround provided by @rjdebona works out for you.

**Comment by ag-petrov** [comment]
It seems that there was a misunderstanding of the real scenario initially. After double checking all the information in regards of the issue, it seems that this is something we need to reference in our code. The fix is already included in the source and will be avaible in the next official release after it passes testing.
