### ISSUE TITLE
Images could not be cut using Ctrl-x on first mouse click inside editor content in IE

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3036]
### Bug report
The images inside editor content could be selected so the user could cut them only on second mouse click. The issue is relevant for Internet Explorer.

### Reproduction of the problem
1. Navigate to [http://demos.telerik.com/kendo-ui/editor/index](http://demos.telerik.com/kendo-ui/editor/index)
2. Click on an image 
3. Try to cut using Ctrl+x

### Current behavior
The image is not cut. It is necessary to click on the image twice so that the image could be cut successfully

### Expected/desired behavior
The image is cut like in non-ie browsers.

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** 1.12.3
* **Browser:** [IE]

**Comment by Iankodj** [comment]
Reproducible with 2017.1.223.

**Comment by Iankodj** [comment]
After some further research it appears that the issue stems from a peculiar  behavior with content editable and images, and click handler. Shortly, the click handler is not raised ([](https://stackoverflow.com/questions/22338745/internet-explorer-contenteditable-image-click-event-only-triggered-every-second)). Thus, the selection is retrieved as if the paragraph is selected and the cut command would work only with a subsequent action with the selection (click or ctrl+x). 

This could be handled with a mouseup or mousedown event, but that will introduce a breaking change with the IE's resize functionality as images will not be resizable due to the selection change occurred. 
Example: https://dojo.telerik.com/axaNEVOM

Due to this reasons, the possibility to select and cut an image will remain that way or by using collapsed selection (drag the cursor through the image to select and highlight). Otherwise, the breaking change that would be introduced would harm the overall behavior with the Kendo Editor.
