### ISSUE TITLE
Select event is fired for only one file when multiple files are dropped

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3064]
### Reproduction of the problem

1. http://dojo.telerik.com/AjUWir;
1. Open the browser console;
1. Drag multiple files over the Upload;

### Current behavior
Only one filename is logged.

### Expected/desired behavior
The select event to fire for all the files.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by zdravkov** [comment]
This behavior is expected since - the select event is triggered per drop - so when one drop is performed one select event is expected and the e.files property contains the files that are dropped so if you want to show the files you should iterate them. The same is happening when clicking on the input and selecting multiple files for upload.
