### ISSUE TITLE
Toggle of chart series could lead to canvas resize

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3078]
### Bug report
Enabling/disabling chart series could lead to increase of canvas height by several pixel for some markup.

### Reproduction of the problem
See this sample: http://dojo.telerik.com/ALazE/2
If you will add style="width:100%; height:100%" to a div without styles - issue disappears.

### Current behavior
Disabling/enabbling series increase chart's height for each toggle operation.

### Expected/desired behavior
Chart size remains the same.

### Environment

* **Kendo UI version:** v2017.1.223
* **jQuery version:** 3.1.1
* **Browser:** all

**Comment by inikolova** [comment]
We have added an improvement which will prevent the observed outcome - until the fix is available you could use the following CSS as a workaround: `.k-chart > canvas {
   vertical-align: top;
 }`

However, please keep in mind that web standards require elements with a percentage height to have a parent with an explicit height. The rule applies recursively until an element with a pixel height is reached, or the root <html> element is reached. In the latter case the body and html elements need a 100% height style as well. 100% high elements cannot have margins, paddings, borders, and siblings. I.e. following this statement, adding height to the chart div ancestors will fix the problem ->http://dojo.telerik.com/@Iliana/uPuqe
