### ISSUE TITLE
Unable to reach last column custom editor button

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3105]
### Bug report

It is not possible to interact with the custom editor button of the last column, as it is hidden behind the vertical scrollbar.

May be related to: #3862

### Reproduction of the problem
1. Use the following [Dojo](http://dojo.telerik.com/OQiYa)
2. Scroll Spreadsheet to see L column and click on L1

### Current behavior
L1's custom editor button is behind the vertical scrollbar:
![image](https://cloud.githubusercontent.com/assets/6614183/25432496/5dcc83f2-2a8d-11e7-8001-103493dbc094.png)

### Expected/desired behavior
There is additional space to the right of the last cell to fit a custom button, similar to Excel:
![image](https://cloud.githubusercontent.com/assets/6614183/25432585/aeb3d4d2-2a8d-11e7-8fbf-bd8c1ae61220.png)

OR the button appears over the scrollbar

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [all]

**Comment by veselints** [comment]
Also reported in Ticket ID: 1113733 and Ticket ID: 1113633

**Comment by lkarakoleva** [comment]
I suggest we relocate the custom editor button on the left side of the cell in the last column.

![_spreadsheet](https://user-images.githubusercontent.com/16577622/27129360-a1c873ec-510a-11e7-8753-f54f804b8c2b.png)

**Comment by mishoo** [comment]
Actually the fix for this is not good enough yet.  It's done for the very last column, but that's not sufficient — e.g. you have a spreadsheet of 50 columns, so you need to scroll horizontally to see column 40, it's possible to scroll to such position that its button is under the scrollbar.  It needs to be done a little more dinamically (consider the actual dimensions and scroll position when deciding where to place the button).

**Comment by IvanDanchev** [comment]
Also reported in Ticket ID:  1116373
