### ISSUE TITLE
DropDownList auto-selects first option, but does not update MVVM binding.

### ISSUE THREAD

**Issue by rally25rs** [telerik/kendo-ui-core#312]
If a DropDownList is MVVM bound to a `source` and a `value`, the list will visually be set to the first item, but the MVVM bound value stays unset.

jsFiddle: http://jsfiddle.net/rally25rs/kpvgey6p/1/

Code:

```
<input data-role="dropdownlist"
       data-bind="source: items, value: selected"
       data-text-field="text"
       data-value-field = "value"
/>

<button data-bind="click: getSelected">Get Selected Value</button>
```

```
var vm = kendo.observable({
    getSelected: function () {
        alert(vm.selected);
    },
    
    items: [
        { value: 1, text: "Item 1" },
        { value: 2, text: "Item 2" },
        { value: 3, text: "Item 3" }
    ],
    
    selected: undefined
});

kendo.bind($("body"), vm);
```

If you click the button right after opening the page, it will report that `vm.selected` is undefined.

**Comment by ggkrustev** [comment]
Quick clarification what has happened in order to address this issue:
1. [Since Q1 2015](http://docs.telerik.com/kendo-ui/install/changes-and-backward-compatibility#changes-from-2014-q3-sp2-201431411), DropDownList allows to de-select its value. This change was introduced in order to match better default behavior of the SELECT element. It allows to de-select its item using value attribute.
2. The commit (773ff474dea58c5437a42857fe0e10665a84c017) that closes this issue prevents selection of the first item if the widget's value is set using the value method.

With all these changes, now the widget can match the model state and we will not be forced to update the model automatically on load, which is "dead wrong".

If someone wants to get the previous behavior, then he/she will need to select first item manually:
```javascript
  dataBound: function() {
    this.select(0);
    this.trigger("change");
  }
```
