### ISSUE TITLE
Filter menu with multi: true is missing localization message for number of selected items

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3146]
### Bug report

There is no localization message entry for the selected items text in the multi-checkbox filter.

[Screenshot](https://www.screencast.com/t/6y27PHzvnu9)

[Messages file](https://github.com/telerik/kendo-ui-core/blob/master/src/messages/kendo.messages.en-US.js#L292)

### Current behavior
The message can be localized by specifying a custom selected items format, using [selectedItemsFormat](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-filterable.messages.selectedItemsFormat) property.

### Expected/desired behavior
The default message should be localizable like the pager messages that support custom formatting.

**Comment by madelson** [comment]
We just got burned by this as well. When is the fix for this expected?

**Comment by jmclocklin** [comment]
The scope of this issue is actually a bit larger. The kendo.messages files are missing the message entries for several strings that should be localizable. 

It should contain this full set of messages:
`kendo.ui.FilterMultiCheck.prototype.options.messages =
$.extend(true, kendo.ui.FilterMultiCheck.prototype.options.messages,{
  "checkAll": "Select all",
  "clear": "Clear",
  "filter": "Filter",
  "search": "Search", 
  "cancel": "Cancel",
  "selectedItemsFormat": "{0} items selected"`

However, en-US only had 4/6, while ja-JP, zh-CN, zh-TW (for example) only had 1/6.

**Comment by sgjoy1** [comment]
Just ran into this issue, as well as missing translations for dropdown options in FilterCell and FilterMenu. Any update on the state of translations?

**Comment by NikoPenev21** [comment]
reported in #1574330

**Comment by mihaela-lukanova** [comment]
Increased priority due to a report in TicketID: 1574407

**Comment by ag-petrov** [comment]
Seems to be working in the latest version - https://dojo.telerik.com/EqeZacoV
