### ISSUE TITLE
msAllFormatting does not remove text styling, when pasting text (only a part of a paragraph) from Word in IE

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3154]
### Bug report (See [comment](#issuecomment-463982823))

**msAllFormatting** paste cleanup does not remove text styling when pasting text (only a part of a paragraph) from Word.

### Reproduction of the problem
* Open the following [Dojo](http://dojo.telerik.com/oZUla/2) in IE; 
* Copy part of a paragraph from the following Word document: 
[test.docx](https://github.com/telerik/kendo-ui-core/files/2460674/test.docx)

* Paste the text in the Editor;

### Current behavior
The text will retain its font size and name formatting;

### Expected/desired behavior
The font-name and font-size decoration derived from MS Word are stripped: 
https://docs.telerik.com/kendo-ui/controls/editors/editor/pasting#clean-html-on-paste

### Environment
* **Browser:** [ IE 11 ]

**Comment by Iankodj** [comment]
The described behavior is expected and normal. In IЕ, word-specific styling is handled by the browser and the **msAllFormatting** is never actually applied. 

Due to that, there is no available meta data to programmatically define whether this content is copied from Word or another HTML application. 

Therefore, the **css** filter should be applied. 

I am converting this from a bug to documentation task so that it is noted that any MS-Word-related filters are not applied in IE and it is the browser that converts MS-Word content to HTML.
