### ISSUE TITLE
Multiple places with incorrect Date object creation

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3171]
### Reproduction of the problem
There are a lot of places where Date constructor, which accepts year, used without setFullYear call.
E.g. kendo.date.firstDayOfMonth function, but there are more such places.

```
var date = new Date(1, 2, 3);
date.setFullYear(1);
console.log(kendo.date.firstDayOfMonth(date));
```

### Current behavior

```
// result : Fri Mar 01 1901 00:00:00 GMT+0100 (W. Europe Standard Time)
```

### Expected/desired behavior

```
// should be: Thu Mar 01    1 00:00:00 GMT+0100 (W. Europe Standard Time)
```
### Environment

* **Kendo UI version:** v2017.1.223
* **jQuery version:** 3.1.1
* **Browser:** all

**Comment by MaceWindu** [comment]
Same for Date.UTC function

**Comment by ag-petrov** [comment]
Indeed there are places where Date constructors are used which do not handle the case where dates prior to 1900 are used. However this is typical JavaScript behavior and altering the mechanism to not follow the current behavior is a breaking change that will affect users that are currently depending on the way the methods work. Since the last mentioned is not desirable I am marking this as wont fix.

As a workaround I can suggest resetting the year after calling our methods or implementing custom logic to handle these cases.

**Comment by MaceWindu** [comment]
Well, we just replace Date constructor and Date.UTC methods with wrapper that handle parameters properly. As it is not an option to constantly patch all libraries that use it incorrectly.
I agree that Date class is the scariest javascript abomination.
