### ISSUE TITLE
Setting Spreadsheet formulas between sheets does not work properly (using keyboard)

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3210]
### Bug report

Setting Spreadsheet formulas between sheets does not work properly (using keyboard)

### Reproduction of the problem
use the attached document for replication of the problem
[MS Excel vs. Telerik Spreadsheet.pdf](https://github.com/telerik/kendo-ui-core/files/1004498/MS.Excel.vs.Telerik.Spreadsheet.pdf)

### Environment

* **Kendo UI version:** 2017.2.504

* **Browser:** ALL

**Comment by Dimitar-Goshev** [comment]
After the fix, cells from another sheet have a sheet prefix, which shows that they are from another sheet.
However, when the formula is calculated, the current sheet remains visible, instead of switching back to the initial sheet, which holds the cell with the formula.
In addition to that, if you click on the initial sheet, the B1 and B2 cells, which were part of the formula, still appear as part of the formula (they have colorful background). If you click to another cell and then to another one, e.g. C1 and C2, you would not be able to type in them, until you double click a cell.
[Video](http://www.screencast.com/t/PQsfb3EGbux)
Steps to reproduce:
- Use the Spreadsheet Basic usage demo.
- Create a sheet and enter 4 at B1 and 7 at B2
- Create another sheet and enter 5 at B1 and 2 at B2
- Go to Sheet 1 and click on B4.
- Write = and then click on B2, write + and click on B1.
- Write + and click on Sheet 2, then click B2, write + and click on B1.
- Press Enter.

Expected: formula result is calculated, Sheet 1 is shown and B1 and B2 are not colorful anymore. Clicking on another cell, then on another one, would allow you to enter text in the cell.
Actual: formula result is calculated, Sheet 2 remains shown, B1 and B2 on Sheet 1 remain colorful. Clicking on a cell, then on another one and trying to type would not allow you to enter text. If you just click on one cell, without then clicking on another one, you would be able to type.
