### ISSUE TITLE
A navigatable Grid will incell editing is "jumping" when the whole Grid is not visible.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3213]
### Bug report

A navigatable Grid with incell editing is "jumping" when tabbing and the whole Grid is not visible.

### Reproduction of the problem

The issue can be observed in our demo: http://demos.telerik.com/kendo-ui/grid/editing

Please check the video for visualisation: https://www.screencast.com/t/C6Yt6gH5RcOb

### Environment

* **Browser:** [all]

**Comment by ag-petrov** [comment]
The described behavior is expected and is caused by the fact that we internally call focus, after which the browser scrolls automatically. Removing the focusing logic will lead to scenarios where you have scrolled the page in such a manner so that the grid is not visible and once you tab the end user will not see the newly edited cell which is not desirable. Moreover removing the focusing logic may break the overall keyboard navigation.
