### ISSUE TITLE
ToDataSource result method is generating wrong LINQ when the Grid(MVC Core) is grouped by two or more nested fields.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3215]
### Bug report

ToDataSource result method is generating wrong LINQ when the Grid is grouped by two or more nested fields.

### Reproduction of the problem

More information on the issue and a runnable project can be found in ticket: 1104710

Also, @Xizario is aware of the issue in more details.

**Comment by dvdobrovolskiy** [comment]
Any update on this?

**Comment by Xizario** [comment]
@dvdobrovolskiy, it will need major rewrite and change of how the query is built.

At this moment to resolve such problem a View-Model with all fields can be created and bound to the grid, thus, removing the nested grouping.

**Comment by dvdobrovolskiy** [comment]
Can you please advise me how grid paging will work on this case?
So I just make VM, select from model and .ToDataSourceResult(request) all this? isn`t get all rows from table? For now I patched it with .tolist() but I have tremendous amount of data and query time is increasing rapidly.

PS also I cannot sort on grouping filed and this is also makes telerik grid grouping a big shame

**Comment by Xizario** [comment]
I don't mean all rows, rather all fields.
For example if your original model was:

```.
obj.RootProperty
obj.RootProperty.NestedProperty
obj.RootProperty.NestedProperty.NestedNestedProperty
obj.RootProperty2
```
Now you would have model like:
```
obj.RootProperty
obj.NestedProperty
obj.NestedNestedProperty
obj.RootProperty2
```
It is always better to flat the data yourself, since you will show it later in 2D table (the Grid), rather than binding the grid directly to the nested fields. This will simplify the queries, as well, and you can do it even on database level if required.

This does not affects the paging. And you don't need to do .ToList(), yet it also resolves the issue.

off-topic:
About the sorting and grouping and nested properties and all other database related operations, I think some people miss the part that the Grid is UI component, and its main purpose is to render 2D array of data into html table, and providing further user interactions capabilities with nice interface.  
Yet it comes with some automatically grouping and filtering capabilities and people naturally assume they could skip entire layers of the application design.

**Comment by ag-petrov** [comment]
Currently we do not have plans for providing built-in support for grouping on nested properties. Thus I am marking this item as closed. In order to corectly populate the grouped grid one should flatten the data source as suggested by @Xizario.

**Comment by dvdobrovolskiy** [comment]
@Xizario off-topic: you also should consider that there is a lot of solution on market to present flat data and arrange it into nice looking grid. Telerik components good is exactly the fact that you can skip entire layers of the application design. Otherwise if I need to to it myself what is worth $1500? 

I my case I paid exactly for that and I am really disappointed in @ag-petrov decision.
