### ISSUE TITLE
The Grid with virtual scrolling cannot be scrolled on MS Surface with swipes. 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3220]
### Bug report

The Grid with virtual scrolling cannot be scrolled on MS Surface with swipes.

Still, it can be scrolled only via the scrollbar.

### Reproduction of the problem

The issue can be observed in our demo on a Surface tablet: http://demos.telerik.com/kendo-ui/grid/virtualization-local-data

### Environment

* **Browser:** [all (Surface)]

**Comment by Stamo-Gochev** [comment]
The behavior is expected as the MS Surface is a hybrid device (supports both mouse and touch interaction) and our tests show that mixing mobile and desktop interaction results in worse user experience.

The so-called "kinetic scrolling" implementation that is used for other devices (running on Android or iOS for example) is due to the fact that their scrollbars are only shown when dragging the scrollable area (the content of the grid), which prevents the user from dragging the scrollbar itself. 

This is not the case with MS Surface as the scrollbars are visible at all items. That is why the kinetic scrolling is not enabled by default:

https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L2246

However, it can be manually enabled if such interaction is required:
```
$(document).ready(function() {
    var kineticScrollNeeded = kendo.support.kineticScrollNeeded; //cache the original value
    
    if (shouldEnableKineticScroll) {        
        kendo.support.kineticScrollNeeded = true;
    }
    
    //initialize the grid
    
    kendo.support.kineticScrollNeeded = kineticScrollNeeded; //restore the original value
});
```
