### ISSUE TITLE
Grid pager not updated when using pushUpdate to change a record so it stops satisfying the Grid filter criteria.

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3223]
### Bug report

When you use pushUpdate to change a record so it stops satisfying the Grid filter criteria, the record is removed from the Grid. However, the total counter of the pager is not updated.

### Reproduction of the problem

http://dojo.telerik.com/oridO/8

### Current behavior

The pager is not updated.

### Expected/desired behavior

The pager is updated.

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** 1.12
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
Calling `grid.pager.refresh();` is fixing the issue.

**Comment by Stamo-Gochev** [comment]
The behavior is by design - https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.pager.js#L269. because there are cases, in which re-rendering of the pager is not required, such as when the grid is edited by the end user (using the UI).

As there are situations, when a manual update to a data item (with things like `pushUpdate`, `set`, etc.) might or might not require an update of the UI, it is up to the developer to decide whether to call `refresh` or not.
