### ISSUE TITLE
TreeView with enabled LoadOnDemand and local data-binding renders all nodes on load.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3234]
### Bug report

TreeView with enabled LoadOnDemand and local data-binding renders all nodes on load.

### Reproduction of the problem
You can reuse the implementation demonstrated in our online demo below, and simply enable the LoadOnDemand option:
[http://localhost:61330/treeview/local_data_binding](
http://localhost:61330/treeview/local_data_binding)

Same scenario in kendo UI for jQuery is working properly when the LoadOnDemand is enabled ([http://demos.telerik.com/kendo-ui/treeview/local-data-binding](http://demos.telerik.com/kendo-ui/treeview/local-data-binding))
### Current behavior
The items are not rendered upon expand of their parent node

### Expected/desired behavior
The items should be rendered upon expand of their parent node

### Environment

* **Kendo UI version:** 2017.2.504* **jQuery version:** x.y
* **Browser:** ALL

**Comment by zdravkov** [comment]
This is the default expected behavior in the MVC wrapper - when such datasource structure is configured the TreeView will create a TreeView item for every item in the structure and will render it without passing a datasource property to the widget. That is why it is expected that the LoadOnDemand property is also disregarded.
