### ISSUE TITLE
Splitter does not work with AngularJS version 1.6.0+

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3256]
### Reproduction of the problem
Reproducible in our Splitter AngularJS demo, if version 1.6.0+ is loaded. [Dojo](http://dojo.telerik.com/ufOlE) example. 

### Current behavior
Js exception with AngularJS version 1.6.0-1.6.4. 

### Expected/desired behavior
Splitter to work correctly with the [supported](http://docs.telerik.com/kendo-ui/intro/installation/prerequisites#supported-angularjs-versions) AngularJS versions. 

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by JoseGoncalves** [comment]
Is there any milestone for this bug to be fixed?
It still exists with Kendo UI 2017.2.621 with all AngularJS 1.6.x (including the latest 1.6.6).

**Comment by Iankodj** [comment]
Although there is a bug fix on this item, the problem is actually related to the exampled case. 

With AngularJS 1.6.*, `k-ng-model` and `k-value-primitive` should be added to the DropDownList in order to properly bind the orientation property. 

http://dojo.telerik.com/ufOlE/9

Generally, due to the incorrect binding, the orientation property outputs null and the Splitter logic cannot process that appropriate. The fix here addresses a feature detection for the orientation option in order to prevent beeing processed as null. 

However, using the `k-ng-model` against recent AngularJS versions is noted here: http://docs.telerik.com/kendo-ui/intro/installation/prerequisites#supported-angularjs-versions.

**Comment by JoseGoncalves** [comment]
OK, understood, need to use `k-ng-model` and `k-value-primitive` to properly bind the `orientation` property.

Nevertheless, the Kendo UI documentation should be updated, because as it is right now it seems that this is only needed for AngularJS 1.5.* and Kendo UI older than R1 2017. At least that is my understanding from the following quotes;

```
Kendo UI provides limited ngModel support for AngularJS 1.5*.
```
```
Using AngularJS 1.5* and Kendo UI version older than R1 2017 is recommended only with the Kendo UI k-ng-model directive, because the ng-model directive does not reflect the model value.
```

**Comment by mparvanov** [comment]
@JoseGoncalves An internal request for documentation update has been logged in our backlog.
