### ISSUE TITLE
Add demo services for grouped data 

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3258]
### Current behavior

With the current implementation of these services ([Orders](https://demos.telerik.com/kendo-ui/service/Northwind.svc/Orders) and [ValueMapper](https://demos.telerik.com/kendo-ui/service/Orders/ValueMapper)) it is not possible to demonstrate virtualization and grouping of items in the ComboBox, DropDownList, MultiSelect and AutoComplete widgets demos.

[Dojo](http://dojo.telerik.com/EVexU)

### Expected/desired behavior

There should be two new services available for grouped data.

**Comment by Marouenbaklouti** [comment]
Hello 
Any news ? for this !!!

**Comment by SimonHostettler** [comment]
Were also waiting for this future to come, in the MVC Wrapper the DropDown works but when clicking then item to select it, it will give a JS error.

**Comment by freserovski** [comment]
Hi. Is that already done? We are using the virtualization with the kendo ui multiselect. When selecting item with keyboard (enter) the item is selected. But when using mouse click nothing happens! Please fix that as soon as possible - it is a bug!

**Comment by IvanDanchev** [comment]
Currently, except for item selection, virtualization and grouping work together. Correct subsets of data are requested/returned and displayed when scrolling. 
Initially the **_select** function (kendo.virtuallist.js). calls the **_findDataItem** function and passes a subset of the data to it (the view parameter). With grouping enabled _findDataItem expects its first parameter to be an array of objects each of which having an "items" property ([screenshot](https://www.screencast.com/t/2cN1DYYA)).  On item selection a js exception is thrown in _findDataItem function caused by the **dataItemByIndex** function calling _findDataItem 
 and passing a subset of data in a different than the expected format ([screenshot](https://www.screencast.com/t/vTvouTe5B1Y)). An enhancement of selected item index calculation/persistence is needed.
