### ISSUE TITLE
The input elements with type="text" and the selects elements are not exported as expected on PDF.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3264]
### Bug report

The input elements with type="text" and the select elements are not exported as expected on PDF.

- Inputs are exported like they are highlighted 
- The arrow is not exported.

### Reproduction of the problem

The issues can be observed in the following example: http://dojo.telerik.com/OHUPi

### Environment

* **Browser:** [all ]

**Comment by mishoo** [comment]
Rendering of form fields cannot be perfect, as it's browser and OS-dependent. (also, we use the computed style to draw elements, but that does not contain sufficient information, for example there's nothing in there about the select arrow).

The limitation about `<select>` is [documented](http://docs.telerik.com/kendo-ui/framework/drawing/drawing-dom#known-limitations).  The suggestion is to use a Kendo DropDown, which outputs fine.

As for the text fields, they should look OK if explicitly styled.  The issue there is that the browser reports a "2px inset black" border for the text fields, but since we only support solid border (again, documented limtation) that looks like 2px solid black.  The first input in your Dojo (with `k-textbox` class) looks OK.
