### ISSUE TITLE
Spreadsheet destroy method does not terminate the widget completely.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3278]
### Bug report

Event with the empty or remove methods (on spreadsheet dom element) are used in combination with the destroy method, the widgets is not destroyed entirely. This is causing the inability to properly initialize a new instance of the control on the same div. Formulas are also cashed.

### Reproduction of the problem
Use the dojo: [http://dojo.telerik.com/@nenchef/IhUcE/2](http://dojo.telerik.com/@nenchef/IhUcE/2)

Steps to reproduce formula cashing:
1. Delete the first row, using the context menu of the row.
2. Click the "Destroy the Spreadsheet" button to destroy and create a new instance of the widget.

Note: If you initially click the "Destroy the Spreadsheet" button and then follow the above-listed steps, the problem will not appear.
### Current behaviour

You can observe how the wrong calculation of the formula in B2 is cached from the previous instance of the Spreadsheet

### Expected/desired behavior
The widget should get initialized as the first time the page is loaded.

### Environment

* **Kendo UI version:** 2017.2.504

* **Browser:** ALL

**Comment by basarawu66** [comment]
Hello,
Sorry for my bad english.
There have two problem, first one ,because first load a new formula, you can see refs is CellRef ,but formula is not clone(this is important),so when delete row one you can see refs will NullRef in FORMULA_CACHE,
![image](https://cloud.githubusercontent.com/assets/13127870/26660753/8bfd39ac-46ac-11e7-90a5-6fa37e0ed503.png)
![image](https://cloud.githubusercontent.com/assets/13127870/26660815/122f31ba-46ad-11e7-9a27-08a8b6dff2cf.png)

Second  ,FORMULA_CACHE is not clear when destroy

**Comment by mishoo** [comment]
Funny this went undetected for so long.  I would say it's pretty serious.  Fix pushed.
