### ISSUE TITLE
Kendo Data Node's parentNode method returns undefined if the node is set as field value in the view model

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3287]
### Bug report
After setting an Observable's field value with the **set** method by passing a kendo.data.Node object, the node's **parentNode** method returns undefined. 

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/icOsO) example. Click on a child node (Column Node). After the selectedNode filed is set (vm.set("selectedNode", selectedNode);) the node's parentNode method returns undefined. 

### Current behavior
The node's parentNode method returns undefined. 

### Expected/desired behavior
The child nodes' (Columns) parentNode method returns the parent node. 

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by zdravkov** [comment]
The behavior is expected because when we use the 'vm.set' method over the node, it becomes a child of the vm and it looses its actual parent Node. Yet in order to have correctly working Treeview we need the parent child observable relationship between nodes. That is why in such case we would rather recommend setting the sub property of the Node as for example it is done in this [dojo ](http://dojo.telerik.com/@zdravkov/oWAres)
