### ISSUE TITLE
Cell bottom border created before 2017 R2 does not render 

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3328]
### Bug report

Cell bottom border created prior to Kendo 2017 R2 Release (2017.2.504) does not render on latest version.

### Reproduction of the problem

The behavior can be observed [in the following Dojo example](http://dojo.telerik.com/uFOqOM/2). 

Additional screencast can be found [here](https://www.screencast.com/t/ww3ULMBFwIu).

To reproduce the issue follow these steps:
* Run the example (notice that the B2 cell has bottom border)
* Change the Kendo UI version to the latest 
* Run the example (the bottom border for cell B2 is missing)

### Expected/desired behavior

Cell border should be preserved across different versions.

### Environment

* **Kendo UI version:** 2017.2.504

**Comment by mishoo** [comment]
There was a major overhaul of the border rendering.  This minor breaking change is one of the effects.  However, I can argue that the current behavior is the correct one: in the JSON initialization, the cell `B3` specifies: `"borderTop": null`, which means B3 should *not* have a top border — there you go. ;-)

**Comment by jivanova** [comment]
As @mishoo have described, we consider the described behavior as expected. The behavior in the Spreadsheet widget is the same as the one in Excel.

**Comment by jwbqv** [comment]
The behavior in the latest Kendo spreadsheet the behavior is exactly the opposite of the way that Excel works.      The previous versions of Kendo spreadsheet worked like Excel; however the new version of Kendo spreadsheet doesn't work like Excel -- specifically it's not properly saving the user selected top and bottom borders to the JSON.

I think I see where the mis-communication occurred.

In my original support ticket, I stated:

"The JSON in this example was created by version 2017.1.223 via a user's selections from the toolbar.   That user set the cell to have a top border and a bottom border. "

That comment did not get transcribed into this github ticket so of course your analysis that the spreadsheet is processing the JSON properly is a correct statement.

The issue/bug is that the JSON was not saved correctly.   What I put in the Dojo example was the JSON that was created by a user selecting a top and bottom border in t a single cell ... something that a user is able to do from toolbar button just like he does in Excel, and something which shows up properly on the screen when he does it.

The issue/bug is that the two borders are not being properly written to the JSON hence the user's border selections are not properly saved.

As noted, this all worked correctly in the prior versions of Kendo spreadsheet.

Almost every one of our users puts both top and bottom borders in cells, which they use for the "accounting double underlines" which are required by GAAP.

Asking every one of our users to go back to all their spreadsheets and change it will not work for us or for them, especially since what they do now in the older version is exactly how they do it in Excel already hence we can hardly tell them "it's been changed to work like Excel".

That makes this bug a show stopper for us.   We cannot move to the latest release of Kendo spreadsheet until this is fixed.

https://www.screencast.com/t/NJSHT57z

Thank you
