### ISSUE TITLE
Start time of event is incorrectly calculated in timezones with DST

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3381]
### Bug report

Project available: #1116866

### Reproduction of the problem
1. Modify system configuration settings:
     TimeZone: (UTC+10) Canberra,Melbourne,Sidney
     DST ON
2. Set TimeZone to the Scheduler - ("Etc/UTC")

Еxample Start and End for an event:
``` C#
Start = new DateTime(2017, 10, 1, 2, 0, 0, 0, DateTimeKind.Utc),
End = new DateTime(2017, 10, 1, 4, 0, 0, 0, DateTimeKind.Utc)
```
### Current behavior
Event StartTime is displayed - 3:00

### Expected/desired behavior
Event StartTime to be displayed - 2:00

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Setup for reproduction with timezone on machine Europe/Sofia:
```
    <div id="example">
        <div id="scheduler"></div>
    </div>
    <script>
        $(function () {
            $("#scheduler").kendoScheduler({
                date: new Date("2015-03-15"),
                startTime: new Date("2015-03-15T00:00:00.000Z"),
                views: [
                    "day",
                    { type: "week", selected: true },
                    "month",
                    "agenda",
                    { type: "timeline", eventHeight: 50 }
                ],
                timezone: "Etc/UTC",
                dataSource: [{
                    id: 0,
                    title: "Every day +1",
                    start: new Date("2015-03-21T03:00:00.000Z"),
                    end: new Date("2015-03-21T04:00:00.000Z"),
                    recurrenceRule: "FREQ=DAILY"
                },
                {
                    id: 1,
                    title: "29th",
                    start: new Date("2015-03-29T03:00:00.000Z"),
                    end: new Date("2015-03-29T04:00:00.000Z"),
                },
                {
                    id: 2,
                    title: "30th",
                    start: new Date("2015-03-30T03:00:00.000Z"),
                    end: new Date("2015-03-30T04:00:00.000Z"),
                }]
            });
        });
    </script>
```
**Result:**
![image](https://user-images.githubusercontent.com/6614183/28421187-1192686c-6d6d-11e7-9eab-6ab0a7257a69.png)

**Expected:** events on 29th of March start at 3 AM UTC.

**Comment by veselints** [comment]
The current behavior of the Scheduler for recurring events seems correct. It, however, also demonstrates a deficit. When running the following Dojo:
https://dojo.telerik.com/uvAPUrIf/11
you will notice that the occurrence on 29th March has its start time at 4:00 AM and its end time at 5:00. That, I am afraid is not correct. The general issue, in this case, is the fact that the slot between 3:00 AM and 4:00 AM does not exist in the local timezone (Europe/Sofia) where the browser runs. That is because of the DST change. 4:00 AM is immediately after 2:59. Hence, the browser could not create a Date object for the specified timespan. Any Date object created for 3:00 AM will be converted to a Date object for 4:00. That is the reason why the single event has both its start and end dates set to 4:00 AM. I would say that such a result is indeed expected.
