### ISSUE TITLE
Impossible to scroll listbox on touch devices when drag & drop is allowed 

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#3382]
### Reproduction of the problem
Open the following demo on a touch device and try to scroll: https://demos.telerik.com/aspnet-mvc/listbox/drag-and-drop.

Ticket reporting: ID 1117775

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** all browser on touch devices

**Comment by ag-petrov** [comment]
This is not a bug, the bavior is caused by the way we handle events internally. Moreover when enabling drag and drop in a scrollable listbox when tapping and moving should the listbox create the drag item and allow the user to reorder or should it scroll? This is a configusing UX and we recommend displaying the toolbar for performing reorder and transfer without enabling drag and drop thus allowing the user to scroll without any problems.
