### ISSUE TITLE
Refreshing hidden grid leads to incorrect virtual scroll size

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3390]
### Reproduction of the problem
E.g. we have a grid that could be displayed/hidden by user and hide operation triggers data refresh. On data refresh grid recalculates row height, but because grid is hidden already, calculation returns 0. When user displays grid again, he cannot scroll it properly due to incorrect scroll size.

### Expected/desired behavior
Scroll size shouldn't be updated when grid is not displayed (or current row height calculation returned 0)

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 3.1.1
* **Browser:** all

**Comment by matanasov** [comment]
@MaceWindu 
Could you please provide a runnable example that demonstrates the problem?

**Comment by MaceWindu** [comment]
http://dojo.telerik.com/ARInum

you can notice that after each hide/show iteration scrollbar size decreased.

**Comment by matanasov** [comment]
@MaceWindu 
Thank you for the example. It seems like an issue on our side. 
I am assigning it to one of our developers for review.

**Comment by Stamo-Gochev** [comment]
Resetting the data of the grid while it is hidden prevents us from calculating the correct row height as you mentioned and this is also listed in the limitations section of the documentation:

https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#limitations-for-virtual-scrolling

In addition, modifyting the data requires resetting the virtual scrollbar to the top:

>Refreshing or replacing the Grid data in the virtual mode has to be accompanied by resetting the position of the virtual scrollbar to zero—for example, by using $('#GridID .k-scrollbar').scrollTop(0);. In some scenarios, you might also need to call the refresh() method.

What I can suggest is to update the data when the grid is shown (instead of hidden) as changing it when clicking the "hide" button will not result in any visible change anyway:

http://dojo.telerik.com/EgeVe

If you have further questions regarding the matter, do not hesitate to open a support ticket so that our team can provie additional technical assistance.
