### ISSUE TITLE
PDF Export (drawDOM) in IE is very slow

### ISSUE THREAD

**Issue by LuqiYan** [telerik/kendo-ui-core#3401]
When export Kendo Grid to PDF in IE, it is very slow. **When data is large, IE is not responding**.
There is a big performance difference between Chrome and IE. In the following example, Chrome takes **1s** and IE takes **31s**.

Version: 2017.2.621
Example Code: http://dojo.telerik.com/aFaZu

**Comment by cbettero** [comment]
It's the same on Firefox... extremely slow: on a 15 A4 pages html, it takes about 50-60 seconds to complete....

**Comment by matanasov** [comment]
@mishoo 
Is there anything we can do to improve the performance in IE. Edge is a bit better, but still far away from Chrome and FF

**Comment by mishoo** [comment]
@matanasov TL;DR: most probably nope :-(

I looked into it a few times before, but I have no idea for improvement.  IE is just slow.  Profiling shows that the worst performers are actually native [1]:

![ieprofile](https://user-images.githubusercontent.com/334725/31542201-ce04e972-b019-11e7-9dd0-f9cb248b4190.png)

[getClientRects](https://developer.mozilla.org/en-US/docs/Web/API/Range/getClientRects) is called a lot for rendering text (and even much more when `text-align: justify`, or non-contiguous text (such as in a grid, table etc.).  IE seems to be very slow about that.  We also necessarily do some hacks for IE, to workaround bugs (they don't add *much* overhead, but still) — for example IE has a form of [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=612459) too, for which I had to write some horrible code that works both for Chrome and IE.

[1] this profile is for a different demo, but the issue is the same: lots of non-contiguous text.  That particular test takes 200ms in Chrome and 1.6s in IE 11.

**Comment by matanasov** [comment]
@hadjieva 
Let me know how do we proceed with this.

**Comment by tsvetomir** [comment]
Doesn't look to be fixable at the moment. Suggestion is to split the export into smaller batches, if feasible.

Just a reminder that the PDF export module relies a lot on the browser and it's DOM API implementation. If things fail, we don't have an alternative to fall back to.
