### ISSUE TITLE
Currency and DateTime formattings are not imported properly from excel

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3430]
### Bug report

Currency and DateTime formattings are not imported properly from excel
"[$€-2] 9,876,543,210.12" instead of "€ 9,876,543.12", for the value: 9876543210.12345.  And "[$-4428109]3/15/17 6:30 PM" instead of "3/15/17 6:30 PM".

### Reproduction of the problem
Navigate to http://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export
Import the attached excel that contains columns with currency and DateTime formatting.
E.G Row: 

€ 23,00 | Test | 12.5.17 3:30 AM

### Current behavior
The data inside the SpreadSheet is 

[$€-2] 23.00 | Test | [$-4430749]12/5/17 3:30 AM

### Expected/desired behavior
The data inside the SpreadSheet is 
€ 23,00 | Test | 12.5.17 3:30 AM

### Environment

* **Kendo UI version:** 2017.2.621

**Comment by mparvanov** [comment]
[test.xlsx](https://github.com/telerik/kendo-ui-core/files/1162808/test.xlsx)

**Comment by mishoo** [comment]
The problem here is that our code can't understand this format: `[$€-2] #,##0.00`.  Apparently, it's an “international number format”; I found very little information about it (there's this [stackoverflow question](https://stackoverflow.com/questions/5896811/excel-custom-format-what-does-%E2%82%AC-2-mean); nothing in the ​[official docs](https://support.office.com/en-us/article/Number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68) or this [comprehensive guide](http://www.exceltactics.com/definitive-guide-custom-number-formats-excel/).

**Comment by mparvanov** [comment]
Closing as the `[$€-2] #,##0.00` is not a [supported format](https://www.exceltactics.com/definitive-guide-custom-number-formats-excel/).
