### ISSUE TITLE
Editor's resize handle overlaps the vertical scroll bar's down arrow

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3445]
### Bug report

When [resizable.content](http://docs.telerik.com/kendo-ui/api/javascript/ui/editor#configuration-resizable.content) is set to **true** and a vertical scroll bar is shown the resize handle overlaps the scroll bar's down arrow and prevents scrolling by clicking on the arrow. 

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/ECEmi) example. 

Workaround:
```html
<style>  
  .k-editor .k-editable-area .k-content {
    height: 88%;
  }
</style>
```

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [Chrome, Firefox, Edge]

**Comment by Dimitar-Goshev** [comment]
After a fix was applied, now the resize handle does not overlap the scrollbar anymore. Besides that, this fixed another issue that the white resize handle was not visible on white background, e.g. in Material theme.

There is another issue still remaining related to the resize handle, which is since it was made a font icon for R1 2017. The cursor does not become a resizing arrow on hovering in LESS themes.

Another issue related to resize handle in SASS themes is logged here - https://github.com/telerik/kendo-theme-default/issues/659
