### ISSUE TITLE
Core wrappers generate wrong editor names

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3447]
### Bug report

Reported in ticket ID 1119582
Custom DropDownList Editor in the grid does not bind to the value because the wrapper duplicates the name. If the name is `CategoriesVM`, the resulting name is `CategoriesVM.CategoriesVM`. The same behavior is reproducible with other widgets unless the EditorForModel(m=>m) syntax is used.

```
@(Html.Kendo().ColorPicker().Name("Color"))
```

`
<input id="Color_Color" name="Color.Color" type="color" data-role="colorpicker" style="display: none;" data-bind="value:Color.Color">
`

### Reproduction of the problem

Runnable project in the ticket. 

### Current behavior

Grid Model definition:

```
[UIHint("StateProvinceRegionEditor")]
public StateProvinceRegionViewModel StateProvinceRegionVM { get; set; }
```

Columns.Bound definition:

```
columns.Bound(c => c.StateProvinceRegionVM).Width(250).ClientTemplate("#= StateProvinceRegionVM.Name#").Title("StateProvinceRegion");
```

StateProvinceRegionEditor.cshtml

```
@model BethelMarriage.Models.AdminViewModels.StateProvinceRegionViewModel

@(Html.Kendo().DropDownList()
    .Name("StateProvinceRegionVM")
    .DataValueField("Id") 
    .DataTextField("Name") 
    .DataSource(d => d
        .Read(r => r.Action("GetStateProvinceRegions", "Admin"))
    )
)
```

Generated HTML:

![image](https://user-images.githubusercontent.com/10980842/28571481-c14aa80a-714b-11e7-805c-68ae993699e9.png)

### Expected/desired behavior

The generated `name` and `id` should not be repeated for correct binding to occur. It should be the same HTML as generated by `DropdownListFor(m=>m)`

![image](https://user-images.githubusercontent.com/10980842/28571588-3a87bd5c-714c-11e7-96c7-c191137c8b1e.png)

### Workaround

Remove the Name() and use a `.DropDownListFor(m => m)` definition as below:

```
@model BethelMarriage.Models.AdminViewModels.StateProvinceRegionViewModel

@(Html.Kendo().DropDownListFor(m=>m)
    .DataValueField("Id") 
    .DataTextField("Name") 
    .DataSource(d => d
        .Read(r => r.Action("GetStateProvinceRegions", "Admin"))
    )
)
```
### Environment

* **Kendo UI version:** 2017.2.621

**Comment by Alex-Bubblemaster** [comment]
Also encountered here, raising priority and severity:

[Forum](https://www.telerik.com/forums/help-with-autocomplete-for-incell-editing#p5aJBndBR0yz-BddUXXZSw)

**Comment by ivanchev** [comment]
This is expected and not a bug. Since this is an editor defined for properties of type **StateProvinceRegionViewModel**, it should not specify the name of the property, since it's not constant. You can have two other objects, each with a property of type StateProvinceRegionViewModel with different names, and the editor would work for both of them. 

The proper setting of the Name parameter in this case is Name(""), since we are editing the whole StateProvinceRegionViewModel property, and not a property inside it. 

In any case when working with editor templates, it's always best practice to use the **Kendo'Widget'For** syntax, as it handles all of this behind the scenes for you.
