### ISSUE TITLE
Scheduler's navigate event does not fire when you navigate to a different date with the keyboard

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3452]
### Bug report

With the selectable enabled, if you select a slot and navigate to a different date by pressing Left or Right Arrow the navigate event does not fire. 

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/iZotam) example. 

1. Select a slot.
2. Press Left Arrow (6.5.2013) or Right Arrow (6.7.2013). 

### Current behavior
The navigate event does not fire. 

### Expected/desired behavior
The navigate event fires, like it does when the Previous/Next buttons in the header are clicked.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by atdewitz** [comment]
Should also fire navigate event when switching views within keyboard shortcuts (1, 2, 3, etc.), but does not.

**Comment by Dimitar-Goshev** [comment]
The fix has fixed the scenario described in steps for reproduction. But the following relates scenarios are still not fixed:
- Navigate event is not fired, when changing views with keyboard shortcust (1, 2, 3...)
- Navigate event is not fired, when changing views with keyboad as follows (supported since R3 2017):
  - Go to [Dojo](http://dojo.telerik.com/iTUCu)
  - Reduce the size of the code pane and Run the sample.
  - Click on a time slot.
  - Press F10 to move focus to Today button.
  - Press Tab key 4 times - the focus is moved to the selected view in the views group.
  - Press Right arrow and then press Enter. -> The view is changed, but no navigate event is fired.

**Comment by Dimitar-Goshev** [comment]
The above scenarios are fixed as well.
