### ISSUE TITLE
Broken layout of Spreadsheet exported to PDF, if Fit to page is not checked

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3461]
### Bug report
When scaling is not used on PDF exporting, if the worksheet does not fit in the export size, then the spreadsheet may look broken

### Reproduction of the problem
1. Go to http://demos.telerik.com/kendo-ui/spreadsheet/index
2. Click on Export button and change Save as type to PDF.
3. Uncheck **Fit to page** checkbox
4. Click Save button

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/28715100-2527efea-739f-11e7-951f-e56031b55d65.png)

- Columns in the beginning are trimmed
- Some not styled space after Tax column
- As the first row contains merged cells, that cell is visible in the beginning of the spreadsheet on the second page. NOTE: if **Center Horizontally** checkbox is not checked, this issue will not reproduce.

### Expected/desired behavior
Spreadsheet content is distributed on different pages in the exported PDF and the workbook layout is not broken.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [all]

**Comment by tsvetomir** [comment]
Clipping is expected to occur since the content does not fit on the page. @mishoo can advice on the rest.

**Comment by mishoo** [comment]
I improved it — see [attachment](https://github.com/telerik/kendo-ui-core/files/1187329/Workbook.pdf).

Fixes alignment of the first page (so that the first column shows up), and the glitch on the second page.  The white space on the first page is because of the merged cell (it pushes the guidelines to the end of the page).  I'll try to tinker with the algorithm further but I don't guarantee a good solution for that..

(for reference, [see what LibreOffice](https://github.com/telerik/kendo-ui-core/files/1187360/Workbook.6.pdf) makes of that demo; I'd say not ideal either ;-).

**Comment by tsvetomir** [comment]
Much better, thanks!

**Comment by mishoo** [comment]
I'd say this works good enough now.
