### ISSUE TITLE
Dragged node is duplicated on drop when TreeView dataItem is bound to a ViewModel field

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3514]
### Bug report

When the selected TreeView dataItem is bound to a ViewModel field and a node is being drag & dropped on another position, the node is duplicated.

### Reproduction of the problem

The described behavior can be observed [on the following Dojo](http://dojo.telerik.com/AziCe/11).

Steps to reproduce:

* Expand Locations and select "Location 1"
* Drag the selected node and drop it over "My Ships" folder

[Screencast](https://www.screencast.com/t/S4mQsSX3DgLA)

### Current behavior

Duplicates the dragged node

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [all]

**Comment by BlueCoder77** [comment]
Okay I would also like to report that on top of the drag-drop not working I have also discovered that when I create context-menu's for the different types of nodes to do copy-paste-delete functionality, it does not work with the data-binding as well. I have provided an extended example of the original dojo example as well as steps to reproduce said errors. This example can also be used to reproduce the drag-drop bug that was originally reported, I can provide steps on reproducing that bug in this altered example if y'all need me to. I believe that these 2 bugs are related because when I disconnected the data-binding both this copy-paste-delete bug and the drag-drop went away but then the data-binding wasn't working which isn't good.

Altered Dojo Example with Context-Menu's: http://dojo.telerik.com/AziCe/12

Steps

1. Expand "My Locations"

2. Right Click on "Demo Location"

3. Select context-menu item "New Location"

4. Select the new sub-location that created named "New Location". The item should now be selected in the tree-view, highlighted, and the name should be in the input field below.

5. Right-Click "New Location"

6. Select context-menu item "Copy"

7. Right Click the root element "My Locations"

8. Select context-menu item "Paste"

9. Observe there is now 2 items in the tree named "New Location" and both are selected. The tree is now in an error'd state.

10. Right Click the old root element "New Location", the one that is the child element of "Demo Location" still.

11. Select context-menu item "Delete"

12. Observe how the item was not deleted. The tree is now in an error'd state.

**Comment by BlueCoder77** [comment]
Hi! I need this bug fixed before 10/10/17 to for my own release date. Is that possible?

**Comment by zdravkov** [comment]
We have investigated the issue and it is caused by the fact that when the set function is used (this.set('SelectedLocation', data);) the parent of the data object is set to "this"- whioch is expected. This fact is causing the wrong drag and drop functionality. In such case in order to avoid such behavior we would recommend you to use the approach from this [dojo](http://dojo.telerik.com/@zdravkov/uHAQir).
