### ISSUE TITLE
Spreadsheet does not load data properly when filtered data is loaded with fromJSON method

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3523]
### Bug report
Spreadsheet does not load data properly when filtered data is loaded with fromJSON method.

The JSON is generated by the following [Dojo](https://dojo.telerik.com/OSovo), after applying filter on Column A by unchecking value 11, then pressing ToJSON button.

### Reproduction of the problem
1. Use the following [Dojo](https://dojo.telerik.com/iZiHoy) , which has the JSON from the above Dojo applied.
2. Run the Dojo and expand the Filter menu for column A.

### Current behavior
The A2 value is hidden by the filter, but if the filter is opened, its value 11 appears as checked.
It is not possible to show the data in A2.

### Expected/desired behavior
The A2 value is hidden by the filter. If the filter is opened, its value 11 should NOT be checked.
It should be possible to show the data in A2 by checking value 11 in the filter and apply the filter, or by clearing the filter.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [all]

**Comment by mishoo** [comment]
Note: this isn't about filters, but about hidden rows/columns.  I pushed a fix, but previously, we didn't store sufficient information in the JSON to reconstruct the fact that the filtered row is hidden; you can see in your second dojo that, although row 2 is not displayed because it has `height: 0`, it's not hidden either since we can see 2 in the left-side header showing row numbers.

In order to test the fix you must re-generate the JSON with the latest version.
