### ISSUE TITLE
Spreadsheet custom background color is not applied to cell

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3540]
### Reproduction of the problem
Reproducible in the [demos](http://demos.telerik.com/kendo-ui/spreadsheet/index). 
1. Select an empty cell.
2. Click the Background tool. 
3. Click "Custom color" button.
4. Select a color.
5. Click "Apply". The cell background is set as expected.
6. Select a different empty cell repeat the previous steps except for step 4. Expected: the previously selected custom color is applied, actual: the cell background remains unchanged. 

Workaround:

```html
<script>
  $(document).ready(function() {    
    $(".k-spreadsheet-window .k-primary").click(function() {
      var selectedColor = $(".k-spreadsheet-window .k-selected-color-display .k-color-value").val();
      var spreadsheet = $("#spreadsheet").data("kendoSpreadsheet");
      var sheet = spreadsheet.activeSheet();
      var selection = sheet.selection();

      selection.background(selectedColor);
    });
  });
</script>
```

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by eyupyusein** [comment]
I have gone through this case and it seems to be the default behavior by design. 

If you select a blue cell, the custom color in the dialog will be blue. And if you select a pink cell - it will be pink. Analogously, if you select an empty cell - it will be empty/white/transparent color as the custom selected one.

So the question would be, which behavior do you think I should implement?

**Solution 1:**
Change the custom color button indicator to look transparent to prevent confusion:

![image](https://user-images.githubusercontent.com/11816856/154795956-031e2b04-cfed-4af6-ac4a-e5a79d122d88.png)

**Solution 2:**
Change the logic of the widget to preserve the last selected custom color when an empty cell is selected in the spreadsheet.

![image](https://user-images.githubusercontent.com/11816856/154796341-2fa905e6-a41a-490b-acc1-69edf8a23f5c.png)

**Comment by eyupyusein** [comment]
@IvanDanchev @veselints Can you share opinion on this?

**Comment by sspasova** [comment]
This is the default behavior at the moment. If you like another behavior please use the workaround provided. You can also request a feature in our Feedback portal https://feedback.telerik.com/kendo-jquery-ui.
