### ISSUE TITLE
Unexpected focusing of MultiSelect's first item on dropdown opening, instead of focusing the item selected last

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3569]
### Bug report

**highlightFirst: true** puts the focus on the first item. In the following scenario the first item is not focused (highlighted)
### Reproduction of the problem
[Dojo example](http://dojo.telerik.com/EDIzo).
[Screencast](https://www.screencast.com/t/wZmmrqbcEC). 
1. Open the dropdown and select an item.
2. Type a character in the input for the MultiSelect to filter the items (the first returned item is correctly focused)
~~3. Click outside the MultiSelect. Click the input to open the dropdown (the first item in the list is correctly focused).~~
3. Click outside the MultiSelect. Click the input to open the dropdown (the **first item** in the list is **focused**, which is **not correct**). The expected behavior is that the item, which was selected last, is focused.
4. Repeat 3. 

### Current behavior
The first time - the first listview item is focused, The second time - the last selected item is focused.

### Expected/desired behavior
The last selected items to be focused on opening the dropdown in both cases.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by jivanova** [comment]
After discussion - the first item should not have the focus once the popup is closed. If item is selected and the popup is opened - the last selected item should be focused.

**Comment by Dimitar-Goshev** [comment]
Assessing the issue title and description, it appears that the initial expected result is actually the improper behavior. Point 3 in "Reproduction of the problem" state:
- Click outside the MultiSelect. Click the input to open the dropdown (the first item in the list is correctly focused).
BUT the expected behavior should be:
- Click outside the MultiSelect. Click the input to open the dropdown (the **first item** in the list is **focused**, which is **not correct**). The expected behavior is that the item, which was selected last, is focused.

I will update the issue title according to the fix applied.

**Comment by lapetrei** [comment]
Any fixes for this?
