### ISSUE TITLE
Exporting a Chart using kendo.drawing.drawDOM is causing wrong rendering of the Chart after the export(only in Chrome)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3571]
### Bug report

Exporting a Chart using kendo.drawing.drawDOM is causing wrong rendering of the Chart after the export(only in Chrome). This occurs only when the paper size is not auto and when the Chart is rendered as SVG(Canvas is fine).

### Reproduction of the problem

The issue can be observed in the following Dojo:  http://dojo.telerik.com/aBUpi/6

### Environment

* **Browser:** [Chrome]

**Comment by mishoo** [comment]
I couldn't repro immediately, that is, the chart looked fine immediately after exporting to PDF.  But then I'm not sure what I did (resizing the window seems to trigger it reliably) and I got this rendering:

![chart](https://user-images.githubusercontent.com/334725/31329839-96a519da-ace4-11e7-85c0-81c27080fddd.png)

Is this the same issue you were seeing?

**Comment by simonssspirit** [comment]
@mishoo yes, this is the same issue

**Comment by danielkaradachki** [comment]
Seems that Chrome doesn't update the definition references after a copy of the definitions is appended and removed before the existing element. Not sure if we can do this but inserting the copy after the existing element should fix this since the first element with the definition id will never change.

**Comment by ag-petrov** [comment]
Seems to not reproduce anymore.
