### ISSUE TITLE
Dropdown with tooltip doesn't work as expected

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/kendo-ui-core#3591]
I want to create DropDownList with Tooltip. Tooltip should be displayed only when DropDown has **focus**. 

But when using Tab to move to another control, focus is not lost and tooltip persist. Expected behavior is when focus is lost, tooltips is hidden.

![](https://i.stack.imgur.com/p1eUz.jpg)

```
<input autofocus value='focus me then press TAB' />

<br /><br /><br />
<input id="input1" />

<br /><br /><br />
<input id="input2" />
```

```
$("#input1").kendoDropDownList({});
$("#input2").kendoDropDownList({});

$("#input1").kendoDropDownList({}).data("kendoDropDownList")
  .wrapper
  .kendoTooltip({ content: 'tooltip tooltip tooltip', showOn: 'focus', position: 'right' });  

$("#input2").kendoDropDownList({}).data("kendoDropDownList")
  .wrapper
  .kendoTooltip({ content: 'tooltip tooltip tooltip', showOn: 'focus', position: 'right' });  
```

Live: https://codepen.io/raptor/pen/RLPxZj

**Comment by jivanova** [comment]
In the latest releases, we invested time improving the keyboard navigation of our widgets. I believe the issue is not reproducible with the latest version of Kendo UI - you could test the behavior in this dojo - [http://dojo.telerik.com/@jivanova/IBAZe](http://dojo.telerik.com/@jivanova/IBAZe). 

Feel free to reopen the issue if I have missed something in the scenario.
