### ISSUE TITLE
The Grid resize handlers are not visible after zoom in Chrome (only latest v61.0.3163.100)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3609]
### Bug report

The Grid resize handlers are not visible after zooming in Chrome (only latest version 61.0.3163.100)

### Reproduction of the problem.

The issue can be observed in our demo after zooming: http://demos.telerik.com/kendo-ui/grid/column-resizing

### Environment
* **Browser:** [Chrome v61.0.3163.100]

**Comment by Alex-Bubblemaster** [comment]
Also reported in Ticket ID: 113292. Raising priority.

**Comment by Stamo-Gochev** [comment]
Closed in https://github.com/telerik/kendo-ui-core/issues/3623

**Comment by patrickjlee** [comment]
As mentioned before with regard to another bug, the above isn't very helpful from a customer's point of view because it doesn't say whether the issue has been fixed or not.  (Although I suppose it implies it has by the issue being closed, but much better from this customer's point of view to make it absolutely clear, and to say in which release of kendo ui the fix is.)

**Comment by patrickjlee** [comment]
For anyone else wondering, this seems to have been fixed in kendomvc version 2018.2.620.545, and possibly an earlier version too (but I have only tested it with version 2018.2.620.545).

**Comment by Stamo-Gochev** [comment]
@patrickjlee This issue is similar to the one mentioned in my previous [comment](https://github.com/telerik/kendo-ui-core/issues/3609#issuecomment-335132509). The linked issue has its milestone set to 2017 R3 SP1, which is the first version that includes the fix.
