### ISSUE TITLE
With enabled persistSelection, the selectedKeyNames method return items even if they are removed

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3617]
### Bug report

Removing records from the dataSource with the "**remove**" method or with the "**removeRow**" method of the Grid does not update the private **_selectedIds** collection and the **selectedKeyNames** method returns the deleted records as well.

### Reproduction of the problem
The issue could be observed in the following dojo example:
[https://dojo.telerik.com/OtULa/3](https://dojo.telerik.com/OtULa/3)

### Expected/desired behavior
Remove items should be removed from the _selectedIds collection

### Workaround
Manually removing the value from the _selectedIds:
````
var dataItem = grid.dataSource.data()[0];
delete grid._selectedIds[dataItem.id]
grid.dataSource.remove(dataItem);
````

### Environment

* **Kendo UI version:** 2017.3.913

**Comment by ag-petrov** [comment]
Please note that the valid use case here is to remove the row through the grid api, not through the data source one. If the grid [removeRow](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#methods-removeRow) method is used the respective id should be removed from the internal collection. This is so because the data source is not aware of the grid presence. It can be bound to various widgets and the described issue occurs only in the context of the grid.
