### ISSUE TITLE
Kendo UI AngularJS widgets set inside the ListBox template are not initialized.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3649]
### Bug report

Kendo UI AngularJS widgets set inside the ListBox template are not initialized.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/UFEcid/4

### Environment

* **Browser:** [all]

**Comment by gilm0079** [comment]
Has there been any fixes for this yet?  I'm running into the same issue where angular syntax will not execute inside of a listbox template.  This works fine for a grid control, but this is my first attempt using a listbox and the browser DOM shows un-compiled angular syntax when I inspect.

I suspect since this issue is coming up to 2 years old with no movement I should try to use a work around in the meantime.

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
