### ISSUE TITLE
ComboBox change event fires after filtering and selection of a previously selected item

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3650]
### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/eFOWuk) example. 
1. "Bob" is selected. Focus the ComboBox and delete the last letter ("b").
2. Click on the "Bob" item to select it. 

**Expected:** the change event is not fired
**Actual:** the event fires, but only initially. Subsequent filtering and re-selection of the same item does not fire the event. 

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by jivanova** [comment]
Test in **cascade-event** branch.

**Comment by Dimitar-Goshev** [comment]
After the fix for this issue, the change event is not fired, when filtering is applied and the item is selected with arrows. Reproducible on the staging [Events demo](https://demos.telerik.com/kendo-ui/combobox/events):
1. Click on ComboBox and type i.
2. Press Down arrow.
3. Press Tab or click outside the ComboBox to blur it.

Expected: change event is fired, as on the live demo with 2017.3.1026,
Actual: change event is not fired in this scenario. It is fired, if the item is selected by clicking on it only.
