### ISSUE TITLE
Scheduler workDayStart and workDayEnd is not displayed for the current day

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3663]
### Bug report

The styles applied to the **k-today** class override those of the **k-nonwork-hour** for the td elements of the current day.

### Reproduction of the problem
https://dojo.telerik.com/AlInuZ

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all  ]

**Comment by Dimitar-Goshev** [comment]
Besides Day View, the issue is also reproducible in all views, which show working and non-working hours, such as Week, Work Week, Timeline, Timeline Week, Timeline Work Week, Timeline Month.

In addition to the above, there are several other issues related to specific themes:
- Bootstrap v3 - timeslot lines are not visible, and all hours look one and the same:
![image](https://user-images.githubusercontent.com/6614183/31434694-c223f192-ae85-11e7-93c5-d1e43eeec806.png)

- Material - timeslot lines are barely visible, and all hours look one and the same:
![image](https://user-images.githubusercontent.com/6614183/31434714-d2765558-ae85-11e7-8f2c-f6bb16fb0206.png)

- Material Black - current day slots look one and the same and their color seems incorrect for this theme:
![image](https://user-images.githubusercontent.com/6614183/31434649-9afe289e-ae85-11e7-92f0-5d35d195f7ab.png)

- Fiori, Flat, High Contrast, Metro, Metro Black  - all slots in current day look one and the same
- Nova - no timeslots look like non-working at all, no matter current day or not
- Office 365 - there is no different color for current day, so it is not obvious which is the current day in any view
- Silver - the contrast between working and non-working hours is very small. It is hard to tell which one is which, especially with small screen brightness, or if its very bright in the room, or in case of poor vision:
![image](https://user-images.githubusercontent.com/6614183/31434616-7de5d69e-ae85-11e7-946e-ebc0f15ebd9f.png)

**Comment by mparvanov** [comment]
The issue is still reproducible in week view: http://kendobuild-staging.openstack.progress.com/dojo-staging/iwEVEY

Select Week view and click Today:
![image](https://user-images.githubusercontent.com/7202037/31819191-38cf1e50-b5a4-11e7-98c5-0f0397fea7a5.png)

**Comment by joneff** [comment]
According to the design, the actual should be white: see  `~/UX/KendoUI/Themes/Material`
