### ISSUE TITLE
 cultures / kendo.culture.ar-TN.js

### ISSUE THREAD

**Issue by ram-you** [telerik/kendo-ui-core#37]
The correct months names "Arabic for Tunisia":
     months: {
                    names: ["جانفي","فيفري","مارس","أفريل","ماي","جوان","جويلية","أوت","سبتمبر","أكتوبر","نوفمبر","ديسمبر",""],
                    namesAbbr: ["جانفي","فيفري","مارس","أفريل","ماي","جوان","جويلية","أوت","سبتمبر","أكتوبر","نوفمبر","ديسمبر",""]
                }

**Comment by ram-you** [comment]
Sorry to re-open this Issue, but in the last release, I found a regression.
Thank you.

**Comment by underlog** [comment]
@ggkrustev what's the status here?

**Comment by ggkrustev** [comment]
The fix was postponed in favor of this enhancement:
- https://github.com/telerik/kendo-ui-core/issues/768

Nevertheless, it will be better to fix that on our side for now, until the enhancement is implemented. I will apply the changes for the next official release.

**Comment by matanasov** [comment]
Starting from R3 2017 The Kendo UI culture scripts are generated from the Windows 10 and .NET 4.7 server-side culture definitions and match them by design. To customize the culture in your application, refer to the article on [culture definition](http://docs.telerik.com/kendo-ui/framework/globalization/definecultureinfo).
