### ISSUE TITLE
The last row is not visible when the horizontal scrollbar is shown after column resize.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3709]
### Bug report

The last row is not visible when the horizontal scrollbar is shown after column resize.

The Grid will be correctly resized only if the Grid is scrolled to the bottom.

### Reproduction of the problem

The issue can be observed in the following dojo: https://dojo.telerik.com/OYisU/4

Workaround: https://dojo.telerik.com/OYisU/2

### Environment

* **Browser:** [all]

**Comment by Stamo-Gochev** [comment]
The fix applies to the scenario when changing the column width results in a horizontal scrollbar inside the grid's content. However, cases such as when resizing results in changing the average height of the rows (for example when the column's text is going to be displayed from two to one line) will not be handled as they are limitations. A more suitable example for testing without long text in the columns:

https://dojo.telerik.com/OYisU/5

**Comment by MilenaCh** [comment]
1.Navigate to the example below:
http://kendobuild-staging.openstack.progress.com/dojo-staging/AguLUh
2.Resize a column while a horizontal scroll appears
3.Scroll to the bottom
Result:
The last record is not visible

**Comment by deeksha0112** [comment]
Hi, 
Can I have the solution? I didn't find it.

**Comment by Stamo-Gochev** [comment]
@deeksha0112 The fix is part of the R1 2018 release, but if it is still reproducible on your side, please open a support ticket with a sample code configuration (like https://dojo.telerik.com/OYisU/4), so the case can be further investigated.

**Comment by deeksha0112** [comment]
Hi,
I have some queries..How did you fix that issue? I want to know the implementation/fix. Is it possible to provide me solution. We are using kendo v2018.3.1017. still we are facing this issue in our MVC pages which are using kendo grid. Do we need to upgrade kendo? Please help me out.
Thanks!

**Comment by Stamo-Gochev** [comment]
@deeksha0112 The issue is fixed by manually scrolling the container element of the rows during resizing, so that the last row is visible. You can have a look at the `_scrollWrapperOnColumnResize` method in the `kendo.grid.js` file that is available in the source code from [your account](http://www.telerik.com/account/your-products/product-versions.aspx?version=6d9396c7-ea11-e611-80d2-a0369f015862&product=KENDOUICOMPLETE) as this is [not part](https://github.com/telerik/kendo-ui-core#features-of-kendo-ui-core) of Kendo UI Core and cannot be publicly shared here.

As the issue is working with the 2018.3.1017 version ([example](https://dojo.telerik.com/oNogELiY/2)) out of the box (thus no explicit upgrade is necessary), I suppose that there is a difference between the setup of the Dojo sample and the MVC page you are testing with. That is why it will be very helpful if you open a support ticket regarding the case so that the scenario can be further investigated and we can provide further information.
