### ISSUE TITLE
Special characters in the Editor attribute values should be encoded according to the XHTML specifications

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3743]
### Bug report
The value of Editor widget should present a valid XHTML. Therefore, the values of the elements attributes should use the [predefined entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML) instead of their literal representations. Nevertheless, the widget does not encode those characters.

### Reproduction of the problem
The value() method of the Editor on [the following Dojo](http://dojo.telerik.com/eKuqO/11) will return `*<span data-xhtml-bug="1&1">Test </span>*`, while it should return`*<span data-xhtml-bug="1&amp;1">Test </span>*`

**Comment by AndersMad** [comment]
*FIX:* @line 2615 wrap `value` in `kendo.htmlEncode` -> `result.push(dom.fillAttrs[name] ? name : kendo.htmlEncode(value));`

**Comment by Iankodj** [comment]
@AndersMad, thanks for the suggestion. Kendo Editor, however, already provides a built-in facility to fetch the encoded HTML value. This is done by calling the [encodedValue() method](https://docs.telerik.com/kendo-ui/api/javascript/ui/editor/methods/encodedvalue) instead of value(). Here you are an example: http://dojo.telerik.com/OGaPIsUV. 

Also, on content submission, when in form, the value sent is encoded by default.

With this facilities available HTML content can be treated as XHTML. 

Using the value method, however, should return the correct HTML value. And changing the data attributes' value (or any value) would also impact on logic that depends on the accurate value rather the encoded one. 

On a side note, when it comes to XHTML, data attributes are not allowed. The data attributes are introduced with HTML5 and using them against XHTML validation will mark them as invalid. 

If there are some other concerns regarding attributes' value that I might be missing please post a comment so that we can take them into consideration.

**Comment by AndersMad** [comment]
@Iankodj think you misunderstood that one - it's not about the editor get value - its the processing inside `domToXhtml` - fix here in 2. last line:

```
if (name == 'style') {
    styleAttr(value || node.style.cssText);
} else if (name == 'src' || name == 'href') {
    result.push(kendo.htmlEncode(node.getAttribute(name, 2)));
} else {
	result.push(dom.fillAttrs[name] ? name : kendo.htmlEncode(value));
}
```

The main thing here is not that its XHTML compliant with data attributes (and btw. x = "eXtendable"), the gain is to comply to XML for easy manipulation on the server. Without the fix the source cannot be loaded as XML on server nor client.

Also btw. - the `domToXhtml` does a `value.replace(/^[\r\n\v\f\t ]+/, '')` a few places that removes all white space - the editor(s) don't like that - they often edit the raw HTML code (added monaco editor for that) where they insert spaces/lines and comments - the final version is minified/compress on server.

**Comment by Iankodj** [comment]
@AndersMad, I understand your point of view and I understood where you need the change to be added. 

In general, Kendo Editor is meant to create HTML content, not XML. Therefore, there is no requirement or concept to satisfy XML or XHTML validation. 

The domToXhtml method includes the Xhtml part due to legacy reasons. However, the idea of this method is to produce HTML string from DOM. The style attribute is encoded in order to prevent XSS vulnerabilities. This, however, is not the case with other HTML attributes. 

That said, XML validation should be a matter of additional application logic and not to be built-in in the Kendo Editor.  

If we are to introduce the suggested encoding, this will lead to an major change for the HTML output that is produced in general. This will surely impact on already implemented application logic that relies on attribute values.
