### ISSUE TITLE
TreeView collapse method does not work if called right after calling expand method and vise versa

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3786]
### Bug report - scenario 1

The collapse method does not work as expected if it is called after calling expand and the TreeView's animation is enabled. 

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/Ixeve) example. 
1. Run the example. 
2. **Expected**: the "foo" node should be collapsed. 
3.  **Actual**: the "foo" node remains expanded.

### Bug report - scneario 2

The expandTo method does not work as expected if it is called after calling collapse.

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/eWeXOVIF) example. 
1. Run the example. 
2. Click 'Collapse then expand to node' 
3. **Expected**: The node should collapse and then expand again
4.  **Actual**: The node get collapsed, but does not expand again. 
If setTimeout is used, then the node is expanded correctly (click 'Collapse then expand to node (with delay)'

### Workaround
Wrap the second method in setTimeout function. 
`setTimeout(function(){
    treeView.expandTo(dataItem)
}, 500);`

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by jivanova** [comment]
`Expand` and  `Collapse` methods are executed synchronously. Meaning that the dom manipulation and animation is not awaited when calling `collapse` right after the `expand` method. And thus, it will not be collapsed. 

So, the best approach in this scenario will be the implementation of asynchronous expand and collapse in order to have consistent behavior with either loadOnDemand: true, or loadOnDemand:false. For the above scenarios, I would advice:

1) To wait for the dom manipulation to be completed

[https://dojo.telerik.com/UzaviZic](https://dojo.telerik.com/UzaviZic)

``` javascript
treeview.findByText("foo").promise().then(function () {
    treeview.collapse(treeview.findByText("foo"));
})
treeview.expand(treeview.findByText("foo"));
```

2) In scenario of LoadOnDemand true where the loading of an item must be awaited before next operations - use asynchronous loading and setting of expand:

[https://docs.telerik.com/kendo-ui/controls/navigation/treeview/how-to/nodes/node-async-expand](https://docs.telerik.com/kendo-ui/controls/navigation/treeview/how-to/nodes/node-async-expand)

However, this is not considered a bug and the issue will be marked as **Won't fix**. Feel free to leave your comments and feedback on the matter.
