### ISSUE TITLE
mapValueTo: "dataItem" option does not apply selection to the dropdown list

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3814]
### Bug report

When mapValueTo: "dataItem" option is set, the value is bound in the widget, but the item is not selected in the list when trying to retrieve the dataItems from a page that is different than the first one. 

### Reproduction of the problem

[TelerikMvcAppComboBoxListVirtual.zip](https://github.com/telerik/kendo-ui-core/files/1517646/TelerikMvcAppComboBoxListVirtual.zip)

Steps to reproduce the issue:

* Open the ComboBox and select the last item in the list.
* Submit the form.

### Current behavior

The returned dataItem from the service is not being correctly selected in the dropdown list of the widget.

 [Screencast](https://www.screencast.com/t/uQ1v5G00ID)

### Expected/desired behavior

The result to be the same as if mapValueTo: "index" is used.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by Juveniel** [comment]
#3227

**Comment by Juveniel** [comment]
Also reported in TickerID: 1147303

**Comment by Juveniel** [comment]
Also reported in TicketID: 1147303. The select() method in virtuallist scenario when mapValueTo is set to dataItem does not return the indices of the not loaded items.

**Comment by zdravkov** [comment]
The issue is currently documented as a limitation of the virtualization functionality [here](https://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization#mapping-dataitem-values) yet we have discussed a possible solution for these cases by sending additional array with indexes with the response of the valueMapper function that can be used for such cases.

**Comment by zdravkov** [comment]
We have inspected all the possible solutions for this issue and came to a conclusion that the only correct way to solve the issue is to somehow send the index or some identifier of the item from the server that will be the same as switching the mapValueTo: "index" that is currently the recommended way to solve the issue. That is why we will not proceed with implementing an enhancement that is similar to he current solution.
