### ISSUE TITLE
Customized Editor New-line behavior is reset after using the insertUnorderedList or insertOrderedList tool

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3820]
### Bug report

The Editor's default new-line behavior (which is to insert `<p>` tags on pressing Enter key) can be customized:

```htm
var defaultTools = kendo.ui.Editor.defaultTools;
defaultTools["insertLineBreak"].options.shift = true;
defaultTools["insertParagraph"].options.shift = true;
``` 

so that a `<div>` tag is inserted on pressing Enter. If the insertOrderedList or insertUnorderedList tool is used the customized behavior is overridden and the Editor switches back to its default behavior of inserting `<p>` tags.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/uHiCud) example. [Screencast](https://www.screencast.com/t/ei5cLa3XdG). 

1. Click in the Editor's content area and type in some text, e.g. "abc". 
2. Press Enter key. 
3. Type in text, e.g. "def". Inspect the content. -> the text on every new line is wrapped in a `<div>` element. 
4. Press Enter key, then the insertOrderedList or insertUnorderedList tool. 
5. Enter a couple of list items.
6. Deactivate the insertOrderedList or insertUnorderedList tool.
7. Now every new line will be placed in `<p>` tag. 

### Expected behavior
`<div>` elements should be inserted on pressing Enter key after deactivating the insertOrderedList  or insertUnorderedList tool.

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [Chrome 62]

**Comment by Iankodj** [comment]
The shown option to have `div` elements for new lines is canceling  the original ParagraphCommand of Kendo Editor. It does not somehow change the paragraph tag to something else. Thus, internally, within the ListCommand, there is not accurate way to indicate that the paragraph's tag is changed.

This could be possible by implementing an option to control that and properly implement a logic that would accommodate a change for the tags of the new lines. Such a feature is already suggested and it is recommended for anyone considering using div tags for new lines to vote so that the demand gets increased. http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/18363145-editor-newlinemode-to-div
