### ISSUE TITLE
Fix npm package

### ISSUE THREAD

**Issue by hiyelbaz** [telerik/kendo-ui-core#3837]
### Reproduction of the problem
npm install kendo-ui-core

Front-end world is moving from Bower to npm. However kendo-ui-core npm package is different from Bower version. Please fix the npm package;
i. Support jQuery 3.x on npm
ii. Provide src folder
iii. Provide gulp files (for custom builds)

### Environment
Kendo UI version: 2017.x

**Comment by matanasov** [comment]
@hadjieva @ivanchev 
Could you please share your opinion here?

**Comment by ivanchev** [comment]
While the packages are indeed different, the npm package's purpose is not to mimic the bower one, but rather to provide a coherent kendo npm package. To that end:
- we will update the jQuery reference, since we've fixed the issues we are aware of
- changing the scripts location will break current users. The currently shipped scripts are not in a minified form, which defeats the purpose of a separate src folder
- we decided that the gulp tools for custom builds are out of the scope of the npm package. That's why they can be used though the public repository

**Comment by hiyelbaz** [comment]
Referencing a project with git clone is overkill and hard to maintain. As far as I understand current npm package targets webpack users. When I import a small amount of widgets from npm package, minified file size is about 100kb larger compared to gulp custom build (with same widgets) + minified jquery. A lot of people would prefer smaller js files. So I think you can just add a gulp folder containing gulpfile and src folder without touching any other files and folders. So there would be no impact for current npm users.

**Comment by ivanchev** [comment]
The npm package is indeed intended for use in webpack and other module bundlers, and as such relies on these parties for the bundling and minification of the scripts. It's not intended as a distribution method for source files and build scripts.

**Comment by hiyelbaz** [comment]
Ok, any suggestion to decrease the the bundler overhead?

**Comment by hiyelbaz** [comment]
Problem solved. That was mostly dev environment overhead webpack inserted. I think the issue can be closed if jQuery v3 issue was already on your roadmap.

**Comment by ivanchev** [comment]
The jQuery fix will roll out in the R1 2018 release
