### ISSUE TITLE
The MultiCheckBox values are not updated if the Grid data is changed.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3853]
### Bug report

The MultiCheckBox values are not updated if the Grid data is changed.

### Reproduction of the problem

The issue can be observed at the following Dojo: https://dojo.telerik.com/unEJij

### Environment

* **Kendo UI version:** Introduced in version R2 2017 SP 1
* **Browser:** [all]

**Comment by ag-petrov** [comment]
When using the **data** method of the datasource the datasource contents will be changed. However in order to make things work correctly for the grid one should use the **setDataSource** method of the grid so that other widgets that rely on the data can properly recreate. [Here ](https://dojo.telerik.com/unEJij/4)is a modified dojo that demonstrates this approach.
