### ISSUE TITLE
Text cannot be set to custom button in Spreadsheet toolbar

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3865]
### Resolution
Set showText: "both" to the button settings to display the custom text - [Dojo snippet](https://dojo.telerik.com/iruBeCAF)

~~### Bug report~~

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/IJOKij) example.
1. Run the example.
2. The text of the button tool "Button" is not displayed. 

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by mishoo** [comment]
This appears to be [intentional](https://github.com/telerik/kendo/blob/master/src/kendo.toolbar.js#L278).  By default, `options.showText` is `"overflow"`, which makes the text appear only when the button is in the toolbar overflow menu.  I guess all buttons are expected to have an icon.

A workaround is to pass `showText: true` (funny, `false` works too).  [Demo](https://dojo.telerik.com/AsedUBEx).

**Comment by bruestle** [comment]
The bug still persists in the demo at [https://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet/configuration/toolbar]

**Comment by Dimitar-Goshev** [comment]
@bruestle
I updated the docs example to properly use icon setting, instead of spriteCssClass. And showText may be set to "both" to have text in the visible part of the toolbar and inside its overflow dropdown.
[Dojo snippet](https://dojo.telerik.com/iruBeCAF)

I am closing this issue as it is a configuration problem, not a real bug.
