### ISSUE TITLE
ToolBar duplicates the custom attributes on overflow

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3885]
### Bug report
When using ToolBar with Font Awesome icons, the icons are duplicated in the ToolBar overflow container. The issue occur when the class is set by the attributes configuration option. 

### Reproduction of the problem
1. [Open the linked Dojo](https://dojo.telerik.com/AyaRI).
2. Resize in order the overflow container of the ToolBar to appear.
3. Expand the overflow container. 

### Current behavior
Each icon is showing twice.

### Expected/desired behavior
The icon should not be duplicated.

### Workaround
<style>
    li.fa:before { display: none }
</style>

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
As of R1 2019 the approach for adding FontAwesome icons shown in issue's description does not work.
To add Font Awesome icons, use the approach described in [Use FontAwesome Icons How To article](https://docs.telerik.com/kendo-ui/controls/navigation/toolbar/how-to/use-font-awesome-icons). With this approach the issue is not reproduced:
![Use FontAwesome Icons](https://user-images.githubusercontent.com/6614183/68684405-1893bc80-0571-11ea-9e29-483a550fd313.png)
