### ISSUE TITLE
Select and Unselect option in the dropdown with checkboxes doesnt function.

### ISSUE THREAD

**Issue by vikasmathod** [telerik/kendo-ui-core#3891]
Kendo MultiSelect doesnt work . In the dropdown if we have two or three items with checkboxes, the select and unselect doesnt work.

 Reproduction of the problem
In the previous versions of Kendo UI , extension of kendo.ui.DropDownList used to work seemlessly
{
_select: function (li) { }
}

But inclusion of above code in the release "2017.3.1026" , throws exception.

 Environment:

Kendo UI version: 2017.3.1026.trial
jQuery version:1.9.1.
Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by zdravkov** [comment]
In general overriding of private method as '_select' is not a recommended practice because we don't commit that the internal logic behind these functions won't change. In such case I would recommend researching the change and error and consider another approach for your scenario. You can also consider submitting a support ticket about the issue if you need additional help with it.
