### ISSUE TITLE
When en-US messages script file is loaded, TreeList enables the columnMenu 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3930]
### Bug report

Only when the en-US messages script file is loaded, the TreeList widget will enable the columnMenu, even if it is not set to true. With the Kendo UI TreeList the problem is resolved when you set columnMenu to "false", but with the MVC and Core helpers, the ColumnMenu property is overridden and it could not be disabled.

### Reproduction of the problem
https://dojo.telerik.com/ofurij/4

### Note
The following lines from the kendo.messages.en-US.js file is what seems to be causing the issue:
```
if (kendo.ui.TreeList) {
kendo.ui.TreeList.prototype.options.columnMenu =
$.extend(true, kendo.ui.TreeList.prototype.options.columnMenu, {
    "messages": {
        "columns": "Choose columns",
        "filter": "Apply filter",
        "sortAscending": "Sort (asc)",
        "sortDescending": "Sort (desc)"
    }
});
}
```

### Environment
* **Kendo UI version:** 2018.1.117

**Comment by TsvetinaIvanova** [comment]
Reported in: 1153416

Issue happens with other localization files as well. Reported by customer for `fr-FR` and `en-GB` ones. The ` kendo.ui.TreeList.prototype.options.columnMenu` options are indeed the cause of the issue because they create an object for the columnMenu option, making it enabled by default. This configuration is not needed at all because the TreeList picks up the column menu messages from `kendo.ui.ColumnMenu.prototype.options.messages`.

Work around for MVC TreeList is to reset the  `kendo.ui.TreeList.prototype.options.columnMenu` value before creating the widget.
```
<script>
    if (kendo.ui.TreeList) {
        kendo.ui.TreeList.prototype.options.columnMenu = null;
    }
</script>
```
