### ISSUE TITLE
Selected fontName not displayed in the Editor's fontName dropdown

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3942]
### Bug report

When the fontName is set using the Editor's exec method it is inconsistently displayed in IE compared to Chrome and Firefox. In IE the fontName dropdown does not display any selected value.  

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/ewaTUguL) example. [Screenshot](https://www.screencast.com/t/DwfZa0F0).

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [IE11 ]

**Comment by Namiqismayil** [comment]
Any update on this one?

**Comment by Iankodj** [comment]
The problem here is not with the executing of the command, but the way the fontName is defined. In order to have the Arial selected, the value needs to be the same as the one as if the Arial font is defined in the tool. In this case the value is 'Arial, Helvetica, sans-serif;' and only 'Arial' would not select the proper item in the tool. 

https://dojo.telerik.com/ewaTUguL/7
