### ISSUE TITLE
The internal _pageSize is set to the previews max pageSize after endless scrolling.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#4000]
### Bug report

The internal _pageSize is set to the previews max pageSize after endless scrolling. This is causing a case where if the data is changed, all of the records will be shown even if the endless scrolling is used.

### Reproduction of the problem

The issue can be observed here: https://dojo.telerik.com/aRapO

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by geekdad1** [comment]
That's not quite the problem.  If you take your sample and change the number of records to 10 and 30, the problem is much easer to see.  Bring up the dataset with 30 records.  Scroll to the very end.  Make a note of the name of the last person.  Change to the 10 item dataset.  Change back to the 30 item dataset.  Now try and scroll to the bottom.  You will see that you can only scroll down 20 records and the last name you see is not the last record in the file.  It seems like the end of file setting is not being cleared when you swap between data sets.

**Comment by simonssspirit** [comment]
After additional research, the issue is mainly connected to the combination of the Grouping, Endless scrolling and Locked columns.

**Comment by ag-petrov** [comment]
After further researching the matter it seems that the described behavior is expected. When the [data ](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/methods/data)method of the data source is used the grid and datasource settings are not altered. We strongly recommend in such cases to alter the dataSource through the grid [setDataSource ](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/methods/setdatasource)method. [Here ](https://dojo.telerik.com/ahuXuSEB)is modified dojo which demonstrates a possible implementation and behaves as expected.
