### ISSUE TITLE
Data incorrectly sorted in DataSource with grouping enabled 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4016]
### Bug report

If the data contains more than 10 items they are not sorted correctly (by default they are sorted in ascending order). Reproducible in Chrome.  

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/UhEkit) example.
1. Run the example and check the items collection in the console.
2. It starts with "fff", "aaa", "ccc", etc. 
 
If the eleventh item is removed from the data it is sorted as expected.

### Environment

* **Kendo UI version:** 2018.1.117
* **jQuery version:** x.y
* **Browser:** [Chrome XX]

**Comment by Xizario** [comment]
https://docs.telerik.com/kendo-ui/controls/data-management/grid/how-to/sorting/stable-sort-chrome

**Comment by vdh** [comment]
@xinthose Your example is dependent on `groupable: true`. The `group` event listener is not fired when `groupable: false`, even if the data source is configured with `group`.

**Comment by Xizario** [comment]
@vdh The first example does not have grouping. The second show grouping because it is more complex, and in case you have grouping you would like to stable sort the groups as well.

**Comment by vdh** [comment]
@xinthose When a Data Source is configured with a `group`, and that Data Source is used in a Kendo Grid, and _that_ is configured with `groupable: false` (the default), the Kendo Grid will group those items, but display them out of sequence (2, 3, 1, 4), and I've found no way get Kendo to either respect the original data's sort order, or allow a default sorting (that doesn't involve `sort` configs, because **those** are wiped out whenever the user interacts with the column sorting UI).

That second example is hinged entirely around `groupable: true`, which is not actually a solution to the issue of Kendo Grid sorting items arbitrarily (2, 3, 1, 4).

**Comment by vdh** [comment]
Here is even the original Data Source issue, as implemented using the dojo example from your second example link:

https://dojo.telerik.com/osokUTOq

The ids are shown in original order without a group, but when grouped, are shown in the order: 6, 1, 3, 4, 5, 2, 7, 8, 9, 10, 11

**Comment by Xizario** [comment]
I see your point in here. But it is exactly about why this articles are written.

The sorting in Chrome is [not stable](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability). Meaning when you sort per the group field, the original order is lost. Thus you need to apply sorting by something that describes the original sort. In your case this would be the ID.

There is modified version of the example:
https://dojo.telerik.com/osokUTOq/2

This is happening due to many reasons:
1. It is not an issue with the Grid, since the Grid only displays the data that is passed to it. It does not sort it by any means.
2. The DataSource groups the item by first sorting them, because this is the most efficient way of grouping at O(N*logN) complexity. And all alternatives are times slower.
3. The datasource does not have stable sort implementation by default because it will be slower than the browser's built-in Sort algorithms. Moreover it would require to copy all the data, put some indexes to be used by sorting, because it could not know if you have key that determinate the original sort order.
4. The Chrome is using non-stable sort, because it is faster than Firefox and IE versions. Most probably some hybrid quick sort rather than merge sort.
5. If you do remote binding of your data, the same issue will happen on your data layer, thus it is always safe bet to add additional sort descriptor for your queries (and local operations), rather than expecting some original order to be preserved.

**Comment by vdh** [comment]
@xinthose You're passing the buck, it's not Chrome's fault that the Data Source is bad at implementing a stable sort within its grouping. If you're going to hide a call to `.sort()` inside your grouping functionality with no way to configure that sort, that's on you. I tried to looking for that config, you know. I tried `sort` on the Data Source, but the grouping doesn't use that, it's only sorted *after* the fact, and can be wiped out by a Kendo Grid with `sortable: true` as soon as the user clicks on column headers. I even tried `serverGrouping`, but *that* config subsequently broke client-side sorting and filtering in weird and unepected ways (suddenly the column `filterable` with `multi` doesn't render checkboxes any more…?!?). I've poured so much time and energy trying to find a workaround to this issue.

You admitted there in point 2 that you sacrificed compatability in the name of speed. All you did was hard code a dependency on IE/Firefox-specific behaviour (and Chrome 70 now…).

Instead of pointing fingers at Chrome, you could have just more explicitly admitted the fault / dependency in the Data Source grouping and offered this solution earlier:
```js
dataSource.sort({
  field: '',
  dir: 'asc',
  compare: function(a, b) {
    return a.id - b.id;
  }
});
```
Because, okay, that only works because the example was synchronous. Now how do we implement this fix for an _asynchronous_ Data Source that will be fetching data via AJAX?

**Comment by vdh** [comment]
No wait, I tried `dataSource.sort`, that seems to do the same thing as configuring `sort`… it only works _until_ a connected Kendo Grid messes around with the sort.

I checked the https://dojo.telerik.com/osokUTOq/2 example again, and clicking the `id` header three times (sort asc, sort desc, unsort), returns the Grid/Data Source to the same horrible broken sort  (Chrome Version 69.0.3497.100).

I don't know why someone decided that a Grid connected to a Data Source would mutate the Data Source instead of maintaining its own sort config independently. I guess that means two Grids on the same Data Source will break each other…

**Comment by xinthose** [comment]
> I guess that means two Grids on the same Data Source will break each other…
That is correct.  And I think you mean to mention @Xizario.

**Comment by vdh** [comment]
Oops, sorry about that

**Comment by Xizario** [comment]
@vdh, I don't see any broken or unexpected thing about it. Just tried to explain the behaviour.

[DataSource](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.data.js) is open-source, and the code is in this very same repository. If you still think there is a bug, please feel free to open pull request or give a suggestion what you think it should be changed.
