### ISSUE TITLE
Virtualized Grid sorting breaks after scrolling if the Grid was filtered.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#4053]
### Bug report

Virtualized Grid sorting brakes after scroll if the Grid was filtered. The issue occurs if the inPlaceSort property is used.

### Reproduction of the problem

The issue could be reproduced in the following Dojo: https://dojo.telerik.com/ajoDEZOV

1) Filter by any column.
2) Sort by another column.
3) Start scrolling.

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Xizario** [comment]
Bug indeed, when the `inPlaceSort` is enabled, the sorting should happen [before the filtering](https://github.com/telerik/kendo/blob/83b68123fc1b30dc051fc740a6770a1636304b9c/src/kendo.data.js#L1721-L1742).

**Comment by WAPMak** [comment]
17 days already gone since I've posted that issue, at least three Telerik's people worked with this issue and here is a list of the job that was done for during this period: 

1. One like and one comment had been posted.
2. title has been changed. 

Nice work guys! I'm really appreciate it! Can I finally get an ETA for this issue?

**Comment by boyandim** [comment]
The fix for the problem is currently in testing. As soon as we verify the fix works fine the issue will be closed.
