### ISSUE TITLE
The value in ComboBox is not set correctly with k-ng-model when paging is used

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4056]
### Bug report
When there is paging and the value of the widget is set by using 'k-ng-model', the rendered value of the widget is correct only if it is from the first page data. If the value is from the next pages, then it is not rendered as expected. 

### Reproduction of the problem
1. Open the Dojo - [https://dojo.telerik.com/ebimiHUx](https://dojo.telerik.com/ebimiHUx)

### Current behavior
The ComboBox is epxected to display 'item350' as the text of the item, but it shows '350'. In the same Dojo example, if pageSize is commented, then the value is set correctly. 
In the Dojo example [linked here](http://dojo.telerik.com/OBUcAqAh), the 'k-ng-model' is not used and the value is set correctly. 

### Expected/desired behavior
The ComboBox should display the correct text as it is configured in dataTextField.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all  ]

**Comment by Dimitar-Goshev** [comment]
This issue is caused by misconfiguration. As highlighted in [ComboBox Virtualization help article](https://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization#setting-the-page-size), "enabling paging and setting `pageSize` is efficient only when the virtualization of the ComboBox is configured". The second link in issue's description works, because virtualization is configured.

As a side note, when setting virtualization, it is important to set pageSize based on height and itemHeight formula, as explained in the article. The following Dojo shows the correct setup - https://dojo.telerik.com/@Dimitar-Goshev/OhUPeGiN
