### ISSUE TITLE
MultiSelect with virtualization loses values on filtering

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4088]
### Bug report
The issue occur in MultiSelect with virtualization. When filtering, if there are selected items there is a moment when the values are missing from the MutliSelect input and no loading animation is displayed. 

### Reproduction of the problem
1. Open the Demo [https://demos.telerik.com/kendo-ui/multiselect/virtualization](https://demos.telerik.com/aspnet-core/multiselect/virtualization)
2. Start filtering. You may need to clear the text that you entered. 
screencast - [https://www.screencast.com/t/tEf6eMlWve](https://www.screencast.com/t/tEf6eMlWve)

Steps: 
1.focus Multiselect
2.type 'ab'
3.press fast 'backspace'  two times to delete them

### Current behavior
The selected items and the loader are missing for a moment from the widget. It looks like no items are selected and the widget is not loading anything.

### Expected/desired behavior
The selected values should be displayed all the time. There should be loading animation while the request is still running. 

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all  ]

**Comment by mparvanov** [comment]
The issue is reproducible on the following internal example: http://kendobuild-staging.openstack.progress.com/dojo-staging/aKahUpAq

1. focus Multiselect
2. type 'ab'
3. press fast 'backspace' two times to delete them

Expected: The selected items should be displayed all the time 
Actual: The selected items are missing for a moment from the widget
