### ISSUE TITLE
kendo.parseDate("2/29/2014", "M/d/yy") will incorrectly parse the date even though there is no such date

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#413]
Repro demo: http://dojo.telerik.com/agaNa
Reported in TicketID: 882180

**Comment by mailmrmanoj** [comment]
+1

**Comment by VicTachev** [comment]
The parseDate() method will incrementally match portions of the date strings until a corresponding part in a format is satisfied. DatePickers will use parseDate internally and try to match the date formats specified in _format_ and _parseFormats_ settings. 

In the dojo example the widget will try to match the value to the default format first and will fail because 2013 is not a leap year. However the "20" in 2013 will match the "yy" part in the format string added to parseFormats. Thus, the value will be set to February 29, 2020, since this is a valid date.

The [kendo.parseExactDate() method](https://docs.telerik.com/kendo-ui/api/javascript/kendo/methods/parseexactdate) can be used when it is necessary to exactly match a date format.
