### ISSUE TITLE
Keyboard item navigation does not work correctly when the text option is set

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4140]
### Bug report
If the DropDownList's **text** option is set in the data function the items in the DropDownList (with a popup closed)  are not navigated correctly by pressing Right and Left Arrow keys. 

The items can be navigated correctly if the text option value is set in the markup, e.g.: 

```
:text="'test'"
```

### Reproduction of the problem
[Plunker](https://plnkr.co/edit/yF8m4LDN03z94YYyrN45?p=preview) example. [Screencast](https://www.screencast.com/t/ImfF1dXII).

1. Press Tab to focus the DropDownList.
2. Press Right Arrow key consecutively up until the last item => some items are omitted.
3. Press Left Arrow key to cycle through the items from the last one to the first => some items are omitted.

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by zdravkov** [comment]
The issue is caused by a the fact that the text property of the DropDownList is bound to the same data property that is used for the v-model directive and it is constantly changing. This is causing the unusual behavior. By default the text property is only recommended in cases when autoBind is 'false' to display the text while the data is not available - that is why it is rather recommend to be some static text as in this [plunker](https://plnkr.co/edit/yDyfw5H3T7XXYfyPE6eM?p=preview). In all the other cases the displayed text depends on the selected value without the need to set it manually.
