### ISSUE TITLE
Cannot set the localization for grid filter-menu

### ISSUE THREAD

**Issue by Qlipoth** [telerik/kendo-ui-core#4154]
### Bug report

I have some troubles with toltips in the grid filter menu. They are not localized. http://joxi.ru/Vm6xx88hDoQooA

### Reproduction of the problem
localize grid with the file /node_modules/@progress/kendo-ui/js/messages/kendo.messages.ru-RU.js

### Expected/desired behavior
all tooltips are localized

### Environment

* **Kendo UI version:** 2018.1312
* **jQuery version:** latest
* **Browser:** [all ]

**Comment by boyandim** [comment]
According to [our localization policy](https://docs.telerik.com/kendo-ui/framework/localization/overview#contribution) we rely on contribution from the community to our public repository to update each localization messages. The problem here with the tooltips is rather due to missing localization messages in the kendo.messages.ru-RU.js file. For example the FilterMenu localization should look like: 

`/* FilterMenu messages */

if (kendo.ui.FilterMenu) {
kendo.ui.FilterMenu.prototype.options.messages =
$.extend(true, kendo.ui.FilterMenu.prototype.options.messages,{
  "filter": "фильтровать",
  "and": "И",
  "clear": "очистить",
  "info": "Строки со значениями",
  "title": "Строки со значениями",
  "selectValue": "-выберите-",
  "isFalse": "ложь",
  "isTrue": "истина",
  "or": "или",
  "logic": "Фильтр Логики",
  "cancel": "Отмена",
  "operator": "Оператор",
  "value": "Значение",
  "additionalValue": "Дополнительное Значение",
  "additionalOperator": "Дополнительное Оператор",
});
}`

In the current file are missing the translation strings for "title", "logic", "additionalValue" and "additionalOperator". Once they are added to the localization message file they should appear as expected.
