### ISSUE TITLE
When exporting image to PDF with Drawing API an error occur if the mime type is not set correctly.

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4184]
### Bug report

When the user is trying to export an image with incorrect mime type, an error is thrown. 

### Reproduction of the problem
1. Use the following [Demo](https://demos.telerik.com/kendo-ui/pdf-export/index) and add the attached image to its content. 
[img.zip](https://github.com/telerik/kendo-ui-core/files/1942646/img.zip)
The image is png type.
2. Try to export to PDF.

### Current behavior
There is an error in the browser console: Invalid JPEG image

### Expected/desired behavior
No errors should appear even if a user is trying to export an image where image type does not match the image data. 

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all ]

**Comment by kikhtenko** [comment]
The error is fine. The image is actually png. It has incorrect extension.
The problem is more in error handling. Export stops working in case of this incorrect file.

The reason why this happens is in your kendo.pdf.js. version 2018.1.221. line 1913.

reader.onload = function () {
                        var img = new PDFJpegImage(BinaryStream(new Uint8Array(this.result)));
                        URL.revokeObjectURL(bloburl);
                        cont(IMAGE_CACHE[url] = img);
                    };
 
when this line throws an error (and the fact it does. take a look at PDFJpegImage constructor) cont function is not being called and export just freezes. I guess there should be correct error handling to continue export even if part of DOM is not correct.
