### ISSUE TITLE
Tooltip with filter span/.k-icon not shown for Kendo Button

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4185]
### Bug report
Tooltip is not working when certain filters are applied and 'k-button' class is used.

Regression since: **2018.1.117**

### Reproduction of the problem
1. Open the [Dojo example](https://dojo.telerik.com/ucetisOM)
2. Hover the two icons. 

### Current behavior
Tooltip is showing correctly on the first icon, but it is not displayed on the second one. The only difference between the two elements is the 'k-button' class in the parent.

Behavior with other filters:
*  If the filter is changed to 'a', the Tooltip will be working correctly. 
* If the filter is changed to '.k-icon', the Tooltip will not be displayed.

### Expected/desired behavior
Tooltip should be working with specified class as filter or with 'span' element as filter - [R3 2017 SP2](http://dojo.telerik.com/oMOxoMaK)

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by Juveniel** [comment]
The observed behavior is related to disabling pointer-events for icons and is an intended change. This is required in scenarios where the parent element's event listener is not able to identify if the target is itself or a child element(e.g an icon). Additional information on the topic can be found in[ the following CSS-Tricks Article](https://css-tricks.com/slightly-careful-sub-elements-clickable-things/) and in [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events).

The old behavior could still be achieved through the following CSS:
```css
<style>
  .k-button .k-icon {
    pointer-events: auto;
  }
</style>
```

I am closing this issue due to the above mentioned specifics.
