### ISSUE TITLE
Item not on first page is not selected if paging is used in Autocomplete, ComboBox, DropDownList and MultiSelect

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4194]
### Bug report
If the paging is enabled and the user select an item that is not on the first page, when the dropdown with the items is expanded the item is not selected. 

### Reproduction of the problem
1. Open the [Dojo example](https://dojo.telerik.com/ODiMuGEp)
2. Search for an item (for example type 'fab')
3. Select an item that is not on first page ('Mascarpone Fabioli')
4. Expand the items again

### Current behavior
Item is not selected

### Expected/desired behavior
The last selected item should be marked as selected. 

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all  ]

**Comment by zdravkov** [comment]
Having a pageSize in the dataSource options is only recommended for scenarios with virtualization as in this [demo](https://demos.telerik.com/kendo-ui/dropdownlist/virtualization). In the other cases it is not recommended since the DropDownList widget don't expect pages as the Grid widget for example. 
I am changing this to documentation because it seems it have been often configured  wrongly.
