### ISSUE TITLE
Assembly 'Kendo.Mvc, Version=2018.2.516.545, uses 'System.Web.Mvc, Version=5.2.4.0, which has a higher version than referenced assembly 'System.Web.Mvc, Version=5.2.3.0

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4285]
### Bug report

A server error is thrown initially when running the Visual Studio template projects for ASP.NET MVC due to mismatch of System.Web.Mvc version that Kendo.MVC assembly uses (5.2.4.0) and the project reference (5.2.3.0). 

![image](https://user-images.githubusercontent.com/7202037/40780668-cfbcb9f2-64e1-11e8-9889-cd8ba54d4e8a.png)

### Reproduction of the problem
Create a TelerikMvcApp project from Visual Studio MVC templates
Run the App

### Current behavior
A server error is thrown: 
_Compiler Error Message: CS1705: Assembly 'Kendo.Mvc, Version=2018.2.516.545, Culture=neutral, PublicKeyToken=121fae78165ba3d4' uses 'System.Web.Mvc, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'_

Workaround: 
Navigate to the project installed NuGet packages and update Microsoft.Asp.Net.MVC package to at least version 5.2.4

### Environment
* **Kendo UI version:** 2018.2.516

Related:
https://github.com/telerik/kendo/issues/8572
https://github.com/telerik/kendo-ui-core/issues/4023

**Comment by icnocop** [comment]
In my case, I can't update the Microsoft.Asp.Net.Mvc NuGet package to 5.2.4 - 5.2.6 because the new version breaks other things.

See https://github.com/aspnet/AspNetWebStack/issues/162

**Comment by zdravkov** [comment]
Thank you for reaching out - in such case you will have to use the previous version of Kendo.MVC that refers 5.2.3.0 version of System.Web.Mvc. Meanwhile we will be following the newer versions of the System.Web.Mvc as they are released.

**Comment by mparvanov** [comment]
The following article describes possible solutions to this issue:
https://docs.telerik.com/aspnet-mvc/troubleshoot/troubleshooting#the-systemwebmvc-versions-referenced-in-the-application-and-which-kendomvcdll-uses-differ

**Comment by Dimitar-Goshev** [comment]
For R2 2018 SP1, Kendo.Mvc.dll will reference System.Web.Mvc 5.2.6

**Comment by icnocop** [comment]
@mparvanov , the solutions in the link you provided don't work in my scenario:

1. I can't upgrade ASP.NET MVC because of the "IIS integrated pipeline mode" error in new versions of the Microsoft.AspNet.Mvc NuGet package (5.2.4 - 5.2.6) as previously mentioned, so I'm stuck at 5.2.3.

2. The binding redirect doesn't work if my project references an older version of System.Web.Mvc.dll than Kendo.Mvc.dll:
```
<dependentAssembly>
  <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
  <bindingRedirect oldVersion="0.0.0.0-5.2.6.0" newVersion="5.2.3.0" />
</dependentAssembly>
```
The same type of runtime compilation error occurs.

When referencing Kendo.Mvc.dll R2 2018 SP1, the error message is:
`Kendo.Mvc.DLL: error CS1705: Assembly 'Kendo.Mvc, Version=2018.2.620.545, Culture=neutral, PublicKeyToken=121fae78165ba3d4' uses 'System.Web.Mvc, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`
