### ISSUE TITLE
[Editor]: Text align tool styles the entire Editor content when defaultTools["insertLineBreak"].options.shift = false; (<br/> is used instead of <div>)

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4333]
### Bug report
[Editor]: Text align tool styles the entire Editor content when defaultTools["insertLineBreak"].options.shift = false; (`<br/>` is used instead of `<div>`)

Related to #3420 and #3354

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/eyOKuHEJ/3)
* Type in some characters;
* Press enter to go to the next line;
* Type some more characters;
* Select the second line;
* Click the `Center text` tool;
* Both lines will be aligned in the center;

### Expected/desired behavior
Only the selected line should be aligned in the center.

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all ]

**Comment by Iankodj** [comment]
The text align tool is a format command for block elements (such as div, p, h1 and so on). Therefore, it is expected to influence only block element of the selection (in this case the div element). 

The described behavior is normal and it is the same for all rich text editors (like MS Word), where can be tested with Shift+Enter to create a carriage return instead of paragraph.
