### ISSUE TITLE
Setting an empty filter clears all other filters

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#4351]
### Bug report
Setting an empty filter clears all other filters

### Reproduction of the problem
1. Open the[ Demo ](https://demos.telerik.com/kendo-ui/grid/remote-data-binding)
2. Filter any column
3. Open the filter menu of another column and click the "filter" button without inputting a value

### Current behavior
The grid will now reset, clearing all filters

### Expected/desired behavior
The grid should persist the applied filters

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** [all ]

**Comment by matanasov** [comment]
@gyankov 
After the fix is applied we can end in a situation where visually no filtering is set, but the grid is still filtered:

![filter](https://user-images.githubusercontent.com/5861835/42623441-909801e0-85cb-11e8-9d44-48651a73d109.png)

This is misleading to the user.

In the case above we have `Is equal to` as an operator and we should consider it - either apply it explicitly and return empty collection (which will be similar to `Is Empty\Is Null`) or clear the filter as it was previously.
Another option would be to have the `Filter` button disabled when the filter values are empty and enabled it only when some values as entered.
