### ISSUE TITLE
Unexpected change event triggering when using DropDownTree's value() method or value option

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4352]
### Bug report
The change event of the DropDownTree is called twice when the value() method or value option is used.

### Reproduction of the problem
The issue can be observed on [the following Dojo example](https://dojo.telerik.com/iTUJuseX/2).

### Current behavior
Change event is triggered two times.

### Expected behavior
Change event is NOT triggered by value method or value option, as [its documentation highlights](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/events/change) that "The event is not fired when the value of the widget is changed from code." [Value method documentation](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/methods/value) also highlights that "This method does not trigger change event"

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
After the fix if the value is set to an empty string and then an item is selected from the dropdown, the change event is not triggered. To reproduce it, use the setup of the Dojo from the description with latest scripts. Set value as follows:
```
    var dropdowntree = $("#dropdowntree").data("kendoDropDownTree");
    dropdowntree.value("");
```
Expand the dropdown and select an item.
**Expected:** change is fired.
**Actual:** change is NOT fired.

The issue is also reproducible if an item is selected, then the value is set to an empty string and then an item is selected from the dropdown.

**Comment by Dimitar-Goshev** [comment]
After the latest fix, change event is not triggered on setting initial value in single selection mode. Then change is triggered as expected, when selecting/clearing items.
But in checkboxes scenario, change event is not triggered at all, if initial value is set. Changing checked items does not trigger change...
