### ISSUE TITLE
The Grid with endless scrolling is appending the same data multiple time after read.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#4358]
### Reproduction of the problem

The Grid with endless scrolling is appending the same data multiple time after read requests.

### Current behavior

The issue can be observed here: https://dojo.telerik.com/OZUTIJEz/3

Scroll to request a new page
Click the button to call the read method
Notice how the same page is requested and then appended.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment]
In this scenario(remote binding) when **read()** is called for the datasource the last subset of items should be replaced with the one returned from the call.

**Comment by jagjitraja** [comment]
Issue can still be noticed in ASP Core - 2019R1

**Comment by TsvetinaIvanova** [comment]
A new report with a very similar-sounding issue was made:

For working example, see: [https://dojo.telerik.com/UVIgaRoM/5](https://dojo.telerik.com/UVIgaRoM/5)
**Steps:**

1. Note the total record count of 91.
1. Using Endless scrolling; scroll down the grid records, until page changes from "1 - 20" to "1 - 40"
1. Click the "refresh" icon in the bottom left of the grid.
1. Continue scrolling until page changes from "1 - 40" to "1 - 60"
1. Bug: Notice the Total Count is 2x the Number of Records going from 91 to 182. If there were larger record sets, continuing to scroll and refresh will always add the original record count to the DataSource.

My observation is that the issue is reproducible only with local data operations where the total isn't taken from the remote source.

**Comment by ag-petrov** [comment]
I have carefully examined the cases. It seems that calling read can not manage to resolve all the scenarios correctly. Below I am listing my findings.

Case 1 - The grid is configured for endless scrolling and editing, server paging is not enabled. In such a case if you edit an item initially and not call sync but rather scroll to get the next subset of data the edited item will be marked as dirty in the data source. Calling read will try to reapply the initial data to the datasource. If it succeeds this means that the item in the datasource will not be marked as dirty anymore but since we do not re-render the old part of the table visually it will look as it is edited. The alternative is to either re-render the entire table contents which breaks the concept of endless scrolling or reset the entire grid to it's initial state.

Case 2 - The grid is configured for endless scrolling and editing, server paging is enabled. Calling read will only reaply the new data over the last subset of extracted data from the server. Meaning that we have the same issue as in case one with the exception that the problem only occurs for the last extracted subset of data.

Since there is no adequate solution to all cases this seems like a limitation in the current implementation. The only suggestions which will fit the various requirements are to either manually reapply the previous changes or reset the grid to it's original state. @TsvetinaIvanova can we add a note in the documentation that calling read is not supported in this scenario?

**Comment by ag-petrov** [comment]
Since people may not fall in the case of editing and would like to implement either the full reset approach or the data override one I am providing two possible solutions.

1. Solution in which when read is called the grid is reset to its original state - https://dojo.telerik.com/UVIgaRoM/15

2. Solution which overrides the data  - https://dojo.telerik.com/UVIgaRoM/14

**Comment by jagjitraja** [comment]
Issue is still reproducible in 2019.3.917

**Comment by ag-petrov** [comment]
@jagjitraja the described behavior is expected. A fix was not integrated internally as this is a limitation in the current implementation. Have you integrated one of the suggestions in my post from 9th of May? If so everything should work as expected. If this is not the case I would kindly like to ask you to open a support ticket in our system and share with us the problematic view code so we could examine the case.
