### ISSUE TITLE
TabStrip doesn't switch to scrolling when resized smaller

### ISSUE THREAD

**Issue by tharlinsmith** [telerik/kendo-ui-core#4381]
### Bug report

Tabstrips supply scrolling controls (by default) when the tabstrip is initially rendered in a small enough container to require it.  However, if the container starts large enough to show all the tabs and is resized to be too small the tabstrip wraps instead of going into scroll mode.

### Reproduction of the problem
Open the "edit this example" [dojo](https://dojo.telerik.com/@sspasova/iMAMUlix) from the scrollable tabs page at https://demos.telerik.com/kendo-ui/tabstrip/scrollable-tabs.  Make the window wide and hit "Run".  Shrink the window.

### Current behavior
![screen shot 2018-07-16 at 3 03 39 pm](https://user-images.githubusercontent.com/4153458/42786050-8c8c815c-8909-11e8-8381-78e1a9dee8ac.png)

### Expected/desired behavior
![screen shot 2018-07-16 at 3 04 46 pm](https://user-images.githubusercontent.com/4153458/42786068-9e38ae9e-8909-11e8-8c00-5e32f7521722.png)

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** 3.4.1
* **Browser:** all

**Comment by IvanDanchev** [comment]
The issue is reproducible even without resizing. The container's width must be a little bit bigger than the value needed for the scrolling functionality to be triggered. See this [dojo example](https://dojo.telerik.com/esIcuqIq/5), in which the container's width is set to 220px (scrolling appears if the width is set to 218px).

**Comment by antonmironovv** [comment]
Reported in ticket [#1661228](https://supportheroes.telerik.com/ticket/1661228)
