### ISSUE TITLE
valuePrimitive option does not work for DropDownTree when checkboxes option is enabled

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4386]
### Bug report

[The valuePrimitive option](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/configuration/valueprimitive) does not affect the DropDownList value binding behavior when the checkboxes option is enabled.

### Reproduction of the problem

The issue can be observed on [the following Dojo example](http://dojo.telerik.com/aMEYEJoX/5). Although the valuePrimitive option is set to true, the ViewModel field is not updated with the selected dataItem.

### Current behavior

valuePrimitive option does not change the value binding behavior of the widget.

### Expected/desired behavior

valuePrimitive option should change the value binding behavior of the widget.

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by zdravkov** [comment]
Setting a property of an observable object to an array is automatically transforming it to an observable array and that is why the result of the selectedProduct is always an object. In such case in order to take an array out of it we would rather recommend using  selectedProduct.slice() and set a default value [] as  for exampel it is idone in [this dojo](http://dojo.telerik.com/@zdravkov/oQEzoBUK).
