### ISSUE TITLE
Select and Change events of embedded TreeView are not triggered when clicking on already selected node in DropDownTree

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4475]
### Bug report

https://dojo.telerik.com/@zdravkov/uBUlESUN

### Current behavior
1: Click Furniture - it is selected and the events are triggered
2: Click Furniture again - the events are not triggered

### Expected/desired behavior
1: Click Furniture - it is selected and the events are triggered
2: Click Furniture again - the events should be triggered

### Environment

* **Kendo UI version:** 2018.2.620

**Comment by Dimitar-Goshev** [comment]
The described issue, which is reported in the following [forum thread](https://www.telerik.com/forums/embedded-treeview-events-not-work-when-clicked-on-text-part) about the embedded TreeView, is not a bug. It is the expected behavior of TreeView's [select](https://docs.telerik.com/kendo-ui/api/javascript/ui/treeview/events/select) and [change](https://docs.telerik.com/kendo-ui/api/javascript/ui/treeview/events/change) events, as they are triggered when the **selected** TreeView node has changed - select is triggered only by user interaction, while change is can also be triggered on selecting programmatically. In the scenario discussed in the issue, the **selected node remains one and the same** - Furniture. When it is clicked the first time, it becomes selected. When clicked again, the node remains selected, thus there is no changed selection and the two events are not triggered. The same scenario may be tested on TreeView [Events demo](https://demos.telerik.com/kendo-ui/treeview/events) for reference.

As a side note on the TreeView [check](https://docs.telerik.com/kendo-ui/api/javascript/ui/treeview/events/check) event, which is mentioned in the forum thread, this event is triggered by user interaction only. In the above scenario checking and unchecking the node is done internally by the DropDownTree, so TreeView check event is not triggered and this is expected.
