### ISSUE TITLE
Scheduler Agenda view columns do not resize consistently

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4476]
### Bug report
In most of the themes the Agenda view all 3 columns remain visible when the window is very narrow ([screenshot](https://www.screencast.com/t/N87enZXlykS)), however with Default v2, Bootstrap v4 and Fiori the third column (Event) is hidden ([screenshot](https://www.screencast.com/t/FswyMdYjlk4)).

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/scheduler/index
1. Switch to Agenda View
1. Resize browser window to force column resizing.

### Current behavior
Inconsistent columns resizing behavior across different themes. Event column is hidden in SASS themes and in LESS Fiori - [screenshot](https://www.screencast.com/t/FswyMdYjlk4).

### Expected/desired behavior
Consistent resizing behavior. Event column is visible in all themes - ([screenshot](https://www.screencast.com/t/N87enZXlykS))

### Environment
* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by michael-hauser** [comment]
This is currently a problem for us (with Default v2). In which release will this be fixed? Or is there a workaround?

**Comment by Dimitar-Goshev** [comment]
@michael-hauser The issue is still reproducible and currently there is no known workaround for it.
I would suggest you to use Scheduler's Adaptive rendering, which uses the first column as a row - [DOJO](https://dojo.telerik.com/@Dimitar-Goshev/IKEHApEd), thus providing more space for the other 2 columns.
![image](https://user-images.githubusercontent.com/6614183/64177548-63ee6800-ce68-11e9-8544-03d6e615c705.png)


Setting the **mobile** property to **true** automatically uses mobile render mode on mobile devices and desktop on desktop browsers.

**Comment by magdalenaan** [comment]
The issue is actually a limitation related to Kendo UI for jQuery rendering. For small devices, we recommend using [Scheduler adaptive rendering](https://demos.telerik.com/kendo-ui/scheduler/adaptive-rendering).
