### ISSUE TITLE
Cannot disable the animation for TabStrip TagHelper 

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4491]
### Bug report

The 
```javascript
 <kendo-tabstrip name="tabstrip" >
   <popup-animation enabled="false"></popup-animation>            
   <items>
....
   </items>
</kendo-tabstrip>
```
Does not disable the animation.

Issue caused by https://github.com/telerik/kendo/issues/8330
* **Browser:** [all]]

**Comment by ag-petrov** [comment]
The generation is now fixed. However the documentation seems to be a bit confusing. For some of the controls which properties can be boolean or object such as animations we state that setting **animation: true** is not valid. I suppose that this is due to the JavaScript code handling the options. Since the generation uses the default values it would be best to revise this code and modify it so that setting the options to true(which is the default case) is possible. Moreover some of the composite options are excluded from generation. We can now include them and benefit from it.

@nenchef I have contacted @jivanova in regards of this and probably it would be best to revise this and include additional commits in the branch that I have created to reference the problems.
