### ISSUE TITLE
Grid ColumnMenu sometimes displays filter or column menu (with broken position) when opened

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#4506]
### Reproduction of the problem
In the following dojo, open the column menu for the first column and click on "Sort ascending" few times. In most cases the column menu (or the filter menu) will be displayed and overlap the columnMenu initially:
https://dojo.telerik.com/EBULAFOd/5

![c43018f2-8caf-440a-8550-6d1c3806516b_sorting-bug](https://user-images.githubusercontent.com/11787141/45611259-7ad55800-ba67-11e8-83d6-2e0949014a9c.jpg)

### Environment

* **Kendo UI version:** 2018.3.911

**Comment by TeyaVes** [comment]
The issue is in the popup, not the grid. It can also be reproduced in the following Dojo: https://dojo.telerik.com/uWEbOmoL 

![popup-bug](https://user-images.githubusercontent.com/45764088/51911833-7472c780-23db-11e9-9b06-1170d841acf6.png)

**Steps for reproduction:**
1. Hover Women's menu item 
2. Click on Accessories
3. Repeat a couple of times if needed

**Reason:**
Once the menu closes and toggles up, there is a mouse enter event in the rest of the rows that opens the right child menu of the submenu (which in fact is a popup). Afterward, there is a mouse leave event, which is supposed to close the popup if it is visible, but since the parent menu is already closed, the check returns false (although the popup has display: block) and the child popup stays open. Once the submenu is opened again, the child's popup overlaps the submenu. 

**Possible solution:**
Turn off mouse enter and mouse leave events while the menu toggling animation is in progress.

**Comment by Dimitar-Goshev** [comment]
@TeyaVes The issue is reproducible in Grid's ColumnMenu and in the standalone Menu. The issue is fixed for the standalone Menu for R2 2019 SP1, but it is still not fixed for Grid's ColumnMenu.
