### ISSUE TITLE
columns.headerAttributes is ignored when using multi column headers

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4546]
### Reproduction of the problem
Run [this dojo](https://dojo.telerik.com/OWoGiloN/4)

### Current behavior
The headerAttributes are not present in the _th_ elements

### Expected/desired behavior
The specified headerAttributes should be used

### Environment

* **Kendo UI version:** 2018.3.911

**Comment by matanasov** [comment]
@ag-petrov 
Before the fix the `<th>` elements in the DoJo example look like this:
```
<th class="k-header k-with-icon"></th>
```

After the fix the `<th>` elements in the DoJo example look like this:
```
<th class="tst k-with-icon" style="text-align: center;"></th>
```

Note that `k-header` class is missing, but the `k-with-icon` class is preserved. Can you confirm this is the expected behavior because the headers UI considerably changes:

![headers](https://user-images.githubusercontent.com/5861835/46341383-9a13de00-c640-11e8-9d91-27eb14111933.png)
