### ISSUE TITLE
spreadsheet cannot export PDF files containing Chinese character

### ISSUE THREAD

**Issue by somsne** [telerik/kendo-ui-core#4579]
### Current behavior
When user exported PDF file containing chinese character,the PDF files can only display English characters correctly.The Chinese characters are displayed as gibberish.

### Expected/desired behavior
Spreadsheet can import custom font files.The exported PDF file can correctly embed these font files. Then Chinese characters will display currently.

### Environment
- Kendo UI version: 2018.3.1003
- Browser: [all]

**Comment by mishoo** [comment]
This is because the drawing API [cannot do font substitution](https://docs.telerik.com/kendo-ui/framework/drawing/pdf-output#configuration-Unicode).  In order to render to PDF a spreadsheet containing both English and Chinese characters, the cells must use a font that contains glyphs for all the necessary characters, and of course, the font must be available on the server and properly [declared in CSS](https://docs.telerik.com/kendo-ui/framework/drawing/drawing-dom#configuration-Custom), or [embedded](https://docs.telerik.com/kendo-ui/framework/drawing/how-to/pack-fonts-for-export) via our [font packing utility](https://github.com/telerik/kendo-pack-fonts).

**Comment by somsne** [comment]
I had resolved this problem by using 'kendo.pdf.defineFont()'
Thank you very much!
