### ISSUE TITLE
PDF export using Kendo UI v2016.3.1118  not showing degree symbol in IE Edge

### ISSUE THREAD

**Issue by jeff-mccommas** [telerik/kendo-ui-core#4618]
### Bug report

When tried with latest kendu-ui then export is showing degree symbol, but migrating app to latest kendu-ui will require lots of changes. Is it possible to release a patch fix for Kendo UI v2016.3.1118 .

### Current behavior
On doing export from IE Edge degree symbol is not show. It works for chrome though.

### Expected/desired behavior
It should show degree symbol in pdf generated

### Environment

* **Kendo UI version:** 2016.3.1118 
* **jQuery version:** 3.3.1
* **Browser:**IE EDGE Latest

**Comment by matanasov** [comment]
@jeff-mccommas 
We don't have practice to fix already released versions. The version you use is almost 2 years old and applying a patch to it is not possible because of the tons of changes applied afterwards. Based on that you can:
1. Try to find the version where this issue is fixed. You can use our online DoJo service. Currently the last version it keeps is R2 2016. Once you find the "fixed" version, you can reconsider migrating to it.
2. Migrate to the latest version - although this may take some time, it is the recommended option and considered good practice because you will get all the fixes and improvements that were implemented after 2016 R3 was released.
