### ISSUE TITLE
Creating a custom tool based on "formatting" overrides the values of the original

### ISSUE THREAD

**Issue by eSPiYa** [telerik/kendo-ui-core#4643]
I'm trying to make a separate dropdown tool for the line-spacing in the Editor using this [tutorial](https://demos.telerik.com/kendo-ui/editor/styles)

It is kind of working, but it overrides the values of the original "formatting" tool. Or should I make a separate tool by extending this "formatting" tool? It is kind of silly but the user might want to apply double spacing on "heading 1".

**Comment by zdravkov** [comment]
In such case a custom template should be used as for example in this [demo](https://demos.telerik.com/kendo-ui/editor/custom-tools). 

If you have further questions I would recommend you to submit a support ticket or a forum thread because this repository is recommended for bug reports rather than custom scenarios.
