### ISSUE TITLE
Loading panel flickers when collapsing large groups

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#4651]
### Bug report

When having a grid with endless scrolling and large groups, if a group gets collapsed flickering occurs. 

### Reproduction of the problem

1. Run - https://dojo.telerik.com/AgAJIsAG
2. Group by "Country"
3. Click on the arrow to collapse the group
4. After a couple seconds, the loading icon and the grid starts to "flicker"

More information in ticket - 1349780

**Comment by eyupyusein** [comment]
The problem is related to Endless Scrolling. Here is what happens:

1. The grid has many records.
2. The user collapses a group which has 5000 items.
3. The grid assigns a non-transparent overlay to show a progress indicator.
4. The endless scroll automatically gets all grid records set by set. 
5. The grid internally has a timeout for this overlay: after loading a new portion of data finishes - the overlay is hidden in 100 milliseconds. In this scenario with many records, this time delay is not enough to overcome the overlapping mismatch. Therefore, I have increased it to 250 to fix the issue.
