### ISSUE TITLE
Adding item throws exception in TreeList with Paging enabled

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4680]
Reported in [ticket 1361772](https://admin.telerik.com/?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1361772)

When paging is enabled pressing the Add new record button will result in stack overflow exception. Runnable project available in the ticket.

### Environment

* **Kendo UI version:** 2018.3.1017

**Comment by Stamo-Gochev** [comment]
Cannot reproduce it with the latest version in master.

**Comment by Stamo-Gochev** [comment]
The reported problem has been fixed in a previous version. In addition, using the client-side paging (as server paging is not supported) with the attached project from the ticket (where the "id" field is nullable) requires setting a default value for the newly created items:
```
@(Html.Kendo().TreeList<Prueba_Concepto.Models.TablaModelTree>()
    .Name("treelist")
    ...
    .DataSource(dataSource => dataSource
        ...
        .ServerOperation(false)
        .Model(m =>
        {
            m.Field(f => f.id).DefaultValue(0);
            m.Id(f => f.id);
            m.ParentId(f => f.parentid);
            m.Expanded(true);
            m.Field(f => f.tResumido);
        })
    )
    .Height(540)
    .Pageable(p => p.PageSize(15)
                    .PageSizes(true)
    )
)
```
Otherwise, a circular dependency is created as the newly added item has `id: null`, but all root items (with `parentId === null`) will consider this added item as their parent, which is not correct
