### ISSUE TITLE
Spreadsheet does not properly display font color applied to cells in the .xlsx file

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4681]
### Bug report
Opening an Excel file, which contains cells with font color set, from the Spreadsheet's toolbar displays the respective cells content with no font color applied. 
If the same file is imported using server import, font color is applied as expected. 

### Reproduction of the problem
Open the attached file in the Spreadsheet.

[Public item](https://feedback.telerik.com/kendo-jquery-ui/1361892-cell-fore-color-is-not-picking-up-from-excel-sheet).

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** x.y
* **Browser:** [all] 

Attached file:
[TestFontColor.xlsx](https://github.com/telerik/kendo-ui-core/files/2607683/TestFontColor.xlsx)

**Comment by Dimitar-Goshev** [comment]
The fix for the gray background re-introduces another bug, whose fixing resulted in the gray background bug... The following [differentGrayBackgrounds.xlsx test file](https://github.com/telerik/kendo-ui-core/files/2663550/differentGrayBackgrounds.xlsx), which use the first three background color columns shows the issue:
![image](https://user-images.githubusercontent.com/6614183/49740291-8fa73d80-fc9c-11e8-8a6a-49dd4229aa44.png)

Before the fix, gray looking background based on white, would be imported as black background:
![image](https://user-images.githubusercontent.com/6614183/49740159-4eaf2900-fc9c-11e8-8b86-8a300981975a.png)

After the fix, gray looking background based on black, would be imported as white background:
![image](https://user-images.githubusercontent.com/6614183/49740002-eb24fb80-fc9b-11e8-8347-5124f10368c3.png)

**Comment by Dimitar-Goshev** [comment]
The issue I mentioned in my previous comment is now fixed as well and gray background is exported as expected:
![image](https://user-images.githubusercontent.com/6614183/49790341-9edac980-fd36-11e8-87db-295f63998e20.png)
