### ISSUE TITLE
Incorrect rounding when value exceeds formatting  

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4700]
### Bug report

Having a formatting to limit up to 2 decimal points will not round the based on third one. 

Regression from 2018.3.911.

### Reproduction of the problem
https://dojo.telerik.com/ovUvoPEK

### Current behavior
With formatting #,##0.00 and value is 4.009 the formatted number is 4.00.

### Expected/desired behavior
The formatted number to be 4.01.

https://dojo.telerik.com/ocedUWEJ

### Environment

* **Kendo UI version:** 2018.3.1017

**Comment by Iankodj** [comment]
Related to: 
https://github.com/telerik/kendo-ui-core/issues/3520

https://github.com/telerik/kendo-ui-core/issues/4655

**Comment by Dimitar-Goshev** [comment]
The fix causes an error on opening the file attached to the first reply in ticket ID 1348633:
1. Download the file. Open it in Excel, clear its formats so that only content is left and save the file.
1. Open the in Spreadsheet ("Open..." toolbar button)
**RangeError: Maximum call stack size exceeded**
