### ISSUE TITLE
Grid autoFitColumn does not work as expected with sorting

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-ui-core#4716]
Can be reproduced in [this Dojo](https://dojo.telerik.com/@martinpz/UKeVAQIT/5)

1. Sort any of the columns `Ascending` - the sorting icon is not visible and part of the header is cut

Logged in the [feedback portal](https://feedback.telerik.com/kendo-jquery-ui/1365123-autofit-column-does-not-calculate-properly)

**Comment by ag-petrov** [comment]
This is not a bug and is caused by the current life cycle. Now when the grid initializes it first initializes its datasource and attaches a change handler to it. After that it initializes the header and a **columnsorter** widgets to the **th** elements. This widget actually renders the sort indicators and also listens to the change event of the datasource to do so. Since the column sorter change handler is attached second, when sorting is applied the change of the grid data source is first triggered, resulting in the triggering of the dataBound event. At that time the sort indicator is not present and the column width will not be calculated correctly. 

In order to resolve this one can use a slight timeout. [Here ](https://dojo.telerik.com/@martinpz/UKeVAQIT/5)is a modified dojo.

**Comment by randyburden** [comment]
Thanks @ag-petrov for the tip. This was my solution based on your tip:

```js
function onDataBound(e) {
  var grid = this;
  setTimeout(function() {
  	// Auto-fit all columns
  	for (var i = 0; i < grid.columns.length; i++) {
  		grid.autoFitColumn(i);
  	}
  });
}
```
