### ISSUE TITLE
Kendo Core drag and drop (resizing table generate a lot of  new classes )

### ISSUE THREAD

**Issue by ahmadtalal14** [telerik/kendo-ui-core#4748]
Resizing generate a lot of newer classes which ultimately slows down the performance. 
![capture1](https://user-images.githubusercontent.com/46487772/50833066-e6726680-1371-11e9-86ef-f64b073f104a.PNG)
![capture2](https://user-images.githubusercontent.com/46487772/50833067-e6726680-1371-11e9-9ac5-97c94f758005.PNG)

**Comment by mparvanov** [comment]
The k-table-resize-handle-wrapper is the class initially applied to the 8 resize handles (n, s, e, w, se, sw, ne, nw) of the table by design. This could be observed on the following online demo:
https://demos.telerik.com/kendo-ui/editor/index . 
The handles should only appear when the cursor is inside the table and should be cleared when the table is unselected.
If this is not the case and the classes are not cleared, could you provide us with the exact steps to reproduce the problem with resizing table generating new classes ?
