### ISSUE TITLE
Incomplete GanttView TypeScript definitions

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#4782]
### Bug report
[TypeScript definitions] .d.ts typings make it hard to implement custom GanttView without hacks
Gantt control configuration (`kendo.ui.GanttOptions`) use `kendo.ui.GanttView` name for view options (`GanttOptions.views`).
Actually `kendo.ui.GanttView` is a name of existing GanttView class (not defined in d.ts), which makes it hard to implement custom GanttView without `any` cast hacks.

### Expected/desired behavior
- Gantt view options interface should use name, not used by any kendo classes, e.g. GanttViewOptions
- GanttViewOptions should have `title` property defined in d.ts
- GanttView class should be added to d.ts

### Environment
* **Kendo UI version:** 2019.1.115

**Comment by Iankodj** [comment]
In order to implement custom GanttView, you should rather use the GanttView class to extend your own interface so  that you can have the requirments about the title or any other option. The kendo.ui.GanttView interface is kept as generic as possible exactly to provide more flexibility for customization. 

```ts
interface MyGanttView extends kendo.ui.GanttView {
	title: string
}

var elm = document.createElement("div");
elm.id = "gantt";
var technologies = document.body.appendChild(elm);

var myGanttView = <MyGanttView>{
	title: "My Gantt View"
};

var gantt = <kendo.ui.Gantt>$(technologies).kendoGantt({
	views: [ myGanttView ]
}).data("kendoGantt");
```
