### ISSUE TITLE
Clicking on Scheduler Calendar, when the page has been scrolled down, scrolls to top and immediately closes the Calendar

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4802]
### Bug report
Clicking on Scheduler Calendar, when the page has been scrolled down will force the scroll to top and will flicker the Calendar.

**This is a regression introduced with R3 2017.3.913**

### Reproduction of the problem
* Run [the following Dojo](https://dojo.telerik.com/aMeBApew);
* Make the browser window so small, so it displays scroll for the page;
* Scroll down the page up to showing the Scheduler header at the top of the window
* Click on the Scheduler Calendar icon - the page will scroll up and the Calendar will display just for a moment;

### Expected/desired behavior
The page should not scroll up and the Calendar should be properly displayed - [2017.2.621 Dojo](https://dojo.telerik.com/iMUDuMIj)

### Environment
* **Kendo UI version:** 2019.1.115
* **Browser:** all

**Comment by zdravkov** [comment]
introduced in this commit - https://github.com/telerik/kendo/issues/7400

**Comment by Dimitar-Goshev** [comment]
After the fix, the Calendar is not focused on expanding it. Thus, it is not possible to select a date through it using keyboard. Expected behavior can be reproduced on https://demos.telerik.com/kendo-ui/scheduler/selection :
Case 1
1. Click on Calendar icon
1. Press Arrow Down
**Expected:** 20th of June 2013 is focused
**Actual on staging:** page is scrolled

Case 2
1. Click on Scheduler timeslot
1. Press F10 to focus Today button.
1. Press Tab 3 times to focus the Calendar
1. Press Enter/Space - Calendar is expanded
1. Press Down Arrow
**Expected:** the date below the currently selected one is focused
**Actual on staging:** the timeslot below the currently selected one gets selected
