### ISSUE TITLE
Unexpected styles applied to copied text with no styles, when pasted in Editor in Edge 41+

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4805]
### Bug report
Unexpected styles applied to copied text with no styles, when pasted in Editor in Edge 41+.
Reported in ticket 1385267.

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/editor/all-tools in Edge 41+
1. Delete all Editor content and type Test
1. Click on View HTML tool - the tool shows only [text Test](https://www.screencast.com/t/ZiTtQct9o) is entered
1. Select Test and copy it with Ctrl + C or through browser's context menu
1. Click after Test and paste copied content with Ctrl + P or through browser's context menu

### Current behavior
Font-name and font-size picker tools' value is changed and View HTML shows styles applied  - [screenshot](https://www.screencast.com/t/aOlK7zjw3)
Reproducible with Edge 41+ - [screencast](https://www.screencast.com/t/48nAx7nQOnC)

### Expected/desired behavior
Font-name and font-size picker tools' value remains (inherited font) and (inherited size). No styles are applied on paste. Reproducible with Edge 38, Edge 40 - [screencast](https://www.screencast.com/t/z7wVbncn6fP)

### Workaround
The issue is not reproducible when [pasteCleanup.css](https://docs.telerik.com/kendo-ui/api/javascript/ui/editor/configuration/pastecleanup#pastecleanupcss) and [pasteCleanup.span](https://docs.telerik.com/kendo-ui/api/javascript/ui/editor/configuration/pastecleanup#pastecleanupspan) options are set to **true** - this may be tested on [Paste Cleanup Editor demo](https://demos.telerik.com/kendo-ui/editor/paste-cleanup) by checking the **CSS** and **span** checkboxes and repeating the reproduction steps above.

### Environment
* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [Edge 41, Edge 42, Edge 44]

**Comment by Iankodj** [comment]
This is a bug related to the browser and cannot be fixed from the Editor. The bug is also reported here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18190152/. 

These styles are added to the copied text by the browser using its computed styles for some reason. Then, pasting this content back to the content area shows them as inline styles. The Kendo Editor has no mechanism to somehow tell whether those styles are browser generate or the user has chosen to paste with this inline decoration. Thus, it cannot be removed succefully without harming stylization that the user would actually need to paste. 

The workaround suggested is a feasible option and it can be used as a solution when no stylization needs to be pasted.
