### ISSUE TITLE
Date format in the sv-FI culture differ from the fi-FI culture

### ISSUE THREAD

**Issue by natalieconsilia** [telerik/kendo-ui-core#4806]
### Bug report
Date format in sv-FI culture differ from the fi-FI culture.

### Current behavior
The sv-FI culture have multiple date patterns like this: "dd-MM-yyyy".

### Expected/desired behavior
We speak Swedish but live in Finland so we expect the date patterns to be the same as the fi-FI culture: "d.M.yyyy".

### Environment

* **Kendo UI version:** 2018.3.911 and 2019.1.115

**Comment by natalieconsilia** [comment]
sv-FI had the correct date format "d.M.yyyy" in version 2017.2.504

**Comment by matanasov** [comment]
@natalieconsilia 
Starting from R3 2017 (2017.3.1026) the Kendo UI culture scripts are generated from the Windows 10 and .NET 4.7 server-side culture definitions and match them by design. To customize the culture in your application, refer to the article on [culture definition](https://docs.telerik.com/kendo-ui/framework/globalization/definecultureinfo#customization)

More information about Kendo globalization is available [here](https://docs.telerik.com/kendo-ui/framework/globalization/overview)
