### ISSUE TITLE
Table filters elements lose focus in High Contrast

### ISSUE THREAD

**Issue by sryeluri** [telerik/kendo-ui-core#4857]
OS: Windows 1809

Browser: Chrome 70.0.3538.77
Assistive Technology: High Contrast
Steps:
1. Navigate to Application 
2. Press tab until focus is given to the table.
3. Navigate to any filter 
4. Enable High Contrast mode
5. Observe focus indicator.

Actual Results: 
Filter elements do not receive focus in High Contrast

Expected Results:
Focus indicator should not be lost in high contrast

**Comment by matanasov** [comment]
The reported Kendo version (2015.2.805) is quite old. Many accessibility improvements were implemented in later versions and I would suggest that you re-verify the problem with latest version (2019.1.220).

**Comment by kraay** [comment]
@matanasov Thanks for the suggestion. Are there any known accessibility issues with the latest version? We want to make sure that the changes are backward compatible and upgrading will not create new accessibility issues.

**Comment by MilenaCh** [comment]
Currently, we are not aware of regression accessibility issues. However, you can check our [public repo](https://github.com/telerik/kendo-ui-core/issues) for other known accessibility issues and enhancements.

Could you please clarify which element could not be focused? In case, you are facing Filter icon(.k-grid-filter), then this is the expected behavior of the component. It is not needed to focus the element with tab key, because the user can open filter menu using the built-in keyboard [navigation](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/navigatable). You should focus the corresponding header cell and press 'Alt' + 'Arrow Down Key', then the filter menu will be properly displayed. Another option would be to enable [row filtarable mode](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/filterable.mode) and filter icon will be focusable even with tab key. 
General speaking, it is always recommended to use the built-in keyboard navigation of Grid's component instead of navigation with tab key, because the built-in navigation is especially developed to cover different scenarios in Grid, while with Tab key you are able to navigate to limited elements of the Grid.

**Comment by kraay** [comment]
@matanasov @MilenaCh Here's the new sample application with the latest Kendo version and navigatable set to true - https://runner.telerik.io/fullscreen/etUFekow (Code - https://dojo.telerik.com/etUFekow)
When high contrast is disabled, we can see the focus indicator on the cell 'Nancy'. However, when high contrast in enabled, the focus indicator is missing. With the new version, the sprite icon is now visible, but the focus indicator on 'Nancy' still cannot be seen. It doesn't appear even on clicking on the cell.
Kindly check and reopen this bug.

Without High Contrast -
![image](https://user-images.githubusercontent.com/10906811/56357029-1a261d80-61f8-11e9-80e3-ca2db1a09de9.png)

With high contrast - 
![image](https://user-images.githubusercontent.com/10906811/56357136-67a28a80-61f8-11e9-9ee8-84849be744ad.png)

As mentioned before, we are using IE 11 to test for high contrast bugs and are enabling high contrast using the Windows settings.

**Comment by MilenaCh** [comment]
High Contrast windows mode actually adds a lot of  custom styles, so I suppose Microsoft team will be able to provide a better explaination why focus style is not properly indicated in this scenario. Generally speaking KendoUI also provides High Contrast theme, which could be applied the application for accessibility purpuses. You can see how the same example looks like with High Contrast theme [here](https://dojo.telerik.com/@milena/UvEkakeX).

In addition, in case you prefer to use Windows High Contrast mode, you can overcome the unwanted behavior with focus state as add a custom rule:
```    .k-grid td.k-state-focused, 
  .k-grid th.k-state-focused {
    outline: white;
    outline-style: dotted;
    outline-width: 3px;
  }
```

See a runnable example below:
https://dojo.telerik.com/@milena/alaveKUP
