### ISSUE TITLE
The value of cascading DropDownList is not reset after filtering

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4866]
### Bug report

Filtering(serverFiltering: true) a child DropDownList does not reset its value after the selection in the parent DropDownList is changed. 

### Reproduction of the problem

[TelerikMvcAppCascadingDropDownLists.zip](https://github.com/telerik/kendo-ui-core/files/2899472/TelerikMvcAppCascadingDropDownLists.zip)

Steps to reproduce:

* Run the solution 
* Open the "Products" DropDownList and filter "3" and then select "Product 3".
* Change the "Categories" DropDownList by selecting "Category 2".

You will notice that the Products and Orders DropDownLists values are not being reset, thus showing incorrect values.

### Current behavior

The cascading DropDownList value is not reset. 

### Expected/desired behavior

The cascading DropDownList should reset its value after the parent selection is changed.

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by zdravkov** [comment]
I have inspected the issue and it seems to be caused by the fact that on the server we are returning Items with ProductName "ProductName 2" and "ProductName 3" both for CategoryIds 1 and 2 and after that we are applying the filter string. In such case when the Category id is changed to 2 and the filter in the filter input is still 3 (even though the input is hidden its value is still 3). In this case the serve return only Product 3 item and that is why it keeps being selected. 
In order to prevent such behavior we can change the 'filterProducts' function to the one below and take its filter value only when it is visible - in all other cases pass an empty string value:
 ```
   function filterProducts(e) {
        var productsDropDown = $("#products").getKendoDropDownList();
        return {
            categories: $("#categories").val(),
            productFilter: productsDropDown.filterInput.is(":visible") ? productsDropDown.filterInput.val() : ""
        };
    }
```
