### ISSUE TITLE
Grid: Closing The Popup Editor Does Not Reverts Changes In Model

### ISSUE THREAD

**Issue by zubair1103** [telerik/kendo-ui-core#4894]
### Bug report
When create `kendoGrid` widget with following `options`; changes in model are not cancelled when popup is closed using X icon in window's toolbar area.

```
editable: {
  mode: "popup",
  window: {
    close: onEditorClose
  }
}
```

### Current behavior
Changes in model are persisted. New model row does not remove from grid.

### Expected/desired behavior
Changes must be discarded

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 1.12.4

**Comment by matanasov** [comment]
Dojo:
https://dojo.telerik.com/@martinpz/oDixuSid/2

**Comment by boyandim** [comment]
The reason why the changes are not revered is because the onEditorClose (custom close event handler) overrides the default one. The default close event reverts the changes in the model, but eventually since it is overridden by the onEditorClose it is not executed anymore. This is rather a design decision and we recommend to include logic for reverting the changes in the model in your custom close event. Please refer to the [https://dojo.telerik.com/IgIdudEB](https://dojo.telerik.com/IgIdudEB) modified version of the example for reference.
