### ISSUE TITLE
Theme selection in dojo

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-ui-core#492]
Going from an example to the dojo via "Edit this example" is convenient, but may look jarring if switching themes. For example, I have the Material theme selected at http://demos.telerik.com/kendo-ui/grid/column-reordering, and after clicking "Edit this example", the example looks quite different.

An option for the dojo to select the theme would be great. Webix has that feature in its [Snippets](http://webix.com/snippet/dd113b85) tool under Options -> Skins.

**Comment by naskog** [comment]
@dandv , Kendo Dojo is not part of Kendo UI Core project. 

Please note that this issues list is for bugs only, not feature requests, so I’m going to close this issue with this comment.

That said, we do want your feedback and feature requests, which is why we’ve set up a User Voice portal for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll head on over to the portal to enter this request.
