### ISSUE TITLE
JavaScript errors are thrown upon schema definition

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-ui-core#493]
#### Scenario 1

[DOJO](https://dojo.telerik.com/AzUCEvoD )

Shows that having a `schema: { model: { id: "id" } }` breaks treeview instantiation - clicking on a node won't expand it

#### Scenario 2

[DOJO](https://dojo.telerik.com/UBOCizUc)

This dojo works with the `schema: { model: { id: "id" } }` from above, or even an empty schema. But removing the schema altogether will break it.

### Reproduction of the problem

1. Expand a node from the treeview

### Current behavior
Inconsistent type of returned data that lead to javascript errors

### Expected/desired behavior
Schema definition do not throw issues and data is retrieved

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** all

**Comment by nenchef** [comment]
In order to have the TreeView correctly setup, you need to configure the childer collection in the DataSource declaration. Hence, the errors will be avoided. This is described in this article:
https://docs.telerik.com/kendo-ui/framework/datasource/custom-hierarchical#fetching-hierarchy-through-single-requests
That said, the configuration upon which the bug is submitted is invalid.
