### ISSUE TITLE
TimePicker missing times - change to summertime bug

### ISSUE THREAD

**Issue by d-ziegler** [telerik/kendo-ui-core#4951]
Steps to reproduce:

- Change computer time to 31.03.2019
- Visit: https://demos.telerik.com/kendo-ui/timepicker/index (kendo culture here was automatically set to en-US)
- Open example TimePicker in a new browser window
- Times are missing between 1:30 AM and 3:00 AM

Tested in current version of Chrome and Firefox

**Comment by matanasov** [comment]
I am replicating this locally:

![Miss](https://user-images.githubusercontent.com/5861835/55311138-de0a6300-546a-11e9-969b-2cdb257c9013.png)

**Comment by d-ziegler** [comment]
Probably also depending on the timezone of your country? As I'm in germany we (now) have UTC+2.

**Comment by TeyaVes** [comment]
@d-ziegler, this is expected behavior in the Timepicker as in fact the hours between 2 AM and 3 AM (or 3 AM and 4 AM in our timezone) are missing on 31st of March due to the clock changing. The clock is moved 1 hour forward at exactly 2 AM, which makes it rather impossible to choose 2 AM or 2:30 AM as these would already be 3 AM and 3:30 AM. Does it make sense?

**Comment by d-ziegler** [comment]
Somehow it doesnt really make sense to me that a timepicker, without a date specified, uses the current date to show the times. As we probably wont have time changes anymore in a few years in the eu, I guess its not that big of a deal though.

**Comment by matanasov** [comment]
@d-ziegler 
Although it is just a time picker and you don't use a date part in it, it still uses a Javascript Date object behind the scenes.
