### ISSUE TITLE
Security trimming in TabStrip / Menu results in race condition when the page is subject of very heavy traffic

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5013]
### Bug report
Security trimming in TabStrip / Menu results in race condition when the page is subject of very heavy traffic. Further details reported by customers could be found in the following forum thread: [http://www.telerik.com/forums/possible-race-condition-in-menu-security-trimming](http://www.telerik.com/forums/possible-race-condition-in-menu-security-trimming)

### Reproduction of the problem
* Open the following solution in Visual Studio: [ConcurencyIssue.zip](https://github.com/telerik/kendo-ui-core/files/3112002/ConcurencyIssue.zip)
* Restore NuGet and build the solution,
* Publish the MVC app for `Release`. Note! Publishing for `Debug` will not allow you to observe the issue.
* Run the published application in IIS.
* Hammer the `Home/Index` page with heavy traffic - 1000 consecutive requests would almost certainly result in an error. For testing, to replicate the scenario you can use [LINQPad 5](https://www.linqpad.net/download.aspx) with the following logic:
```cs
System.Net.ServicePointManager.DefaultConnectionLimit = 32;
Enumerable.Range(0, 1000).AsParallel().ForAll(async c =>
{
  var client = new System.Net.WebClient();
  var result = await client.DownloadStringTaskAsync("http://localhost:5555/Home/Index");
  Console.WriteLine(result);
});
```

The issue cannot be observed if the application is published for `Debug`. It is also not present if running the application from Visual Studio.

### Current behavior
Internal server error (500) will be observed in most of the cases. That happens when the above 1000 requests are executed for about 50 ms.

### Expected/desired behavior
No error should be thrown, when heavy traffic hist a page with Menu / TabStrip with security trimming.

### Environment
* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by Iankodj** [comment]
We inspected the behavior. And indeed the implemented logic could lead to possible issues. However, in order to have the SecurityTrimming as a feature available there is no technical solution that could provide a better behavior. 

Shortly, in order to check the validation programmatically, the Authorization context is instantiate and every attribute is looped and checked whether the user is authorized. 

That said, Security Trimming does not actually provide much output for the cost. Basically, it sets the specific NavigationItem to Visible false if not authorized. Therefore a possible alternative is to just do the same within the Razor page with the authentication context already available. 

```razor
@(Html.Kendo().Menu().Name("TabStrip")
        .SecurityTrimming(false)
        .Items(tabs =>
	    {
		    tabs.Add().Text("Tab1").Action("Tab1", "Home");
		    tabs.Add().Text("Tab2").Action("Tab2", "Home").Visible(User.Identity.IsAuthenticated);
		    tabs.Add().Text("Tab3").Action("Tab3", "Home").Visible(User.Identity.IsAuthenticated);
		    tabs.Add().Text("Tab4").Action("Tab4", "Home").Visible(User.Identity.IsAuthenticated);
	    })

)
```
This would need some more configuration on the Razor page. But it would use the MVC internally created context and it would work much better in complex scenarios with so much load.
