### ISSUE TITLE
Official support jQuery 3.4.1

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5019]
Official support jQuery 3.4.0 - https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

**Comment by zdravkov** [comment]
Aslo asked in ticket - 1406794

**Comment by zdravkov** [comment]
ticket - 1407073

**Comment by FizzingWhizbee** [comment]
Is there a timeline for when jQuery 3.4.0 will officially be supported?  The currently supported versions of jQuery (1.12.4, 3.3.1) all have known security vulnerabilities.  I'd prefer to ship our product with Kendo UI bundled with jQuery 3.4.0 which has the necessary security fixes.  Otherwise, it looks like I'll have to go out with jQuery 3.3.1 and hand patch the security fixes into it.  Let me know if I need to file a support ticket to request support for 3.4.0.  Thanks!

**Comment by zdravkov** [comment]
Hi @FizzingWhizbee ,

You don't have to file a support ticket - we are currently in a process of testing Kendo UI against the latest jQuery so we will do our best to announce support as soon as possible. You can follow this issue for more information.

Greetings,
Plamen
