### ISSUE TITLE
NumericTextBox containing negative number positions cursor at the wrong position when focusing

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#5038]
### Bug report

When a NumerictextBox is initialized with a negative number, and the user attempts to focus by clicking behind the last digit of the number, the cursor is not positioned behind the last digit, but behind the penultimate digit.

### Reproduction of the problem
Focus the NumericTextBox in the following dojo:
[https://dojo.telerik.com/AyEqUrUy](https://dojo.telerik.com/AyEqUrUy)

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment]
This seems like a browser behavior. I was able to only replicate it in Chrome. It seems that when the inputs of the numeric switch visibility the browser does not set the caret correctly. However our calculations for the carret position are correct. In order to resolve the problem one can override our click handler and set a slight timeout before setting the caret position. [Here ](https://dojo.telerik.com/AyEqUrUy/9)is a dojo.

**Comment by kdikov82** [comment]
Ticket ID: 1407908

**Comment by ag-petrov** [comment]
We checked the item again, to see if there is an alternative solution however the only solution for now is to use a timeout and reset the caret position. This solution however may cause flickering in some cases and will not be integrated. If it desirable it can be used by applying the solution from the dojo I provided previously.
