### ISSUE TITLE
JS error on expanding widgets due to R2 2019 compatibility issue with jQuery 1.10.x, 1.11.x, 2.0.x and 2.1.x

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5052]
### Bug report
$.uniqueSort() is not supported in jQuery versions prior 2.2.x and 3.x . Thus, using jQuery version 1.10.x, 1.11.x, 2.0.x or 2.1.x throws an error.

The usage of $.uniqueSort() in jQuery 1.10.x throws an error in multiple components like Menu, DropDownList, DropDownTree, and TreeView. 

Related to #4665

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/AGAsAKAG) and try to use some of the components in it.
2. Error messages appear in the console and the components get stuck

### Current behavior
![uniqueSort](https://user-images.githubusercontent.com/41293735/57836921-669a5400-77ca-11e9-9ec8-7772a199160e.png)

### Expected/desired behavior
All components should work properly no matter of the jQuery version used.

To see the expected behavior change 
`    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
`  
to 
`    <script src="https://kendo.cdn.telerik.com/2019.2.514/js/jquery.min.js"></script>
` in the provided Dojo. 

### Environment
* **Kendo UI version:** 2019.2.514
* **jQuery version:** 1.10.x, 1.11.x, 2.0.x and 2.1.x
* **Browser:** [all]

**Comment by boyandim** [comment]
A workaround for this problem is to assign jQuery unique method implementation to the jQuery uniqueSort if missing before initialization of any Kendo UI widget on the page. 

For example please refer to the [https://dojo.telerik.com/AGAsAKAG/3](https://dojo.telerik.com/AGAsAKAG/3) dojo where the following code 

kendo.jQuery.uniqueSort = kendo.jQuery.uniqueSort ? kendo.jQuery.uniqueSort : kendo.jQuery.unique;
is included before the initialization of the Kendo UI widgets.
