### ISSUE TITLE
TreeList parentId should be nullable by default

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5055]
### Bug report

Ticket ID 1402301 

The jQuery Kendo UI TreeList has a `parentId` which is `nullable:true` and `type:number` by default. [Documentation](https://docs.telerik.com/kendo-ui/api/javascript/data/treelistmodel/configuration/parentid)

The MVC and Core wrappers serialize both nullable integers and strings into `nullable:false`. This leads to no records being shown for the TreeLists which have a string `parentId` because no default value is serialized, too:

Here is a simplified serialized TreeList with sample data with a parentId which is a `string`:

[Dojo](https://dojo.telerik.com/@bubblemaster/OGiPoCEf)

When the `parentId` is numeric, we add a `defaultValue:null` which prevents the situation, nonetheless, the field should be `nullable:true` by default unless configured otherwise.

Here is a simplified serialized TreeList with sample data with a parentId which is a `number`:

[Dojo](https://dojo.telerik.com/@bubblemaster/oYuRoWUc)

### Reproduction of the problem

Demonstrated above in the Dojos.

### Expected/desired behavior

ParentId should be `nullable:true` by default.

### Environment

* **Kendo UI version:** 2019.2.514
* **jQuery version:** 1.12

**Comment by boyandim** [comment]
It turned out that the previous fix introduced a regression for not applying the default value for certain fields (logged and explained in the [https://github.com/telerik/kendo-ui-core/issues/5139](https://github.com/telerik/kendo-ui-core/issues/5139) issue) A new fix has been committed that fixes the problem with the parent id and does not affect the default value of the fields.
