### ISSUE TITLE
Docs for Gantt React wrapper are broken/gone

### ISSUE THREAD

**Issue by k290** [telerik/kendo-ui-core#5078]
### Bug report

When you navigate to the link there are no longer docs
https://www.telerik.com/kendo-react-ui-wrappers/wrappers/gantt/

**Comment by simonssspirit** [comment]
@k290 Since we decided to only focus on pure React components, the wrappers documentation was removed and redirected to the mentioned page. We made an article in the Kendo UI for jQuery documentation on how to use the wrappers or directly the jQuery widgets in React. 

In this case, the Gantt wrapper has the same configuration options as the jQuery version as it is based on it. I can suggest using the documentation for the Gantt from the Kendo UI docs, as it is more complete as has more examples.
