### ISSUE TITLE
Spreadsheet comments are not properly exported in XLSX

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5129]
### Bug report
Spreadsheet comments are not properly exported in XLSX

### Reproduction of the problem
If you export the Spreadsheet from the following Dojo: https://dojo.telerik.com/uhEWEsAf/6
the result will be:
![CommentWhenExported](https://user-images.githubusercontent.com/3431388/59911176-01b2c900-941c-11e9-8715-6c648f9f333b.png)
while it should be:
![CorrectComment](https://user-images.githubusercontent.com/3431388/59911318-48a0be80-941c-11e9-96a9-bda10e1f36d4.png)

### Current behavior
The shape of the comment box after export is not proper

### Expected/desired behavior
The shape of the comment box after export should be rectangular

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by mishoo** [comment]
I could not reproduce that, please confirm if it's still happening.

**Comment by mparvanov** [comment]
The issue is reproducible with latest Kendo version 2020.3.915 on the Basic Usage example:
1. Open https://demos.telerik.com/kendo-ui/spreadsheet/index 
1. Insert a comment "Test" to A2 for instance
1. Export to xlsx
Actual: https://take.ms/Ge1gM
[Workbook (1).xlsx](https://github.com/telerik/kendo-ui-core/files/5305777/Workbook.1.xlsx)
