### ISSUE TITLE
Change event issue in DropDownList with initial value - MVVM context

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5162]
### Bug report

The change event is being triggered when having an initially selected item in the DropDownList and then open the DropDownList and click on the default selected item. This bug is represented only in MVVM. 

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/UkIyehUV) and run it. The three cascading DropDownLists will have default selected items
2. Click on the first DropDownList and select the already selected "Confections" option
3. The other two DropDownLists will be reset because of the change event thrown in the first DropDownList

### Current behavior
The change event of a DropDownList with initial data selected is being triggered when clicking on the already selected value. 

### Expected/desired behavior
Selecting the already selected item of a DropDownList shouldn't trigger its change event because there is no actual change in the component's value. Please check[ this Dojo](https://dojo.telerik.com/IqOdAFOw) for the expected behavior. 

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by zdravkov** [comment]
The issue is only observed when the DropDownList is initialized from select element, used in MVVM scenario and bound to remote data. In such complex cases we recommend using input instead of select for initialization to avoid such specific issues. Here is an example with with a correctly working DropDownLists - https://dojo.telerik.com/@zdravkov/UfUguhEk
