### ISSUE TITLE
Editable grid with locked columns gets misaligned on edit

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5173]
### Bug report

Ticket ID 1418377 

### Reproduction of the problem

[Dojo](https://dojo.telerik.com/@bubblemaster/IKAZemiX)

- Scroll to the bottom, click on John Doe (non-locked) table
- Click on the multi-line text - locked table

### Current behavior

The `<td/>` element seems to collapse to 200px when the cell goes into edit mode when the grid has a defined height

### Expected/desired behavior

The grid's locked and unlocked tables should be synced

### Environment

* **Kendo UI version:** 2019.2.619

**Comment by dmanova** [comment]
The issue seems to be partially fixed. The rows are getting misaligned when clicking on non-frozen (not locked), multi-line text cell. If you click on frozen (locked), multi-line text cell it is fine.

**Comment by ag-petrov** [comment]
The issue is now replicatable only for the specific case in FireFox and it seems like a browser bug. If the cell is opened for edit and you just wait a while the browser will repaint the content. We can try and add a workaround for the specific browser but generally this is not a best practise as the browser bug may not be present in future versions.

**Comment by dmanova** [comment]
Verified and working with the following remarks:

- In FireFox v.58.0 (previous one was fine) the cells get misaligned in the described case above and after a while the are refreshed and aligned.
- There is a slight jumping of the rows at the bottom from time to time, but they keep aligned.

**Comment by matanasov** [comment]
FF 58 is an old version. Current is 68
