### ISSUE TITLE
Loading indicator incorrectly displayed with local dataSource when using spriteCssClass

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5174]
### Bug report

Loading indicator incorrectly displayed with local dataSource when using spriteCssClass.

### Reproduction of the problem

https://dojo.telerik.com/iWACuLIj

### Current behavior

Loading icon is displayed with local dataSource.

### Expected/desired behavior

Loading icon should not be displayed with local dataSource.

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is reproducible when spriteCssClass property is used to show kendo font icons, which need k-icon class + k-iconspecific class. The k-icon class is used to add and remove loading icon while sub-items are fetched.

The current fix is to change the ICON_SELECTOR to ".k-menu-icon". But there is no k-menu-icon class on menu items, so k-i-loading icon is no longer displayed.
**Reproduction of the issue:**
1. Load [Binding to remote data demo](https://demos.telerik.com/kendo-ui/menu/remote-data-binding) on staging with the applied fix.
1. Use Chrome dev tools Network tab to simulate Slow 3G network.
1. Hover a menu item

**Expected:** the arrow down is substituted with k-i-loading while the request for sub-items is performed. When sub-items are available, the loading icon disappears and the arrow down icon is visible.
**Actual:**  No loading icon is visible while requesting sub-items.

**Comment by Dimitar-Goshev** [comment]
The issue is fixed
