### ISSUE TITLE
kendo-editor throws SyntaxError: "missing name after . operator" in some cases

### ISSUE THREAD

**Issue by fschlaef** [telerik/kendo-ui-core#5184]
### Bug report

In some of our use cases, `kendo-editor` throws an error on loading and doesn't bind to the model. We abstract the actual component to work with our infrastructure and it works fine, except 
when the `<form>` is also abstracted. Only `kendo-editor` has this problem so far, we've had no issues with stuff like `grid`

### Reproduction of the problem
https://dojo.telerik.com/asoLiPoh/3

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** 3.4.1
* **Browser:** Firefox, Chrome and Edge

**Comment by Iankodj** [comment]
The problem here is the abstraction of the ng-form. When Editor initializes as a form input, the form is found in order to get the name attribute. However, with the abstraction the value of the name attribute is not evaluated. This is why the JavaScript error is thrown. 

That cannot be handled automatically by the **k-ng-model** directive and a good substitution is using the native **ng-model** one. 

Or, you can use the [k-ng-delay](https://docs.telerik.com/kendo-ui/framework/AngularJS/widget-basics/delayed-initialization) and push some change of the state when the form abstraction is ready so that the widget is initialized after that.
