### ISSUE TITLE
Can't resolve 'kendo-ui-core/css/web/kendo.common.core.css'

### ISSUE THREAD

**Issue by wickedrahul** [telerik/kendo-ui-core#5240]
Causing this error upon running the command `npm run build:prof` after upgrading `kendo-ui-code`  to its 2019 version from 2017.

Inspected node_modules of Kendo packages and found that the above css file indeed was missing in its latest version.

P.S Have been using webpack2

**Comment by PreslavKozovski** [comment]
@wickedrahul 

With our `2019.1.115` version, we decided to remove all the `*.core.less`, and the respective `*.core.css` files.

This is because maintaining two codebases for the styles requires more time, and the benefits of having them cannot justify the efforts.

Having said that, now, use the `kendo.common.css` or the `kendo.common.min.css` file.
