### ISSUE TITLE
Filter fails on iPhone Safari when contains a single quote

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#5241]
### Bug report

There are no results as soon as the apostrophe present in the search pattern.
Works fine on Safari on a mac, chrome on any system, but has the above result above on an iphone.

### Reproduction of the problem
1. Open the following sample in iPhone: [https://dojo.telerik.com/uraLukus/6](https://dojo.telerik.com/uraLukus/6)
1. Enter O in the input field
1. Filter the datasource -> 4 results are found as expected
1. Enter ' in the input field next to O and filter the datasource

### Current behavior
0 results are found

### Expected/desired behavior
1 result is found

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [ iPhone 6 iOS 12.3 Safari ] 

Feedback Portal: https://feedback.telerik.com/kendo-jquery-ui/1427138-filter-fails-on-ios-safari-when-contains-a-single-quote

**Comment by ag-petrov** [comment]
This is not a bug. It is caused by a change in the iOS where the default quotation mark is changed with another symbol and now when you type you get a different type of quote. Before it was ' whereas now it is ‘. However if you turn off the Smart Punctuation functionality the filtering works. More about this can be found [here](https://apple.stackexchange.com/questions/299505/ios-11-default-quotation-mark-changed-to-and).
