### ISSUE TITLE
Spreadsheet throws an error when trying to filter a single cell of a column

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5279]
### Reproduction of the problem
An error is thrown when you try to filter a column (filter configuration of the Spreadsheet **is not set**). 
1. Open [this Dojo](http://dojo.telerik.com/USUfoPER/2)
1. Select a single cell (e.g. C2 Quantity). 
1. Toggle filter from toolbar. Try: filter by value -> all.

### Current behavior

An error "Uncaught TypeError: s[0].children.data is not a function" is thrown.
### Expected/desired behavior
No error should be thrown.

### Environment

* **Kendo UI version:** 2019.3.917

* **Browser:** [all]

**Comment by mparvanov** [comment]
The JS error is fixed. The use case of applying a filter to a single cell doesn't make much indeed. The valid options I see are:
1. Disable the button unless cells in multiple rows are selected
2. Follow Excel behavior and extend the range of the values to the last filled in cell of the column/value  and apply the filter to the relevant multiple cells/rows.
@mishoo

**Comment by mishoo** [comment]
The issue here appears to be that the icon font (WebComponentsIcons) is not declared with `kendo.pdf.defineFont` (see in the source how DejaVu fonts are declared).  I'm not sure where does this font come from (I can't see it in the Network tab in devtools), but I suspect it's bundled in some Woff file; unfortunately, the PDF library does not support Woff, only TTF.

**Comment by mishoo** [comment]
I've sent a PR on branch `spreadsheet-filter-button`. The resolution is that the button will be disabled unless a filter is already active, or more than one row is selected.
