### ISSUE TITLE
On scrolling of Kendo Window with thousands of images makes IE11 unresponsive

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5287]
### Bug report

On scrolling of Kendo Window containing hundreds to thousands of images makes IE11 unresponsive. If images are placed inside of Bootstrap Modal or on main window the issue does not exist. 

### Reproduction of the problem

Run the following dojos in IE11 and scroll through the content for demonstration of the issue:
 * [Kendo Window](https://dojo.telerik.com/@AleksandarEvangelatov/uHebAKIT)
 * [Bootstrap Modal](https://dojo.telerik.com/@AleksandarEvangelatov/idOsACAW)
 * [Scrollable div in main window](https://dojo.telerik.com/@AleksandarEvangelatov/USoPESUj)

### Current behavior

On scrolling of the content inside the Kendo Window on IE11 the browser becomes almost unresponsive

### Expected/desired behavior

On scrolling of the content inside the Kendo Window on IE11 the browser should remain responsive

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [ IE 11  ]

**Comment by zdravkov** [comment]
The bug is replicated only with static HTML and the 'k-window-content' class  - https://dojo.telerik.com/@zdravkov/AtAdeFOJ

**Comment by Juveniel** [comment]
The issue is related strictly to IE 9, 10, and 11 where adding overflow: hidden and border-radius: x on the same element results in slow paint of the elements. Additional information regarding the issue could be found in [the following StackOverflow thread](https://stackoverflow.com/questions/39490557/how-does-overflow-hidden-border-radius-on-a-container-cause-massive-slowdown).

As currently, the rendering of the Window does not allow to separate those styles (only 1 element for the Window content), the border bottom radius will removed from the Window in IE.
