### ISSUE TITLE
Scheduler: Selecting a slot partially hidden by the all-day slot results in selecting the all-day slot

### ISSUE THREAD

**Issue by mpoelman** [telerik/kendo-ui-core#5299]
### Bug report
The issue starts to reproduce since 2016.2.607.

### Reproduction of the problem
1. Go to the following dojo: https://dojo.telerik.com/ilolitoN or use [Keyboard Navigation demo](https://demos.telerik.com/kendo-ui/scheduler/selection)
2. Scroll the scheduler a bit down so that a slot is partially hidden by the all-day slot, like this:
![image](https://user-images.githubusercontent.com/4239223/65950804-194c1580-e43f-11e9-8720-34e71558215e.png)
3. Click on a partially hidden slot (tuesday 6/11, 9:30 - 10:00 for example)

### Current behavior
If you follow the reproduction steps, you will notice that the selection jumps to the all-day slot.
I noticed that it happens less often when you increase the overall slot height, but it still happens.

### Expected/desired behavior
The clicked slot gets selected, not the all-day slot. As in [Dojo with 2016.2.504](https://dojo.telerik.com/OJAFeHiY)

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.3 and 3.3.1
* **Browser:** Chrome 77.0.3865.90, IE11, Edge 44 and Firefox 68.0.1

**Comment by Dimitar-Goshev** [comment]
@Iankodj After the fix wrong slot is selected, if the whole page is scrolled down. Also the following JS error may be thrown by kendo.core.js:
Cannot read property 'getFullYear' of undefined
```
        function toUtcTime(date) {
            return Date.UTC(date.getFullYear(), date.getMonth(),
                        date.getDate(), date.getHours(), date.getMinutes(),
                        date.getSeconds(), date.getMilliseconds());
        }
```
To reproduce the issue, use Scheduler Keyboard Navigation demo on staging. After loading the demo, scroll down the page so that the Scheduler top border hits the demos' products header.
Then click on a slot which is before 10 AM - error thrown.
If a slot after 10 AM is clicked - a timeslot will be selected, but the selection will be inaccurate - clicking on 10-10:30 slot selects all day slot

**Comment by Dimitar-Goshev** [comment]
@Iankodj After the latest fix Chrome is OK.
There are issues when tested on on scheduler/selection demo in **LESS** themes as follow:

- IE11 and Edge:  **without scrolling the whole page** there is a JS error on clicking the **last timeslots when Business hours** are shown:
`Unable to get property 'getFullYear' of undefined or null reference`

- Edge: with scrolling the whole page selection may be displaced downwards, depending on the page scrolling. E.g. scroll down so that the Views selection is hidden and click on Wed 6/12 10:30-11:00 PM timeslot -> 11:00-11:30 PM timeslot is selected
![Edge - displaced selection](https://user-images.githubusercontent.com/6614183/69236115-8c4e4e80-0b9b-11ea-93ce-b20977a77f13.png)
If the last timeslot is clicked, JS error is thrown:
`Unable to get property 'getFullYear' of undefined or null reference`
- Firefox: with/without scrolling the whole page there is a JS error on clicking the last timeslots in Full day/Business hours:
`date is undefined`
