### ISSUE TITLE
There is a problem with the filtering function of merging cells in spreadsheet

### ISSUE THREAD

**Issue by zhenzi887** [telerik/kendo-ui-core#5376]
### Bug report

** In spreadsheet, there are cells merged across rows. Select the last row of cells in merging and click the filter button in the toolbar. Then, clicking the down arrow to filter cells merged across rows will not work.

### Steps to reproduce:
1. https://demos.telerik.com/kendo-ui/spreadsheet/index
1. Merge A2 and A3 
1. Select Row 4 and click the filter  button
1. Click the down error button over the merged cell

### Current behavior
Filter box of merged cell does not display

### Expected/desired behavior
The filter box of the merged cell can be displayed normally

### Environment

* **Kendo UI version:** 2019.3.1023

**Comment by Dimitar-Goshev** [comment]
The reproduction steps point that this issue is another issue, which has been already fixed - [Spreadsheet throws an error when trying to filter a single cell of a column](https://github.com/telerik/kendo-ui-core/issues/5279). The issue was that if you select a single cell in a column, instead of cells on several rows for a column, the Filter button was enabled and when clicking it, an error was thrown and the filter menu was not shown. Now on Step 3 - "Select Row 4 and click the filter button" - this cannot be reproduced as the Filter button is disabled, when only 1 row is selected.
