### ISSUE TITLE
Grid InCell editing does not accept new values when in Desktop Mode

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5419]
### Bug report

Grid editing in InCell edit mode does not change new values on iPad and Mobile devices in Desktop Website mode.

### Reproduction of the problem

1. Open https://demos.telerik.com/kendo-ui/grid/editing on iPad >v.13 or mobile device in Desktop mode (browsers' configuration).
2. Edit the value in a cell and click on another cell - https://screencast-o-matic.com/watch/cqiUoEOkwE

### Current behavior
The old value is present in the cell.

### Expected/desired behavior
The new/changed value is present in the cell after losing focus.

### Environment

* **Kendo UI version:** 2019.3.1023
jQuery version: 1.12.4
Browser: [ Safari | Chrome | Firefox ]
OS: Android | iOS

**Comment by msereda** [comment]
I put in a ticket about this yesterday (prompting the priority increase), just wanted to post the same info here regarding the impact this issue is having on us.
--------------------------------------------------------------------------

We recently updated a large application to Kendo 2019.3.1023 in order to fix all of the issues that previous Kendo versions had with iOS13, frozen grid scrolling, combobox drop downs being unselectable, multiselects unable to remove values, etc.  All of these previous issues, to the best of our testing so far, have been fixed, which is great because the issues made our application unusable on iOS13.

However, it appears that 2019.3.1023 also introduced a new bug, in that grid in-cell editing on iPads w iOS13 is pretty much broken.  This can be seen in the batch editing demo (link below), if I click into a cell, change the value, then click into another cell, the value in the first cell is reverted back to the previous value.  We have over a dozen in-cell grids in our app and some are used for calculating payments, so this bug has already caused issues with fee calculations.

We are really hoping that there is a good workaround or that the issue is going to be fixed right away, as we are stuck.  We need to update Kendo for all of the previous iOS13 issues that you've fixed, but at the same time we can't update Kendo due to the really nasty in-cell editing bug introduced on iPads.

I was going to try updating to the 2020.1 version but I assume it doesn't work either since the batch editing demo here still reproduces the same issue on iPad iOS13:

https://demos.telerik.com/kendo-ui/grid/editing
