### ISSUE TITLE
dataBound event fires in PDF export

### ISSUE THREAD

**Issue by dday9** [telerik/kendo-ui-core#5422]
### Bug report
The dataBound event is fired unexpectedly row whenever the kendoGrid is generating a PDF.

### Reproduction of the problem
Setup a basic kendoGrid and click on Export to PDF. Different things will cause the dataBound event to fire more often.

### Current behavior
1. The dataBound event will fire once when there is no pdfExport event handled or the pdfExport event is handled but you do not get the argument _e_ from the progress event: https://dojo.telerik.com/ImErEpaC
2. The dataBound event will fire once **for each row** when there is the pdfExport event is handled and you do get the argument _e_ from the progress event: https://dojo.telerik.com/oTiSIZAB

### Expected/desired behavior
According to the documentation the dataBound event should only "Fired when the widget is bound to data from its data source."

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** (only tested on) FireFox 70.0.1

**Comment by dday9** [comment]
Any update on this bug? This is still present in 2021.2.511.

**Comment by ag-petrov** [comment]
Actually this is not a bug, in order to export the content the grid should page iteself to allow the drawing mechanism to copy the content. Altering the internal workings here may result in breaking changes as clients may rely on the event to fire to modify the content befo the export happens. We will update our documentation about this scenario so developers are aware that the behavior is expected.
