### ISSUE TITLE
Scheduler current time marker causes extra padding on time headings

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-ui-core#5470]
### Bug report
The current time marker will sometimes overflow the inner table while resizing the scheduler, causing extra padding to be added below the time headings to accommodate for a horizontal scrollbar, despite there not being one.

### Reproduction of the problem
1. Open Dojo at: https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/how-to/appearance/expand-scheduler-to-100-height-and-width
2. Choose library version
3. Jump to today on day or week view
4. Zoom or resize window until padding appears below time headings

### Expected/desired behavior
Padding should only appear when there is a horizontal scrollbar.

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 3.4.1
* **Browser:** Chrome 78

**Comment by Dimitar-Goshev** [comment]
@austinw-fineart I followed the described steps, but I am not sure if I see the issue. Is it reproducible on the following [Dojo snippet](https://runner.telerik.io/fullscreen/@Dimitar-Goshev/OpuvAmuf) ? Could you add a screenshot to clarify it?

**Comment by austinw-fineart** [comment]
Sure thing, look for the bottom left corner:
![runner telerik io_fullscreen_@Dimitar-Goshev_OpuvAmuf](https://user-images.githubusercontent.com/40481873/70505695-94c6f300-1b63-11ea-8ade-43bddeb71b6a.png)

**Comment by Dimitar-Goshev** [comment]
@austinw-fineart Thank you for the clarification. The issue is reproducible on my side only when resizing the Dojo pane or browser window. It is not reproducing on refreshing the page at the time it appears.
For resizing Scheduler height, I would recommend the approach from [Calculate Scheduler Height Dynamically How To article](https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/how-to/appearance/dynamic-calc-of-height). When it is applied to [the previous example](https://dojo.telerik.com/OxeDEtUT), the issue is fixed.
