### ISSUE TITLE
Wrong time display for 24 hours format cultures in the scheduler vertical ruler

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#5492]
### Bug report

The time format is not properly diplayed for 24 hours format cultures in the scheduler vertical ruler, e.g. fr-CA, bg-BG

### Reproduction of the problem
https://dojo.telerik.com/ecaBuSIm/7

### Current behavior
The time in the vertical ruler after 12 o'clock is displayed as 1,2...12

### Expected/desired behavior
The time in the vertical ruler after 12 o'clock is displayed as 12, 13 ... 
R1 2019: https://dojo.telerik.com/ecaBuSIm/3 

The incorrect behavior is introduced with R2 2019
### Environment

* **Kendo UI version:** 2019.3.1023

**Comment by mparvanov** [comment]
Internal Note: Consider adding also the kendo.culture setup to the [Scheduler Localization demo](https://demos.telerik.com/kendo-ui/scheduler/localization) similar to the [General globalization example.](https://demos.telerik.com/kendo-ui/globalization/index)

**Comment by Juveniel** [comment]
The issue with the time slot not honoring the current culture is related to changes in the `majorTimeHeaderTemplate` as part of [the adaptive rendering story](https://github.com/telerik/kendo-ux/blob/master/themes/default/PNG/adaptive-scheduler-main-screens.png) for the Scheduler.

After further discussion with @ivelina-penkova, we decided to change the design and display the time and am/pm designator on the same row (instead of two rows) for mobile. Thus, it is no longer needed to separate the time in two elements.
