### ISSUE TITLE
Weird Grid behavior using Bootstrap modal 

### ISSUE THREAD

**Issue by Ram-97** [telerik/kendo-ui-core#5504]
https://dojo.telerik.com/IpiwAGOl/2 
Whenever open the modal, Kendo scrollable height is not set automatically. After refresh the grid, Kendo scrollable height sets automatically. 

Also, I have tried using the latest kendo latest libraries.

**Comment by Ram-97** [comment]
@dmanova ,Please share alternate approach to load the grid in bootstrap modal.

**Comment by Ram-97** [comment]
could you please change the bug severity level to medium

**Comment by dmanova** [comment]
Hi @Ram-97 you could use kendoWindow instead of a native modal widow and try some of the approaches described at this KB:
https://docs.telerik.com/kendo-ui/knowledge-base/resize-grid-when-the-window-is-resized

Or you could set up the Grid height after creation, by changing its height. In your dojo sample it will look like:

_if (!$('#grid').data('kendoGrid')) {
                createGrid();
                **$( ".k-grid-content" ).css( "height", "20em" );**
            }_

**Comment by ag-petrov** [comment]
This is not a bug. The container is animated and the grid initially can not calculate the height properly. Forcing a resize fixes the problem - > https://dojo.telerik.com/IpiwAGOl/14
