### ISSUE TITLE
FileManager dataSource destroy endpoint is not called after calling cancelChanges

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5564]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/@GaloisGirl/IPAMIHik) example.
1. Follow the instructions in the linked example. 

### Current behavior
The destroy endpoint is called once when deleting a file. Subsequent file deletion results in the file being removed from the FileManager, but no request to the destroy endpoint is sent. 

### Expected/desired behavior
The **destroy** endpoint should be called on every attempt to delete a folder or a file. 

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by GaloisGirl** [comment]
Re-tested on 2020.1.219 (still present):  https://dojo.telerik.com/@GaloisGirl/aDacanik

**Comment by Iankodj** [comment]
The described behavior is a result of calling the cancelChanges. Indeed, with most DataSource-boundable component cancelChanges to the DataSource will lead to the effect you are after, but due to the complexity of the FileManager this component is an exception to that rule. 

The FileManager automatically calls the sync method to sync the actions performed directly. This is why cancelChanges will not have any effect. You should only rely on the refresh method in order to bring back the actual view from the server. https://dojo.telerik.com/AGefUyiz

We are currently working on a new event called `command` that will yield a status upon success or failure with the specific item and action. That will give more control over the FileManager based on server responses.
