### ISSUE TITLE
Broken action button styles when autoupload is false

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5599]
### Bug report
regression
https://dojo.telerik.com/@zdravkov/AKuSIDax

### Current behavior
The buttons are not styled correctly

### Expected/desired behavior
The buttons should be styled correctly

### Environment

* **Kendo UI version:2020.1.114

**Comment by Dimitar-Goshev** [comment]
@Juveniel After the fix the appearance in SASS themes is OK. But there are regressions in LESS themes:
- [ ] The action buttons are one over the other, instead of next to each other:
![jQuery Asynchronous File Upload Example _ Kendo UI Upload Demo - Google Chrome 2020-02-15 15 32 55](https://user-images.githubusercontent.com/6614183/74588832-73253480-5008-11ea-95b6-e782a5ad5edf.png)
- [ ] Adding k-primary, combined with the previously existing k-upload-selected class results in illegible button text in the following themes:
Blue Opal, Bootstrap v3 (pic below), Default, Fiori, Material, Metro, Metro Black, Nova, Office 365, Siulver, Uniform
![jQuery Asynchronous File Upload Example _ Kendo UI Upload Demo - Google Chrome 2020-02-15 15 35 42](https://user-images.githubusercontent.com/6614183/74588865-d616cb80-5008-11ea-905f-2ac74c2b6844.png)
