### ISSUE TITLE
Scheduler Footer is disabled by default (MVC)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5608]
### Bug report
The Footer option of the UI for ASP.NET MVC Scheduler is disabled by default. 

### Reproduction of the problem
[Demo](https://demos.telerik.com/aspnet-mvc/scheduler).

### Current behavior
No footer is rendered. 

### Expected/desired behavior
The footer should be enabled by default.

Currently, it has to be enabled explicitly: **.Footer(true)**

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mparvanov** [comment]
Before the fix with the default configuration of Scheduler helper the serialization was adding "footer":false. If setting .Footer(true) the "footer" option was incorrectly removed from the serialization at all which was used as a potential workaround to this issue. That's why after this fix the workaround  .Footer(true) should be removed since it's leading to the following serialization:
https://dojo.telerik.com/IXolUBEP/2 and the "Show Business Hours " button is missing. It would be available only when the footer command is set to "workDay" which is the default value:
https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/configuration/footer.command#footercommand
