### ISSUE TITLE
DataSourceRequestModelBinder throws errors in Razor Pages as `Page` is a reserved query parameter

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#5618]
### Bug report

Since `Page` is a reserved by the framework query parameter, its value is always a string. Thus, when we try to parse it to a number, an exception occurs. To avoid the exception we should use a method like Int.TryParse which does not throw an exception when the parsing fails.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by lacutah** [comment]
I'm the end user / reportee - I also provided a solution. I'm happy to address any questions you may have - this is a causing a very tangible slowdown on our servers rendering times due to the expense of throwing exceptions, and it's amplified even more if more than one control exists on the razor page. Right now we're using a custom build to resolve the performance issue. Fortunately, the implemented solution is a 3-liner... although it may not meet your standards.
