### ISSUE TITLE
NOT RESOLVED: Inconsistent responsiveness of the Drawer button located in the NavBar

### ISSUE THREAD

**Issue by cdahl** [telerik/kendo-ui-core#565]
I think this issue was closed prematurely (and I can no longer comment on it):

https://github.com/telerik/kendo-ui-core/issues/543#issuecomment-75070662

I do have the default threshold set correctly (as per http://www.telerik.com/forums/click-event-does-not-fire-reliably#JzzYDDZBCkCItzP17Yw5PA). However, there are still issues with the buttons not being as responsive as it was in older versions of Kendo. Sometimes you have to click the button several times in order for it to work. The issue seems to be limited to buttons inside of layouts.

This is even happening in your demo, found in the link below. The drawer button isn't consistently responsive - it seems to receive the event (the button highlights) but nothing happens. Run it on an iPhone, using iOS8:

http://demos.telerik.com/kendo-ui/m/index#drawer/index

**Comment by underlog** [comment]
Hi, 

The demo you have linked to does not feature the threshold setting, which is *critical for the behavior in question to be addressed*. In case you need further assistance with the problem, I may suggest the following steps:

- Prepare an up-to-date test case with the threshold setting applied correctly. 
- Record a video of the malfunctioning behavior.
- Post it as a support ticket in the Telerik ticketing system. This will guarantee a timely response on our side. 

Since the issue you have opened does not contribute to the problem by bringing any further information than what we have here, I am going to close it too. Thank you for your understanding.
