### ISSUE TITLE
Multiselect in IE with autoClose: false does not remain open

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5656]
### Bug report

In IE 11, MultiSelect with autoClose:false does not prevent the popup from closing. The widget has to be placed at the bottom of the page, so that there is no space for the popup to open below the input field.

### Reproduction of the problem
1. Open [this Dojo example](https://dojo.telerik.com/eLOzoyAp/20).
2. Scroll to the bottom of the page.
3. Start selecting items until the tags do not fit the input field.
4. When the input's height expands, the popup closes.

Note: when the popup closes, .k-state-focused class remains on the div.k-multiselect element.

Workaround - https://dojo.telerik.com/eLOzoyAp/23
### Current behavior
The popup closes when the height of the input field expands to fit tags on a new line.

### Expected/desired behavior
The popup should remain open.

### Environment

* **Kendo UI version:** 2020.1.219
* **Browser:** [Internet Explorer 11]

**Comment by nelito987** [comment]
The issue could be replicated in other browsers as well. Another example is below:
1. Open the [Dojo example](https://dojo.telerik.com/@NeliKondova/iyUQojim/2)
2. Resize the browser window to a small size in order to have a vertical scroller
3. Scroll, so the MultiSelect to be near to the top of the screen.
4. Select items with long texts

Reported in ticket ID: 1489065

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
