### ISSUE TITLE
Release notes for Vue

### ISSUE THREAD

**Issue by SaphuA** [telerik/kendo-ui-core#5681]
Every now and then new versions of the Vue components are published to npm. It seems impossible to find out what has been fixed/changed in these updates. Because we have reported some bugs, either through github or through the forums and have workarounds for some of them, I would very much like to know what has been changed in these updates.

For Vue I could find these resources, none of them useful:

**Release History** - not updated since september 2019.
https://www.telerik.com/kendo-vue-ui/release-history/
**What's New** - lists only new components.
https://www.telerik.com/support/whats-new/kendo-ui
**Roadmap** - not very useful information
https://www.telerik.com/kendo-vue-ui/roadmap/

**Comment by Dimitar-Goshev** [comment]
Hi @SaphuA 
Thank you for your feedback, we really appreciate it.
1. **Release History** - We will update Release History with the relevant R1 2020 information.
Since Kendo Vue Native components are using semantic release, each fix publishes a new release. For the time being I would suggest checking the status of reported issues in [kendo vue repo](https://github.com/telerik/kendo-vue/issues?q=is%3Aissue+is%3Aclosed). We have logged a task to add a change log page, when there are available resources for that.

1. **What's New** - Currently this page holds the information for all Kendo UI flavors - jQuery, Angular, React and Vue. There is a fast navigation section to the right. Vue Updates in R1 2020 is at the bottom of the page. We will reconsider if we can change the page in a way that makes Vue and other flavors more discoverable on the page. It seems that the fast navigation to the right is not as obvious as intended.

1. **Roadmap** - the page depicts what we have planned for R1 2020.
