### ISSUE TITLE
Tabstrip Scrollable Buttons don't work on iOS 13 and Android in Desktop mode

### ISSUE THREAD

**Issue by bloodlanser** [telerik/kendo-ui-core#5698]
### Bug report
Tabstrip scrollable feature doesn't work on Ipad devices due to incorrect **kendo.support.mobileOS** (it equals to false on ipad).

### Reproduction of the problem
* Open Safari on Ipad and navigate to tabstrip demo page: https://demos.telerik.com/kendo-ui/tabstrip/scrollable-tabs
* Try to click on scroll button(s)

### Current behavior
Tabs are not scrollable.

### Expected/desired behavior
Clicking on scroll buttons should scroll the tabs.

### Environment

* **Kendo UI version:** 2020.1.402
* **jQuery version:** 3.4.1
* **IpadOS:** 13.4
* **Browser:** iOS 13 Safari

**Comment by dmanova** [comment]
This is also reproducible in Android for Desktop mode.

**Comment by AbacasXchange** [comment]
On an Iphone, this is still not working and can be reproduced using your documentation example on a mobile phone for scrollable tabs.  Buttons appear, and it appears the buttons are calling events, but the tab content is not paging across as the buttons are pressed.
How is this still a problem when it was supposedly fixed in 2020 ?
