### ISSUE TITLE
2020.2.513 & 2020.2.512 breaks kendoEditor

### ISSUE THREAD

**Issue by Shereef** [telerik/kendo-ui-core#5769]
**Describe the bug**
I tried 2020.2.513 it didn't work so I tried 2020.1.406 it worked

**To Reproduce**
open [this stackBlitz](https://stackblitz.com/edit/angular-g72q3q-kcneuw)

**Expected behavior**
that it would return the kendoEditor instead of breaking.

**Screenshots**
N/a

**Browser**
 - OS:  all
 - Browser chrome
 - Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
in my code i used kendoEditor with params but for simplicity I removed them form the blitz

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** x.y
* **Browser:** all

Moved from: https://github.com/telerik/kendo-angular/issues/2898

**Comment by Juveniel** [comment]
The issue in the provided Stackblitz is related to incorrect initialization of the jQuery Editor. In order to fix this, simply wrap the initialization element as follows:

```
const kEditor: kendo.ui.Editor = kendo
      .jQuery(editorTextArea)
      .kendoEditor()
      .data("kendoEditor");
```

[Here is a modified Stackblitz](https://stackblitz.com/edit/angular-g72q3q-hdfwsm?file=app/app.component.ts) where the above is applied and the Editor is correctly initialized.

For further reference on utilizing the jQuery components in Angular application, please refer to [the following article](https://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/).

Taking the above into consideration, I am closing the issue.
