### ISSUE TITLE
Listview broken when initialized from table due to new rendering

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#5772]
### Bug report

Due to the new rendering of the listview and the new container, we are adding to wrap the content: 'k-listview-content', the layout of the listview is broken when initialized from a table.

Reported in:
https://supportheroes.telerik.com/ticket/1466084

* **Kendo UI version:** 2020.2.513

**Comment by GaloisGirl** [comment]
Same when initialized from unordered list tag: https://dojo.telerik.com/@GaloisGirl/uGagAhog

**Comment by architech99** [comment]
I ran across this today. I have temporarily locked my applications to 2020.1.406 because this will impact a lot of clients. [Sample Fiddle](https://jsfiddle.net/y0eopqjz/3/) that renders broken interface.

**Comment by dmanova** [comment]
As a workaround, you could try to remove the div tag with the following:
`$("[role='listbox'] > div > *:nth-child(1)").unwrap();`

**Comment by GaloisGirl** [comment]
@dmanova  That helps visually, but breaks the dataItem method.

**Comment by gh5692** [comment]
The new _div.k-listview-content_ also causes existing Sortable components referencing their parent ListViews to break.

**Comment by ag-petrov** [comment]
We can not remove the added element however we will expose a setting that can alter its type from div to table or list. That way if you initialize the listview over a div you should be able to render inside it a list ot table correctly.

As for last commend @gh5692 can you provide us with a sample?

**Comment by architech99** [comment]
@ag-petrov Is that container that you're adding being used internally for something? It seems strange that it can't be removed and adding something arbitrary like breaks a lot of reusability (clearly).

I'm not sure that the setting will really help. Take the following scenario as an example. I create the basic table wrapper for my listview and then call the kendoListView() method on the tbody. I have my templates all set up with table rows (tr) so it renders fine (in 2020.1.406). Example:

```
<table>
<thead>
<tr>
<th>Column 1</th>
<th>Column 2</th>
</thead>
<tbody id="my-listview">
</tbody>
</table>

<script>
$("#my-listview").kendoListView({
  template: '<tr><td>data 1</td><td>data 2</td></tr>',
  data: [
    { property1: "data", property2: "data" },
    { property1: "data", property2: "data" }
  ]
});
</script>
```

If I'm understanding your comment correctly, you're saying we'll have a setting where we can specify what the nested tag is. The problem I see is, in my scenario, you're still adding something that will result in output like:

```
<table>
<thead>
<tr>
<th>Column 1</th>
<th>Column 2</th>
</thead>
<tbody id="my-listview">
**<table>**
<tr><td>data 1</td><td>data 2</td></tr>
<tr><td>data 1</td><td>data 2</td></tr>
**</table>**
</tbody>
</table>
```

That setting will still break the solution. And I suspect it will still cause similar issues if I use a flex row such as you find in Bootstrap.

```
<div id="my-listview" class="row">
</div>
```

Binding that with a template like `<div class="col-6">Data block</div>` will still result in a visually-broken interface.

```
<div id="my-listview" class="row">
<div>
<div class="col-6">Data block</div>
<div class="col-6">Data block</div>
</div>
</div>
```

So, while I appreciate the added change, I don't believe it actually solves the problem.

Obviously, I haven't seen the setting and how its being implemented, so I'd love to hear how it will actually solve the problem but based on my understanding of your explanation as provided so far, I'm skeptical.

**Comment by joneff** [comment]
@architech99 separation of the content is part of a bigger effort: the idea is to have header template, footer template, as well as various forms of layout be it flex, grid, or left to the individual developer to decide. We want to provide additional features like grouping for certain scenarios, predefined configuration for borders, custom layouts, etc.

That's we need a wrapper around the actual items that can control those.

Being iterative process, we first released the styles and the content separation, which caused some frustration in developers such as yourself. To solve the issues presented, we added contentElement, which solves most, but not all issues. For instance, it doesn't solve the issues you are having.

What we could do is to allow empty content element. However, that would require some refactoring and some configuration validation. For instance, if no content element is provided (empty string), then the layout of the listview can only be "default" and there can not be header and footer templates. Would that make sense?

Considering javascript is not a strongly typed language, we can not throw exceptions in compile time. However, if there is invalid combination of properties, we should throw errors, right? I mean, we could try and fail, to "resolve" the combination of properties to something that makes sense, but that might be a bit tricky...

We want to find the right transition path between what the component is now and how you and other developers want to use it, to the features we want it to have and your feedback will be highly appreciated.

And because it got quite lengthy I will recap:

* we'll work on `contentElement: ""` and deliver it as soon as possible
* we'll probably make `contentElement` empty by default
* if the content element is empty, a certain set of the new features will not work, like setting the layout to grid / flex
* the same will apply to header and footer templates, once they are implemented: without a content element, there can't be header / footer template

Does the above make sense?

**Comment by ag-petrov** [comment]
I totally agree with @joneff , providing us with feedback will indeed allows us to get a better understanding in what direction to move forward.

One other thing, the idea is that the ListView will in future be a more functionality rich component as we will drive new features into it. For really simple scenarios like rendering rows one can use the kendo.render as shown in [this ](https://demos.telerik.com/kendo-ui/datasource/index)demo.

**Comment by architech99** [comment]
@joneff Thanks for the explanation. It does make sense and the empty `contentElement` property seems like it would solve the problem. I'm used to troubleshooting Kendo UI component rendering using my dev console, so I don't see throwing an error when there's an invalid combination of properties as an issue - as long as the error message makes sense and gives some kind of indicator of which properties are in conflict. 

The only real comment/concern I would have regarding the header/footer template approach is that it comes as a step back to me and generally makes things more difficult for companies where designers and developers have any separation of duties. I'm primarily a back-end developer but also a small company and don't have a dedicated designer, so I look to UI libraries to fill in the gaps. One of the main reasons I started using the ListView so much was because of the flexibility it provided regardless of the CSS/UI framework I used. I could fully-define a structure with starting and closing tags in a single file which keeps it simple when working with a front-end designer (which I'll hopefully add at some point). 

The header/footer approach tends to require you to start a component (i.e. a table) in one spot and put the closing tag for it somewhere else. It breaks validation in most IDEs and generally causes headaches for UI/UX teams to have a pass. The header/footer is something that's been around for over 20 years and, in practice, has caused the teams I've been a part of more headaches. Our preference has always been to create fully-defined elements with templates.

So, if the `contentElement` determined only the wrapper tags and header could contain a fully-defined `thead` (both starting and closing tags), the footer template could contain a fully-defined `tfoot`, and there was a way to somehow define the row template to be wrapped in a proper `tbody`, I can see this as being a solution. My brain is telling me that I would still need the `tbody` to start at the bottom of the header template and be closed at the top of the footer template.

@ag-petrov I glanced at the demo link and that's one I had not seen before. I'll dig into it some more next week as it may address the issues I mention above.

**Comment by joneff** [comment]
@architech99 you make some great points there. Allow me to address some of the concerns you have:

* on the errors: perfect. we try to minimize "production" level warnings / errors to minimum, but still, sometimes it's required
* by default, with empty content element implemented, you will have the same behaviour, as in prior the change, so it won't really be a step back, if you don't use it. 

Considering the introduction of empty content element will actually revert the listview to the previous way it was. In that respect, we can treat the listview as a blank slate and see what we can achieve with it **if** you set additional settings.

The next part is a bit "what if".

Let's look at a different UI framework, one that is quite mature and with a different set of components. Namely ASP.NET WebForms. (DISCLAIMER:  The current state of the kendo-jquery-listview (after the empty content element) would be more akin to a [Repeater](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.repeater?view=netframework-4.8) component than a [ListView](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.listview?view=netframework-4.8) component.

So let's examine the following snippets:

```html
<table>
    <thead>
        <!-- custom user defined -->
    </thead>
    <!-- actually, tfoot element needs to be after thead... -->
    <tfoot>
        <!-- custom user defined -->
    </tfoot>
    <tbody id="listview">
        <!-- items go here -->
    </tbody>
</table>

<table id="listview">
    <thead data-something="header">
        <!-- header template will go here -->
    </thead>
    <!-- actually, tfoot element needs to be after thead... -->
    <tfoot data-something="footer">
        <!-- footer template will go here -->
    </tfoot>
    <tbody data-something="content">
        <!-- items go here -->
    </tbody>
</table>
```

The first case is what you would normally have: you don't set any additional settings so things go on as planned; contentElement is empty and so on and so forth.

The second case is a bit more interesting: using `data-` attributes you could specify which part of the snippet is going to be the actual header, footer and content of the listview, a lot like `LayoutTemplate` in web forms ListView component. Note that would happen automatically: those attributes need to be set. The way the logic may work is:

* look for a `data-something="content"` element
* if found, use it;
* if not, check if the contentElement equals empty string
* ...

Another approach might be to specify additional values for the `layout` property, say `table`. Knowing this, we may render the header / footer template in `thead` / `tfoot` elements respectively. Again, none of this would happen automatically.

The goal, as @ag-petrov  mentioned, is to make the listview more powerful than a mere Repeater. Say you want to do that:

![image](https://user-images.githubusercontent.com/8048/90565588-d35f8380-e1af-11ea-837b-cecba0f2f768.png)

Sure, this can be done with Bootstrap or similar frameworks, but you need to resort to third party markup. Or, it could be something like:

```js
// Assuming
// <div id="listview"></div>

$("#listview").kendoListview({
    header: {
        template: "header template",
    },
    footer: {
        template: "footer template",
    },
    template: "#= item.text",
    aPropThatRendersBuiltInItemElement: true,
    layout: "flex",
    borders: "all"
});
```

But that's just a "what if" part. Considering our last improvement caused more issues than it solved, we'll consider carefully what improvements we add next.

**Comment by architech99** [comment]
@joneff Thanks for the additional detail. I like the flexibility I'm seeing in the example table snippets - using a data attribute to map something to the header/footer/item template. That's one thing I've liked about implementing Bootstrap's UI components - I can have the render settings be part of the markup.

The last "what if" scenario you gave, though, seems like it would run into similar issues. Using your example, the `layout` property is set to `flex` which could lead to style duplication (thus, a larger site payload) unless Kendo UI is somehow aware of a style library it's supposed to use (off the top of my head, I don't remember if there's both a kendo-bootstrap javascript file and a style sheet or if there's just the style sheet for the theme). I'm less enthused about the what-if scenario than the two examples you provided earlier. Extrapolating on that and getting away from the table example (which is admittedly specific), something like:

```
<div id="listview" class="row">
  <div data-content="header"><div class="col-12"><h1>My List</h1></div></div>
  <div data-content="footer"><div class=col-12"><p>Data provided by an API</p></div></div>
  <div data-content="item"><div class="col-4">#= item.text #</div></div>
</div>
``` 

That's obviously another Bootstrap-based example, but you could easily replace the class names with Tailwind or Foundation styles. I like this approach overall. Right now, I currently inject a bunch of partials that include a template wrapped in a `script` tag with the `type` attribute set as `application/x-kendo-template` and use those. This would actually simplify that approach.

**Comment by gh5692** [comment]
@ag-petrov 

I've taken the example from https://docs.telerik.com/kendo-ui/controls/interactivity/sortable/how-to/multiple-items-reordering and altered it to show the breaking change when using a sortable. Please see https://dojo.telerik.com/@so3678/IfOFUjOd

Notice when using a version of 2020 R2 all of the items from the ListView are included in the drag operation. Prior to the 2020 R2 versions only one item, as expected, is included in the drag.

I've already patched existing code to handle the change so I agree with not removing the added element.

**Comment by dmanova** [comment]
To summarize a little bit:

-  If you need to remove the new wrapper tag `<div class="k-listview-content">` could achieve it with new Listview property, with empty string value  `contentElement: ""` 

**Note**: Removing the tag will remove the class and hence some style changes are possible. So you may need to specify additionally for the listview style to be `display: block;` for example.

- If needed another tag container, e.g. `< table ...>` could be specified again with the property  `contentElement: "table"`
