### ISSUE TITLE
Strongly typed mvvm bindings via data-type attribute not working

### ISSUE THREAD

**Issue by frankhuiskamp** [telerik/kendo-ui-core#599]
The example on http://docs.telerik.com/kendo-ui/framework/mvvm/bindings/checked#strongly-typed-checked-binding verifies that all values are still strings.

**Comment by tapopov** [comment]
@frankhuiskamp, the strongly typed bindings will be included in the next official release. The documentation was updated because the feature is now available fore preview in the Q1 2015 Beta. Check demos [here](http://demos.telerik.com/kendo-ui/Beta/mvvm/types) and [here](http://dojo.telerik.com/@popov/OJAWo).
