### ISSUE TITLE
Scheduler does not export background color with specific LESS themes.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6039]
### Bug report

Exporting the Scheduler to PDF through the drawing api does not apply the background color for themes with dark background - kendo.black, kendo.moonlight, kendo.highcontrast etc.

### Reproduction of the problem

[Open this Dojo](https://dojo.telerik.com/@martin.tabakov@progress.com/OWODUTAk/2) with any of the below themes:
- kendo.black.min.css
- kendo.moonlight.min.css
- kendo.highcontrast.min.css
- kendo.materialblack.min.css
- kendo.metroblack.min.css

### Current behavior

The theme-specific background color is not applied and the content is not readable.

### Expected/desired behavior
The background color should be exported as well.

### Environment

* **Kendo UI version:** 2020.3.915
* **Browser:** [all]

**Comment by Juveniel** [comment]
The reason why the theme background is not exported in this case is because the Drawing API is configured to target the "#scheduler .k-scheduler-content":
```js
 drawing.drawDOM("#scheduler .k-scheduler-content", { ... })
```
However, the background color is actually applied to the wrapper of the Scheduler wrapper element. Therefore, targeting the wrapper of the Scheduler will successfully export the widget background color:
```js
 drawing.drawDOM("#scheduler", { ... })
```

To prevent the Toolbar from being exported, the `.k-pdf-export` class can be utilized as explained in [the Customizing Appearance article](https://docs.telerik.com/kendo-ui/framework/drawing/pdf-output/custom-appearance).

[Dojo example](https://dojo.telerik.com/afOrilEh/2) where the above is demonstrated.

Taking the above into consideration, I am closing the issue.
