### ISSUE TITLE
resizing a window from the top (with kendo.bootstrap-v4.min.css included) reduces its size

### ISSUE THREAD

**Issue by alhuber1502** [telerik/kendo-ui-core#6061]
There's a write-up of the issue here (2013), which is still observable in the latest version:

https://stackoverflow.com/questions/15100620/kendo-window-jumps-on-drag-and-resize

**Comment by Dimitar-Goshev** [comment]
@alhuber1502 Following the steps from the thread above, the issue is not reproducible on my side in Chrome - https://dojo.telerik.com/@Dimitar-Goshev/isuhEwAW

**Comment by alhuber1502** [comment]
Hi! Thanks for your quick response.  I did some more digging, and it actually seems to be a problem with kendo.bootstrap-v4.min.css !

If you add

    <link href="https://kendo.cdn.telerik.com/2020.3.915/styles/kendo.bootstrap-v4.min.css" rel="stylesheet">

at the bottom of the <head> and then try resizing the window from the top, you can see the effect: the window shrinks about 50px every time you try and resize.

**Comment by alhuber1502** [comment]
Hi! Thanks for your quick response.  I did some more digging, and it actually seems to be a problem with kendo.bootstrap-v4.min.css !

If you add

    <link href="https://kendo.cdn.telerik.com/2020.3.915/styles/kendo.bootstrap-v4.min.css" rel="stylesheet">

at the bottom of the <head> and then try resizing the window from the top, you can see the effect: the window shrinks about 50px every time you try and resize.

**Comment by Dimitar-Goshev** [comment]
@alhuber1502 Thank you for isolating it further. Since the issue is related to our SASS themes, I opened an issue in the respective https://github.com/telerik/kendo-themes/issues/2001 repository.

As a side note, just to make sure there are no misunderstanding, when SASS themes are used, their reference should be used instead of all the references to LESS based themes. And it should be placed above the js files references - [Dojo example](https://dojo.telerik.com/@Dimitar-Goshev/uFesUNuc)
