### ISSUE TITLE
File with apostrophe(') in its filename cannot be uploaded using chunk upload

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6078]
### Bug report
When we have a scenario with the Upload component configured with a chunk upload configuration, we cannot upload a file that contains an apostrophe in its name. 
  
* The reported issue is not reproducing when the Upload is used inside a form or when it is configured to work in Asynchronous mode. 
* The reported issue is also no reproducing when we try to upload a file that contains the ( ` ) symbol. It is replicated only when the apostrophe is in the filename

### Reproduction of the problem
1. Open [this demo](https://demos.telerik.com/kendo-ui/upload/chunkupload)
2. Upload the Dr's notes.pdf file from the below archive
[TestFiles.zip](https://github.com/telerik/kendo-ui-core/files/5385824/TestFiles.zip)

### Current behavior
The selected for upload file is not being uploaded. 

** If the above scenario is tested in an MVC project, the error returned from the server is "A potentially dangerous Request.Form value was detected from the client". Below you will find a test project:
[ChunkUpload.zip](https://github.com/telerik/kendo-ui-core/files/5385912/ChunkUpload.zip)

### Expected/desired behavior
The files selected for upload should not have any issues with their uploading, no matter if there is an apostrophe in their name or not.

### Environment

* **Kendo UI version:** 2020.3.915
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Juveniel** [comment]
The issue is a result of failed request validation performed by the MVC default request validation. 

With the Chunk Upload, additional meta data is being sent to the remote service. Thus, the default MVC request validation is triggered and fails for html entities contained in it (in this case the apostrophe). Note: the request validatio will also fail even if the apostrophe is encoded.

Taking the above into consideration, this issue is related to the application scenario, rather than a bug in the Upload functionality. That being said, per application scenario, skipping the request validation can be implemented by decorating the save end-point with the following attribute([ref](https://stackoverflow.com/questions/81991/a-potentially-dangerous-request-form-value-was-detected-from-the-client)):

```cs
[HttpPost, ValidateInput(false)]
public ActionResult Chunk_Upload_Save(IEnumerable<HttpPostedFileBase> files, string metaData)
{
}
```

**Comment by GedraCom** [comment]
In a serious production environment, it is not acceptable disable the protection mechanisms that the framework provides. 
For now, I will fix it with the workaround of putting a client event handler in this way:
```
 kendo.uploadOnSelect = function (e) {
        e.files.forEach(f => {
            f.name = f.name.replaceAll("&#39;", "'");
        });
}
```

**Comment by DoomerDGR8** [comment]
> In a serious production environment, it is not acceptable disable the protection mechanisms that the framework provides. For now, I will fix it with the workaround of putting a client event handler in this way:
> 
> ```
>  kendo.uploadOnSelect = function (e) {
>         e.files.forEach(f => {
>             f.name = f.name.replaceAll("&#39;", "'");
>         });
> }
> ```

Doesn't work for me. I can conform he JS code is executed but no upload takes place
