### ISSUE TITLE
Dropdownlist: Support for removing autofocus of filter text input.

### ISSUE THREAD

**Issue by bhuvangoradia** [telerik/kendo-ui-core#611]
In iPads and most tablets, if a text input has focus it will bring up the system keyboard. This is what happens when you open the dropdownlist, because the filter input has focus. This is not ideal since the user would want to filter only in cases when they cannot find the item to be selected. 

I tried to use jquery to remove focus during the open event in a way similar to #229. This however just keeps on closing the list. I have created a plunker <a href="http://plnkr.co/edit/xZufGmhQMVPBn2WWIH0L">here </a>

Thanks.

**Comment by ggkrustev** [comment]
The suggestion makes sense. We will further investigate the case and will try to improve current mobile behavior of dropdownlist.

**Comment by ggkrustev** [comment]
Related to #411

**Comment by IlBaffo** [comment]
Hi, we leveraged on this behaviour for our project and our client expects the keyboard to appear when he taps on the dropdownlist from iOS.

We choose the dropdownlist because it is like an autocomplete (or combobox) but forces you to choose an element from the list and no other widget could enforce this.
We tried to override the 'open' function globally but this is not working as expected and could potentially be broken in future updates.

Could it be possible to have a config option to turn back on this funcion like 'data-filter-autofocus=true' or is there any workaround for a fast fix?

Thank you.

**Comment by ggkrustev** [comment]
Hello @IlBaffo,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!

**Comment by IlBaffo** [comment]
Hu @ggkrustev , now I have to tell to my customer that, after upgrading to a new release to fix some bugs, they have got a feature removed...
Since we subscribed Kendo UI Professional, we expected some degree of backward compatibility even for the *Core features or, at least, some way to work around the new behaviour.

**Comment by ggkrustev** [comment]
Hi @IlBaffo,

This enhancement is actually a **bug fix**, as it was reported numerous times in our ticketing system.  We marked it as an enhancement here, as it improves the behavior of the widget. Another important fact is that no other focusable Kendo UI widget opens the keyboard on popup open (e.g. combobox). That is why we consider the old behavior as erroneous and it was fixed in last release.

If you would like to revert the old behavior, then you can easily accomplish this task focusing the [filterInput](http://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#fields-filterInput) on [open](http://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#events-open):
```javascript
function ddl_open() {
  if (this.filterInput) {
      this.filterInput.focus();
  }
}
```

If you would like to include this functionality as a `configuration`, then please post your request in our feedback portal. Thus we can evaluate the community interest and determine its priority

**Comment by IlBaffo** [comment]
Hi @ggkrustev this is exactly what I tried but it doesn't seem to work on iOS Safari (8.1), probably because the focus() method is not called directly from within a click event handler and thus is ignored by the browser.
This seems to be a change made from iOS 7 to iOS 8.

From the source code I can see that the click event on the select triggers an animation on the popup then, the "activate" event is triggered on the popup and the the focus() is called on the control.
This cannot work in iOS 8 because the "activate" event in the chain is not directly triggered by the "click" DOM event but probably (correct me if I'm wrong) from a setTimeout handler.
