### ISSUE TITLE
Editor - two new lines are create on pressing Shift + Enter keys

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6159]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/IYIqAZUn) example. Video available in ticket id: 1496525 (first post).

1. Click at the end of line2 in paragraph1
2. Press Enter
3. Type in some text, e.g., "paragraph2"
4. Press Shift + Enter

### Current behavior
Two new lines are created instead of one.

### Expected/desired behavior
One new line is created.

### Environment

* **Kendo UI version:** 2020.3.1118
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mparvanov** [comment]
1. Click at the end of line2 in paragraph1
1. Press Shift + Enter
A new line is not created

**Comment by Dimitar-Goshev** [comment]
The fix for this issue causes a JS error `Object doesn't support property or method 'remove'` in IE in the following scenario:
1. Go to https://demos.telerik.com/kendo-ui/editor/immutable-elements?autoRun=true&theme=default
2. Click after the end of the paragraph _Lorem ipsum_ (after _id facilisis._) OR Click after the end of the paragraph _Aenean lacinia_ (after _interdum ex._)
3. Press Shift + Enter
Error - Object doesn't support property or method 'remove' is thrown by linebreak.js
```
if(!!br.nextSibling && dom.isWhitespace(br.nextSibling)) {
  br.nextSibling.remove();
}
```
