### ISSUE TITLE
FileManager navigate method throws an error when navigating to a subfolder 

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#6207]
### Bug report

When using the navigate method to open a subfolder the following error is thrown:
"Uncaught TypeError: Cannot read property 'loaded' of undefined"

[FileManager_SubFolder.zip](https://github.com/telerik/kendo-ui-core/files/5741832/FileManager_SubFolder.zip)

### Reproduction of the problem
1. Navigate to https://demos.telerik.com/kendo-ui/filemanager/index
2. Create a "NestedFolder" under "Images" folder
3. Reload the page and call navigate method to the New Folder:

```
var fileManager = $("#filemanager").data("kendoFileManager");
            fileManager.navigate("Images/NestedFolder");
```

### Current behavior
"Uncaught TypeError: Cannot read property 'loaded' of undefined"

### Expected/desired behavior
The navigation to "NestedFolder" is successful and no errors are thrown:

The navigation is successful in case calling the navigate method for the folder and subfolder consequently:

```
var fileManager = $("#filemanager").data("kendoFileManager");
            fileManager.navigate("Images");
            setTimeout(function () { fileManager.navigate("Images/NestedFolder"); }, 200);
```
### Environment

* **Kendo UI version:** 2020.3.1118

Public itemL
https://feedback.telerik.com/kendo-jquery-ui/1500317-filemanager-navigate-method-throws-an-error-when-navigating-to-a-subfolder

**Comment by veselints** [comment]
The failure to navigate to a subfolder of a folder which contents has not been loaded yet is expected. That is because the FileManager DataSource is a Hierarchical DS that is loaded on demand. Each node (folder) content is loaded only when navigation to that folder occurs, or when it has been expanded in the TreeView section of the FileManager. Before that, the content of a folder (in the above example `Images`) is not present on the client. Hence, the navigation would not be successful as the FileManager DS does not even know about the existence of a folder called `NestedFolder`.

If there is a need to navigate to nested folders that are not part of already loaded folders, that should be logged as a Feature request instead of a bug.

Apart from the above, the `navigate()` method logic should not throw a JS error on the console. That is the issue to be fixed.

**Comment by veselints** [comment]
In order to properly load a nested folder, all its parent folders should already be loaded. To do that, one could follow the below logic:
```js
var fileManager = $("#filemanager").data("kendoFileManager");
var parentFolder = fileManager.dataSource.get("Documents");

if(!parentFolder.loaded()) {
    parentFolder.load().then(function() {
        fileManager.navigate("Images/NestedFolder"); 
    });
} else {
    fileManager.navigate("Images/NestedFolder"); 
}
```

**Comment by Juveniel** [comment]
After the fix, it is no longer possible to navigate to the root through the Breadcrumb, as no entry is being found.

@veselints, @mparvanov
