### ISSUE TITLE
Chart animation is not displayed when it is initialized in a Splitter

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6260]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/@sspasova/ewiqonAT) example.
1. Run the example

### Current behavior
The Chart's animation does not work when it is nested in the Splitter. 

### Expected/desired behavior
The Chart's animation should work.

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by pepinho24** [comment]
The problem is a timing issue in initialization of the components. As the script that initializes the chart is executed outside a document.ready, it is interrupted by the initialization of the splitters. 

The solution is to initialize the Chart after the Splitter is initialized: 
- https://dojo.telerik.com/uaupjuBI/3
