### ISSUE TITLE
Memory leak when destroying and recreating a drop-down widget multiple times

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6267]
### Bug report
That applies to multiple drop-down widgets (DropDownList, ComboBox and MultiSelect). It is not tested with MultiColumnComboBox and DropDownTree.

### Reproduction of the problem
* Run the following dojo: https://runner.telerik.io/fullscreen/iDaBUdeY/9
* In Chrome open DevTools Performance tab and start recording
* Click the button
* Observe the console. After the logs have finished, stop the recording
* Note the JS memory heap usage at the beginning and the end of the recording (+ 4 MB). Note also the number of nodes (+ 35 000 nodes).

### Expected/desired behavior
The JS heap usage should not augment, there should be no new elements.

### Environment
* **Kendo UI version:** 2021.1.119
* **Browser:** [all]

**Comment by Iankodj** [comment]
Memory leak is not observed when Dojo is corrected so that the proper elements are destroyed and removed: http://dojo.telerik.com/eyIbOpoF. 

Also, garbage collection should be manually triggered after starting and before stoping the profiling: 

![image](https://user-images.githubusercontent.com/4222379/121007983-233d2480-c79b-11eb-8091-8fa4943450e0.png)
