### ISSUE TITLE
TimePicker does not scroll to selected value

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#6276]
### Bug report

Timepicker does not scroll to selected value. For more information and a sample refer to ticked with id 1505670.

### Environment

* **Kendo UI version:** 202x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gyankov** [comment]
The issue seems to be caused by the SASS themes. When using a LESS theme the k-list ul overflow its parent, thus the scroll appears to the parent div, which is the expected behavior.

@PreslavKozovski  could you please look into this?

**Comment by PreslavKozovski** [comment]
Based on my tests, I think that the issue is caused by a new behavior of the JavaScript that sets `display: flex;` to the `k-list-container k-list-scroller` element.

I believe that assigning `display: flex;` to this element with JS is the correct behavior as it is `flex` from the CSS. However, this breaks the logic of the overflowing child element which we use for the scrolling.

For the tests, I used the following Dojos:
https://dojo.telerik.com/EQIJacOK - 2021.1.119
https://dojo.telerik.com/usezafIW - 2019.3.917
https://dojo.telerik.com/ibuYijAF - 2021.1.119 (styles) & 2019.3.917 (JS)

**Comment by gyankov** [comment]
The issue appears to be related to the following commit:

- https://github.com/telerik/kendo-themes/commit/f7abe08f9c44282bf0af80bf2d8448ee5816bf01

Once I override the display setting of the k-popup class, the issue does not seem to reproduce:

-  https://dojo.telerik.com/EQIJacOK/4

**Comment by dmanova** [comment]
Notes from internal testing: The scrolling is affecting the containing element as when used in Kendo demo pages. Also, pay attention to the keyboard navigation.
