### ISSUE TITLE
PDFViewer shows empty print preview in Edge

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6336]
### Bug report

PDFViewer shows an empty print preview after refreshing the page. 

### Reproduction of the problem
[KendoPdfViewerTest (2).zip](https://github.com/telerik/kendo-ui-core/files/6173391/KendoPdfViewerTest.2.zip)

1. Open the attached page in Edge (not reproducible in the demos)
2. Open the Print Dialog => The Print preview is visible
3. Press F5 (or click the refresh icon, without clearing the cache)
4. Open the Print Dialog again => The Print preview is empty 

Comment: If you press Ctrl + F5 and open the Print dialog, the preview will be visible again.

### Current behavior
PDFViewer shows empty print preview in Edge ([screencast](https://screencast-o-matic.com/watch/creqFQVVVyW))

### Expected/desired behavior
PDFViewer should preview the loaded file.

### Environment

* **Kendo UI version:** 2021.1.224
* **Browser:** [Edge]

**Comment by caseydierking** [comment]
Is there any plan to move forward on this bug? This is an issue with Chrome as well. This seems like a critical bug to me.

**Comment by cb2bdaniel** [comment]
I'm really looking forward to this issue being resolved, it's been reported since March this year and has been a bug in the last few releases. I'm hoping the Telerik team can prioritise resolving this bug. I'm disappointed to see that there isn't even a timeline indication and no progress yet. Fingers crossed!
