### ISSUE TITLE
ConnectionTemplateName not working in MVC

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#6347]
### Bug report

When using ConnectionTemplateName in MVC the template editors are not bound to the values. More information can be found in ticket - 1511633

### Current behavior
The template editors are not populated with values

### Expected/desired behavior
The editors should get populated

**Comment by gyankov** [comment]
Internally the connectionsDataSource maps the items to [connection](https://docs.telerik.com/kendo-ui/api/javascript/dataviz/diagram/connection) objects using the model.from syntax.

e.g.
```
"from": {
    "from": "FromShapeId",
    "type": "number",
    "defaultValue": null
},
"to": {
    "from": "ToShapeId",
    "type": "number",
    "defaultValue": null
},
"text": {
    "from": "Text",
    "editable": false,
    "type": "string"
},
"fromX": {
    "from": "FromPointX",
    "type": "number",
    "defaultValue": null
},
"fromY": {
    "from": "FromPointY",
    "type": "number",
    "defaultValue": null
},
"toX": {
    "from": "ToPointX",
    "type": "number",
    "defaultValue": null
},
"toY": {
    "from": "ToPointY",
    "type": "number",
    "defaultValue": null
}
```

As a result the client side connection model differs from the server model, thus, their field names might be different and the editor binding will fail.

There are two solutions, either use the Html.TextBox instead of HtmlTextBoxFor:

```
            <div class="form-group">
                @Html.Label("from", "FromShapeId", new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8 col-md-6">
                    @Html.TextBox("from", null, new { @class = "form-control" })
                    @Html.ValidationMessage("from", null, new { @class = "text-danger" })
                </div>
            </div>
```
Or modify the field names of the server side model to match the connection's model field names.

e.g.

```
 public Nullable<int> from{ get; set; }
```
