### ISSUE TITLE
Group paging does not work correctly when groups count is less than page size

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#6348]
### Bug report

When the number of groups is less than the page size count the grid does not display the entire set of groups, Reported in ticket - 1512639

### Reproduction of the problem
Run this dojo - https://dojo.telerik.com/@efb@qad.com/eCizuraT

### Current behavior
Only a subset of the groups is displayed

### Expected/desired behavior
All the groups should be displayed

### Environment

* **Kendo UI version:** 2022.3.915
* **Browser:** [all]

**Comment by StoyanGoranov** [comment]
Also reported in 1586580
Reproducible since 2020.3.915
https://dojo.telerik.com/@Stoyan/ejAfAHAk

**Comment by StoyanGoranov** [comment]
Reported in 1623001 as well.

**Comment by niwred** [comment]
In my tests, the problem showed up only when the page size was greater than number of groups but less than double the number of groups. The number of groups shown is PageSize - number of groups that should show. Example: Grouping results in 35 groups and Page Size is 50,  15 instead of 35 groups are shown. If the PageSize is 80 (> 70) the problem does not show up, all 35 groups are shown.
