### ISSUE TITLE
The text in disabled ComboBox is not selected properly

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6359]
### Bug report

When a ComboBox is disabled, if the user tries to select the value by double click, additional new line is added to the selection

### Reproduction of the problem
1. Open the [Api ComboBoxDemo](https://demos.telerik.com/kendo-ui/combobox/api)
2. Select an item
3. Click on the 'Disable' button
4. Double click in the ComboBox to select the value
5. Paste it 

### Current behavior
In the Demos a new line is added before the value of the ComboBox. When the same Demo is opened in a Dojo, a part from the text above the ComboBox is also highlighted. ([screencast](https://www.screencast.com/t/pp6fmHaWyRXz))

### Expected/desired behavior
Only the text in ComboBox should be selected even if the widget is disabled.

### Workaround
The element holding the down arrow icon could be hidden when the ComboBox is disabled. - [Dojo](https://dojo.telerik.com/@NeliKondova/uLItIHoh)

### Environment

* **Kendo UI version:** 2020.1.330
* **Browser:** [all  ]

**Comment by nelito987** [comment]
Could no longer reproduce the bug.

**Comment by Dimitar-Goshev** [comment]
This seems as a browser issue that is not reproducible anymore with Chrome 103 even with the workaround Dojo after removing the mentioned workaround for hiding the arrow button - https://dojo.telerik.com/@Dimitar-Goshev/ofeSELiT
And in Firefox 103 it is not even possible to select the text of a disabled input. The issue is not reproducible on the API demo as well.
