### ISSUE TITLE
TextArea takes its value from different DOM element with the same name

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#6367]
### Bug report

On the Kendo MVC demo site is visible that the TextArea has the same value as the "Description" text.
It seems the reason is that there is a DOM element with the same attribute `name="description"`:

< meta name="description" content="This example demonstrates the ASP.NET MVC TextArea Floating Label." >
and
< textarea id="description" name="description" data-role="textarea" aria-disabled="false" rows="5" class="k-input" autocomplete="off" style="width: 100%; resize: none;" spellcheck="false" >< /textarea >

### Reproduction of the problem
https://demos.telerik.com/aspnet-mvc/textarea/floating-label
![image](https://user-images.githubusercontent.com/52446546/113984817-2cba1700-9854-11eb-9681-e759d5b59991.png)

### Current behavior
_(optional)_
The TextArea has the wrong value from another DOM element.

### Expected/desired behavior
The TextArea has no value.

### Environment

* **Kendo UI version:** 2021.1.330
* **Browser:** [all]

**Comment by dmanova** [comment]
Seems related to https://github.com/telerik/kendo-ui-core/issues/6326

**Comment by gyankov** [comment]
Not a bug. The behavior is specific to our demos application as we store the description of each demo within the ViewBag under the "description" key which happens to match the name of the widget in the referenced demo. Thus, when retrieving the value of the widget through the modelState, we get the demo's description due to their names/keys being identical.

To avoid this, we can simply change the name of the widget in the demo. @VicTachev
