### ISSUE TITLE
ImageEditor throws JavaScript error on reselecting Original Ratio for portrait images

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6453]
### Bug report

The ImageEditor throws a JavaScript error on reselecting Original Ratio for portrait images

### Reproduction of the problem
Open the [ImageEditor Demo](https://demos.telerik.com/kendo-ui/imageeditor/index)

1. Load a Portrait image (Width < Height) (sample image: [Portrait format image](https://user-images.githubusercontent.com/46348689/122025383-02478580-cdd2-11eb-983b-f99ec3e52e8e.png))
2. Select the Crop tool
3. Click on Landscape
4. Select any aspect ratio, for example 16:9
5. Select "Original ratio" back again

### Current behavior
JavaScript error is thrown

### Expected/desired behavior
JavaScript error should not be thrown
### Environment

* **Kendo UI version:** 2021.2.511
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The fix resolves the issue. Upon testing I found another scenario, which may be improved.
1. Load a Portrait image (Width < Height) (sample image: Portrait format image)
2. Select the Crop tool - Aspect ratio is "Original ratio", Orientation is Portrait and the resize frame covers the whole image
3. Click on Landscape - Resize frame becomes landscape
4. Select any aspect ratio, for example 16:9 - Resize frame remains landscape
5. Select "Original ratio" back again - the resize frame covers the whole image as on step 2, but the Orientation button incorrectly shows Landscape selected, instead of Portrait.

**Comment by Iankodj** [comment]
@Dimitar-Goshev Commit https://github.com/telerik/kendo/commit/0513a91408e46bd0d92ebca7eba9b28a61e568fd addresses https://github.com/telerik/kendo-ui-core/issues/6453#issuecomment-864117248
