### ISSUE TITLE
Editor Templates cannot be rendered with strict CSP enabled when using jQuery v3.1.1 or higher 

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6456]
### Bug report

If strict Content-Security-Policy (CSP) mode is enabled and the [guideline on resolving the issue](https://docs.telerik.com/aspnet-core/troubleshoot/troubleshooting-content-security-policy) for ASP.NET Core helpers is followed, using Editor Templates still throws the `Refused to execute inline script because it violates the following Content Security Policy directive:` error  the  if the jQuery version used is 3.1.1. or higher. 

### Reproduction of the problem
1. Run the attached application
2. Click on Edit button
[Sample Application](https://github.com/telerik/kendo-ui-core/files/6670192/TelerikAspNetCoreApp262.zip)

### Current behavior
The `Refused to execute inline script because it violates the following Content Security Policy directive:` error is thrown for the Editor Templates that need to be initialized.

### Expected/desired behavior
The `Refused to execute inline script because it violates the following Content Security Policy directive:` error should not be thrown and Editor Templates should be usable as when using jQuery versions up to 2.2.4

### Environment

* **Kendo UI version:** 2021.2.511
* **jQuery version:** 3.1.1. or higher
* **Browser:** [all]

**Comment by ng-neer** [comment]
We have to use CSP and are currently forced to downgrade to jQuery 2.2.4 with XSS-vulnerabilities, since we already use the "Html-Helpers"-variant implementation everywhere.

Since you mentioned to [drop support for IE11 in R1 2023 release](https://www.telerik.com/blogs/end-internet-explorer-support-telerik-kendo-ui-web-components), does it also mean, you start using latest jQuery (v3.6.x) instead of the IE supported version (v1.12.x) ? Will the fix be in R1 2023?

If not, any news on when it gets fixed?

Do you have maybe a workaround with latest jQuery (v3.6.x) + Html-Helpers variant?

**Comment by ng-neer** [comment]
alright, seems like the new v2023.1.117 did not fix it...
any info on this, guys?

btw, don't know if it helps, but i'm also getting CSP-errors using the jQuery version 3.0.0 and 3.1.0. 
The actual latest compatible jQuery version with Kendo and CSP is **2.2.4**.

**Comment by alestoya** [comment]
Reported in 1606461
