### ISSUE TITLE
Grid column resizing is broken when column width is in percentage and there are hidden columns

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6464]
### Bug report
Reported in: Ticket ID: 1524543. Reproducible in Chrome and Firefox. Not reproducible in Edge
Version 91.0.864.54.

### Reproduction of the problem
Dojo example: [https://dojo.telerik.com/iqUFarUV/3](https://dojo.telerik.com/iqUFarUV/3)
1. Hide half of the columns (uncheck them in the column menu -> Columns)
2. Try to resize a column

### Current behavior
On dragging the handle the column width automatically increases. Then if you try to decrease the width, you can't go past a certain width threshold. 

### Expected/desired behavior
The columns can be resized precisely, similarly to when their width is set in "px" instead of "%".

### Environment

* **Kendo UI version:** 2021.2.616
* **jQuery version:** x.y
* **Browser:** [Chrome 91, Firefox 89]

**Comment by ag-petrov** [comment]
This is actually a limitation caused by the default behavior of the HTML table. When hiding some of the columns and starting to resize one of them initially it stretches to occupy the space left as the other column widtsh are in percents and that column acts as a buffer. As resizing of columns works in pixels one hits a breakpoint where the content is resized to the minimum in values(for example 10px) but the visual appearance of the column is different due to the table stretching the column. Overall mixing such percentages and pixels can not work flawlessly. That said I suggest setting widths in pixels instead of percents.
