### ISSUE TITLE
navigator.userAgent and navigator.platform should be avoided in line of the Chromium deprecation plan

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6579]
- [x] Review `navigator.platform` usage;
- [x] Review `navigator.userAgent` usage;

### Bug report
Current we use in our source code `navigator.userAgent` and `navigator.platform`. Chromium, however, plans to reduce the amount of information available in the User Agent string. Further information could be found here:
https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html

### Reproduction of the problem
Review the source code for the use of  `navigator.userAgent` and `navigator.platform`.

### Expected/desired behavior
Review the use of  `navigator.userAgent` and `navigator.platform` and implement alternative approach to handle scenarios in question.

### Environment
* **Kendo UI version:** 2021.3.914
* **Browser:** [Chrome]

**Comment by veselints** [comment]
After consulting the [User-Agent Reduction guide](https://www.chromium.org/updates/ua-reduction/), I can confirm there is no immediate need to introduce changes to the Kendo source. The usage of `.platform` is only to check for a MAC device. That info will remain as a part of the `.platform` string.

There is some logic relying on the OS version from the `.userString`. Nevertheless, that is applicable for very old OS versions (iOS 7 and Android 2 to 4). With the changes in Chromium, those will be reported to be the latest OS version. That, however, is unlikely to cause issues as practically, there is no usage of such devices:
https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide
https://gs.statcounter.com/ios-version-market-share/mobile-tablet/worldwide

**Comment by Iankodj** [comment]
In general, we should avoid targeting specific device versions within code as they sooner or later become obsolete. For example, I doubt anyone is using Android 2 or 4  anymore. For iOS 7 we might need to check if we can remove such code. 

However, we should definitely update our device detection logic in order to be up to the latest standards. The device detection is not being utilized only internally, but there are clients relying on it. Therefore, it is a vital part of the Kendo UI for jQuery library.
