### ISSUE TITLE
Named Range for merged cells in Kendo Spreadsheet cannot be reused in another column 

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#6631]
### Bug report

Named Range for merged cells in Kendo Spreadsheet cannot be reused in another column 

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem

https://user-images.githubusercontent.com/3043283/142155653-7b0989be-d3fc-4fd8-86b4-707ff44f1b9f.mov

### Current behavior
The value of the reused named range is not set for the new cell

### Expected/desired behavior
The value of the named range should be successfully set.

### Environment

* **Kendo UI version:** 2021.3.1109
* **jQuery version:** x.y* **Browser:** [all]

**Comment by mishoo** [comment]
It behaves like this because merged cells are actually ranges (`H1:I1` in your example), so `=c_text` is equivalent to `=H1:I1`. I do agree it's a bug, but for the time being the formula engine does not take into account that a range might be merged (in which case it should logically return a single value for it). I'll have to check if fixing it doesn't break anything else; in the mean time, a workaround would be to use the `INDEX` function to select the first value, e.g. `=INDEX(c_text, 1, 1)`.

**Comment by nelito987** [comment]
Related To: #5500 (duplicated issue #6163)

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/pull/13871
