### ISSUE TITLE
Kendo UI ColorPicker opacity slider throws error when globalize.js is included

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#671]
Can be reproduced here:
http://dojo.telerik.com/aDUYU/2

**Comment by mishoo** [comment]
Seems it's more generally a Slider issue.  Notice the simple slider here throws the same error: http://dojo.telerik.com/@mishoo/iBOPi

Apparently, the default [tooltip format](https://github.com/telerik/kendo-ui-core/blob/1ff4a2b3313275c780bbb80c79f47dabae189af3/src/kendo.slider.js#L670) is not compatible with Globalize, which is [used by kendo.format by default](https://github.com/telerik/kendo-ui-core/blob/a15bf88e08829e03d0eb490d7303deaf9de0b1e7/src/kendo.core.js#L1060-L1078) if available.

**Comment by mishoo** [comment]
CC @ggkrustev — not sure the issue is really in the Slider or kendo.core.js.

**Comment by ggkrustev** [comment]
Hi guys,
The problem is in the Globalization.js library, as it does not support [custom numeric formats](http://docs.telerik.com/kendo-ui/framework/globalization/numberformatting#custom-numeric-formats). The format "#,#.##" that slider uses will cause the exception.

The only thing that I can suggest is to change the format to "n2", which basically "#,#.##" format does. Let me know if the suggested format does not solve the problem.

**Comment by ggkrustev** [comment]
We removed support for GlobalizeJS in Q1 2016:

http://docs.telerik.com/kendo-ui/backwards-compatibility/2016/2016-backward-compatibility#kendo-ui-2016-q1
