### ISSUE TITLE
CheckChildren option of the DropDownTree doesn't work when the filtering is turned on

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6796]
### Bug report
The **DropDownTree** allows us to configure its [checkChildren ](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/configuration/checkboxes.checkchildren) and [filter ](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/configuration/filter) options. Both options are working correctly, when used separately. 

When the two options are defined for the DropDownTree, the **checkChildren** options don't select the child elements of a given node that is checked. 

### Reproduction of the problem
1. Open [this Dojo example](https://dojo.telerik.com/uCejInIM)
2. Expand the DropDownTree popup
3. Check the "Furniture" node checkbox

### Current behavior
Only the "Furniture" checkbox is being checked

### Expected/desired behavior
The "Furniture" and all of its child nodes should be selected when clicking on the "Furniture" checkbox. 
[Here is a Dojo example](https://dojo.telerik.com/OSuGAJEd) in which the **checkChildren** configuration is working as expected. 

### Environment

* **Kendo UI version:** 2022.1.412
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
"Note: when [filter](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/configuration/filter) is enabled 'checkboxes.checkChildren' property is reset to 'false' because enabling both at the same time could lead to ambiguous scenarios. Currently this scenario is not supported by the widget."
https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/configuration/checkboxes.checkchildren
