### ISSUE TITLE
Dropdownlist with multi-select checkboxes

### ISSUE THREAD

**Issue by dmathisen** [telerik/kendo-ui-core#680]
Regarding [this thread](http://www.telerik.com/forums/multi-select-with-checkboxes-plugin), which went inactive over a year ago...
There were a [few](http://plnkr.co/edit/OVPTCV?p=preview) good [examples](http://jsfiddle.net/8caNL/10/) of working dropdownlists with checkboxes. Unfortunately none of them work in the latest version of Kendo (2015.1.318).

The only [uservoice post](http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/4125610-multiselect-dropdown) I see regarding this was rejected 2 years ago. Using KendoLabs was suggested, but it doesn't look like that's been active in 2 years either.

Are there any plans for this? Anyone that maybe will make a plugin for it?

**Comment by naskog** [comment]
Hi Dan,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests, so I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!

**Comment by dmathisen** [comment]
Will do. Thank you!
