### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by fourlincoln10** [telerik/kendo-ui-core#694]
After downloading a fresh version of kendo-ui-core and running npm build, I received this error msg: 

version not found: i@0.3.2

To fix it I added 

if(data && data.name === "i") { ver = "0.3.3";}

to line 117 of [path]/node_modules/npm/lib/cache/add-named.js

ver 0.3.2. does not appear to be a valid version of i

**Comment by underlog** [comment]
The error suddenly manifested itself yesterday in our Travis build, too. We are yet to figure out what happened, since we did not touch anything.

On Apr 4, 2015, at 11:33 AM, fourlincoln10 <notifications@github.com<mailto:notifications@github.com>> wrote:


After downloading a fresh version of kendo-ui-core and running npm build, I received this error msg:

version not found: i@0.3.2

To fix it I added

if(data && data.name === "i") { ver = "0.3.3";}

to line 117 of [path]/node_modules/npm/lib/cache/add-named.js

ver 0.3.2. does not appear to be a valid version of i

**Comment by underlog** [comment]
This should fix it: https://github.com/telerik/kendo-ui-core/commit/cc79ba5b40d5a0bfaa93fa7bc83c612eda10b67d
