### ISSUE TITLE
Adding multiple new tasks to the Gantt causes the browser to become unresponsive

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6949]
### Reproduction of the problem
Reproducible in the demos (MVC and Core): [https://demos.telerik.com/aspnet-mvc/gantt](https://demos.telerik.com/aspnet-mvc/gantt)
1. Select a task in the Gantt's treelist (e.g., Market Research).
2. Click on the "Add Task" button in the Gantt's toolbar and select "Add child" from the dropdown.
3. Repeat step 2 until the browser becomes unresponsive.  

### Current behavior
The issue seems related to the **_subtree** method in kendo.treelist.js. This number of calls of this method increases with every new task. The time it takes for every next task to be added increases. After adding a few tasks **_subtree** is now called thousands of times every time a new task is added, which results in a Maximum call stack error. 

### Expected/desired behavior
Performance should not degrade when adding new tasks to the Gantt. The browser should remain responsive. 

### Environment

* **Kendo UI version:** 2022.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by gyankov** [comment]
The issue is caused because the `TaskViewModel` has two properties `PlannedStart` and  `PlannedEnd` that refer to fields that are never initialized in the Overview demo. As a result the Gantt always marks these fields as dirty. If you remove these fields from the model and test the demo, the issue won't replicate. 

@IvanDanchev could you please log an issue to fix the demo?
