### ISSUE TITLE
Unexpected space before each listbox item

### ISSUE THREAD

**Issue by kakone** [telerik/kendo-ui-core#6968]
### Bug report

There is a unexpected space before each listbox item.

### Reproduction of the problem
https://dojo.telerik.com/@kakone/ILeBIduR

### Current behavior
The k-list-item-text class seems to be incorrect, there is an empty content before. The problem appears when we set a custom template in the kendoListBox.

### Expected/desired behavior
We don't want this space before each listbox item.

### Environment

* **Kendo UI version:** 2022.2.802
* **jQuery version:** 3.6.0
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
@kakone Since R1 2022 the class for a ListBox item is changed from `.k-item` to `.k-list-item-text` . The [Templates demo](https://demos.telerik.com/kendo-ui/listbox/templates?autoRun=true&theme=bootstrap-main) is not updated according to this change and we will update it as soon as possible.
With 2021.3.1207 before the class name change the ListBox with templates looks as on this Dojo - https://dojo.telerik.com/@Dimitar-Goshev/oRuMuSUb .
With 2022.2.802 the demo with updated classes looks as on this Dojo - https://dojo.telerik.com/@Dimitar-Goshev/apiSUzEC . In both cases there is space between the ListBox left border and the item. This space is due to padding coming from our bootstrap theme.
![image](https://user-images.githubusercontent.com/6614183/183676448-da514ad2-203a-46ee-9fbe-8d5e9d7e73e6.png)

If there used to be no padding-left on your side, it is most probably due to custom CSS rule, which should be updated. The previous selector was
```
.k-list .k-item, .k-list-optionlabel {
    padding: 0.25rem 1rem;
}
```
And the new padding rule selector is
```
.k-list-md .k-list-item, .k-list-md .k-list-optionlabel {
    padding: .25rem 1rem;
}
```

To remove the left padding a custom CSS rule such as the following would be needed:
```
.k-list-md .k-list-item, .k-list-md .k-list-optionlabel {
    padding: .25rem 1rem .25rem 0;
}
```

If you have further questions, please open a support ticket or a forum thread.

**Comment by kakone** [comment]
The problem is not on the left, but above the item. I'm going to open a support ticket.
