### ISSUE TITLE
Widget does not retain radio button checked property

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-ui-core#697]
[Example, including a workaround](http://dojo.telerik.com/@popov/EFuku)

**Comment by valchev** [comment]
The issue occurs because the [defaultPlaceholder](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.sortable.js#L43) and the [defaultHint](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.sortable.js#L39) clone the element that will be moved (including its `name` attribute). 

This results in having two (or three) `radio` inputs with same `name`, `value` and `checked` property which is **not a valid scenario**. According to the specification **at all times, exactly one of the radio buttons in a set is checked**.

The solution is to customize the hint and the placeholder so they will not copy the `name` and `id` attribute of the radio inputs.

        hint: function (element) {
          var hint = element.clone();
          hint.find(":radio").removeAttr("name").removeAttr("id");
          return hint;
        },
        placeholder: function(element) {
            var placeholder = element.clone();
            placeholder.find(":radio").removeAttr("name").removeAttr("id");
            return placeholder;
        }

Here is a working example: http://dojo.telerik.com/ujOJe
