### ISSUE TITLE
ImageBrowser and FileBrowser not position RTL correctly

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-ui-core#6977]
**Describe the bug**
ImageBrowser and FileBrowser breadcrumb and search box not position RTL correctly

**To reproduce**
1. Go to [dojo](https://dojo.telerik.com/@vzsoft/IleSuMAN)
2. See position breadcrumb and search box

**Screenshots**
![rtl2](https://user-images.githubusercontent.com/5305981/184508151-c5d95a39-64c4-4b9c-98b0-9550326df13a.png)

**Affected package**
Kendo UI Theme
* kendo.black
* kendo.blueopal
* kendo.fiori
* kendo.highcontrast
* kendo.metro
* kendo.moonlight

**Affected suites**
* Kendo UI for jQuery

**Affected browsers**
* Firefox 
* Chrome 

**Build system information **
* Windows 10

**Comment by Dimitar-Goshev** [comment]
The issue is caused by a mismatch between the needed CSS files for a given LESS theme - using kendo.common-bootstrap.min.css with kendo.highcontrast.min.css . The matching files are described in [Less Themes](https://docs.telerik.com/kendo-ui/styles-and-layout/less-themes/overview) help article. When the correct file kendo.common.min.css required for kendo.highcontrast.min.css is used, there is no such issue - https://dojo.telerik.com/@Dimitar-Goshev/elUJOZoP
