### ISSUE TITLE
Calendar next and back buttons not RTL correctly

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-ui-core#6978]
**Describe the bug**
Calendar next and back buttons icon not RTL correctly

**To reproduce**
[RTL correct](https://dojo.telerik.com/@vzsoft/EfiQaGiW)
[RTL not correct](https://dojo.telerik.com/@vzsoft/ulICAwom)

**Screenshots**
![rtl](https://user-images.githubusercontent.com/5305981/183120328-54b7d289-f2d2-4ac9-a2da-65e35f0affef.jpg)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-classic

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: [Windows]

**Comment by Dimitar-Goshev** [comment]
This issue is caused by wrong configuration - referencing both the SASS theme's kendo.default-main.min.css and the LESS theme's kendo.rtl.min.css files simultaneously. The SASS theme file contains the RTL styles needed and Calendar appears as expected - [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/AvASUgAj). Adding the kendo.rtl.min.css file to it is not necessary.
