### ISSUE TITLE
The sequence of the internal scripts' load of the @progress/kendo-ui(v.2022.2.802) package is broken

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6982]
### Bug report
With version 2022.2.802 of the **@progress/kendo-ui** package, the sequence by which the internal scripts are loaded is changed when compared to version 2022.2.621 of the package. The changed sequence results in the following error when using the  **@progress/kendo-ui** package

<img width="504" alt="image" src="https://user-images.githubusercontent.com/41293735/185080482-74a54dd8-f4df-426a-92d0-1c867bcdc49f.png">

* The issue is related to [this commit](https://github.com/telerik/kendo/commit/4898f1d3549a6cf451a794e82bcfd6d921873c51)

### Reproduction of the problem
1. Download [this project](https://github.com/telerik/kendo-ui-core/files/9358216/vite-project.zip) and unarchive it
2. Run "npm install"
3. Run "npm run dev"
4. Open the project in a browser and see the dev console

### Current behavior
The error from the above screenshot appears in the browser's console

### Expected/desired behavior
The following screen should appear when starting the project:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/41293735/185083528-f69f9430-7297-4c52-91f7-e20a450dea19.png">

### Environment

* **Kendo UI version:** 2022.2.802
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Iankodj** [comment]
The sequence of the internal modules is correct when added in the dependency array by WebPack. However, webpack started listing the modules in the files in alphabetical order which should not lead to any problems with the script conversion to ESM. Generally, any module bundler that supports commonjs loading should be able to take care of the dependency order properly.  

The built-in Vite's require-import conversion is not capable to handle complex commonjs scenarios and it should be resolved by using the **vite-pugin-commonjs** package and the `esbuildCommonjs` plugin. However, `@progress/kendo-ui` should not be excluded from the plugin as it needs to be optimized using esbuild instead of Vite's optimization logic. 

The latter however brings an error with resolving the `kendo.pdf.js` file. That was earlier resolved by excluding the package from  the esbuild which is now stated as incorrect. The original cause for the file not being resolved is a case with a Vite pre-bundle plugin for esbuild to handle import of non-js files where the Regex filter catches the kendo.pdf as pdf file and does not recognize it as js file. 

The remedy for all of that is to add an additional custom plugin that resolves the `kendo.pdf` to its proper js file before the pre-bundle plugin takes place:

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { viteCommonjs, esbuildCommonjs } from '@originjs/vite-plugin-commonjs';
import path from 'path';


// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    viteCommonjs(),
    vue()
  ],
  optimizeDeps: {
    force: true,
    esbuildOptions: {
      plugins: [
        {
            name: "kendo:pdf:resolver",
            setup(build) {
                build.onResolve({
                    filter: new RegExp("\.+\/kendo.pdf$")
                }, async () => {
                    return {
                      path: path.resolve(__dirname, `node_modules/@progress/kendo-ui/js/kendo.pdf.js`)
                    };
                });
            }
        },
        esbuildCommonjs(['@progress/kendo-ui']),
      ]
    }
  }
})
```

Attaching a project as well: 

[vite-project-with-components.zip](https://github.com/telerik/kendo-ui-core/files/9458908/vite-project-with-components.zip)

@PekoPPT @zdravkov As Vite is being mostly used with Vue you can consider placing that info in the docs for the Vue wrappers so that it is well known how to resolve the import of the kendo-ui library. 

Also, we can also consider including ESM distribution in the `@progresss/kendo-ui` npm package as this will avoid using a commonjs loader at all.
