### ISSUE TITLE
The pager in FileManager's Grid view is incorrectly displayed on large screen

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7077]
### Bug report

In the FileManager's Grid view, if the Grid has alwaysVisible set to false, the Pager is displayed as if viewed on a smaller viewport.

### Reproduction of the problem
1. Open this Dojo example, with Chrome DevTools opened - https://runner.telerik.io/fullscreen/@sspasova/uyuyogEX
3. Resize the browser - the Pager is now displayed as expected.

### Current behavior

The Pager is incorrectly displayed. 
There is an error in the console "Uncaught TypeError: Cannot read properties of undefined (reading 'switchInstance')"

### Expected/desired behavior
The Pager should be displayed correctly on a large viewport

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all]

**Comment by iordanGrancharov** [comment]
The error that is thrown in the console "Uncaught TypeError: Cannot read properties of undefined (reading 'switchInstance') is caused by the custom logic for the `filemanager.toolbar.fileManagerDetailsToggle.switchInstance.toggle()` which is no longer the right way to toggle details in the toolbar. The demo is already up to date and can be used as a reference https://demos.telerik.com/kendo-ui/filemanager/index. Working version: 2024.1.319
