### ISSUE TITLE
The 'M' format does not work as expected

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#713]
Demo: http://dojo.telerik.com/IFUna

    kendo.toString(kendo.parseDate('1/1/2014'), 'M');
    //outputs 'January 1'
    //expected output '1'

**Comment by ggkrustev** [comment]
The described behavior is expected, because "M" is valid short date patter:
- https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L518

Formatter finds a match and gets the corresponding date format, which in this case is `MMMM dd`.

If the user wants to format date using `M` designator, then either needs to avoid using `kendo.toString` or override the culture `M` date pattern
