### ISSUE TITLE
MVVM auto-bind = false not obeyed

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#716]
Ticked ID: 924972 
Can be reproduced on: [http://dojo.telerik.com/@codeowl/AxeHu](http://dojo.telerik.com/@codeowl/AxeHu)

The combobox binds straight away, even with data-auto-bind="false" set. Behavior is different in 2014 Q3 version.

**Comment by ggkrustev** [comment]
The described behavior is actually expected, because the MVVM value binding uses widget's [value](http://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#methods-value) method, which in turn will fetch the data if data source is not bound, thus ignoring the autoBind option.

The only way to overcome this case is to modify the value binding to honour widgets with such "autoBind" option and treat them differently. Here is a [custom binding demo](http://docs.telerik.com/kendo-ui/web/combobox/how-to/deferred-value-binding), that actually does this. We suggest our customers to use the custom binding until we decide to make that functionality built-in.

Any inputs are welcomed.

**Comment by ggkrustev** [comment]
After further internal discussion, we decided to add support for autoBind option into the default MVVM value binding.
