### ISSUE TITLE
ClientTemplate syntax breaking when upgraded the existing .NetMvc Kendo UI version from 2019.2.619 to 2023.1.117

### ISSUE THREAD

**Issue by gawadesantosh14** [telerik/kendo-ui-core#7228]
### Bug report

In KendoUI version 2019.2.619, the below syntax is working fine but when it upgraded to 2023.1.117, the page is breaking with below error in browser console.
Existing code
`columns.Bound(c => c.date).Width("25%").ClientTemplate("#=DateStr#");
`
The error displayed in the browser console:
`Uncaught Error: Invalid template:'#=DateStr#' Generated code:'var $kendoOutput, $kendoHtmlEncode = kendo.htmlEncode;with(data){$kendoOutput=''+(DateStr)+'';}return $kendoOutput;'
    at Object.compile (kendo.all.js:313050:21)
    at kendo.all.js:313050:21
    at c (kendo.all.js:313050:21)
    at init._rowsHtml (kendo.all.js:313050:21)
    at init._renderContent (kendo.all.js:313050:21)
    at init.refresh (kendo.all.js:313050:21)
    at init.trigger (kendo.all.js:313050:21)
    at init._process (kendo.all.js:313050:21)
    at init.success (kendo.all.js:313050:21)
    at success (kendo.all.js:313050:21)`
### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via http://dojo.telerik.com or similar.

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 2023.1.117
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gawadesantosh14** [comment]
The above syntax is failing only when we added our content security policy in which we have removed unsafe-eval and just kept unsafe-inline for script-src, else it is working fine if we include the unsafe-eval in the content security policy

**Comment by Dimitar-Goshev** [comment]
Hi @gawadesantosh14 ,

Strict CSP mode for UI for ASP.NET MVC  is supported as of R1 2023 SP1(version 2023.1.314) by following the [Content Security Policy setup article](https://docs.telerik.com/aspnet-mvc/html-helpers/helper-basics/content-security-policy#for-r1-2023-sp1-and-later-working-with-telerik-ui-for-aspnet-mvc-components). We had the [ClientTemplateHandler() method is not available for the Grid columns](https://github.com/telerik/kendo-ui-core/issues/7325) issue, which was fixed in 2023.2.606 release. Please upgrade to R2 2023 and follow the above setup article.
