### ISSUE TITLE
item.index() returns wrong value when DropDownList has optionLabel

### ISSUE THREAD

**Issue by matbeard** [telerik/kendo-ui-core#736]
Since the 2015 Q1 release, the DropDownList widget returns the wrong value for item.index() onSelect.

The method for getting the dataItem of the selected item on select, which is: 
  var dataItem = this.dataItem(e.item.index());
no longer return the correct dataItem if an optionLabel is configured. This can be demonstrated by editing the DropDownList Events demo and simply adding an optionLabel to the definition.

**Comment by naskog** [comment]
In order to support grouping and virtualization, we decided to move the optionLabel outside the items list and place it as a static header on top of the popup element. For more details please refer to this [article](http://docs.telerik.com/kendo-ui/install/changes-and-backward-compatibility)

**Comment by matbeard** [comment]
I've already read through that -- given that the optionLabel is outside the items list, it doesn't explain why e.item.index() returns the wrong value when an optionLabel is configured. How would you suggest getting the dataItem of the selected item?

**Comment by naskog** [comment]
The e.item.index() returns the correct index in the context of the HTML element,  which however is not the correct one in the context of the data items list - the option label corresponds to index 0 and the first data item has index 1.
In order to get the correct data item based on the item, just pass the jQuery element itself:

var dataItem = this.dataItem(e.item);
