### ISSUE TITLE
Notification is partially hidden by page scroller

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7378]
The Notification is not entirely displayed when the scroller appears on the page. 

**To reproduce**

1. Open the demos - https://demos.telerik.com/kendo-ui/notification/index
1. Click on the '_As a popup at bottom-right_' button.

**Expected behavior**
The Notification seems to be cut at the end.

**Screenshots**
![image](https://github.com/telerik/kendo-themes/assets/14364791/b8934900-9b63-4e2c-af2e-dd21e7540d09)

With versions prior to 2023 R2 (2023.2.606) the Notification was displayed with a slight distance on the right

![image](https://github.com/telerik/kendo-themes/assets/14364791/b13087b0-1db3-4e00-8540-a8a5ca398aa1)

### Environment

* **Kendo UI version:** 2023.2.606
* **Browser:** [all ]

**Comment by gdenchevprog** [comment]
Does not seem like a bug with the notification itself. I can see the cut off in the demo, but in a Dojo or anywhere else the notification appears as expected.

https://dojo.telerik.com/@gdenchev/EtoQOxUN 

The reason it appears closer to the end of the page is because of a fix related to the width of the notification. The demo seems to be affected by some style in the `demorunner.min.css` stylesheet.

In either case, the [`position.right`](https://docs.telerik.com/kendo-ui/api/javascript/ui/notification/configuration/position#positionright) property can be used to apply more "padding". For  the demo, I'd recommend we check the stylesheet and see what could be affecting the appearance of the popup.

**Comment by gdenchevprog** [comment]
The problem seems to also occur when the close button property is enabled `button: true`.

We could increase the default `right` offset if the close icon is rendered. For the time being the workaround would be to simply set the offset manually through the `position` configuration.

```javascript
{
 position: { right: 40, bottom: 20 } // The current defaults are right=20 and bottom=20
}
```

**Comment by gdenchevprog** [comment]
The problem with the close button not being visible can be tracked here - https://github.com/telerik/kendo-ui-core/issues/7737
