### ISSUE TITLE
MVC Grid Toolbar IconClass Ignored 

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#7415]
### Bug report

When a UI for ASP.NET MVC Grid contains a PDF or Excel button within the Toolbar, the IconClass is being ignored.

### Reproduction of the problem
```razor
.ToolBar(t => t.Excel().Text("Export to Excel").IconClass("icon here"))
```

### Current behavior
![image](https://github.com/telerik/kendo-ui-core/assets/19593058/5da4fd30-39ba-4789-988c-2278fe9269f5)

### Expected/desired behavior
The specific icon should be added based on the IconClass.

### Environment

* **Kendo UI version:** 2023.2.606
* **jQuery version:** All Supported Versions
* **Browser:** All

**Comment by KelseyDDC** [comment]
Hi, 
In version 2023.2.718 the IconClass is also ignored in general (commands, toolbar, ...). I don't know if this may be connected to this issue.

Here some screenshots for examples:
![image](https://github.com/telerik/kendo-ui-core/assets/73241639/70fc8f19-54cd-42c8-93f0-3873169c4727)
![image](https://github.com/telerik/kendo-ui-core/assets/73241639/02cf933a-8e81-445c-9821-c449f3474f0b)

**Comment by StoyanGoranov** [comment]
Starting from version 2023.2.718 onwards the IconClass configuration property of the Grid's Toolbar button is ignored - and isn't render on the client-side.

Review the behavior in [this Telerik REPL](https://netcorerepl.telerik.com/cRaDQhll44tVQThz01).

**Comment by aleksandarevangelatov** [comment]
Fixed with https://github.com/telerik/kendo/pull/18530

Passing the [font icon class name](https://docs.telerik.com/aspnet-core/styles-and-layout/sass-themes/font-icons#list-of-font-icons) to the [IconClass](https://docs.telerik.com/aspnet-mvc/api/kendo.mvc.ui.fluent/gridtoolbarcommandbuilder#iconclasssystemstring) will render the corresponding SVG or Font icon (depending on the application configuration). 

For example, the following configuration:
```
    .ToolBar(toolbar => toolbar.Pdf().IconClass("k-i-gears"))
```
will render a Toolbar Button with an SVG icon
```
<button class="k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-grid-pdf" type="button">
  <span class="k-icon k-svg-icon k-svg-i-gears">
    <svg aria-hidden="true" focusable="false" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
      <path d="..."></path>
    </svg>
  </span>Export to PDF </button>
```

Passing an arbitrary class name will render a `span` element with the class:
```
    .ToolBar(toolbar =>toolbar.Excel().IconClass("fa-solid fa-user"))
```
```
<button class="k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-grid-excel" type="button">
  <span class="fa-solid fa-user"></span>Export to Excel </button>
```

Passing a font icon class name  or an arbitrary class name to a Command Button results in a similar behavior.
