### ISSUE TITLE
Editor Format tool displays differently in Safari

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7561]
### Bug report

The options in the Format Tool dropdown are displayed differently in Safari.

![editor-format](https://github.com/telerik/kendo-ui-core/assets/20702110/cc5b13df-d511-4181-ac33-49133d4aa768)

**Regression introduced with 2023.1.314**

### Reproduction of the problem

1. Open this Dojo example on Mac in Safari - https://dojo.telerik.com/OmEpaJOF/5
2. Open the Format tool.

### Current behavior

The options in the Tool are displayed with different styles compared to Chrome

### Expected/desired behavior

The options should be displayed as in Chrome.

### Environment

* **Kendo UI version:** 2023.3.1010
* **Browser:** [Safari]

**Comment by gdenchevprog** [comment]
Some additional information - if you add the `stylesheets` configuration even with an invalid stylesheet, the problem seems to disappear.

```javascript
                stylesheets: [
                    ".",
                ]
```

**Comment by sspasova** [comment]
The popup width is incorrect after the first launch.

**Comment by gdenchevprog** [comment]
> The popup width is incorrect after the first launch.

The problem is related to a default behavior in Safari. The front-end team will review it and let us know if there's anything that can be done.

For now, as a workaround users can close and immediately reopen the dropdownlist on the initial expand. This will probably cause a bit of flickering, but there's nothing that we can do for the moment.
