### ISSUE TITLE
Aggregates in Grid's footer shift after editing a cell if a column is hidden

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7756]
### Bug report

In a Grid with a hidden column, the aggregates in the footer shift to the right if you edit a cell.

**Regression introduced with 2023.2.829**

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/EXOmOcAs
2. Scroll to the bottom to see the footer 
3. Edit a cell

### Current behavior
The footer cells shift to the right.

### Expected/desired behavior

The footer cells shouldn't shift to the right after updating a cell.

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all]

**Comment by iordanGrancharov** [comment]
This is not a bug. Since the replacement of the footer template is a custom implementation, it is expected edge cases to appear that differ from the built-in behavior of the Grid component and should be handled by custom implementation as well. A way to handle the current issue is to add `kendo.applyStylesFromKendoAttributes(grid.footer, ['display'])`, right after the replacement of the template. This will evaluate all kendo data attributes and apply the necessary styles.
