### ISSUE TITLE
MultiSelect does not allow you to add new tags

### ISSUE THREAD

**Issue by devmondo** [telerik/kendo-ui-core#782]
hi, 
multi select is great, but it restricts you to predefined list, to make it act as a true Tag editor, it must allow user to add new values in addition to predefined or server search ability, is this possible ?

thanks in advanced.

**Comment by KirilNN** [comment]
Hi @devmondo,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests, so I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!
