### ISSUE TITLE
Bundling the kendo js files results in an error

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7828]
### Bug report
Bundling the Kendo js files in an ASP.NET MVC application throws a NullReferenceException error. Reproduced with versions 2024.1.319 and 2024.2.514. The bundling works without exceptions in version 2023.3.1114.

### Reproduction of the problem
1. Add the following bundle to the BundleConfig.cs file:

```
bundles.Add(new ScriptBundle("~/bundles/kendo").Include(
        "~/Scripts/kendo/2024.2.514/kendo.web.min.js",
        "~/Scripts/kendo/2024.2.514/kendo.aspnetmvc.min.js"
));
```

Instead of kendo.web.min.js you can use kendo.all.min.js with the same result.

2. Render the scripts in the _Layout.cshtml's head element after jQuery by calling:

```
@Scripts.Render("~/bundles/kendo")
```

### Current behavior

**Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.**

Workaround:

Use ```bundles.Add(new Bundle("~/bundles/kendo")``` instead of ```bundles.Add(new ScriptBundle("~/bundles/kendo")```

### Expected/desired behavior
No exception is thrown when bundling the Kendo script files. 

### Environment

* **Kendo UI version:** 2024.2.514
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1653064

**Comment by gdenchevprog** [comment]
The problem occurs because the MVC Bundler(as well as older versions of webpack) cannot properly process new JS features. As we strive to write code that is in accordance with the latest best practices, such problems can occur when using tools that are not compatible with newer ECMAScript versions.

We'll introduce a new CLI command in the `source` package that would enable users to compile the Kendo source code using Babel. This would resolve the problem with the outdated bundlers, however it will require you to manually compile the source code any time you wish to update to a new Kendo/Telerik version.

The ideal approach would be to switch to a bundler that is kept up to date with the latest JavaScript versions.

The following articles will be updated once the changes are live:

https://docs.telerik.com/aspnet-mvc/installation/adding-client-side-resources/ecmascript#manually-building-the-source-code
https://docs.telerik.com/kendo-ui/intro/installation/ecmascript#manually-building-the-source-code

**Note** - the `source` bundle refers to the source code zip/7z file that you can [download from your telerik.com profile](https://www.telerik.com/account/downloads/product-download).
![image](https://github.com/telerik/kendo-ui-core/assets/70957719/a88b2036-634a-406e-8095-a1602b9b1521)
