### ISSUE TITLE
Flip and PageTurn effects does not work in FireFox

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7845]
### Bug report

In the latest FireFox (126.0) flip and pageTurn effects does not work properly

### Reproduction of the problem
1. Open FireFox and upgrate to 126 version if needed
2. Opne the Demos: https://demos.telerik.com/kendo-ui/fx/pageturn and https://demos.telerik.com/kendo-ui/fx/flip click to turn a page in the first demo and the 'Store' button in the second

### Current behavior
The effect does not work and the text is reversed when the flip effect is used. screencast - https://somup.com/cZhuiL5mUu

### Expected/desired behavior
The effects should be applied and tetx should not be reversed. 

### Environment

* **Kendo UI version:** 2024.2.514
* **jQuery version:** x.y
* **Browser:** [Firefox XX]

**Comment by iordanGrancharov** [comment]
The bug is related to the latest Firefox release rather than the Kendo library. There are other reports of broken animations in the different components and they all appeared with v126 of Firefox. 

There is a bug logged in the Bugzilla website with details around it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1898455

Note: The logged issue is about the `transform` property, but it applies the same to the `transition` property.
