### ISSUE TITLE
NumericTextBox is displaying regular keyboard on mobile

### ISSUE THREAD

**Issue by mc-suchecki** [telerik/kendo-ui-core#806]
Like here: http://www.telerik.com/forums/get-the-numeric-pad-when-focused-on-the-numeric-field-ipad

Setting type="number" in input tag is not working, because Kendo is overwriting that to type="text" even on mobile. Shouldn't Kendo set the input type to "number" on mobile? Setting pattern to "[0-9]*" is not acceptable as it prevents characters like dot or comma and does not work on Android.

That issue was supposed to be solved in 2012:
http://www.telerik.com/forums/open-numeric-keypad-on-mobile-device

**Comment by ggkrustev** [comment]
Hi @mc-suchecki,

The widget does set `type="text"`, because this is the only way to support internalized numbers. When type is set to `number`, then the browser applies specific validation rules [(link)](http://www.w3.org/TR/html-markup/input.number.html), which prevents the normal work of the widget. 

That being said, if you want to use `type="number"`, then you will need to use regular **input** element. You can style it using `k-textbox` CSS class.

I will close this issue, as it cannot be resolved at the current state of the mobile browsers.

**Comment by mc-suchecki** [comment]
Hi @ggkrustev,

Thank you for a very fast answer. Unfortunately, I am not able to use a regular input element, as I want to use Kendo k-format mask feature. Is there any way to use k-format and have numeric keyboard on mobile? AFAIK, there is not, but maybe I am missing something.
