### ISSUE TITLE
What a complex way to bind a viewmodel in the MVVM framework 

### ISSUE THREAD

**Issue by andyforever** [telerik/kendo-ui-core#808]
I think a viewmodel can be binded directly on the DOM element.
For example,
```javascript
<div kd-controller='viewmodel'>
	<button kd-click="click"></button>
</div>

<script>
	var viewmodel = kendo.observable({
		click: function() {
			alert('I am clicked!');
		}
	})
</script>
```

**Comment by KirilNN** [comment]
Hi @andyforever,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests, so I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!
