### ISSUE TITLE
kendo window. setOptions resets actions in the maximized state

### ISSUE THREAD

**Issue by olsh** [telerik/kendo-ui-core#839]
Steps to reproduce:
1. Create a new window with the "Maximize" action
2. Maximize the window, the restore button appears in the title
3. Call the setOptions method in the maximized state, the restore button disappears
4. You unable to restore or maximize the window

[Demo](http://dojo.telerik.com/obAYu)

**Comment by olsh** [comment]
Is that a good solution to restore a window on calling the setOptions method?
For example I just want to disable dragging of the window and keep the window maximized, how can I do that?

**Comment by gyoshev** [comment]
The restore method is called because it [cleans up after the maximize() method](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.window.js#L936-L942). Ideally, the maximized / minimized flags should be provided from the configuration options, to allow . At this time, you would need to call the maximize method after setOptions.
