### ISSUE TITLE
Issue with keyboard navigation on touch enabled Win8 device

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#848]
Easily reproducible on:
[http://demos.telerik.com/kendo-ui/button/keyboard-navigation](http://demos.telerik.com/kendo-ui/button/keyboard-navigation)

Press "Alt +W" - widget is focused
Press Space or Enter -> nothing happens

**Comment by Iankodj** [comment]
It seems that this is related to an IE10 quirk with enabled touch events. Keyboard combination Alt+[Key] prevents elements to be focused. The same can be reproduced even with a plain `<button>` element (http://dojo.telerik.com/OZoVEX). 

The same is fixed in Windows 8.1. 

Possible solution is to use a different keyboard shortcut for focusing buttons. For example, 

```
if (e.ctrlKey && e.altKey && e.keyCode == 87) {
    $("#textButton")[0].focus();
}
```

http://dojo.telerik.com/ItOjU
