### ISSUE TITLE
autocomplete k-ng-model should accept object (in addition to an array)

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#892]
This dojo is ... counterintuitive to say the least:

http://dojo.telerik.com/@petyosi/UwOje

**Comment by ggkrustev** [comment]
The applied fix is partial, because the `autocomplete` will set the model to an array value on change, which IHMO is not expected.
A solution that comes to my mind is to return an object instead of an array when selected data items are basically 1 and the `separator` (multiple selection is not enabled):

```
 if (options.separator === null && dataItems.length == 1) {
     return dataItems[0];
 }
```
(added before this line https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L1106)

**This, however, will be a breaking change**. I am open to any suggestions, whether we should make this breaking change or not.

/cc @underlog
