### ISSUE TITLE
Allow an object with the request configuration options to be set per tab

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-ui-core#90]

**Comment by tsvetomir** [comment]
Implementing this would resolve [Add ability to pass parameters via javascript for load on demand TabStrip](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/5677000-add-ability-to-pass-parameters-via-javascript-for)

**Comment by vladimirivanoviliev** [comment]
Just wanted to confirm the changes: 

We need the [`contentUrls`](http://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip#configuration-contentUrls) option to start accepting `objects` (with Ajax options) as items in the array. This change will require the `.k-link` item `contentUrl` data property to also start containing object in addition to strings or introducing new data property. This is required in order to maintain backward compatibility with existing custom solutions where this data property is manipulated by our users to bring dynamic url functionality.

**Comment by rusev** [comment]
I don't think that you should touch what's stored in `contentUrl` data property. You can simply extend [contentUrls](http://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip#configuration-contentUrls) option to accept a list of objects (_jQuery.ajax config._). Isn't that sufficient?

**Comment by vladimirivanoviliev** [comment]
After offline discussion with @rusev  we both agreed that the `contentUrl` option behavior should not be modified. Instead the items in the `contentUrls` option of the Tabstrip should be kept in sync with the order of the DOM elements. This way we can access the item options directly from the Tabstrip options instead of  `data` prop of the DOM element.

**Comment by vladimirivanoviliev** [comment]
This feature require change in the way the Tabstrip access it's content elements related to given tab (previously accessed by index, now by their `id` attribute). This change brings to light bug in Tabstrip - previously it was required to provide invalid parameters to the `insertBefore` and `insertAfter` methods (in case of **integration with Sortable widget** which reorder the tabs elements) in order to actually reorder the tabs. After fixing the bug and making the contents to be accessed by `id` attribute, the previous invalid behavior is no longer supported. Such **invalid behavior can be seen in our official demo for Tabstrip integration with Sortable widget** - it always pass the same element to both parameters accepted by the `insertBefore` / `insertAfter` methods.

**Previous, invalid behavior:**
```
change: function(e) {
    var tabstrip = $("#tabstrip1").data("kendoTabStrip");
        reference = tabstrip.tabGroup.children().eq(e.newIndex);

    if(e.oldIndex < e.newIndex) {
        //same element is passed:
        tabstrip.insertAfter(e.item, reference);
    } else {
        //same element is passed:
        tabstrip.insertBefore(e.item, reference);
    }
}
```

**Updated code:**
```
change: function(e) {
    var tabstrip = $("#tabstrip").data("kendoTabStrip");
        reference = tabstrip.tabGroup.children().eq(e.newIndex);

    if(e.oldIndex < e.newIndex) {
        tabstrip.insertAfter(e.item, $(e.item.parent().children()[e.newIndex - 1]));
    } else {
        tabstrip.insertBefore(e.item, $(e.item.parent().children()[e.newIndex + 1]));
    }
}
```

**Comment by petyosi** [comment]
From the previous explanation, it sounds to me that the Sortable integration demo no longer works. Is this so?

**Comment by vladimirivanoviliev** [comment]
After offline discussion we decided to add backward compatibility for all users that use previous behavior where the same elements were passed to the insert methods of the Tabstrip.

**Comment by ipeshev** [comment]
The functionality looks fine.
