### ISSUE TITLE
KendoDropDownList Scroll not working on IE 10,11

### ISSUE THREAD

**Issue by ssalot-continuum** [telerik/kendo-ui-core#952]
KendoDropDownList Scroll not working on IE 10,11 : 

I checked for the solution and found that in latest version of Kendo it's resolved, But when i try to use that i get other implementation concern.

Can i get exact code changes required in following 2014.1.528 Kendo All Js min version [kendo.all.min.js] ?, So i can just add those changes and get it working.

Note : https://github.com/telerik/kendo-ui-core/issues/170 ,  i tried this but not of help.

**Comment by naskog** [comment]
Hi ssalot-continuum,

Thanks for your post, and for your interest in Kendo UI Core! This issues list is for bugs only. As the problem is not present in the latest version of Kendo UI Core, I’m going to close it with this comment.

That said, I want to make sure that you’re able to get the help you need, and the good news is that you have two options:

1. You can visit us on [Stack Overflow](http://stackoverflow.com/questions/tagged/kendo-ui), where you can search previous questions using the #kendo-ui tag, or enter your request for the community.
2. You can visit the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework). All Kendo UI users have read access to the complete forum history, while commercial license-holders (Professional, UI for MVC, PHP or JSP) have read and write access to the forums. 

If these options won’t cut it, and you’re looking for direct support from our team, you have a few options for upgrading to a commercial license:

1. You can purchase a [Kendo UI Professional](http://www.telerik.com/kendo-ui) license, which grants you read-write access to the forums, 10 tickets in our support system and access to additional professional-grade widgets, charts and graphs.
2. You can purchase a [Kendo UI Premium Support](http://www.telerik.com/kendo-ui) license, which grants you read-write access to the forums and 10 tickets in our support system.

Thanks again for your post and I hope you enjoy working with Kendo UI!

**Comment by ssalot-continuum** [comment]
Thanks for your inputs, Will look for it accordingly.
